### ISSUE TITLE
[BUG]自动化测试脚本调用平台提供的mock服务报错。

### ISSUE THREAD

**Issue by billguo** [metersphere/metersphere#11085]
**MeterSphere 版本**1.18.0

您所使用的 MeterSphere 版本是？1.18.0

**Bug 描述**自动化测试脚本调用平台提供的mock服务报错。

简要描述您碰到的问题

**Bug 重现步骤**

1.  平台创建API。
2.  平台创建mock服务。
3.  平台创建接口自动化脚本调用mock服务。
4.  调用接口自动化测试脚本报错。

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.
2022-03-01 14:27:15,480 [Async-Executor-5] INFO  i.m.n.sender.AbstractNoticeSender ? - Method[handleFollows][FOLLOW_PEOPLE: []]
2022-03-01 14:27:15,481 [XNIO-1 task-5] ERROR i.m.api.mock.utils.MockApiUtils ? - Method[getApiResponse][java.lang.NumberFormatException: For input string: ""]
java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:592)
        at java.lang.Integer.parseInt(Integer.java:615)

**Comment by zyyfit** [comment]
1.19.0已修复
