### ISSUE TITLE
[QUESTION]使用v1.18.1官网离线包，配置文件只修改了mysql端口。报错Communications link failure

### ISSUE THREAD

**Issue by cloudswar** [metersphere/metersphere#11230]
**请描述您的问题.**
2022-03-07 15:47:42,583 [main] INFO  com.zaxxer.hikari.HikariDataSource ? - DatebookHikariCP - Starting...
2022-03-07 15:47:43,843 [main] ERROR com.zaxxer.hikari.pool.HikariPool ? - DatebookHikariCP - Exception during pool initialization.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)

**Comment by cloudswar** [comment]
已经解决了，因为修改端口为3307，后面重新默认参数安装发现了默认映射就是3307，这里应该是有BUG，没分析。重新安装就可以了。
