### ISSUE TITLE
[BUG]测试计划，接口测试tab标签页面报错

### ISSUE THREAD

**Issue by 472173257dl** [metersphere/metersphere#11379]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？

**Bug 描述**

简要描述您碰到的问题

**Bug 重现步骤**

1.  新建测试计划
2. 进入测试计划
3. 点击接口测试tab标签
4. 选择接口用例页面报错

**期待的正确结果**

正确情况下应该是什么样的？

正常显示列表数据且无报错

如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/20190050/157856912-cd075762-33f9-445a-97a7-3bdc8e43b6e6.png)

**Comment by ltfit** [comment]
您好 你这个是那个版本呢 建议升级到最新版本在尝试下

**Comment by 472173257dl** [comment]
最新版，1.18.2

**Comment by ltfit** [comment]
您这边再重新安装尝试下 我这没有复现这种问题

**Comment by 472173257dl** [comment]
> 您这边再重新安装尝试下 我这没有复现这种问题

我这是源码本地运行的，win10系统

**Comment by 472173257dl** [comment]
![image](https://user-images.githubusercontent.com/20190050/158098797-79082ff2-96db-48a6-89da-e1c2b6d3109b.png)



Caused by: java.lang.NullPointerException: null
	at io.metersphere.commons.utils.ServiceUtils.buildVersionInfo(ServiceUtils.java:263)
	at io.metersphere.track.service.TestPlanApiCaseService.list(TestPlanApiCaseService.java:83)
	at io.metersphere.track.service.TestPlanApiCaseService$$FastClassBySpringCGLIB$$f41afd42.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at io.metersphere.track.service.TestPlanApiCaseService$$EnhancerBySpringCGLIB$$ba2f555e.list(<generated>)
	at io.metersphere.track.service.TestPlanApiCaseService$$FastClassBySpringCGLIB$$f41afd42.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)

**Comment by AgAngle** [comment]
你的代码是什么分支？我看了下 1.18.2 tag 的代码，这一行应该不太会报空指针，或者你简单排查一下看看，是什么原因？
