### ISSUE TITLE
[BUG]提取参数后设置变量报错

### ISSUE THREAD

**Issue by kusotest** [metersphere/metersphere#11407]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是：1.18.1

**Bug 描述**
添加case后置脚本设置变量；执行后设置变量报错

**Bug 重现步骤**

1.  添加case后置脚本设置变量
2. 执行后查看控制台日志

**期待的正确结果**
生成项目环境变量

**控制台日志**
2022-03-14 16:32:01 ERROR ThreadGroup 1-1 Problem in JSR223 script, 设置变量：data
In file: inline evaluation of: ``String data;  vars.put("MS.ENV.d8fa25e8-5937-473e-a796-4313c950446a."+"data","[" . . . '' Encountered "( \"MS.ENV.d8fa25e8-5937-473e-a796-4313c950446a.\" + \"data\" , \"[\" 20220314033644" at line 2, column 9.
 in inline evaluation of: ``String data;  vars.put("MS.ENV.d8fa25e8-5937-473e-a796-4313c950446a."+"data","[" . . . '' at line number 2
javax.script.ScriptException
   at bsh.engine.BshScriptEngine.evalSource(BshScriptEngine.java:82)
   at bsh.engine.BshScriptEngine.eval(BshScriptEngine.java:46)
   at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:260)
   at org.apache.jmeter.extractor.JSR223PostProcessor.process(JSR223PostProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPostProcessors(JMeterThread.java:971)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:586)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:486)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:250)
   at java.lang.Thread.run(Thread.java:748)

**Comment by zrfit** [comment]
您好，未复现该问题，能提供更详细的数据和操作步骤吗？
