### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by chenqi199** [metersphere/metersphere#1175]
**MeterSphere 版本**
1.6.2
#### 系统版本
macOS Mojave 10.14.6
#### docker docker-compose
Docker version 17.03.1-ce-rc1, build 3476dbf
docker-compose version 1.11.2, build dfed245

**Bug 描述**
简要描述您碰到的问题
性能测试
日志出现
2021-01-13 19:27:28,812 Setting Locale to en_EN
2021-01-13 19:27:29,201 Loading user properties from: /opt/jmeter/bin/user.properties
2021-01-13 19:27:29,204 Loading system properties from: /opt/jmeter/bin/system.properties
2021-01-13 19:27:29,206 Setting JMeter property: server.rmi.ssl.disable=true
2021-01-13 19:27:29,211 Copyright (c) 1998-2020 The Apache Software Foundation
2021-01-13 19:27:29,214 Version 5.3
2021-01-13 19:27:29,216 java.version=1.8.0_252
2021-01-13 19:27:29,219 java.vm.name=OpenJDK 64-Bit Server VM
2021-01-13 19:27:29,221 os.name=Linux
2021-01-13 19:27:29,223 os.arch=amd64
2021-01-13 19:27:29,225 os.version=3.10.0-957.21.3.el7.x86_64
2021-01-13 19:27:29,227 file.encoding=UTF-8
2021-01-13 19:27:29,229 java.awt.headless=true
2021-01-13 19:27:29,231 Max memory =1073741824
2021-01-13 19:27:29,233 Available Processors =8
2021-01-13 19:27:29,240 Default Locale=English (EN)
2021-01-13 19:27:29,242 JMeter Locale=English (EN)
2021-01-13 19:27:29,244 JMeterHome=/opt/jmeter
2021-01-13 19:27:29,245 user.dir =/jmeter-log
2021-01-13 19:27:29,247 PWD =/jmeter-log
2021-01-13 19:27:29,249 IP: 172.17.0.2 Name: 2cfe6475aa28 FullName: 2cfe6475aa28
2021-01-13 19:27:29,250 user.classpath=/test/
2021-01-13 19:27:29,252 Adding to classpath and loader: /test/
2021-01-13 19:27:29,255 An error occurred: org.apache.jmeter.report.config.ConfigurationException: The file /test/*.jmx doesn't exist or can't be opened
at org.apache.jmeter.JMeter.runNonGui(JMeter.java:1003) ~[ApacheJMeter_core.jar:5.3]
at org.apache.jmeter.JMeter.startNonGui(JMeter.java:994) ~[ApacheJMeter_core.jar:5.3]
at org.apache.jmeter.JMeter.start(JMeter.java:566) [ApacheJMeter_core.jar:5.3]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
at org.apache.jmeter.NewDriver.main(NewDriver.java:252) [ApacheJMeter.jar:5.3]
2021-01-13 19:27:28,812 Setting Locale to en_EN
2021-01-13 19:27:29,201 Loading user properties from: /opt/jmeter/bin/user.properties
2021-01-13 19:27:29,204 Loading system properties from: /opt/jmeter/bin/system.properties
2021-01-13 19:27:29,206 Setting JMeter property: server.rmi.ssl.disable=true
2021-01-13 19:27:29,211 Copyright (c) 1998-2020 The Apache Software Foundation
2021-01-13 19:27:29,214 Version 5.3
2021-01-13 19:27:29,216 java.version=1.8.0_252
2021-01-13 19:27:29,219 java.vm.name=OpenJDK 64-Bit Server VM
2021-01-13 19:27:29,221 os.name=Linux
2021-01-13 19:27:29,223 os.arch=amd64
2021-01-13 19:27:29,225 os.version=3.10.0-957.21.3.el7.x86_64
2021-01-13 19:27:29,227 file.encoding=UTF-8
2021-01-13 19:27:29,229 java.awt.headless=true
2021-01-13 19:27:29,231 Max memory =1073741824
2021-01-13 19:27:29,233 Available Processors =8
2021-01-13 19:27:29,240 Default Locale=English (EN)
2021-01-13 19:27:29,242 JMeter Locale=English (EN)
2021-01-13 19:27:29,244 JMeterHome=/opt/jmeter
2021-01-13 19:27:29,245 user.dir =/jmeter-log
2021-01-13 19:27:29,247 PWD =/jmeter-log
2021-01-13 19:27:29,249 IP: 172.17.0.2 Name: 2cfe6475aa28 FullName: 2cfe6475aa28
2021-01-13 19:27:29,250 user.classpath=/test/
2021-01-13 19:27:29,252 Adding to classpath and loader: /test/
2021-01-13 19:27:29,255 An error occurred: org.apache.jmeter.report.config.ConfigurationException: The file /test/*.jmx doesn't exist or can't be opened
at org.apache.jmeter.JMeter.runNonGui(JMeter.java:1003) ~[ApacheJMeter_core.jar:5.3]
at org.apache.jmeter.JMeter.startNonGui(JMeter.java:994) ~[ApacheJMeter_core.jar:5.3]
at org.apache.jmeter.JMeter.start(JMeter.java:566) [ApacheJMeter_core.jar:5.3]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
at org.apache.jmeter.NewDriver.main(NewDriver.java:252) [ApacheJMeter.jar:5.3]
2021-01-13 19:27:28,812 Setting Locale to en_EN
2021-01-13 19:27:29,201 Loading user properties from: /opt/jmeter/bin/user.properties
2021-01-13 19:27:29,204 Loading system properties from: /opt/jmeter/bin/system.properties
2021-01-13 19:27:29,206 Setting JMeter property: server.rmi.ssl.disable=true
2021-01-13 19:27:29,211 Copyright (c) 1998-2020 The Apache Software Foundation
2021-01-13 19:27:29,214 Version 5.3
2021-01-13 19:27:29,216 java.version=1.8.0_252
2021-01-13 19:27:29,219 java.vm.name=OpenJDK 64-Bit Server VM
2021-01-13 19:27:29,221 os.name=Linux
2021-01-13 19:27:29,223 os.arch=amd64
2021-01-13 19:27:29,225 os.version=3.10.0-957.21.3.el7.x86_64
2021-01-13 19:27:29,227 file.encoding=UTF-8
2021-01-13 19:27:29,229 java.awt.headless=true
2021-01-13 19:27:29,231 Max memory =1073741824
2021-01-13 19:27:29,233 Available Processors =8
2021-01-13 19:27:29,240 Default Locale=English (EN)
2021-01-13 19:27:29,242 JMeter Locale=English (EN)
2021-01-13 19:27:29,244 JMeterHome=/opt/jmeter
2021-01-13 19:27:29,245 user.dir =/jmeter-log
2021-01-13 19:27:29,247 PWD =/jmeter-log
2021-01-13 19:27:29,249 IP: 172.17.0.2 Name: 2cfe6475aa28 FullName: 2cfe6475aa28
2021-01-13 19:27:29,250 user.classpath=/test/
2021-01-13 19:27:29,252 Adding to classpath and loader: /test/
2021-01-13 19:27:29,255 An error occurred: org.apache.jmeter.report.config.ConfigurationException: The file /test/*.jmx doesn't exist or can't be opened
at org.apache.jmeter.JMeter.runNonGui(JMeter.java:1003) ~[ApacheJMeter_core.jar:5.3]
at org.apache.jmeter.JMeter.startNonGui(JMeter.java:994) ~[ApacheJMeter_core.jar:5.3]
at org.apache.jmeter.JMeter.start(JMeter.java:566) [ApacheJMeter_core.jar:5.3]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
at org.apache.jmeter.NewDriver.main(NewDriver.java:252) [ApacheJMeter.jar:5.3]
2021-01-13 19:27:28,812 Setting Locale to en_EN
2021-01-13 19:27:29,201 Loading user properties from: /opt/jmeter/bin/user.properties
2021-01-13 19:27:29,204 Loading system properties from: /opt/jmeter/bin/system.properties
2021-01-13 19:27:29,206 Setting JMeter property: server.rmi.ssl.disable=true
2021-01-13 19:27:29,211 Copyright (c) 1998-2020 The Apache Software Foundation
2021-01-13 19:27:29,214 Version 5.3
2021-01-13 19:27:29,216 java.version=1.8.0_252
2021-01-13 19:27:29,219 java.vm.name=OpenJDK 64-Bit Server VM
2021-01-13 19:27:29,221 os.name=Linux
2021-01-13 19:27:29,223 os.arch=amd64
2021-01-13 19:27:29,225 os.version=3.10.0-957.21.3.el7.x86_64
2021-01-13 19:27:29,227 file.encoding=UTF-8
2021-01-13 19:27:29,229 java.awt.headless=true
2021-01-13 19:27:29,231 Max memory =1073741824
2021-01-13 19:27:29,233 Available Processors =8
2021-01-13 19:27:29,240 Default Locale=English (EN)
2021-01-13 19:27:29,242 JMeter Locale=English (EN)
2021-01-13 19:27:29,244 JMeterHome=/opt/jmeter
2021-01-13 19:27:29,245 user.dir =/jmeter-log
2021-01-13 19:27:29,247 PWD =/jmeter-log
2021-01-13 19:27:29,249 IP: 172.17.0.2 Name: 2cfe6475aa28 FullName: 2cfe6475aa28
2021-01-13 19:27:29,250 user.classpath=/test/
2021-01-13 19:27:29,252 Adding to classpath and loader: /test/
2021-01-13 19:27:29,255 An error occurred: org.apache.jmeter.report.config.ConfigurationException: The file /test/*.jmx doesn't exist or can't be opened
at org.apache.jmeter.JMeter.runNonGui(JMeter.java:1003) ~[ApacheJMeter_core.jar:5.3]
at org.apache.jmeter.JMeter.startNonGui(JMeter.java:994) ~[ApacheJMeter_core.jar:5.3]
at org.apache.jmeter.JMeter.start(JMeter.java:566) [ApacheJMeter_core.jar:5.3]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
at org.apache.jmeter.NewDriver.main(NewDriver.java:252) [ApacheJMeter.jar:5.3]
2021-01-13 19:27:28,812 Setting Locale to en_EN
2021-01-13 19:27:29,201 Loading user properties from: /opt/jmeter/bin/user.properties
2021-01-13 19:27:29,204 Loading system properties from: /opt/jmeter/bin/system.properties
2021-01-13 19:27:29,206 Setting JMeter property: server.rmi.ssl.disable=true
2021-01-13 19:27:29,211 Copyright (c) 1998-2020 The Apache Software Foundation
2021-01-13 19:27:29,214 Version 5.3
2021-01-13 19:27:29,216 java.version=1.8.0_252
2021-01-13 19:27:29,219 java.vm.name=OpenJDK 64-Bit Server VM
2021-01-13 19:27:29,221 os.name=Linux
2021-01-13 19:27:29,223 os.arch=amd64
2021-01-13 19:27:29,225 os.version=3.10.0-957.21.3.el7.x86_64
2021-01-13 19:27:29,227 file.encoding=UTF-8
2021-01-13 19:27:29,229 java.awt.headless=true
2021-01-13 19:27:29,231 Max memory =1073741824
2021-01-13 19:27:29,233 Available Processors =8
2021-01-13 19:27:29,240 Default Locale=English (EN)
2021-01-13 19:27:29,242 JMeter Locale=English (EN)
2021-01-13 19:27:29,244 JMeterHome=/opt/jmeter
2021-01-13 19:27:29,245 user.dir =/jmeter-log
2021-01-13 19:27:29,247 PWD =/jmeter-log
2021-01-13 19:27:29,249 IP: 172.17.0.2 Name: 2cfe6475aa28 FullName: 2cfe6475aa28
2021-01-13 19:27:29,250 user.classpath=/test/
2021-01-13 19:27:29,252 Adding to classpath and loader: /test/
2021-01-13 19:27:29,255 An error occurred: org.apache.jmeter.report.config.ConfigurationException: The file /test/*.jmx doesn't exist or can't be opened
at org.apache.jmeter.JMeter.runNonGui(JMeter.java:1003) ~[ApacheJMeter_core.jar:5.3]
at org.apache.jmeter.JMeter.startNonGui(JMeter.java:994) ~[ApacheJMeter_core.jar:5.3]
at org.apache.jmeter.JMeter.start(JMeter.java:566) [ApacheJMeter_core.jar:5.3]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
at org.apache.jmeter.NewDriver.main(NewDriver.java:252) [ApacheJMeter.jar:5.3]

**Bug 重现步骤**
0 quick_start
1.  上传jmeter 脚本
2. 上传cvs 报错
3. 保存并执行
4. 

**期待的正确结果**
期待可以返回正确的压测结果

**截图**
![image](https://user-images.githubusercontent.com/20620118/104603739-ac9e6e00-56b7-11eb-8426-d707dc706057.png)

**Comment by chenqi199** [comment]
- 这不是bug 
- 我个人原因 没好好看文档
- 差了个配置

### 系统设置-> 系统 -> 系统参数设置->基本参数->当前站点url
#### 要写ip 不能用localhoat 默认的是localhost

## 感谢 @wangzhen-fit2cloud wang

**Comment by priyesh-tuli-lab49** [comment]
what is the solution of this? I am also facing same issue.
