### ISSUE TITLE
[BUG]场景用例中自定义sql请求提示找不到数据源

### ISSUE THREAD

**Issue by qingmu2633** [metersphere/metersphere#12375]
### MeterSphere 版本

 v1.19.1-4fb56789

### 使用外置数据库

否

### 问题描述

V17.1升级到V19.1后场景用例中while循环控制器中自定义sql请求提示数数据源为空；
V17.1是正常能执行的

### 重现步骤

场景用例点击调试执行

### 相关日志输出

```shell
2022-04-07 13:58:10,804 [XNIO-1 task-12] ERROR ms-jmeter-run-log ? - Method[debug][io.metersphere.commons.exception.MSException: 获取该客群的CG_STATUS值（是否已经同步完毕0-未完成 1-已完成）：数据源为空请选择数据源]
io.metersphere.commons.exception.MSException: 获取该客群的CG_STATUS值（是否已经同步完毕0-未完成 1-已完成）：数据源为空请选择数据源
	at io.metersphere.commons.exception.MSException.throwException(MSException.java:14)
	at io.metersphere.api.dto.definition.request.sampler.MsJDBCSampler.toHashTree(MsJDBCSampler.java:152)
	at io.metersphere.api.dto.definition.request.controller.MsLoopController.lambda$toHashTree$0(MsLoopController.java:89)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at io.metersphere.api.dto.definition.request.controller.MsLoopController.toHashTree(MsLoopController.java:86)
	at io.metersphere.api.dto.definition.request.MsScenario.toHashTree(MsScenario.java:177)
	at io.metersphere.api.dto.definition.request.MsScenario.toHashTree(MsScenario.java:177)
	at io.metersphere.api.dto.definition.request.MsScenario.toHashTree(MsScenario.java:177)
	at io.metersphere.api.dto.definition.request.MsThreadGroup.toHashTree(MsThreadGroup.java:47)
	at io.metersphere.api.dto.definition.request.MsTestPlan.lambda$toHashTree$0(MsTestPlan.java:33)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at io.metersphere.api.dto.definition.request.MsTestPlan.toHashTree(MsTestPlan.java:32)
	at io.metersphere.plugin.core.MsTestElement.generateHashTree(MsTestElement.java:86)
	at io.metersphere.api.exec.scenario.ApiScenarioExecuteService.debug(ApiScenarioExecuteService.java:331)
	at io.metersphere.api.service.ApiAutomationService.debugRun(ApiAutomationService.java:844)
	at io.metersphere.api.service.ApiAutomationService$$FastClassBySpringCGLIB$$a31b65d1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at io.metersphere.api.service.ApiAutomationService$$EnhancerBySpringCGLIB$$a8575d8a.debugRun(<generated>)
	at io.metersphere.api.service.ApiAutomationService$$FastClassBySpringCGLIB$$a31b65d1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
```

### 附加信息

![image](https://user-images.githubusercontent.com/86302975/162129987-dbfc61e7-1a4e-4583-b26b-a51c866e5a33.png)

**Comment by qingmu2633** [comment]
![image](https://user-images.githubusercontent.com/86302975/162130183-5e67c1b6-6ea4-40cc-b329-0a46f01751ad.png)

1. 数据源是有的
2. 即使把这个请求禁用了，点调试还是有这个报错

**Comment by zrfit** [comment]
您好，未复现该问题，是否能导出场景我们尝试复现。

**Comment by qingmu2633** [comment]
问题已排查到：api_scenario表中scenario_definition字段中的sql请求的environmentId值和environment_json字段值中的不一致导致的找不到数据源；这里升级后不知道为啥有部分场景的会不一致~

![image](https://user-images.githubusercontent.com/86302975/162349329-3779edd8-021b-4b26-8e34-5932bc23764b.png)

**Comment by zyyfit** [comment]
您好，1.19.2修复了这个问题，请升级试试
