### ISSUE TITLE
[BUG]数据库连接无法释放， 修改最大连接数配置无法生效

### ISSUE THREAD

**Issue by 1137wangshen** [metersphere/metersphere#12556]
### MeterSphere 版本

1.19.2

### 使用外置数据库

否

### 问题描述

启动ms-server  数据库连接数就占满，  修改完配置  重启不生效，恢复到150的上限。   改临时配置生效set GLOBAL max_connections = 8000  ,无法重启
可能和历史定时任务有关。

同时发现  lower_case_table_names  这个配置也未生效 

导致 Table 'metersphere.QRTZ_TRIGGERS' doesn't exist    大写的表都不识别 影响很多功能

### 重现步骤

可能和历史定时任务有关。
停止ms-server 才能连上数据库  否在无法连接

### 相关日志输出

```shell
Caused by: java.sql.SQLNonTransientConnectionException: Data source rejected establishment of connection,  message from server: "Too many connections"
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)



——————————————————————————————分割线——————————————————————————

Caused by: java.sql.SQLSyntaxErrorException: Table 'metersphere.QRTZ_TRIGGERS' doesn't exist
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:1
```

### 附加信息

![image](https://user-images.githubusercontent.com/47882424/163086323-b17b80ad-2fac-4a49-840b-9f31e74364ad.png)
![image](https://user-images.githubusercontent.com/47882424/163086672-d5c58fe4-206f-4d94-97fe-1d858af086f2.png)

**Comment by 1137wangshen** [comment]
![image](https://user-images.githubusercontent.com/47882424/163088680-4fd48007-ff4a-47e1-b87d-312e336425ba.png)

**Comment by liuruibin** [comment]
请问一下，my.cnf的文件权限是655吗，我这里没有复现出这个问题，设置的最大连接数和表名大小写都是生效的

**Comment by xulinde** [comment]
您超过30天未反馈信息，我们将关闭此Issue，如有需要您可以重新打开或提交新的Issue
