### ISSUE TITLE
bug：当参数中含有特殊符号时，接口返回失败

### ISSUE THREAD

**Issue by kekeguo** [metersphere/metersphere#1265]
postman运行正常，metersphere报错
java.net.URISyntaxException: Illegal character in query at index 40: https:xxx/?params={"authCode":"x7yOHmt068q13adGN/3RoAeK0AwC3uaNsnVmwSU2ghx3/FDEmc8nX8eImla81nvEc/NwXbmsYGrFS37i9Ai+jPqSBaDNngaCkmXxNnrG+S06zX4+kmX5nfAYi2h3p/dVWW+Ck7uW1ii5AqAodF+W3FZhRgPishjM6+8bAYNupZDbtkjC8CHGjg&command=Production/GetMetalConfigurationList
at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3111)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URL.toURI(URL.java:953)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.sample(HTTPHC4Impl.java:535)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:67)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1282)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1271)
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:627)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:551)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:490)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:257)
	at java.lang.Thread.run(Thread.java:748)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，我们的环境没复制您的问题，请问参数中的特殊符号是哪些？上传截图信息最好啦～ @kekeguo
