### ISSUE TITLE
[BUG]get请求中请求信息QUERY设置开启编码实际执行没有进行对数据编码

### ISSUE THREAD

**Issue by fit2cloud-yangxufu** [metersphere/metersphere#12785]
### 联系方式

xufu.yang@fit2cloud.com

### MeterSphere 版本

1.19.2

### 使用外置数据库

否

### 问题描述

1、在请求信息QUERY的其他设置中 编码格式选择：是
2、实际传入参数json格式数据 {"departmentId":"","kpiCycle":"2021","subCompanyId":""}
3、测试执行接口后提示错误 ：Non HTTP response code: java.net.URISyntaxException
4、错误日志：
java.net.URISyntaxException: Illegal character in query at index 55: https://baidu.com/mock/100065/isLogin?js=${__urlencode({"departmentId":"","kpiCycle":"2021","subCompanyId":""})}
	at java.net.URI$Parser.fail(URI.java:2847)
	at java.net.URI$Parser.checkChars(URI.java:3020)
	at java.net.URI$Parser.parseHierarchical(URI.java:3110)
	at java.net.URI$Parser.parse(URI.java:3052)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URL.toURI(URL.java:964)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.sample(HTTPHC4Impl.java:620)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:119)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1296)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1285)
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:652)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:571)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:486)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:250)
	at java.lang.Thread.run(Thread.java:748)

5、实际应该对传入数据进行执行${__urlencode()}方法

### 重现步骤

1、发送HTTP get请求
2、把QUERY参数编码设置 “是”
3、QUERY传参 {"departmentId":"","kpiCycle":"2021","subCompanyId":""}
4、执行接口

### 期待的正确结果

对参入的参数执行${__urlencode()}方法不是只把参数放在方法内不执行

### 相关日志输出

```shell
java.net.URISyntaxException: Illegal character in query at index 55: https://baidu.com/mock/100065/isLogin?js=${__urlencode({"departmentId":"","kpiCycle":"2021","subCompanyId":""})}
	at java.net.URI$Parser.fail(URI.java:2847)
	at java.net.URI$Parser.checkChars(URI.java:3020)
	at java.net.URI$Parser.parseHierarchical(URI.java:3110)
	at java.net.URI$Parser.parse(URI.java:3052)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URL.toURI(URL.java:964)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.sample(HTTPHC4Impl.java:620)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:119)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1296)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1285)
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:652)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:571)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:486)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:250)
	at java.lang.Thread.run(Thread.java:748)
```

### 附加信息

![image](https://user-images.githubusercontent.com/101856439/163803414-a2e456e6-219f-4f3f-b6cd-ba1e67700e3a.png)
![image](https://user-images.githubusercontent.com/101856439/163803441-02064560-153d-4079-a8e1-65b79f81fb59.png)
![image](https://user-images.githubusercontent.com/101856439/163803486-fc31c8d6-b7ae-4f7e-951a-b57e450ca99a.png)
![image](https://user-images.githubusercontent.com/101856439/163803529-5990fd65-02ae-4b90-be43-cf478f0146f5.png)

**Comment by youliyuan-fit2cloud** [comment]
目前不支持对json格式的数据进行编码，需要自己写脚本处理

**Comment by fit2cloud-yangxufu** [comment]
数据是升级之前写完的可以编码 之前版本18.3 升级之后没有修改过东西定时任务执行 升级19.2版本出现错误

**Comment by youliyuan-fit2cloud** [comment]
> 数据是升级之前写完的可以编码 之前版本18.3 升级之后没有修改过东西定时任务执行 升级19.2版本出现错误

Jmeter里面是不支持的，我们再看下18.3版本是怎么回事....

**Comment by fit2cloud-yangxufu** [comment]
再次验证发现:
json格式中只有一条数据  {"test1":1}  编码功能使用正常
![image](https://user-images.githubusercontent.com/101856439/165470344-edf8991e-dabe-446b-836a-8117c1bed1b5.png)
json格式中数据不为一条  {"test":1,"test2":2}  编码功能报错 无法使用
![image](https://user-images.githubusercontent.com/101856439/165470050-04f79ce9-6439-4594-bfcf-2950e3e35b14.png)

可能原因是在处理逗号的问题
