### ISSUE TITLE
[QUESTION] ms-data-streaming 服务启动存在问题，bootstrap.servers 读取旧IP地址启动失败

### ISSUE THREAD

**Issue by auto110** [metersphere/metersphere#1286]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？1.7.0

**Bug 描述**
简要描述您碰到的问题
ms-data-streaming 服务启动存在问题

![image](https://user-images.githubusercontent.com/33770132/106148971-aaa6d580-61b4-11eb-9cb5-243c5b592c31.png)

**Bug 重现步骤**
1. 执行命令：msctl upgrade

错误日志：
2021-01-28 21:58:52,914  INFO che.kafka.clients.admin.KafkaAdminClient:1097 - [AdminClient clientId=adminclient-1] Forcing a hard I/O thread shutdown. Requests in progress will be aborted.
2021-01-28 21:58:52,915  INFO nts.admin.internals.AdminMetadataManager:   ? - [AdminClient clientId=adminclient-1] Metadata update failed
org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call.
2021-01-28 21:58:52,932  INFO he.kafka.clients.admin.AdminClientConfig: 347 - AdminClientConfig values:
	bootstrap.servers = [xxxx.xxxx.xxxx.xxxx:19092]
	client.dns.lookup = default
	client.id =
	connections.max.idle.ms = 300000
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 120000
	retries = 5
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	send.buffer.bytes = 131072
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = https
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS

2021-01-28 21:58:52,937  INFO .apache.kafka.common.utils.AppInfoParser: 117 - Kafka version: 2.3.1
2021-01-28 21:58:52,937  INFO .apache.kafka.common.utils.AppInfoParser: 118 - Kafka commitId: 18a913733fb71c01
2021-01-28 21:58:52,937  INFO .apache.kafka.common.utils.AppInfoParser: 119 - Kafka startTimeMs: 1611842332937
2021-01-28 22:00:52,939  INFO nts.admin.internals.AdminMetadataManager: 238 - [AdminClient clientId=adminclient-2] Metadata update failed
org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call.
2021-01-28 22:01:00,273  WARN   org.apache.kafka.clients.NetworkClient: 748 - [AdminClient clientId=adminclient-2] Connection to node -1 (/xxxx.xxxx.xxxx.xxxx:19092) could not be established. Broker may not be available.
2021-01-28 22:01:00,274  INFO nts.admin.internals.AdminMetadataManager: 238 - [AdminClient clientId=adminclient-2] Metadata update failed
org.apache.kafka.common.errors.TimeoutException: The AdminClient thread has exited.
2021-01-28 22:01:00,278  WARN ConfigServletWebServerApplicationContext: 558 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'org.springframework.kafka.config.internalKafkaListenerEndpointRegistry'; nested exception is java.lang.IllegalStateException: Topic(s) [JMETER_LOGS] is/are not present and missingTopicsFatal is true
2021-01-28 22:01:00,279  INFO duling.concurrent.ThreadPoolTaskExecutor: 218 - Shutting down ExecutorService 'applicationTaskExecutor'
2021-01-28 22:01:00,287  INFO         org.eclipse.jetty.server.session: 158 - node0 Stopped scavenging
2021-01-28 22:01:00,290  INFO ipse.jetty.server.handler.ContextHandler:1019 - Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@6e0f5f7f{application,/,[file:///tmp/jetty-docbase.4196461774045134576.8084/],UNAVAILABLE}
-------------- Application Start Failed --------------
org.springframework.context.ApplicationContextException: Failed to start bean 'org.springframework.kafka.config.internalKafkaListenerEndpointRegistry'; nested exception is java.lang.IllegalStateException: Topic(s) [JMETER_LOGS] is/are not present and missingTopicsFatal is true
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:894)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at io.metersphere.streaming.Application.main(Application.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.IllegalStateException: Topic(s) [JMETER_LOGS] is/are not present and missingTopicsFatal is true
	at org.springframework.kafka.listener.AbstractMessageListenerContainer.checkTopics(AbstractMessageListenerContainer.java:383)
	at org.springframework.kafka.listener.ConcurrentMessageListenerContainer.doStart(ConcurrentMessageListenerContainer.java:144)
	at org.springframework.kafka.listener.AbstractMessageListenerContainer.start(AbstractMessageListenerContainer.java:340)
	at org.springframework.kafka.config.KafkaListenerEndpointRegistry.startIfNecessary(KafkaListenerEndpointRegistry.java:312)
	at org.springframework.kafka.config.KafkaListenerEndpointRegistry.start(KafkaListenerEndpointRegistry.java:257)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
	... 22 more

**期待的正确结果**
正确情况下应该是什么样的？
健康状态应该是healthy

**截图**
如果有截图，请附上截图.

![image](https://user-images.githubusercontent.com/33770132/106148874-8cd97080-61b4-11eb-9774-0c3947a05575.png)

**分析说明：**
注意到 bootstrap.servers = 【ip:port】这里的ip地址不正确，ping不通。现在记住了曾经用过的ip地址，但是这个ip已经换了失效了，但是仍然读之前旧的IP。是不是这个ip导致的，但是没找到在哪里去改？

**Comment by wangzhen-fit2cloud** [comment]
你好，请修改 /opt/metersphere/.env 文件中的相关配置后，执行 `msctl reload` 重新加载服务
