### ISSUE TITLE
[BUG]后置脚本使用java提取响应内容后设置变量报错

### ISSUE THREAD

**Issue by cheneys789** [metersphere/metersphere#13092]
### MeterSphere 版本

v1.19.2-b1

### 使用外置数据库

否

### 问题描述

使用后置脚本，beanshell，java代码提取响应内容后，设置变量报错，注释掉vars.put("variable_n", s)正常
String obj = prev.getResponseDataAsString();
cn.hutool.json.JSONObject jsonObject = new cn.hutool.json.JSONObject(obj);
cn.hutool.json.JSONArray result = jsonObject.getJSONObject("data").getJSONArray("allocateList");
int allocateUserNum = 0;
String corpName2 = null;
for (int i = 0; i < result.size(); i++) {
    String corpName = result.getJSONObject(i).getStr("corpName");
    if (corpName.equals("江鑫祥01")) {
        corpName2 = result.getJSONObject(i).getStr("corpName");
        allocateUserNum = result.getJSONObject(i).getInt("allocateUserNum") - 2;
    }
}

String s = String.valueOf(allocateUserNum);
log.info(s)

vars.put("variable_n", s)

### 重现步骤

使用后置脚本，beanshell，java代码提取响应内容后，设置变量 vars.put("variable_n", s)正常

String obj = prev.getResponseDataAsString();

cn.hutool.json.JSONObject jsonObject = new cn.hutool.json.JSONObject(obj);
cn.hutool.json.JSONArray result = jsonObject.getJSONObject("data").getJSONArray("allocateList");
int allocateUserNum = 0;
String corpName2 = null;
for (int i = 0; i < result.size(); i++) {
    String corpName = result.getJSONObject(i).getStr("corpName");
    if (corpName.equals("江鑫祥01")) {
        corpName2 = result.getJSONObject(i).getStr("corpName");
        allocateUserNum = result.getJSONObject(i).getInt("allocateUserNum") - 2;
    }
}

// String s = String.valueOf(allocateUserNum);
log.info("=============")
// log.info(s)
// vars.put("variable_n", s)

### 期待的正确结果

vars.put("variable_n", s) 成功， 不报错

### 相关日志输出

```shell
In file: inline evaluation of: ``String obj = prev.getResponseDataAsString();    cn.hutool.json.JSONObject jsonOb . . . '' Encountered "<EOF>" at line 19, column 29.
 in inline evaluation of: ``String obj = prev.getResponseDataAsString();    cn.hutool.json.JSONObject jsonOb . . . '' at line number 19
javax.script.ScriptException
   at bsh.engine.BshScriptEngine.evalSource(BshScriptEngine.java:82)
   at bsh.engine.BshScriptEngine.eval(BshScriptEngine.java:46)
   at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:253)
   at org.apache.jmeter.extractor.JSR223PostProcessor.process(JSR223PostProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPostProcessors(JMeterThread.java:971)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:586)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:486)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:250)
   at java.lang.Thread.run(Thread.java:748)
```

**Comment by youliyuan-fit2cloud** [comment]
非常抱歉长时间未回复该问题，请检查脚本或者升级到最新版本尝试一下。
