### ISSUE TITLE
[BUG]调用自定义jar包里的静态方法报java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by ast001wang** [metersphere/metersphere#13238]
### 联系方式

wangxiaobo97@hotmail.com

### MeterSphere 版本

v1.19.2

### 使用外置数据库

否

### 问题描述

metersphere平台接口测试 - 前置脚本 - 调用已上传jar包里的静态方法失败

import com.autotest.HttpRequestApi;
HttpRequestApi.signatureRequest(sampler);

### 重现步骤

import com.autotest.HttpRequestApi;
log.info("starting....");

try{

Class.forName("java.lang.StringBuilder");
Class.forName("com.autotest.HttpRequestApi");
    
} catch (Exception e) {
    log.info("eee....");

    log.error("",e);
}

log.info("end3....");

### 期待的正确结果

metersphere平台接口测试 - 前置脚本 - 调用已上传jar包里的静态方法成功

### 相关日志输出

```shell
2022-05-02 22:31:04 INFO ThreadGroup 1-1 starting....
2022-05-02 22:31:04 INFO ThreadGroup 1-1 eee....
2022-05-02 22:31:04 ERROR ThreadGroup 1-1 
com.autotest.HttpRequestApi
java.lang.ClassNotFoundException
   at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
   at java.lang.Class.forName0(Native Method)
   at java.lang.Class.forName(Class.java:264)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:498)
   at bsh.Reflect.invokeMethod(Reflect.java:131)
   at bsh.Reflect.invokeStaticMethod(Reflect.java:95)
   at bsh.Name.invokeMethod(Name.java:793)
   at bsh.BSHMethodInvocation.eval(BSHMethodInvocation.java:69)
   at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:96)
   at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:41)
   at bsh.BSHBlock.evalBlock(BSHBlock.java:125)
   at bsh.BSHBlock.eval(BSHBlock.java:75)
   at bsh.BSHBlock.eval(BSHBlock.java:41)
   at bsh.BSHTryStatement.eval(BSHTryStatement.java:80)
   at bsh.Interpreter.eval(Interpreter.java:659)
   at bsh.Interpreter.eval(Interpreter.java:750)
   at bsh.Interpreter.eval(Interpreter.java:739)
   at bsh.engine.BshScriptEngine.evalSource(BshScriptEngine.java:78)
   at bsh.engine.BshScriptEngine.eval(BshScriptEngine.java:46)
   at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:253)
   at org.apache.jmeter.modifiers.JSR223PreProcessor.process(JSR223PreProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:981)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:546)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:486)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:250)
   at java.lang.Thread.run(Thread.java:748)
2022-05-02 22:31:04 INFO ThreadGroup 1-1 end3....
2022-05-02 22:31:04 INFO ThreadGroup 1-1 Local host = 3339c8772e89
2022-05-02 22:31:04 INFO ThreadGroup 1-1 HTTP request retry count = 0
2022-05-02 22:31:04 INFO ThreadGroup 1-1 Setting up HTTPS TrustAll Socket Factory
2022-05-02 22:31:04 INFO ThreadGroup 1-1 Using default SSL protocol: TLS
2022-05-02 22:31:04 INFO ThreadGroup 1-1 SSL session context: per-thread
2022-05-02 22:31:04 INFO ThreadGroup 1-1 JmeterKeyStore Location:  type JKS
2022-05-02 22:31:04 INFO ThreadGroup 1-1 KeyStore created OK
2022-05-02 22:31:04 WARN ThreadGroup 1-1 Keystore file not found, loading empty keystore
```

### 附加信息

相同的jar包，jmeter本地调用成功。

<img width="859" alt="image (12)" src="https://user-images.githubusercontent.com/104779442/166260439-1930a844-9636-4e97-88b8-76d5bd7eff88.png">
<img width="949" alt="image (13)" src="https://user-images.githubusercontent.com/104779442/166260469-427f7b40-361e-4235-a465-bc6c584a9753.png">

**Comment by ast001wang** [comment]
<img width="801" alt="image (17)" src="https://user-images.githubusercontent.com/104779442/166656341-70c44613-3a2c-462a-bcac-0de5831a4597.png">

**Comment by fit2-zhao** [comment]
@ast001wang  是自定义的jar 吗 确认是否上传成功了；从错误来看应该是jar 没有加载成功。

**Comment by fit2-zhao** [comment]
@ast001wang  方便的话 把jar包发出来看看。

**Comment by ast001wang** [comment]
这个jmeter的包也不行哇。


Sourced file: inline evaluation of: ``import java.math.BigDecimal; import org.apache.jmeter.assertions.AssertionResult . . . '' : Cannot reach instance method: setFailure( boolean ) from static context: org.apache.jmeter.assertions.AssertionResult : at Line: 34 : in file: inline evaluation of: ``import java.math.BigDecimal; import org.apache.jmeter.assertions.AssertionResult . . . '' : AssertionResult .setFailure ( true )

 in inline evaluation of: ``import java.math.BigDecimal; import org.apache.jmeter.assertions.AssertionResult . . . '' at line number 34

javax.script.ScriptException

   at bsh.engine.BshScriptEngine.evalSource(BshScriptEngine.java:93)

   at bsh.engine.BshScriptEngine.eval(BshScriptEngine.java:46)

   at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)

   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:253)

   at org.apache.jmeter.extractor.JSR223PostProcessor.process(JSR223PostProcessor.java:45)

   at org.apache.jmeter.threads.JMeterThread.runPostProcessors(JMeterThread.java:971)

   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:586)

   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:486)

   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:250)

   at java.lang.Thread.run(Thread.java:748)

[cid:bbb6aa9e-e282-4ae1-9288-75d246bf6bdc]


________________________________

**Comment by ast001wang** [comment]
是自定义的jar包，肯定上传成功了，在服务器上/opt/metersphere/data/jar 目录下能看到上传的jar包，服务使用 ./msctl restart 重启过多次。
________________________________

**Comment by ast001wang** [comment]
打包的问题，已解决。

**Comment by ast001wang** [comment]
fixed , jar的问题。
