### ISSUE TITLE
[BUG] 上一个 lts 升级最新 lts 后，过一段时间会报错 org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Increase connection pool size.

### ISSUE THREAD

**Issue by LoopLupe** [metersphere/metersphere#13283]
### 联系方式

子非鱼

### MeterSphere 版本

v1.20.0-lts-c599aa69

### 使用外置数据库

是

### 问题描述

从上一个 lts 版本升级最新的 lts 版本，登录使用 metersphere 平台，过一段时间后会报：

`Caused by: org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Increase connection pool size. Node source: NodeSource [slot=0, addr=null, red
isClient=null, redirect=null, entry=null], connection: RedisConnection@1706596252 [redisClient=[addr=redis://10.193.200.154:6379], channel=[id: 0x60121a79, L:/172.30.10.7:40244 ! R:
10.193.200.154/10.193.200.154:6379], currentCommand=null, usage=1], command: (HGETALL), params: [[115, 112, 114, 105, 110, 103, 58, 115, 101, 115, ...]] after 3 retry attempts
        at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java:281)
        at org.redisson.command.RedisExecutor.access$100(RedisExecutor.java:61)
        at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:164)
        at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java:161)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:999)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:860)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
        at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 common frames omitted
Caused by: io.netty.channel.StacklessClosedChannelException: null
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
2022-05-05 17:41:17,551 [XNIO-1 task-5] ERROR io.undertow.request ? - UT005022: Exception generating error page /error`

### 重现步骤

上面的错误应该是如下错误引起的：
`2022-05-05 17:39:02,656 [redisson-timer-4-1] ERROR o.r.c.handler.PingConnectionHandler ? - Unable to send PING command over channel: [id: 0x5727442c, L:/172.30.10.7:40252 - R:10.193
.200.154/10.193.200.154:6379]
org.redisson.client.RedisException: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are dis
abled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details abo
ut the RDB error.. channel: [id: 0x5727442c, L:/172.30.10.7:40252 - R:10.193.200.154/10.193.200.154:6379] command: (PING), promise: java.util.concurrent.CompletableFuture@153d30bc[N
ot completed, 1 dependents], params: []
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:370)
        at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:198)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:137)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:113)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)`

### 期待的正确结果

升级 lts 时使用的是 metersphere 自带的 redis 配置，将 metersphere 安装配置中 redis 的默认配置 `stop-writes-on-bgsave-error` 设置为 `no`，reload 一下即可解决问题：
<img width="681" alt="image" src="https://user-images.githubusercontent.com/11781785/166902229-903c1b94-cc70-48d1-8108-50a7f7f46bc3.png">

### 附加信息

出现错误时 metersphere 的报错：
![middle_img_v2_6eb7de8a-5d45-4f07-9f8b-25f8ecdf0e9g](https://user-images.githubusercontent.com/11781785/166902080-60fa2aaf-5d34-45a2-b7ad-0868f519630c.jpg)

**Comment by zyyfit** [comment]
报错可能是部署机内存的问题，可以看看这个文章，不过既然你已经找到解决办法了，你提这个issue的目的是什么呢？

https://blog.csdn.net/qq_43178138/article/details/119144986

**Comment by zyyfit** [comment]
您长时间反馈信息，我们将关闭此Issue，如有需要您可以重新打开或提交新的Issue
