### ISSUE TITLE
[BUG] jmeter 内置方法不可用

### ISSUE THREAD

**Issue by ZALZ** [metersphere/metersphere#13439]
### 联系方式

824266572@qq.com

### MeterSphere 版本

 v1.20.0-lts-c599aa69

### 使用外置数据库

否

### 问题描述

jmeter 内置方法不可用

### 重现步骤

1. 添加接口自动化步骤。
2. 参数中使用jmeter 内置函数 ${__time(,)}
3. 选择环境点击调试， 查看响应内容。
4. 内置函数 ${__time(,)} 依旧是方法， 不是预期的时间戳

### 相关日志输出

```shell
java.net.URISyntaxException: Illegal character in query at index 43: https://10.67.2.142:31201/test?start_time=${__time(,)}&end_time=${__time(,)}&pagesize=5&page=1
	at java.base/java.net.URI$Parser.fail(URI.java:2913)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3172)
	at java.base/java.net.URI$Parser.parse(URI.java:3114)
	at java.base/java.net.URI.<init>(URI.java:600)
	at java.base/java.net.URL.toURI(URL.java:1061)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.sample(HTTPHC4Impl.java:620)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:119)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1296)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1285)
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:652)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:571)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:486)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:250)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### 附加信息

![image](https://user-images.githubusercontent.com/25241922/167754469-f482bbb9-bba0-4840-b00e-0295f04a7c22.png)

**Comment by dengying721** [comment]
我也遇到一模一样的问题，版本v1.20.1-lts

**Comment by zrfit** [comment]
您好，请求是在旧版本上升级到最新版本的还是新环境安装的最新版本？

**Comment by ZALZ** [comment]
> 您好，请求是在旧版本上升级到最新版本的还是新环境安装的最新版本？

新环境离线安装的最新版本。
