### ISSUE TITLE
[BUG] 从某项目导出一定数量接口，metersphere格式，导入到新的项目，导入异常，报异常日志

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#13606]
### 联系方式

王进

### MeterSphere 版本

1.20

### 使用外置数据库

否

### 问题描述

从某项目导出一定数量接口，metersphere格式，导入到新的项目，导入异常，报异常日志

### 重现步骤

1. 从百度网盘下载测试文件，客户提供的测试文件
   链接: https://pan.baidu.com/s/1lMSQbm_tQV-0QZlturX62g 提取码: 4pem 
2. 导入到metersphere接口定义下面，解析错误

### 相关日志输出

```shell
2022-05-14 20:40:55,031 [XNIO-1 task-6] ERROR i.m.api.service.ApiDefinitionService ? - Method[apiTestImport][syntax error, pos 3754, line 1, column 3755{"clazzName":"io.metersphere.api.dto.definition.request.sampler.MsHTTPSamplerProxy","type":"HTTPSamplerProxy","id":"3d7b9855-f90e-36ac-84a0-83799aa233b5","name":"Generate Policy Codes","active":false,"enable":true,"hashTree":[{"clazzName":"io.metersphere.api.dto.definition.request.processors.pre.MsJSR223PreProcessor","jSR223PreProcessor":{"cacheKey":"","comment":"","enabled":true,"filename":"","name":"JSR223PreProcessor","parameters":"","script":"","scriptLanguage":"","searchableTokens":["TestElement.enabled","true","TestElement.name","JSR223PreProcessor","TestElement.test_class","org.apache.jmeter.modifiers.JSR223PreProcessor","TestElement.gui_class","org.apache.jmeter.testbeans.gui.TestBeanGUI","scriptLanguage","beanshell","script","vars.put(\"randomInt1\", \"${__time(yyyyMMddHHmmssS,)}\");\r\nvars.put(\"currentTime\", \"${__time(yyyy-MM-dd,)}T${__time(HH:mm:ss.S,)}Z\");"]},"type":"JSR223PreProcessor","id":"4de3ebcb-f60c-409e-bf96-9df1b8437cb3","name":"JSR223PreProcessor","active":true,"enable":true,"mockEnvironment":false,"script":"vars.put(\"randomInt1\", \"${__time(yyyyMMddHHmmssS,)}\");\r\nvars.put(\"currentTime\", \"${__time(yyyy-MM-dd,)}T${__time(HH:mm:ss.S,)}Z\");","scriptLanguage":"beanshell"},{"clazzName":"io.metersphere.api.dto.definition.request.assertions.MsAssertions","document":{"data":{"json":[],"jsonFollowAPI":"false","xml":[],"xmlFollowAPI":"false"},"type":"JSON"},"duration":{"type":"Duration","valid":false,"value":0},"jsonPath":[{"description":"$.result expect: 1","expect":"1","expression":"$.result","option":"EQUALS","type":"JSON","valid":true},{"description":"$.policyCodeList[0] expect: ${p_policyNumber}","expect":"${p_policyNumber}","expression":"$.policyCodeList[0]","option":"EQUALS","type":"JSON","valid":true}],"jsr223":[],"regex":[{"assumeSuccess":false,"description":"Response Code has: ^200$","expression":"^200$","subject":"Response Code","type":"Regex","valid":true}],"type":"Assertions","xpath2":[],"id":"8f0ade58-f0d0-ec7f-e98f-2e74d2e68f88","resourceId":"10357c5c-1475-4887-8198-0964ae60c050","active":true,"enable":true,"mockEnvironment":false},{"clazzName":"io.metersphere.api.dto.definition.request.extract.MsExtract","json":[{"expression":"$.policyCodeList[0]","multipleMatching":false,"type":"JSONPath","valid":true,"value":"${p_policyNumber}","variable":"p_policyNumber"}],"regex":[],"type":"Extract","xpath":[],"id":"8543ab3f-4986-f400-fa9f-9905663ab37f","resourceId":"c92bea6a-85b8-48e1-9541-10e9da0d077c","active":false,"enable":true,"mockEnvironment":false}],"mockEnvironment":false,"protocol":"HTTP","method":"POST","path":"/geminibs-bs/policies/${a_insurerCode}generatePolicyNumbers","headers":[{"enable":true,"file":false,"name":"","required":true,"urlEncode":false,"valid":false,"value":""}],"body":{"binary":[{"enable":true,"file":false,"required":true,"urlEncode":false,"valid":false}],"format":"false","json":true,"jsonSchema":{"$schema":"http://json-schema.org/draft-07/schema#","title":"The Root Schema","type":"object","properties":{"quantity":{"mock":{"mock":1},"title":"The quantity Schema","type":"integer","$id":"#/properties/quantity"},"clientRequestId":{"mock":{"mock":"${randomInt1}"},"title":"The clientRequestId Schema","type":"string","$id":"#/properties/clientRequestId"},"clientRequestTime":{"mock":{"mock":"${currentTime}"},"title":"The clientRequestTime Schema","type":"string","$id":"#/properties/clientRequestTime"}},"$id":"http://example.com/root.json"},"kV":false,"kvs":[{"enable":true,"file":false,"required":true,"type":"text","urlEncode":false,"valid":false}],"oldKV":false,"raw":"{\n   \"clientRequestId\": \"${randomInt1}\",\n    \"clientRequestTime\": \"${currentTime}\",\n    \"quantity\": 1\n}","type":"JSON","valid":true,"xml":false},"rest":[},],"followRedirects":false,"doMultipartPost":false,"useEnvironment":"5e83b37f-51cd-4277-883e-c9d9b13d2a4b","arguments":[],"customizeReq":false}]

com.alibaba.fastjson.JSONException: syntax error, pos 3754, line 1, column 3755{"clazzName":"io.metersphere.api.dto.definition.request.sampler.MsHTTPSamplerProxy","type":"HTTPSamplerProxy","id":"3d7b9855-f90e-36ac-84a0-83799aa233b5","name":"Generate Policy Codes","active":false,"enable":true,"hashTree":[{"clazzName":"io.metersphere.api.dto.definition.request.processors.pre.MsJSR223PreProcessor","jSR223PreProcessor":{"cacheKey":"","comment":"","enabled":true,"filename":"","name":"JSR223PreProcessor","parameters":"","script":"","scriptLanguage":"","searchableTokens":["TestElement.enabled","true","TestElement.name","JSR223PreProcessor","TestElement.test_class","org.apache.jmeter.modifiers.JSR223PreProcessor","TestElement.gui_class","org.apache.jmeter.testbeans.gui.TestBeanGUI","scriptLanguage","beanshell","script","vars.put(\"randomInt1\", \"${__time(yyyyMMddHHmmssS,)}\");\r\nvars.put(\"currentTime\", \"${__time(yyyy-MM-dd,)}T${__time(HH:mm:ss.S,)}Z\");"]},"type":"JSR223PreProcessor","id":"4de3ebcb-f60c-409e-bf96-9df1b8437cb3","name":"JSR223PreProcessor","active":true,"enable":true,"mockEnvironment":false,"script":"vars.put(\"randomInt1\", \"${__time(yyyyMMddHHmmssS,)}\");\r\nvars.put(\"currentTime\", \"${__time(yyyy-MM-dd,)}T${__time(HH:mm:ss.S,)}Z\");","scriptLanguage":"beanshell"},{"clazzName":"io.metersphere.api.dto.definition.request.assertions.MsAssertions","document":{"data":{"json":[],"jsonFollowAPI":"false","xml":[],"xmlFollowAPI":"false"},"type":"JSON"},"duration":{"type":"Duration","valid":false,"value":0},"jsonPath":[{"description":"$.result expect: 1","expect":"1","expression":"$.result","option":"EQUALS","type":"JSON","valid":true},{"description":"$.policyCodeList[0] expect: ${p_policyNumber}","expect":"${p_policyNumber}","expression":"$.policyCodeList[0]","option":"EQUALS","type":"JSON","valid":true}],"jsr223":[],"regex":[{"assumeSuccess":false,"description":"Response Code has: ^200$","expression":"^200$","subject":"Response Code","type":"Regex","valid":true}],"type":"Assertions","xpath2":[],"id":"8f0ade58-f0d0-ec7f-e98f-2e74d2e68f88","resourceId":"10357c5c-1475-4887-8198-0964ae60c050","active":true,"enable":true,"mockEnvironment":false},{"clazzName":"io.metersphere.api.dto.definition.request.extract.MsExtract","json":[{"expression":"$.policyCodeList[0]","multipleMatching":false,"type":"JSONPath","valid":true,"value":"${p_policyNumber}","variable":"p_policyNumber"}],"regex":[],"type":"Extract","xpath":[],"id":"8543ab3f-4986-f400-fa9f-9905663ab37f","resourceId":"c92bea6a-85b8-48e1-9541-10e9da0d077c","active":false,"enable":true,"mockEnvironment":false}],"mockEnvironment":false,"protocol":"HTTP","method":"POST","path":"/geminibs-bs/policies/${a_insurerCode}generatePolicyNumbers","headers":[{"enable":true,"file":false,"name":"","required":true,"urlEncode":false,"valid":false,"value":""}],"body":{"binary":[{"enable":true,"file":false,"required":true,"urlEncode":false,"valid":false}],"format":"false","json":true,"jsonSchema":{"$schema":"http://json-schema.org/draft-07/schema#","title":"The Root Schema","type":"object","properties":{"quantity":{"mock":{"mock":1},"title":"The quantity Schema","type":"integer","$id":"#/properties/quantity"},"clientRequestId":{"mock":{"mock":"${randomInt1}"},"title":"The clientRequestId Schema","type":"string","$id":"#/properties/clientRequestId"},"clientRequestTime":{"mock":{"mock":"${currentTime}"},"title":"The clientRequestTime Schema","type":"string","$id":"#/properties/clientRequestTime"}},"$id":"http://example.com/root.json"},"kV":false,"kvs":[{"enable":true,"file":false,"required":true,"type":"text","urlEncode":false,"valid":false}],"oldKV":false,"raw":"{\n   \"clientRequestId\": \"${randomInt1}\",\n    \"clientRequestTime\": \"${currentTime}\",\n    \"quantity\": 1\n}","type":"JSON","valid":true,"xml":false},"rest":[},],"followRedirects":false,"doMultipartPost":false,"useEnvironment":"5e83b37f-51cd-4277-883e-c9d9b13d2a4b","arguments":[],"customizeReq":false}

        at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1510)

        at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1390)

        at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1268)

        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:530)

        at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1430)

        at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1390)

        at com.alibaba.fastjson.JSON.parse(JSON.java:181)

        at com.alibaba.fastjson.JSON.parse(JSON.java:191)

        at com.alibaba.fastjson.JSON.parse(JSON.java:244)

        at com.alibaba.fastjson.JSON.parseObject(JSON.java:248)

        at io.metersphere.api.dto.definition.parse.MsDefinitionParser.lambda$parseCase$3(MsDefinitionParser.java:151)

        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)

        at io.metersphere.api.dto.definition.parse.MsDefinitionParser.parseCase(MsDefinitionParser.java:149)

        at io.metersphere.api.dto.definition.parse.MsDefinitionParser.parseApiDefinition(MsDefinitionParser.java:140)

        at io.metersphere.api.dto.definition.parse.MsDefinitionParser.lambda$parseMsFormat$2(MsDefinitionParser.java:102)

        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)

        at io.metersphere.api.dto.definition.parse.MsDefinitionParser.parseMsFormat(MsDefinitionParser.java:101)

        at io.metersphere.api.dto.definition.parse.MsDefinitionParser.parse(MsDefinitionParser.java:44)

        at io.metersphere.api.dto.definition.parse.MsDefinitionParser.parse(MsDefinitionParser.java:25)

        at io.metersphere.api.service.ApiDefinitionService.apiTestImport(ApiDefinitionService.java:1187)

        at io.metersphere.api.service.ApiDefinitionService$$FastClassBySpringCGLIB$$72d8ca15.invoke(<generated>)

        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)

        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)

        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)

        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)

        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)

        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)

        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)

        at io.metersphere.api.service.ApiDefinitionService$$EnhancerBySpringCGLIB$$3e7698ad.apiTestImport(<generated>)

        at io.metersphere.api.service.ApiDefinitionService$$FastClassBySpringCGLIB$$72d8ca15.invoke(<generated>)

        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)

        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)

        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)

        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)

        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)

        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)

        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)

        at io.metersphere.api.service.ApiDefinitionService$$EnhancerBySpringCGLIB$$937b86f9.apiTestImport(<generated>)

        at io.metersphere.api.controller.ApiDefinitionController.testCaseImport(ApiDefinitionController.java:216)

        at io.metersphere.api.controller.ApiDefinitionController$$FastClassBySpringCGLIB$$312d2c8b.invoke(<generated>)

        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)

        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)

        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)

        at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)

        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)

        at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:58)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)

        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)

        at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)

        at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:58)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)

        at org.apache.shiro.spring.security.interceptor.AopAllianceAnnotationsAuthorizingMethodInterceptor$1.proceed(AopAllianceAnnotationsAuthorizingMethodInterceptor.java:82)

        at org.apache.shiro.authz.aop.AuthorizingMethodInterceptor.invoke(AuthorizingMethodInterceptor.java:39)

        at org.apache.shiro.spring.security.interceptor.AopAllianceAnnotationsAuthorizingMethodInterceptor.invoke(AopAllianceAnnotationsAuthorizingMethodInterceptor.java:115)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)

        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)

        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)

        at io.metersphere.api.controller.ApiDefinitionController$$EnhancerBySpringCGLIB$$95e86012.testCaseImport(<generated>)

        at io.metersphere.api.controller.ApiDefinitionController$$FastClassBySpringCGLIB$$312d2c8b.invoke(<generated>)

        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)

        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)

        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)

        at org.apache.shiro.spring.security.interceptor.AopAllianceAnnotationsAuthorizingMethodInterceptor$1.proceed(AopAllianceAnnotationsAuthorizingMethodInterceptor.java:82)

        at org.apache.shiro.authz.aop.AuthorizingMethodInterceptor.invoke(AuthorizingMethodInterceptor.java:39)

        at org.apache.shiro.spring.security.interceptor.AopAllianceAnnotationsAuthorizingMethodInterceptor.invoke(AopAllianceAnnotationsAuthorizingMethodInterceptor.java:115)

        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)

        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)

        at io.metersphere.api.controller.ApiDefinitionController$$EnhancerBySpringCGLIB$$323bbe06.testCaseImport(<generated>)

        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.base/java.lang.reflect.Method.invoke(Method.java:566)

        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)

        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)

        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)

        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)

        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)

        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)

        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)

        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)

        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)

        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)

        at javax.servlet.http.HttpServlet.service(HttpServlet.java:517)

        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)

        at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)

        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)

        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)

        at io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:173)

        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)

        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)

        at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:67)

        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)

        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)

        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:112)

        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)

        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)

        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)

        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)

        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)

        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)

        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)

        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)

        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)

        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)

        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)

        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)

        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)

        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)

        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)

        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)

        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)

        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)

        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)

        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:450)

        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)

        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)

        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)

        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)

        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)

        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)

        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)

        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)

        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)

        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)

        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)

        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)

        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)

        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)

        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)

        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)

        at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:142)

        at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:82)

        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)

        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)

        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)

        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)

        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)

        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)

        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)

        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)

        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)

        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)

        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)

        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)

        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)

        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)

        at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)

        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)

        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)

        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)

        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)

        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)

        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)

        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)

        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)

        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)

        at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)

        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)

        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)

        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)

        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)

        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)

        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)

        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)

        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)

        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)

        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)

        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)

        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)

        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)

        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)

        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)

        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)

        at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)

        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by youliyuan-fit2cloud** [comment]
文件格式错误
![image](https://user-images.githubusercontent.com/54612864/169455424-045fc45b-0602-468e-8fca-aa6d5b0896ca.png)
