### ISSUE TITLE
[BUG] 开源项目，新建项目后创建接口失败

### ISSUE THREAD

**Issue by meihaoyidian** [metersphere/metersphere#13657]
### 联系方式

vida112728@gmail.com

### MeterSphere 版本

v1.20

### 使用外置数据库

是

### 问题描述

![image](https://user-images.githubusercontent.com/26756176/168772769-8e8017e9-451c-41cf-bd65-fc8a0c5025dd.png)

### 重现步骤

开源版本，新建项目后，创建分组，创建接口报错
![image](https://user-images.githubusercontent.com/26756176/168773145-cd1ad249-efe5-4d7e-8ece-5b06f3916311.png)

### 相关日志输出

```shell
Caused by: java.lang.RuntimeException: Value for versionId cannot be null
	at io.metersphere.base.domain.ApiDefinitionExample$GeneratedCriteria.addCriterion(ApiDefinitionExample.java:95)
	at io.metersphere.base.domain.ApiDefinitionExample$GeneratedCriteria.andVersionIdEqualTo(ApiDefinitionExample.java:1818)
	at io.metersphere.base.domain.ApiDefinitionExample$Criteria.andVersionIdEqualTo(ApiDefinitionExample.java:1938)
	at io.metersphere.api.service.ApiDefinitionService.checkNameExist(ApiDefinitionService.java:509)
	at io.metersphere.api.service.ApiDefinitionService.createTest(ApiDefinitionService.java:718)
	at io.metersphere.api.service.ApiDefinitionService.create(ApiDefinitionService.java:329)
	at io.metersphere.api.service.ApiDefinitionService$$FastClassBySpringCGLIB$$72d8ca15.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
```

**Comment by zrfit** [comment]
与该问题为同一个问题，[BUG]新增项目，接口定义，创建接口报错 #13379，测试环境未复现，辛苦研发跟进下。

**Comment by meihaoyidian** [comment]
必现的问题。开源版本，新建项目后创建接口就出现了

zrfit ***@***.***> 于2022年5月17日周二 18:08写道：

**Comment by youliyuan-fit2cloud** [comment]
v1.20.3-lts版本修复了，升级一下吧
