### ISSUE TITLE
[BUG]kafka异常，Error processing fetch with max size 1048576 from consumer on partition JMETER_METRICS-2

### ISSUE THREAD

**Issue by seasoncool** [metersphere/metersphere#13682]
### MeterSphere 版本

v1.19.1

### 使用外置数据库

否

### 问题描述

我们在做稳定性测试，挂机超过24小时，在此期间kafka出现了报错信息，**导致磁盘容量暴增，性能测试页面数据不刷新**。

### 重现步骤

我们做了2件事情：
1. 持续挂机超过8小时以上
2. 查看硬盘容量暴增后，我们手动清理 kafka下面的.log 文件

### 期待的正确结果

稳定性测试后，无用的日志自行清理，以免造成磁盘爆掉，导致测试失败，同时性能测试页面（WEBUI）实时刷新数据。

### 相关日志输出

```shell
[2022-05-17 03:59:59,996] ERROR [ReplicaManager broker=1001] Error processing fetch with max size 1048576 from consumer on partition JMETER_METRICS-2: (fetchOffset=30829443, logStartOffset=-1, maxBytes=1048576, currentLeaderEpoch=Optional[0]) (kafka.server.ReplicaManager)
org.apache.kafka.common.KafkaException: java.io.EOFException: Failed to read `log header` from file channel `sun.nio.ch.FileChannelImpl@7436edc2`. Expected to read 17 bytes, but reached end of file after reading 0 bytes. Started read from position 607040150.
        at org.apache.kafka.common.record.RecordBatchIterator.makeNext(RecordBatchIterator.java:40)
        at org.apache.kafka.common.record.RecordBatchIterator.makeNext(RecordBatchIterator.java:24)
        at org.apache.kafka.common.utils.AbstractIterator.maybeComputeNext(AbstractIterator.java:79)
        at org.apache.kafka.common.utils.AbstractIterator.hasNext(AbstractIterator.java:45)
        at org.apache.kafka.common.record.FileRecords.searchForOffsetWithSize(FileRecords.java:299)
        at kafka.log.LogSegment.translateOffset(LogSegment.scala:275)
        at kafka.log.LogSegment.read(LogSegment.scala:298)
        at kafka.log.Log.$anonfun$read$2(Log.scala:1500)
        at kafka.log.Log.read(Log.scala:2318)
        at kafka.cluster.Partition.$anonfun$readRecords$1(Partition.scala:1006)
        at kafka.cluster.Partition.readRecords(Partition.scala:996)
        at kafka.server.ReplicaManager.read$1(ReplicaManager.scala:997)
        at kafka.server.ReplicaManager.$anonfun$readFromLocalLog$8(ReplicaManager.scala:1069)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at kafka.server.ReplicaManager.readFromLocalLog(ReplicaManager.scala:1068)
        at kafka.server.ReplicaManager.readFromLog$1(ReplicaManager.scala:882)
        at kafka.server.ReplicaManager.fetchMessages(ReplicaManager.scala:887)
        at kafka.server.KafkaApis.handleFetchRequest(KafkaApis.scala:827)
        at kafka.server.KafkaApis.handle(KafkaApis.scala:129)
        at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:70)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.EOFException: Failed to read `log header` from file channel `sun.nio.ch.FileChannelImpl@7436edc2`. Expected to read 17 bytes, but reached end of file after reading 0 bytes. Started read from position 607040150.
```

**Comment by liuruibin** [comment]
你可以调整kafka的日志保留时间来解决磁盘占用问题
<img width="783" alt="image" src="https://user-images.githubusercontent.com/23045261/168991061-c311db44-8c46-4635-8685-d96a5b92a42e.png">
