### ISSUE TITLE
[BUG]断言脚本报错mismatched input '' expecting DEDENT in <script>

### ISSUE THREAD

**Issue by Faerie1999** [metersphere/metersphere#13764]
### 联系方式

714318994@qq.com

### MeterSphere 版本

v1.20.2

### 使用外置数据库

是

### 问题描述

调试过程中， 断言脚本出现打印了以下错误：
```
SyntaxError: mismatched input '' expecting DEDENT in <script> at line number 19 at column number 5
javax.script.ScriptException
   at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:213)
   at org.python.jsr223.PyScriptEngine.compileScript(PyScriptEngine.java:93)
   at org.python.jsr223.PyScriptEngine.compile(PyScriptEngine.java:76)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:251)
   at org.apache.jmeter.assertions.JSR223Assertion.getResult(JSR223Assertion.java:50)
   at org.apache.jmeter.threads.JMeterThread.processAssertion(JMeterThread.java:951)
   at org.apache.jmeter.threads.JMeterThread.checkAssertions(JMeterThread.java:920)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:591)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:487)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:251)
   at java.base/java.lang.Thread.run(Thread.java:829)
```
这个是否是metersphere底层代码爆出的错误？是否脚本编译有问题？
这个错误出现在断言脚本里面，出现过好几次了，有时候重新复制一下没有了，有时候一直出现，暂时没有找到他出现的规律，且我将代码去掉AssertionResult.setFailureMessage(msg)
AssertionResult.setFailure(True)这两行，放到后置脚本中，没有报错，说明脚本本身应该语法没问题。

### 重现步骤

不规律偶现bug

**Comment by zrfit** [comment]
您好，只提供一个报错这边没法复现呢，1、是api-test？api-case？自动化场景？哪里设置的断言脚本？ 能否提供您的文件，我们尝试复现问题。

**Comment by Faerie1999** [comment]
在自动化场景中的一个接口步骤中的断言tag里，选择脚本断言，并在里面自己写脚本后（并非自动生成的脚本），发现会报这个错误。
至于文件，它是一个比较奇怪的bug，同样的文件（从未修改过内容），我后来重新复制了一遍之后，又不会出现这个报错，所以我怀疑脚本的编译或者解析是否有问题。
今天我又遇到了，同样是在场景中的一个接口步骤中，在前置脚本里面出现了类似的报错（控制台报错），而且我之前运行过，没有报错的，之后也没有修改过，今天运行突然报错，报错如下：

```
ValueError: No JSON object could be decoded in <script> at line number 15
javax.script.ScriptException
   at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:222)
   at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:59)
   at org.python.jsr223.PyScriptEngine.access$300(PyScriptEngine.java:20)
   at org.python.jsr223.PyScriptEngine$PyCompiledScript.eval(PyScriptEngine.java:250)
   at java.scripting/javax.script.CompiledScript.eval(CompiledScript.java:89)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:260)
   at org.apache.jmeter.extractor.JSR223PostProcessor.process(JSR223PostProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPostProcessors(JMeterThread.java:975)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:590)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:487)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:251)
   at java.base/java.lang.Thread.run(Thread.java:829)
```
它会提示报错行数，但是实际上那一行没有问题，第15行的代码是一个导入：
`import java.util.HashMap;`
我将代码重新复制粘贴之后，又没有报错了，因此不太好提供文件，只能描述大概是这样的，都是脚本中偶现的问题，比较影响使用.

**Comment by zrfit** [comment]
您好，您也说了时好时坏，而且是自己写的脚本，如果不保密的话可以把api导出和场景导出单独发到邮箱中，复现问题才能去定位和排查，多谢。
