### ISSUE TITLE
[BUG]  调试接口报错 IllegalArgumentException:User name may not be  null

### ISSUE THREAD

**Issue by Ycr123888** [metersphere/metersphere#14082]
### 联系方式

18311441708

### MeterSphere 版本

1.20.2

### 使用外置数据库

否

### 问题描述

用户导入license文件前，接口都能测试成功，导入文件后，出现图中问题
同样的接口，用postman可以调试通过，但是ms就不通。网络也查看了，通的，防火墙也是关闭的
![495694920378467259](https://user-images.githubusercontent.com/103925124/170674292-0875f077-6b12-41fe-bbcf-e92bff903ac7.jpg)

### 重现步骤

客户删除redis中数据
重新服务，清除缓存
此问题均存在，重现步骤不确定

报的错中SecurityManager没初始化，是因为没有正常登录造成
调用 /login接口之前，从shiro调用SecurityUtils.getSubject()获取主体信息，所以报错
<img width="587" alt="1653647677(1)" src="https://user-images.githubusercontent.com/103925124/170683565-0701f150-7a37-49ed-a440-8d81a678091a.png">
https://blog.csdn.net/Mint6/article/details/104346675

### 期待的正确结果

postman 可正常调用的接口
ms可正常调用

### 相关日志输出

```shell
d to the org.apache.shiro.util.ThreadContext or as a vm static singleton.  This is an invalid application configuration.]
org.apache.shiro.UnavailableSecurityManagerException: No SecurityManager accessible to the calling code, either bound to the org.apache.shiro.util.ThreadContext or as a vm
 static singleton.  This is an invalid application configuration.
	at org.apache.shiro.SecurityUtils.getSecurityManager(SecurityUtils.java:123)
	at org.apache.shiro.subject.Subject$Builder.<init>(Subject.java:626)
	at org.apache.shiro.SecurityUtils.getSubject(SecurityUtils.java:56)
	at io.metersphere.commons.utils.SessionUtils.getUser(SessionUtils.java:32)
	at io.metersphere.commons.utils.SessionUtils.getUserId(SessionUtils.java:26)
	at io.metersphere.service.UserService.getCurrentPlatformInfo(UserService.java:1289)
	at io.metersphere.service.UserService$$FastClassBySpringCGLIB$$a338bc71.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at io.metersphere.service.UserService$$EnhancerBySpringCGLIB$$d3fd7008.getCurrentPlatformInfo(<generated>)
	at io.metersphere.service.UserService$$FastClassBySpringCGLIB$$a338bc71.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
```

### 附加信息

<img width="957" alt="f15d89ed9eead3712e75469b24a360bc_" src="https://user-images.githubusercontent.com/103925124/170683745-f99d5b3a-685d-49fe-bcc5-c7bf6cabef85.png">

**Comment by Ycr123888** [comment]
非MS产品bug
