### ISSUE TITLE
[BUG] 接口用例Delete请求服务抛出异常“No SecurityManager accessible to the calling code”

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#14152]
### 联系方式

王进

### MeterSphere 版本

1.20

### 使用外置数据库

否

### 问题描述

完全相同的请求在postman可以成功发出delete 操作

但是在ms上爆异常，请求没有发出去，因为服务端没有收到delete操作

### 重现步骤

1. 下面是 客户接口用例detele操作发出去的请求内容：
请求地址:
http://api-noauth.project.test.huansi.net/paas-userright-manager/api/tenant1?ids=1516971694811111111
请求头:
Connection: keep-alive
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjFCQzIzNkNFNUZDRkY2ODBGQjdFRTcwNjNGQzAxQUY3IiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE2NTM2NTQ2MDIsImV4cCI6MTY1MzY5MDYwMiwiaXNzIjoiaHR0cHM6Ly90ZXN0LWhhbmd6aG91Lm9hdXRoLnNhYXMuaHVhbnNpLm5ldCIsImF1ZCI6WyJVc2VyUmlnaHQiLCJodHRwczovL3Rlc3QtaGFuZ3pob3Uub2F1dGguc2Fhcy5odWFuc2kubmV0L3Jlc291cmNlcyJdLCJjbGllbnRfaWQiOiJhcHBtYXJrZXQgaW1wbGljaXQgY2xpZW50Iiwic3ViIjoiMTQzNjIxNDEzNTU5ODc0NzY0OSIsImF1dGhfdGltZSI6MTY1MzY1NDYwMiwiaWRwIjoibG9jYWwiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiIxNTE3MDEyNjUyMyIsIm5hbWUiOiLkuKrkurrlkajlkagiLCJ0ZW5hbnRfaWQiOiIxNDM2MjE0MTM1NTk4NzQ3NjQ4IiwidGVuYW50X2NvZGUiOiJjc3RkIiwicm9sZSI6Iui2hee6p-euoeeQhuWRmCIsImlzX2FkbWluIjp0cnVlLCJzaWQiOiJEOEJBQjBBQTAyNzlCOTBDMjZDNjc4RUVBNDg5Q0M0MCIsImlhdCI6MTY1MzY1NDYwMiwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsInJvbGUiLCJVc2VyUmlnaHQiXSwiYW1yIjpbInB3ZCJdfQ.nfro_ZFog2SOmWfbeXo86uSAgZbVcdUTpejex-sk4d2RPR0zyilRAawZwcyZoBoR-9jLF0vudknqw6rUXgbdLIXZQl2q3BHE8zjT8yyIA81BU_GRKuXgMQVOrc1JIBJnOiDZGcmij7gXL1_6WNv2H9XG8YNRuWd8dt9yw1B8_ht7Pc9lIDChTXHGKkKdkSWVuAFG70LUM8Q5uwPR09xPbG7KnMaBER9a9TpMUwkQ37WVp8-e6uOPrJf2CBaSu1-V4afkgouzz6MGcUF5vjD0GyLL1Yd3M_PqThkDAIv6aaWZKfhLoLxK8ZjMCf0PKKe9OF_69Ir1H-yPkbWtrVsvfw
Content-Type: application/json;charset=UTF-8
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 Edg/98.0.1108.62
Content-Length: 0
Host: api-noauth.project.test.huansi.net

Cookies :

Body:
DELETE http://api-noauth.project.test.huansi.net/paas-userright-manager/api/tenant1?ids=1516971694811111111

DELETE data:

[no cookies]

后台爆出异常：
2022-05-27 20:42:06,892 [Thread-3191] ERROR i.m.commons.utils.SessionUtils 176 - Method[getUser][No SecurityManager accessible to the calling code, either bound to the org.apache.shiro.util.ThreadContext or as a vm static singleton.  This is an invalid application configuration.]
org.apache.shiro.UnavailableSecurityManagerException: No SecurityManager accessible to the calling code, either bound to the org.apache.shiro.util.ThreadContext or as a vm static singleton.  This is an invalid application configuration.
        at org.apache.shiro.SecurityUtils.getSecurityManager(SecurityUtils.java:123)
        at org.apache.shiro.subject.Subject$Builder.<init>(Subject.java:626)
        at org.apache.shiro.SecurityUtils.getSubject(SecurityUtils.java:56)
        at io.metersphere.commons.utils.SessionUtils.getUser(SessionUtils.java:32)
        at io.metersphere.commons.utils.SessionUtils.getUserId(SessionUtils.java:26)
        at io.metersphere.api.service.ApiDefinitionExecResultService.sendNotice(ApiDefinitionExecResultService.java:186)
        at io.metersphere.api.service.ApiDefinitionExecResultService.saveApiResult(ApiDefinitionExecResultService.java:96)
        at io.metersphere.api.service.ApiDefinitionExecResultService$$FastClassBySpringCGLIB$$55a9a227.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
        at io.metersphere.api.service.ApiDefinitionExecResultService$$EnhancerBySpringCGLIB$$51209f34.saveApiResult(<generated>)
        at io.metersphere.api.service.ApiDefinitionExecResultService$$FastClassBySpringCGLIB$$55a9a227.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
        at io.metersphere.api.service.ApiDefinitionExecResultService$$EnhancerBySpringCGLIB$$97440dcc.saveApiResult(<generated>)
        at io.metersphere.api.service.TestResultService.saveResults(TestResultService.java:117)
        at io.metersphere.api.service.TestResultService$$FastClassBySpringCGLIB$$63cf7459.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
        at io.metersphere.api.service.TestResultService$$EnhancerBySpringCGLIB$$6526050a.saveResults(<generated>)
        at io.metersphere.api.service.TestResultService$$FastClassBySpringCGLIB$$63cf7459.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
        at io.metersphere.api.service.TestResultService$$EnhancerBySpringCGLIB$$a975beae.saveResults(<generated>)
        at io.metersphere.api.jmeter.APISingleResultListener.handleTeardownTest(APISingleResultListener.java:36)
        at io.metersphere.jmeter.MsBackendListenerClient.handleSampleResults(MsBackendListenerClient.java:41)
        at org.apache.jmeter.visualizers.backend.BackendListener.sendToListener(BackendListener.java:254)
        at org.apache.jmeter.visualizers.backend.BackendListener.access$600(BackendListener.java:50)
        at org.apache.jmeter.visualizers.backend.BackendListener$Worker.run(BackendListener.java:225)
2022-05-27 20:42:06,897 [Async-Executor-14] INFO  i.m.n.sender.impl.InSiteNoticeSender ? - Method[sendAnnouncement][发送站内通知: [Receiver(userId=hanfengtao, type=SYSTEM_NOTICE)]]

### 期待的正确结果

MS的Delete请求应该发送出去

### 附加信息

开发同学能不能从异常日志发现点问题。

异常爆出的权限错误，之前没碰到过。

**Comment by zyyfit** [comment]
我用kubeoperator系统的delete接口测试了一下，是没有问题的
![image](https://user-images.githubusercontent.com/73461316/171096461-be56434e-6ab8-4780-9c19-b240ea6f0b83.png)
