### ISSUE TITLE
[BUG]性能测试：点击保存并运行时报错:Could not extract response: no suitable HttpMessageConverter found

### ISSUE THREAD

**Issue by Notfound1011** [metersphere/metersphere#1432]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.7.2-bd12a36a
**Bug 描述**
简要描述您碰到的问题
页面报错：【Could not extract response: no suitable HttpMessageConverter found for response type [class io.metersphere.controller.ResultHolder] and content type [text/html]】

后台日志：
2021-02-07 23:52:23,018 [qtp1234586997-243] ERROR i.m.c.handler.GlobalExceptionHandler 52 - Fail to proceed /performance/run
org.springframework.web.client.RestClientException: Could not extract response: no suitable HttpMessageConverter found for response type [class io.metersphere.controller.ResultHolder] and content type [text/html]
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:123)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:741)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:674)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:315)
	at io.metersphere.performance.engine.docker.DockerTestEngine.lambda$stop$4(DockerTestEngine.java:125)

**Bug 重现步骤**
1.  已经创建好场景，添加性能测试
2. 进入性能测试页面
3. 点击保存并运行
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/37465937/107152304-261d3980-69a2-11eb-996f-758ac56ae514.png)
![image](https://user-images.githubusercontent.com/37465937/107152316-38977300-69a2-11eb-9104-07a2c75d186e.png)

**Comment by liuruibin** [comment]
是自己代码部署的吗

**Comment by Notfound1011** [comment]
> 是自己代码部署的吗

我用的是quick_start.sh脚本，一键快速部署的

**Comment by liuruibin** [comment]
仍然没有复现
