### ISSUE TITLE
[BUG]jenkins上面执行测试计划日志提示npe

### ISSUE THREAD

**Issue by hymylove** [metersphere/metersphere#14471]
### 联系方式

heyuan02@imdada.cn

### MeterSphere 版本

20.5

### 使用外置数据库

是

### 问题描述

jenkins上面执行测试计划日志提示npe

### 重现步骤

jenkins上面执行测试计划日志提示npe

### 相关日志输出

```shell
2022-06-07 19:54:58,993 [XNIO-1 task-4] ERROR io.undertow.request ? - UT005023: Exception handling request to /test/plan/report/status/
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:497)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
```

**Comment by youliyuan-fit2cloud** [comment]
你好，请描述以下具体复现步骤
需要确认
1.jenkins 是不是最新的版本
2.jenkins里面的配置截图
3.测试计划里面关联了哪些用例，接口case？场景用例还是性能测试用例？
