### ISSUE TITLE
[BUG]性能测试引用两个以上带证书的场景保存报错

### ISSUE THREAD

**Issue by fit2cloud-yangxiaoyan** [metersphere/metersphere#14669]
### 联系方式

杨晓燕

### MeterSphere 版本

1.20.5

### 使用外置数据库

否

### 问题描述

性能测试引用两个以上带证书的场景保存的时候报sql错误，cloud环境可复现

### 重现步骤

1、创建一个带证书的环境
<img width="944" alt="3" src="https://user-images.githubusercontent.com/72729206/173020878-41de369d-6619-4eb2-a5a5-ccb209dc661e.png">
2、创建两个需要带证书的场景，并引用步骤1的环境
<img width="1439" alt="4" src="https://user-images.githubusercontent.com/72729206/173021015-52bf4ace-8acb-45fb-ba76-4898422c4618.png">
3、创建性能测试，引用场景（步骤2的两个场景），保存
![Uploading 2.png…]()

### 期待的正确结果

1、可以正常保存

### 相关日志输出

```shell
2022-06-10 14:51:46,116 [XNIO-1 task-2] ERROR i.m.c.h.RestControllerExceptionHandler 176 - Method[sqlExceptionHandler][Duplicate entry '70224493-2814-480e-84be-d54095ef9f1d-44c40bf9-733d-430d-9ea9-6e6' for key 'load_test_file_unique_key']
java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '70224493-2814-480e-84be-d54095ef9f1d-44c40bf9-733d-430d-9ea9-6e6' for key 'load_test_file_unique_key'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at jdk.internal.reflect.GeneratedMethodAccessor454.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64)
	at com.sun.proxy.$Proxy399.update(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor454.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at io.metersphere.interceptor.MybatisInterceptor.intercept(MybatisInterceptor.java:38)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at com.sun.proxy.$Proxy399.update(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor454.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64)
	at com.sun.proxy.$Proxy399.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:194)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:181)
	at jdk.internal.reflect.GeneratedMethodAccessor1049.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by fit2cloud-yangxiaoyan** [comment]
<img width="1439" alt="2" src="https://user-images.githubusercontent.com/72729206/173299305-4a9de436-b905-4e58-be73-675e90714a84.png">
刚刚发现最后一张图片没展示出来，补充

**Comment by xulinde** [comment]
客户环境方便提供下吗

**Comment by fit2cloud-yangxiaoyan** [comment]
> 客户环境方便提供下吗

cloud环境就可以复现
