### ISSUE TITLE
[BUG]MQTT，10线程并发，"错误记录"页面抛出502 Client [wjz_test] failed with exception. jmeter.log有个空指针错误。

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#14965]
### 联系方式

王进

### MeterSphere 版本

1.20.6

### 使用外置数据库

否

### 问题描述

MQTT，10线程并发，"错误记录"页面抛出502 Client [wjz_test] failed with exception. jmeter.log有个空指针错误。

### 重现步骤

1. 基于标准版镜像，新做一个镜像，把mqtt jar包打到原来镜像
FROM  registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master:5.4.3-ms5-jdk11  
ADD /extra/metersphere-plugin-mqtt-1.2.4-jar-with-all-dependencies.jar  /opt/jmeter/lib/ext/  

docker build -t registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master:5.4.4-ms5-jdk11 .
2. 把ms资源池里面的镜像 改成定制镜像registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master:5.4.4-ms5-jdk11
3. 调试通过的mqtt接口自动化场景 列表页，创建性能测试
4. 上传mqtt jar包，设置10个线程，执行测试
5. 看到错误消息，还有空指针记录

### 相关日志输出

```shell
2022-06-16 11:24:27,531 Setting Locale to en_EN
2022-06-16 11:24:27,778 Loading user properties from: /opt/jmeter/bin/user.properties
2022-06-16 11:24:27,780 Loading system properties from: /opt/jmeter/bin/system.properties
2022-06-16 11:24:27,788 Copyright (c) 1998-2021 The Apache Software Foundation
2022-06-16 11:24:27,791 Version 5.4.3
2022-06-16 11:24:27,793 java.version=11.0.15
2022-06-16 11:24:27,795 java.vm.name=OpenJDK 64-Bit Server VM
2022-06-16 11:24:27,797 os.name=Linux
2022-06-16 11:24:27,798 os.arch=amd64
2022-06-16 11:24:27,801 os.version=4.15.0-66-generic
2022-06-16 11:24:27,802 file.encoding=UTF-8
2022-06-16 11:24:27,804 java.awt.headless=true
2022-06-16 11:24:27,806 Max memory     =1073741824
2022-06-16 11:24:27,808 Available Processors =8
2022-06-16 11:24:27,817 Default Locale=English (EN)
2022-06-16 11:24:27,819 JMeter  Locale=English (EN)
2022-06-16 11:24:27,822 JMeterHome=/opt/jmeter
2022-06-16 11:24:27,824 user.dir  =/jmeter-log
2022-06-16 11:24:27,825 PWD       =/jmeter-log
2022-06-16 11:24:27,827 IP: 127.0.1.1 Name: compass FullName: compass
2022-06-16 11:24:27,829 user.classpath=/test/
2022-06-16 11:24:27,830 Adding to classpath and loader: /test/
2022-06-16 11:24:27,836 Default base='/jmeter-log'
2022-06-16 11:24:27,839 Set new base='/test'
2022-06-16 11:24:27,987 Testplan (JMX) version: 2.2. Testlog (JTL) version: 2.2
2022-06-16 11:24:28,018 Using SaveService properties version 5.0
2022-06-16 11:24:28,022 Using SaveService properties file encoding UTF-8
2022-06-16 11:24:28,025 Loading file: /test/018476d7-32ae-4026-bb47-7a60f1a844c4.jmx
2022-06-16 11:24:28,061 Note: Sample TimeStamps are START times
2022-06-16 11:24:28,063 sampleresult.default.encoding is set to UTF-8
2022-06-16 11:24:28,065 sampleresult.useNanoTime=true
2022-06-16 11:24:28,067 sampleresult.nanoThreadSleep=5000
2022-06-16 11:24:28,086 Creating summariser <summary>
2022-06-16 11:24:28,094 Running the test!
2022-06-16 11:24:28,097 List of sample_variables: []
2022-06-16 11:24:28,098 List of sample_variables: []
2022-06-16 11:24:28,103 Note: Function class names must contain the string: '.functions.'
2022-06-16 11:24:28,105 Note: Function class names must not contain the string: '.gui.'
2022-06-16 11:24:28,379 Backend Listener: Starting worker with class: class io.github.rahulsinghai.jmeter.backendlistener.kafka.KafkaBackendClient and queue capacity: 20000
2022-06-16 11:24:28,382 Backend Listener: Started  worker with class: class io.github.rahulsinghai.jmeter.backendlistener.kafka.KafkaBackendClient
2022-06-16 11:24:28,408 Running test (1655349868408)
2022-06-16 11:24:28,427 Starting ThreadGroup: 1 : 建立MQTT连接-0
2022-06-16 11:24:28,429 Starting 10 threads for group 建立MQTT连接-0.
2022-06-16 11:24:28,431 Thread will continue on error
2022-06-16 11:24:28,433 Starting thread group... number=1 threads=10 ramp-up=5 delayedStart=false
2022-06-16 11:24:28,441 Started thread group number 1
2022-06-16 11:24:28,441 Thread started: 建立MQTT连接-0 1-1
2022-06-16 11:24:28,443 All thread groups have been started
2022-06-16 11:24:28,936 Thread started: 建立MQTT连接-0 1-2
2022-06-16 11:24:29,437 Thread started: 建立MQTT连接-0 1-3
2022-06-16 11:24:29,937 Thread started: 建立MQTT连接-0 1-4
2022-06-16 11:24:30,436 Thread started: 建立MQTT连接-0 1-5
2022-06-16 11:24:30,936 Thread started: 建立MQTT连接-0 1-6
2022-06-16 11:24:31,436 Thread started: 建立MQTT连接-0 1-7
2022-06-16 11:24:31,935 Thread started: 建立MQTT连接-0 1-8
2022-06-16 11:24:32,435 Thread started: 建立MQTT连接-0 1-9
2022-06-16 11:24:32,936 Thread started: 建立MQTT连接-0 1-10
2022-06-16 11:25:00,462 summary +     49 in 00:00:32 =    1.5/s Avg:  5108 Min:     0 Max: 10224 Err:    49 (100.00%) Active: 10 Started: 10 Finished: 0
2022-06-16 11:25:30,482 summary +     60 in 00:00:30 =    2.0/s Avg:  5001 Min:     0 Max: 10006 Err:    60 (100.00%) Active: 10 Started: 10 Finished: 0
2022-06-16 11:25:30,487 summary =    109 in 00:01:02 =    1.8/s Avg:  5049 Min:     0 Max: 10224 Err:   109 (100.00%)
2022-06-16 11:26:00,499 summary +     60 in 00:00:30 =    2.0/s Avg:  5001 Min:     0 Max: 10004 Err:    60 (100.00%) Active: 10 Started: 10 Finished: 0
2022-06-16 11:26:00,508 summary =    169 in 00:01:32 =    1.8/s Avg:  5032 Min:     0 Max: 10224 Err:   169 (100.00%)
2022-06-16 11:26:08,777 Thread is done: 建立MQTT连接-0 1-1
2022-06-16 11:26:08,781 Thread finished: 建立MQTT连接-0 1-1
2022-06-16 11:26:08,997 Thread is done: 建立MQTT连接-0 1-2
2022-06-16 11:26:09,003 Thread finished: 建立MQTT连接-0 1-2
2022-06-16 11:26:09,473 Thread is done: 建立MQTT连接-0 1-3
2022-06-16 11:26:09,478 Thread finished: 建立MQTT连接-0 1-3
2022-06-16 11:26:09,982 Thread is done: 建立MQTT连接-0 1-4
2022-06-16 11:26:09,987 Thread finished: 建立MQTT连接-0 1-4
2022-06-16 11:26:10,519 Thread is done: 建立MQTT连接-0 1-5
2022-06-16 11:26:10,524 Thread finished: 建立MQTT连接-0 1-5
2022-06-16 11:26:10,977 Thread is done: 建立MQTT连接-0 1-6
2022-06-16 11:26:10,981 Thread finished: 建立MQTT连接-0 1-6
2022-06-16 11:26:11,485 Thread is done: 建立MQTT连接-0 1-7
2022-06-16 11:26:11,490 Thread finished: 建立MQTT连接-0 1-7
2022-06-16 11:26:11,973 Thread is done: 建立MQTT连接-0 1-8
2022-06-16 11:26:11,977 Thread finished: 建立MQTT连接-0 1-8
2022-06-16 11:26:12,481 Thread is done: 建立MQTT连接-0 1-9
2022-06-16 11:26:12,483 Thread finished: 建立MQTT连接-0 1-9
2022-06-16 11:26:12,978 Thread is done: 建立MQTT连接-0 1-10
2022-06-16 11:26:12,981 Thread finished: 建立MQTT连接-0 1-10
2022-06-16 11:26:12,982 Notifying test listeners of end of test
2022-06-16 11:26:12,985 Problem closing files at end of test java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964) ~[?:?]
	at org.apache.jmeter.testelement.TestPlan.testEnded(TestPlan.java:241) [ms-jmeter-core.jar:5.4.3]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:218) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:493) [ApacheJMeter_core.jar:5.4.3]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2022-06-16 11:26:12,995 Test plan 建立MQTT连接test end
2022-06-16 11:26:12,996 Worker ended
2022-06-16 11:26:13,005 summary +     31 in 00:00:13 =    2.5/s Avg:  4839 Min:     0 Max: 10003 Err:    31 (100.00%) Active: 0 Started: 10 Finished: 10
2022-06-16 11:26:13,007 summary =    200 in 00:01:45 =    1.9/s Avg:  5002 Min:     0 Max: 10224 Err:   200 (100.00%)
```

**Comment by 35plus** [comment]
liyuan，这个缺陷无需复测，直接转给赵勇，感谢。

**Comment by fit2-zhao** [comment]
为了满足上版用户提出的需求，改造过mqtt 插件源码，在我们仓库中有Fork ，请用改造后的插件。
