### ISSUE TITLE
[BUG] v1.20.8 接口定义-接口列表-CASE页面报错：SQL error happened, please check logs.

### ISSUE THREAD

**Issue by bobbz** [metersphere/metersphere#15303]
### 联系方式

bz0915@gmial.com

### MeterSphere 版本

版本:   v1.20.8-lts-ba947709

### 使用外置数据库

否

### 问题描述

Request URL: http://*******/api/testcase/list/1/10
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: 127.0.0.1:1354
Referrer Policy: strict-origin-when-cross-origin

{"success":false,"message":"SQL error happened, please check logs.","data":null}

![image](https://user-images.githubusercontent.com/4591927/175912711-3c47b18f-bef0-444d-a9af-979a7897d1cb.png)

### 重现步骤

1. 接口测试 - 接口定义 - 接口列表 
2.  点击切换到“CASE”页面

**Comment by youliyuan-fit2cloud** [comment]
你好，我们这边没有复现这个问题，请上传服务器的日志信息，谢谢~

**Comment by bobbz** [comment]
ERROR i.m.c.h.RestControllerExceptionHandler 176 - Method[sqlExceptionHandler][Table 'metersphere.USER' doesn't exist]
java.sql.SQLSyntaxErrorException: Table **'metersphere.USER' doesn't exist**
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)

**Comment by bobbz** [comment]
> 你好，我们这边没有复现这个问题，请上传服务器的日志信息，谢谢~

ERROR i.m.c.h.RestControllerExceptionHandler 176 - Method[sqlExceptionHandler][Table 'metersphere.USER' doesn't exist]
java.sql.SQLSyntaxErrorException: **Table 'metersphere.USER' doesn't exist**
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)

**Comment by youliyuan-fit2cloud** [comment]
是数据库大小写 没忽略，参考文件下面附件，修改my.cnf，然后重启mysql服务
[my.cnf.zip](https://github.com/metersphere/metersphere/files/8997207/my.cnf.zip)
