### ISSUE TITLE
[BUG]数据库缺少字段

### ISSUE THREAD

**Issue by maojunxyz** [metersphere/metersphere#15328]
### 联系方式

@maojunxyz

### MeterSphere 版本

自构建最新主干

### 使用外置数据库

是

### 问题描述

从源码构建Metersphere,手动上传jar包部署的时候，数据库缺少字段导致页面操作频繁报错。

```
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'retry_enable' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'retry_enable' in 'field list'
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
        at com.sun.proxy.$Proxy133.selectList(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
        at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147)
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80)
        at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:145)
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
        at com.sun.proxy.$Proxy239.selectByExample(Unknown Source)
        at io.metersphere.api.service.ApiExecutionQueueService.defendQueue(ApiExecutionQueueService.java:364)
        at io.metersphere.api.service.ApiExecutionQueueService$$FastClassBySpringCGLIB$$d7e5fe4f.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
        at io.metersphere.api.service.ApiExecutionQueueService$$EnhancerBySpringCGLIB$$f65ac608.defendQueue(<generated>)
        a
```

### 重现步骤

手动源码构建最新版，并部署。

### 相关日志输出

```shell
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'retry_enable' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'retry_enable' in 'field list'
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
        at com.sun.proxy.$Proxy133.selectList(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
        at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147)
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80)
        at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:145)
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
        at com.sun.proxy.$Proxy239.selectByExample(Unknown Source)
        at io.metersphere.api.service.ApiExecutionQueueService.defendQueue(ApiExecutionQueueService.java:364)
        at io.metersphere.api.service.ApiExecutionQueueService$$FastClassBySpringCGLIB$$d7e5fe4f.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
        at io.metersphere.api.service.ApiExecutionQueueService$$EnhancerBySpringCGLIB$$f65ac608.defendQueue(<generated>)
        a
```

### 附加信息

![bbb2894fb0500650d7999ffef2efe6d](https://user-images.githubusercontent.com/28778042/176345403-92a2ee3f-1347-4dce-8e18-493e54d63be3.jpg)

**Comment by zyyfit** [comment]
您好，建议直接用在线包或者离线包的方式进行安装部署

**Comment by maojunxyz** [comment]
@zyyfit 环境不支持，只能源码构建。已手动添加数据库字段解决。
