### ISSUE TITLE
[BUG]创建用例会报错。SQL error happened, please check logs.

### ISSUE THREAD

**Issue by cxltsui** [metersphere/metersphere#15334]
### 联系方式

交流群44，崔崔

### MeterSphere 版本

dev,1.20.8有同样问题

### 使用外置数据库

否

### 问题描述

api_definition.to_be_updated字段缺少SQL，custom_field_issues，custom_field_test_case缺少建表语句。创建用例会报错

### 重现步骤

创建用例会报错。SQL error happened, please check logs.

### 相关日志输出

```shell
org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'to_be_updated' in 'field list'
### The error may exist in io/metersphere/base/mapper/ApiDefinitionMapper.xml
### The error may involve io.metersphere.base.mapper.ApiDefinitionMapper.selectByExample-Inline
### The error occurred while setting parameters
### SQL: select                 id, project_id, `name`, `method`, module_path, environment_id, schedule, `status`,      module_id, user_id, create_time, update_time, protocol, `path`, num, tags, original_state,      create_user, case_total, case_status, case_passing_rate, delete_time, delete_user_id,      `order`, ref_id, version_id, latest, to_be_updated         from api_definition                    WHERE (  module_id is null )
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'to_be_updated' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'to_be_updated' in 'field list'
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy130.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)

"3":"3"},"view":{"account":"scutech","products":"1","projects":"1,2"},"company":"\u6613\u8f6f\u5929\u521b","token":"32fd03412d0ae86977990f308f2faaca"}}]
2022-06-29 14:15:01,331 [SessionValidationThread-1] INFO  o.a.s.s.m.AbstractValidatingSessionManager ? - Validating all active sessions...
2022-06-29 14:15:01,331 [SessionValidationThread-1] INFO  o.a.s.s.m.AbstractValidatingSessionManager ? - Finished session validation.  No sessions were stopped.
2022-06-29 14:27:04,772 [XNIO-1 task-1] ERROR i.m.c.h.RestControllerExceptionHandler ? - Method[sqlExceptionHandler][Table 'metersphere_dev.custom_field_test_case' doesn't exist]
java.sql.SQLSyntaxErrorException: Table 'metersphere_dev.custom_field_test_case' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)
```

**Comment by xulinde** [comment]
您是二次开发？这个是我们还没发布的功能，有报错是正常的
