### ISSUE TITLE
[BUG] SQL脚本中使用insert语句报错

### ISSUE THREAD

**Issue by kamalyes** [metersphere/metersphere#15336]
### 自动化自定义SQL脚本使用以下的脚本、调试中报错
场景一：
`vars.put("sku_id","1050255001");
vars.putObject("stock",1235678);
vars.put("warehouse_id","156998");
insert into dc_order.warehouse_goods(goodsid,stock,warehouse_id) values('${sku_id}','${stock}','${warehouse_id}');`

2022-06-29 15:00:59 WARN a660b7ca 1-1 SQL Problem in JDBCPreProcessor: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'insert into dc_order.warehouse_goods(goodsid,stock,warehouse_id) values('1050255' at line 2

场景二：
无参数化插入、同样也报错了、但同样的情况下调用select操作即是正常：
`insert into dc_order.warehouse_goods (goodsid,stock,warehouse_id) values ("1050276001", 105021, 11);`
javax.script.ScriptException
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:267)
   at org.apache.jmeter.protocol.java.sampler.JSR223Sampler.sample(JSR223Sampler.java:72)
   at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:656)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:575)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:487)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:251)
   at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by xulinde** [comment]
您好，v1.20.8版本未复现该问题，您使用的是什么版本，建议升级到最新版本
![image](https://user-images.githubusercontent.com/64065190/176400180-de9e145d-533c-4b60-a566-633d4d53fd46.png)

**Comment by kamalyes** [comment]
使用的版本:   v1.20.7-lts-f835cdf2
![aaa](https://user-images.githubusercontent.com/40486003/176403558-a0c8790d-41d6-4cb8-be79-4d3c4f9b6267.gif)

**Comment by kamalyes** [comment]
是个必现的问题哦、已升级版本、发现在自定义脚本中去使用时就会报错、接口列表导入或场景导入的方式去添加前置||后置是正常的
![image](https://user-images.githubusercontent.com/40486003/176412896-10ec5433-3bc5-4cba-a403-0b27f71c87c2.png)

![image](https://user-images.githubusercontent.com/40486003/176412345-aa1e6c34-9d45-489d-8465-33c6f5967409.png)

**Comment by xulinde** [comment]
自定义脚本目前不支持sql语句。您可以添加一个自定义请求，然后使用执行sql脚本
![image](https://user-images.githubusercontent.com/64065190/176416712-85853d1a-e923-4ed5-a532-29d275e325a0.png)

**Comment by xulinde** [comment]
自定义请求可以创建sql类型
![image](https://user-images.githubusercontent.com/64065190/176574304-a0e98a57-ee61-48c9-b879-49eae78722f6.png)

**Comment by kamalyes** [comment]
谢谢，这将是一个不错的选择
