### ISSUE TITLE
[BUG]在Python脚本中使用vars.get()获取Json对象报错

### ISSUE THREAD

**Issue by kamalyes** [metersphere/metersphere#15448]
### 联系方式

mryu168@163.com

### MeterSphere 版本

版本:   v1.20.8-lts-ba947709

### 使用外置数据库

是

### 问题描述

使用# -*- coding:utf-8 -*-报错如下：
```java
org.python.antlr.ParseException: org.python.antlr.ParseException: encoding declaration in Unicode string
javax.script.ScriptException
   at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:226)
   at org.python.jsr223.PyScriptEngine.compileScript(PyScriptEngine.java:93)
   at org.python.jsr223.PyScriptEngine.compile(PyScriptEngine.java:76)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:253)
   at org.apache.jmeter.modifiers.JSR223PreProcessor.process(JSR223PreProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:985)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:547)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:487)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:251)
   at java.base/java.lang.Thread.run(Thread.java:829)
```

不使用# -*- coding:utf-8 -*-报错如下：
```java
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128) in <script> at line number 4
javax.script.ScriptException
   at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:222)
   at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:59)
   at org.python.jsr223.PyScriptEngine.access$300(PyScriptEngine.java:20)
   at org.python.jsr223.PyScriptEngine$PyCompiledScript.eval(PyScriptEngine.java:250)
   at java.scripting/javax.script.CompiledScript.eval(CompiledScript.java:89)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:262)
   at org.apache.jmeter.modifiers.JSR223PreProcessor.process(JSR223PreProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:985)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:547)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:487)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:251)
   at java.base/java.lang.Thread.run(Thread.java:829)
```

### 重现步骤

前提：
有俩个接口：分别为A->B
接口A：返回值
```json
{
    "code": 200,
    "message": "Success",
    "error": "",
    "ShopInfoList": [
        {
            "shop_id": "CX0010",
            "shop_name": ""
        },
        {
            "shop_id": "CX0011",
            "shop_name": ""
        }
    ]
}
```
步骤
1、接口A中使用json提取得出ShopInfoList
![image](https://user-images.githubusercontent.com/40486003/177074878-a16d731c-4906-4634-9210-5da1facccba8.png)
2、接口B使用python脚本
```python
# -*- coding:utf-8 -*-
import json
ShopInfoList = vars.get("ShopInfoList"); # 实际这里就错了 意思是在python方式里不能使用vars.get？那该怎么传入变量呢
zl_shop_id = vars.get("zl_shop_id");
log.info("上游给到的ShopInfoList-------------------"+ShopInfoList)
log.info("上游给到的zl_shop_id-------------------"+zl_shop_id)
zl_shop_id = json.loads(zl_shop_id)
shopinfolist = json.loads(ShopInfoList)
log.info("ShopInfoList："+shopinfolist,"zl_shop_id"+zl_shop_id)
for index in range(len(shopinfolist)-1, -1, -1):
    shop_info = shopinfolist[index]
    if int(shop_info["shop_id"]) == zl_shop_id:
        shopinfolist.pop(index)
res=json.dumps(shopinfolist)
vars.putObject("shopinfolist",res);
vars.putObject("warehouse_id",3094);
```

**Comment by kamalyes** [comment]
这不是一个问题、后续发现是因为序列化过程中Jython报错出来的、已加异常处理
