### ISSUE TITLE
[BUG] Jmx文件导入执行抛出异常，1.20.8之前是好的，异常信息no protocol: ${QA}/services/integration/carrier/sortation

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#15706]
### 联系方式

王进

### MeterSphere 版本

1.20.9

### 使用外置数据库

否

### 问题描述

 Jmx文件导入执行抛出异常，1.20.8之前是好的，异常信息no protocol: ${QA}/services/integration/carrier/sortation

### 重现步骤

1. 请下载jmx文件链接: https://pan.baidu.com/s/1WCi3DbiJdr71J4bO69Su-g 提取码: xzw8 
2. 这是一个很典型的jmx文件，在1.20.8之前用户导入就能跑，因为环境是定义在用户自定义变量组件的。
3. 后来用户升级到1.20.8后，每次执行，也都会执行完成，但是问题如下：
   调试报告里，所有步骤和断言都是成功的，但是调试报告结果是Failed。
    在测试计划的报告里面是失败的，点击失败看不到任何失败的地方，所有步骤和断言都是成功的。
4. 检查日志，可以看到如下信息：
    链接: https://pan.baidu.com/s/1opTT0x61qQZYjf0y5vlTYg 提取码: a19p 
    2022-07-12 11:21:25,339 [XNIO-1 task-11] ERROR i.m.a.d.d.r.s.MsHTTPSamplerProxy ? - Method[setSamplerPath][no protocol: ${QA}/services/integration/carrier/sortation]
java.net.MalformedURLException: no protocol: ${QA}/services/integration/carrier/sortation
	at java.base/java.net.URL.<init>(URL.java:645)
	at java.base/java.net.URL.<init>(URL.java:541)
	at java.base/java.net.URL.<init>(URL.java:488)
	at io.metersphere.api.dto.definition.request.sampler.MsHTTPSamplerProxy.setSamplerPath(MsHTTPSamplerProxy.java:399)
	at io.metersphere.api.dto.definition.request.sampler.MsHTTPSamplerProxy.toHashTree(MsHTTPSamplerProxy.java:188)
	at io.metersphere.api.dto.definition.request.unknown.MsJmeterElement.toHashTree(MsJmeterElement.java:99)
	at io.metersphere.api.dto.definition.request.unknown.MsJmeterElement.toHashTree(MsJmeterElement.java:99)
	at io.metersphere.api.dto.definition.request.MsScenario.toHashTree(MsScenario.java:183)
	at io.metersphere.api.dto.definition.request.MsThreadGroup.toHashTree(MsThreadGroup.java:47)
	at io.metersphere.api.dto.definition.request.MsTestPlan.lambda$toHashTree$0(MsTestPlan.java:33)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.metersphere.api.dto.definition.request.MsTestPlan.toHashTree(MsTestPlan.java:32)

### 附加信息

这个问题是1.20.8新带出来的。客户把URL自定义在用户自定义变量里，URL里 用 ${QA}/...  也是正常的。

另外，在接口定义，接口用例，或者单个请求这些地方，校验URL是不是/开头，似乎可以拿掉，把灵活性留给用户。

**Comment by youliyuan-fit2cloud** [comment]
v1.20.10-lts中已修复~

**Comment by 35plus** [comment]
这个问题没有修复。今天客户升级 依然有这个问题。调试报告里，所有步骤和断言都是成功的，但是调试报告结果是Failed。 客户刚升级完验证。

**Comment by 35plus** [comment]
metersphere.walltechsystem.com/shareApiReport?shareId=0973e8a6-d9ae-44de-8323-3511120f05ff
这是客户环境给的报告，1.20.10上还有
