### ISSUE TITLE
[BUG] 无法进行场景化测试

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#1645]
**MeterSphere 版本**
1.7.3 新版

**Bug 描述**
无法从接口自动化创建接口测试

**Bug 重现步骤**
1.  下载1.7.3离线安装包；使用默认安装
2.  使用admin创建场景化测试；给场景化测试增加自定义接口测试
3. 
![image](https://user-images.githubusercontent.com/5517369/111309504-f2b38600-8696-11eb-9ba7-4824e67f739f.png)

3. 点击场景化调试报错
```
2021-03-16 20:34:42,264 [StandardJMeterEngine] WARN  o.a.j.engine.StandardJMeterEngine ? - Error encountered during shutdown of org.apache.jmeter.visualizers.backend.BackendListener@2e180fe8
java.lang.IllegalStateException: Failed calling teardownTest
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:378)
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:384)
        at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:218)
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:492)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
        at io.metersphere.api.jmeter.APIBackendListenerClient.teardownTest(APIBackendListenerClient.java:210)
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:376)
        ... 4 common frames omitted
```
4. 点击‘接口右侧的调试按钮’报错
```2021-03-16 20:34:46,892 [StandardJMeterEngine] WARN  o.a.j.engine.StandardJMeterEngine ? - Error encountered during shutdown of org.apache.jmeter.visualizers.backend.BackendListener@5aab4dc8
java.lang.IllegalStateException: Failed calling teardownTest
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:378)
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:384)
        at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:218)
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:492)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.metersphere.commons.exception.MSException: Test cannot be found:
        at io.metersphere.commons.exception.MSException.throwException(MSException.java:14)
        at io.metersphere.api.service.ApiDefinitionService.addResult(ApiDefinitionService.java:407)
        at io.metersphere.api.service.ApiDefinitionService$$FastClassBySpringCGLIB$$72d8ca15.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
        at io.metersphere.api.service.ApiDefinitionService$$EnhancerBySpringCGLIB$$76c83423.addResult(<generated>)
        at io.metersphere.api.service.ApiDefinitionService$$FastClassBySpringCGLIB$$72d8ca15.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
        at io.metersphere.api.service.ApiDefinitionService$$EnhancerBySpringCGLIB$$cbcd226f.addResult(<generated>)
        at io.metersphere.api.jmeter.APIBackendListenerClient.teardownTest(APIBackendListenerClient.java:174)
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:376)
        ... 4 common frames omitted


```

**期待的正确结果**
场景化可正常运行

**截图**
如果有截图，请附上截图.

**Comment by xulinde** [comment]
选的环境有配置ip那些吗，如果环境是空的，会报空指针

**Comment by guhan121** [comment]
@xulinde 没有配任何东西

**Comment by xulinde** [comment]
环境不配置任何东西，选环境是会报错的，至少得配个ip或域名吧
