### ISSUE TITLE
[BUG]非超管，但是是项目管理员的人员，进行切换到项目设置时会有一堆error

### ISSUE THREAD

**Issue by junwei-liu** [metersphere/metersphere#16762]
### 联系方式

1121213408@qq.com

### MeterSphere 版本

v2.0.1-473aa26e

### 使用外置数据库

是

### 问题描述

非超管，但是是项目管理员的人员，进行切换到项目设置时会有一堆error
![image](https://user-images.githubusercontent.com/78710778/183575910-f5493a81-b429-4f84-b692-0bebb8736a57.png)

### 重现步骤

非超管，但是是项目管理员的人员，进行切换到项目设置时

### 相关日志输出

```shell
2022-08-09 13:35:00,714 [main] ERROR i.m.service.ScheduleService 176 - Method[lambda$startEnableSchedules$2][初始化任务失败]
org.quartz.JobPersistenceException: Failed to obtain DB connection from data source 'springTxDataSource.clusterScheduler': java.sql.SQLNonTransientConnectionException: Data source rejectedestablishment of connection,  message from server: "Too many connections"
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.getConnection(JobStoreSupport.java:783)
        at org.quartz.impl.jdbcjobstore.JobStoreCMT.executeInLock(JobStoreCMT.java:242)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeWithoutLock(JobStoreSupport.java:3800)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.checkExists(JobStoreSupport.java:1978)
        at org.quartz.core.QuartzScheduler.checkExists(QuartzScheduler.java:1534)
        at org.quartz.impl.StdScheduler.checkExists(StdScheduler.java:593)
        at io.metersphere.job.sechedule.ScheduleManager.addOrUpdateCronJob(ScheduleManager.java:272)
        at io.metersphere.service.ScheduleService.lambda$startEnableSchedules$2(ScheduleService.java:167)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at io.metersphere.service.ScheduleService.startEnableSchedules(ScheduleService.java:163)
        at io.metersphere.service.ScheduleService$$FastClassBySpringCGLIB$$7d6abca5.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at io.metersphere.service.ScheduleService$$EnhancerBySpringCGLIB$$82e5e65b.startEnableSchedules(<generated>)
        at io.metersphere.service.ScheduleService$$FastClassBySpringCGLIB$$7d6abca5.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at io.metersphere.service.ScheduleService$$EnhancerBySpringCGLIB$$cf6fe307.startEnableSchedules(<generated>)
        at io.metersphere.listener.AppStartListener.onApplicationEvent(AppStartListener.java:118)
        at io.metersphere.listener.AppStartListener.onApplicationEvent(AppStartListener.java:26)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
```

**Comment by youliyuan-fit2cloud** [comment]
你好，我们没有复现该问题，是100%复现吗？
