### ISSUE TITLE
[BUG]接口测试入参图片字段值为base64 加密后较长时，报java.io.IOException: java.io.IOException: Mark invalid

### ISSUE THREAD

**Issue by suki1222** [metersphere/metersphere#17044]
### MeterSphere 版本

v1.20.1-lts

### 使用外置数据库

否

### 问题描述

接口测试入参图片字段值为base64 加密后较长时，报错
java.io.IOException: java.io.IOException: Mark invalid
javax.script.ScriptException
   at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:207)
   at org.python.jsr223.PyScriptEngine.compileScript(PyScriptEngine.java:75)
   at org.python.jsr223.PyScriptEngine.compile(PyScriptEngine.java:59)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:244)
   at org.apache.jmeter.modifiers.JSR223PreProcessor.process(JSR223PreProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:999)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:560)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:500)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:264)
   at java.base/java.lang.Thread.run(Thread.java:829)

### 重现步骤

接口入参字段值为base64加密后的字符串

**Comment by silvia-zhou123456** [comment]
您好，不知道您加密后的字符长度是多少呢？发送的是get请求还是post请求？入参是否是以json格式放置在请求体中的？按照您问题中描述的场景，我造了个base64加密后的字符串，mock请求了下，并没有报错
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/110455682/185737032-2c29f85f-14c4-4f59-93e2-8f7cc10ff123.png">

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/110455682/185736874-79a19da5-861b-4dcf-aa46-c6dcb6c10386.png">

**Comment by silvia-zhou123456** [comment]
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/110455682/185737609-14a79f3e-9500-48dd-a14b-c738482d88d7.png">
