### ISSUE TITLE
[BUG]在前置脚本json格式数据中参数值为Boolean型时，在环境的前置脚本后执行的脚本报错，报True不存在

### ISSUE THREAD

**Issue by Tannii** [metersphere/metersphere#17223]
### 联系方式

941177402@qq.com

### MeterSphere 版本

v2.0.1

### 使用外置数据库

否

### 问题描述

步骤一：在前置脚本设置参数，如图
![image](https://user-images.githubusercontent.com/34464876/185895400-e7ff1a14-a8e5-4e70-b267-c838a7a9e618.png)
步骤二：在环境中的前置脚本获取参数，获取失败，如图（报错内容见图一）
![image](https://user-images.githubusercontent.com/34464876/185895573-7da97e91-43e0-4d4b-846c-beb7603c5097.png)

### 重现步骤

同问题描述

### 期待的正确结果

正常可以获取对应参数

### 相关日志输出

```shell
NameError: name 'false' is not defined in <script> at line number 62
javax.script.ScriptException
   at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:202)
   at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:42)
   at org.python.jsr223.PyScriptEngine.access$300(PyScriptEngine.java:20)
   at org.python.jsr223.PyScriptEngine$PyCompiledScript.eval(PyScriptEngine.java:231)
   at java.scripting/javax.script.CompiledScript.eval(CompiledScript.java:89)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:250)
   at org.apache.jmeter.modifiers.JSR223PreProcessor.process(JSR223PreProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:999)
```

**Comment by song-tianyang** [comment]
${request_bodys} 改为 vars.get("request_bodys") 试试呢

**Comment by Tannii** [comment]
> ${request_bodys} 改为 vars.get("request_bodys") 试试呢

这个方法可以哈，谢谢啦
