### ISSUE TITLE
[BUG] 无法完成场景测试

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#1725]
**MeterSphere 版本**
1.8.0

**Bug 描述**
在场景测试的时候经常出现;下面的报错.然后前端看不到报告.

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
```shell
2021-03-26 18:23:22,731 [qtp2131597042-38] INFO  o.a.s.s.m.AbstractValidatingSessionManager ? - Enabling session validation scheduler...
2021-03-26 18:23:39,932 [qtp2131597042-38] INFO  org.apache.jmeter.save.SaveService ? - Testplan (JMX) version: 2.2. Testlog (JTL) version: 2.2
2021-03-26 18:23:39,943 [qtp2131597042-38] INFO  org.apache.jmeter.save.SaveService ? - Using SaveService properties file encoding UTF-8
2021-03-26 18:23:39,949 [qtp2131597042-38] INFO  org.apache.jmeter.save.SaveService ? - Using SaveService properties version 5.0
2021-03-26 18:23:43,348 [qtp2131597042-38] INFO  o.a.j.p.http.sampler.HTTPSamplerBase ? - Parser for text/html is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2021-03-26 18:23:43,348 [qtp2131597042-38] INFO  o.a.j.p.http.sampler.HTTPSamplerBase ? - Parser for application/xhtml+xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2021-03-26 18:23:43,349 [qtp2131597042-38] INFO  o.a.j.p.http.sampler.HTTPSamplerBase ? - Parser for application/xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2021-03-26 18:23:43,349 [qtp2131597042-38] INFO  o.a.j.p.http.sampler.HTTPSamplerBase ? - Parser for text/xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2021-03-26 18:23:43,350 [qtp2131597042-38] INFO  o.a.j.p.http.sampler.HTTPSamplerBase ? - Parser for text/vnd.wap.wml is org.apache.jmeter.protocol.http.parser.RegexpHTMLParser
2021-03-26 18:23:43,350 [qtp2131597042-38] INFO  o.a.j.p.http.sampler.HTTPSamplerBase ? - Parser for text/css is org.apache.jmeter.protocol.http.parser.CssParser
2021-03-26 18:23:43,378 [qtp2131597042-38] INFO  org.apache.jmeter.util.JMeterUtils ? - Setting Locale to en_US
2021-03-26 18:23:43,383 [qtp2131597042-38] INFO  o.a.jmeter.samplers.SampleResult ? - Note: Sample TimeStamps are START times
2021-03-26 18:23:43,383 [qtp2131597042-38] INFO  o.a.jmeter.samplers.SampleResult ? - sampleresult.default.encoding is set to UTF-8
2021-03-26 18:23:43,383 [qtp2131597042-38] INFO  o.a.jmeter.samplers.SampleResult ? - sampleresult.useNanoTime=true
2021-03-26 18:23:43,384 [qtp2131597042-38] INFO  o.a.jmeter.samplers.SampleResult ? - sampleresult.nanoThreadSleep=5000
2021-03-26 18:23:43,392 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine ? - Running the test!
2021-03-26 18:23:43,394 [StandardJMeterEngine] INFO  o.apache.jmeter.samplers.SampleEvent ? - List of sample_variables: []
2021-03-26 18:23:43,394 [StandardJMeterEngine] INFO  o.apache.jmeter.samplers.SampleEvent 63 - List of sample_variables: []
2021-03-26 18:23:43,398 [StandardJMeterEngine] INFO  o.a.j.engine.util.CompoundVariable ? - Note: Function class names must contain the string: '.functions.'
2021-03-26 18:23:43,398 [StandardJMeterEngine] INFO  o.a.j.engine.util.CompoundVariable 69 - Note: Function class names must not contain the string: '.gui.'
2021-03-26 18:23:43,786 [StandardJMeterEngine] INFO  o.a.j.v.backend.BackendListener ? - 981e222c-fdcf-51a0-2ff6-9d1cf500a149: Starting worker with class: class io.metersphere.api.jmeter.APIBackendListenerClient and queue capacity: 5000
2021-03-26 18:23:43,788 [StandardJMeterEngine] INFO  o.a.j.v.backend.BackendListener ? - 981e222c-fdcf-51a0-2ff6-9d1cf500a149: Started  worker with class: class io.metersphere.api.jmeter.APIBackendListenerClient
2021-03-26 18:23:44,303 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine ? - Starting ThreadGroup: 1 : ThreadGroup
2021-03-26 18:23:44,303 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine ? - Starting 1 threads for group ThreadGroup.
2021-03-26 18:23:44,304 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine 521 - Thread will continue on error
2021-03-26 18:23:44,304 [StandardJMeterEngine] INFO  o.apache.jmeter.threads.ThreadGroup 220 - Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false
2021-03-26 18:23:44,320 [StandardJMeterEngine] INFO  o.apache.jmeter.threads.ThreadGroup 248 - Started thread group number 1
2021-03-26 18:23:44,321 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine 462 - All thread groups have been started
2021-03-26 18:23:44,330 [ThreadGroup 1-1] INFO  o.apache.jmeter.threads.JMeterThread ? - Thread started: ThreadGroup 1-1
2021-03-26 18:23:44,340 [ThreadGroup 1-1] INFO  java.util.prefs ? - Created user preferences directory.
2021-03-26 18:23:44,448 [ThreadGroup 1-1] INFO  o.apache.jmeter.threads.JMeterThread ? - Thread finished: ThreadGroup 1-1
2021-03-26 18:23:44,450 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine ? - Notifying test listeners of end of test
2021-03-26 18:23:44,456 [StandardJMeterEngine] INFO  o.apache.jmeter.services.FileServer 86 - Default base='/deployments'
2021-03-26 18:23:44,456 [Thread-44] INFO  o.a.j.v.backend.BackendListener 235 - Worker ended
2021-03-26 18:23:44,481 [StandardJMeterEngine] WARN  o.a.j.engine.StandardJMeterEngine ? - Error encountered during shutdown of org.apache.jmeter.visualizers.backend.BackendListener@3fd1bd2e
java.lang.IllegalStateException: Failed calling teardownTest
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:377)
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:383)
        at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:218)
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:493)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.metersphere.commons.exception.MSException: Test cannot be found:
        at io.metersphere.commons.exception.MSException.throwException(MSException.java:14)
        at io.metersphere.api.service.ApiDefinitionService.addResult(ApiDefinitionService.java:519)
        at io.metersphere.api.service.ApiDefinitionService$$FastClassBySpringCGLIB$$72d8ca15.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
        at io.metersphere.api.service.ApiDefinitionService$$EnhancerBySpringCGLIB$$f6c1250a.addResult(<generated>)
        at io.metersphere.api.service.ApiDefinitionService$$FastClassBySpringCGLIB$$72d8ca15.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
        at io.metersphere.api.service.ApiDefinitionService$$EnhancerBySpringCGLIB$$4bc61356.addResult(<generated>)
        at io.metersphere.api.jmeter.APIBackendListenerClient.teardownTest(APIBackendListenerClient.java:182)
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:375)
        ... 4 common frames omitted
2021-03-26 18:24:14,894 [Quartz Scheduler [clusterScheduler]] INFO  o.s.s.quartz.SchedulerFactoryBean ? - Starting Quartz Scheduler now, after delay of 60 seconds
2021-03-26 18:24:14,904 [Quartz Scheduler [clusterScheduler]] INFO  org.quartz.core.QuartzScheduler 547 - Scheduler clusterScheduler_$_05604612b9971616754183460 started.
2021-03-26 18:24:14,959 [Thread-23] INFO  org.quartz.core.QuartzScheduler ? - Scheduler clusterScheduler_$_05604612b9971616754183460 started.
2021-03-26 18:24:16,944 [Thread-32] INFO  org.quartz.core.QuartzScheduler ? - Scheduler clusterScheduler_$_05604612b9971616754183460 started.
```

**Comment by guhan121** [comment]
#1729

**Comment by zyyfit** [comment]
已在v1.8.1版本修复，请等待1.8.1版本发布后查看
