### ISSUE TITLE
[BUG] 运行场景调试异常

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#1728]
**MeterSphere 版本**
1.8.0

**Bug 描述**
第一次 运行出现bug后；第二次继续异常

**Bug 重现步骤**
1. 第一次异常日志
```shell
2021-03-27 09:29:16,415 [Quartz Scheduler [clusterScheduler]] INFO  org.quartz.core.QuartzScheduler ? - Scheduler clusterScheduler_$_dc579d66aeae1616808483770 started.
2021-03-27 09:29:16,439 [Thread-23] INFO  org.quartz.core.QuartzScheduler ? - Scheduler clusterScheduler_$_dc579d66aeae1616808483770 started.
2021-03-27 09:29:18,229 [Thread-32] INFO  org.quartz.core.QuartzScheduler ? - Scheduler clusterScheduler_$_dc579d66aeae1616808483770 started.
2021-03-27 09:29:40,759 [qtp2019826979-212] INFO  org.apache.jmeter.util.JMeterUtils ? - Setting Locale to en_US
2021-03-27 09:29:40,762 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine ? - Running the test!
2021-03-27 09:29:40,762 [StandardJMeterEngine] INFO  o.apache.jmeter.samplers.SampleEvent ? - List of sample_variables: []
2021-03-27 09:29:40,764 [StandardJMeterEngine] INFO  o.a.j.v.backend.BackendListener ? - 1fbc0197: Starting worker with class: class io.metersphere.api.jmeter.APIBackendListenerClient and queue capacity: 5000
2021-03-27 09:29:40,765 [StandardJMeterEngine] INFO  o.a.j.v.backend.BackendListener ? - 1fbc0197: Started  worker with class: class io.metersphere.api.jmeter.APIBackendListenerClient
2021-03-27 09:29:41,208 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine ? - Starting ThreadGroup: 1 : 1fbc0197
2021-03-27 09:29:41,208 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine ? - Starting 1 threads for group 1fbc0197.
2021-03-27 09:29:41,208 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine ? - Thread will continue on error
2021-03-27 09:29:41,208 [StandardJMeterEngine] INFO  o.apache.jmeter.threads.ThreadGroup ? - Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false
2021-03-27 09:29:41,212 [StandardJMeterEngine] INFO  o.apache.jmeter.threads.ThreadGroup ? - Started thread group number 1
2021-03-27 09:29:41,212 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine 461 - All thread groups have been started
2021-03-27 09:29:41,216 [1fbc0197 1-1] INFO  o.apache.jmeter.threads.JMeterThread ? - Thread started: 1fbc0197 1-1
2021-03-27 09:29:41,259 [1fbc0197 1-1] INFO  o.apache.jmeter.threads.JMeterThread ? - Thread finished: 1fbc0197 1-1
2021-03-27 09:29:41,260 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine 214 - Notifying test listeners of end of test
2021-03-27 09:29:41,260 [Thread-49] INFO  o.a.j.v.backend.BackendListener 236 - Worker ended
2021-03-27 09:29:41,273 [StandardJMeterEngine] WARN  o.a.j.engine.StandardJMeterEngine ? - Error encountered during shutdown of org.apache.jmeter.visualizers.backend.BackendListener@26ce1734
java.lang.IllegalStateException: Failed calling teardownTest
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:378)
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:384)
        at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:218)
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:492)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
        at io.metersphere.api.jmeter.APIBackendListenerClient.teardownTest(APIBackendListenerClient.java:221)
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:376)
        ... 4 common frames omitted
```
2. 第二次异常日志
```shell
2021-03-27 09:37:04,039 [qtp2019826979-41] INFO  org.apache.jmeter.util.JMeterUtils ? - Setting Locale to en_US
2021-03-27 09:37:04,040 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine ? - Running the test!
2021-03-27 09:37:04,041 [StandardJMeterEngine] INFO  o.apache.jmeter.samplers.SampleEvent ? - List of sample_variables: []
2021-03-27 09:37:04,042 [StandardJMeterEngine] INFO  o.a.j.v.backend.BackendListener ? - a1a1d7d9-99c8-8c7a-ebc6-e831078e0519: Starting worker with class: class io.metersphere.api.jmeter.APIBackendListenerClient and queue capacity: 5000
2021-03-27 09:37:04,049 [StandardJMeterEngine] INFO  o.a.j.v.backend.BackendListener ? - a1a1d7d9-99c8-8c7a-ebc6-e831078e0519: Started  worker with class: class io.metersphere.api.jmeter.APIBackendListenerClient
2021-03-27 09:37:04,450 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine 450 - Starting ThreadGroup: 1 : ThreadGroup
2021-03-27 09:37:04,450 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine 510 - Starting 1 threads for group ThreadGroup.
2021-03-27 09:37:04,450 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine 520 - Thread will continue on error
2021-03-27 09:37:04,450 [StandardJMeterEngine] INFO  o.apache.jmeter.threads.ThreadGroup 220 - Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false
2021-03-27 09:37:04,451 [StandardJMeterEngine] INFO  o.apache.jmeter.threads.ThreadGroup 246 - Started thread group number 1
2021-03-27 09:37:04,451 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine 461 - All thread groups have been started
2021-03-27 09:37:04,453 [ThreadGroup 1-1] INFO  o.apache.jmeter.threads.JMeterThread ? - Thread started: ThreadGroup 1-1
2021-03-27 09:37:04,489 [ThreadGroup 1-1] INFO  o.apache.jmeter.threads.JMeterThread ? - Thread finished: ThreadGroup 1-1
2021-03-27 09:37:04,490 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine ? - Notifying test listeners of end of test
2021-03-27 09:37:04,490 [Thread-50] INFO  o.a.j.v.backend.BackendListener ? - Worker ended
2021-03-27 09:37:04,491 [StandardJMeterEngine] WARN  o.a.j.engine.StandardJMeterEngine ? - Error encountered during shutdown of org.apache.jmeter.visualizers.backend.BackendListener@1da59f0a
java.lang.IllegalStateException: Failed calling teardownTest
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:378)
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:384)
        at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:218)
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:492)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.metersphere.commons.exception.MSException: Test cannot be found:
        at io.metersphere.commons.exception.MSException.throwException(MSException.java:14)
        at io.metersphere.api.service.ApiDefinitionService.addResult(ApiDefinitionService.java:519)
        at io.metersphere.api.service.ApiDefinitionService$$FastClassBySpringCGLIB$$72d8ca15.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
        at io.metersphere.api.service.ApiDefinitionService$$EnhancerBySpringCGLIB$$76c83423.addResult(<generated>)
        at io.metersphere.api.service.ApiDefinitionService$$FastClassBySpringCGLIB$$72d8ca15.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
        at io.metersphere.api.service.ApiDefinitionService$$EnhancerBySpringCGLIB$$cbcd226f.addResult(<generated>)
        at io.metersphere.api.jmeter.APIBackendListenerClient.teardownTest(APIBackendListenerClient.java:182)
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:376)
        ... 4 common frames omitted
```
**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，能具体说明一下是怎样出现bug的吗

**Comment by guhan121** [comment]
#1729
