### ISSUE TITLE
[BUG] 场景调试异常

### ISSUE THREAD

**Issue by guhan121** [metersphere/metersphere#1729]
**MeterSphere 版本**
1.8.0

**Bug 描述**
1. 测试用jmx文件
```xml
<?xml version="1.0" encoding="UTF-8"?><jmeterTestPlan version="1.2" properties="5.0" jmeter="5.2.1">
  <hashTree>
    <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="导包测试" enabled="true">
      <boolProp name="TestPlan.functional_mode">false</boolProp>
      <boolProp name="TestPlan.serialize_threadgroups">true</boolProp>
      <boolProp name="TestPlan.tearDown_on_shutdown">true</boolProp>
      <elementProp name="TestPlan.user_defined_variables" elementType="Arguments">
        <collectionProp name="Arguments.arguments"/>
      </elementProp>
    </TestPlan>
    <hashTree>
      <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="导包测试" enabled="true">
        <intProp name="ThreadGroup.num_threads">1</intProp>
        <intProp name="ThreadGroup.ramp_time">1</intProp>
        <longProp name="ThreadGroup.delay">0</longProp>
        <longProp name="ThreadGroup.duration">0</longProp>
        <stringProp name="ThreadGroup.on_sample_error">continue</stringProp>
        <boolProp name="ThreadGroup.scheduler">false</boolProp>
        <elementProp name="ThreadGroup.main_controller" elementType="LoopController" guiclass="LoopControlPanel" testclass="LoopController" testname="LoopController" enabled="true">
          <boolProp name="LoopController.continue_forever">false</boolProp>
          <intProp name="LoopController.loops">1</intProp>
        </elementProp>
      </ThreadGroup>
      <hashTree>
        <Arguments guiclass="ArgumentsPanel" testclass="Arguments" testname="导包测试" enabled="true">
          <collectionProp name="Arguments.arguments">
            <elementProp name="test1" elementType="Argument">
              <stringProp name="Argument.name">test1</stringProp>
              <stringProp name="Argument.value">123</stringProp>
              <stringProp name="Argument.metadata">=</stringProp>
            </elementProp>
            <elementProp name="paymentGateway" elementType="Argument">
              <stringProp name="Argument.name">paymentGateway</stringProp>
              <stringProp name="Argument.value">//pa-api-prev.joyyinc.com</stringProp>
              <stringProp name="Argument.metadata">=</stringProp>
            </elementProp>
            <elementProp name="paymentAdmin" elementType="Argument">
              <stringProp name="Argument.name">paymentAdmin</stringProp>
              <stringProp name="Argument.value">//pa-admin-prev.joyyinc.com</stringProp>
              <stringProp name="Argument.metadata">=</stringProp>
            </elementProp>
          </collectionProp>
        </Arguments>
        <hashTree/>
        <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="百度" enabled="true">
          <elementProp name="HTTPsampler.Arguments" elementType="Arguments">
            <collectionProp name="Arguments.arguments"/>
          </elementProp>
          <stringProp name="MS-ID">2c60d4ae-10bc-1fcd-53d6-61a39364ea5c</stringProp>
          <stringProp name="HTTPSampler.method">GET</stringProp>
          <stringProp name="HTTPSampler.contentEncoding">UTF-8</stringProp>
          <stringProp name="HTTPSampler.connect_timeout">6000</stringProp>
          <stringProp name="HTTPSampler.response_timeout">6000</stringProp>
          <boolProp name="HTTPSampler.follow_redirects">true</boolProp>
          <boolProp name="HTTPSampler.use_keepalive">true</boolProp>
          <boolProp name="HTTPSampler.DO_MULTIPART_POST">false</boolProp>
          <stringProp name="HTTPSampler.domain">www.baidu.com</stringProp>
          <stringProp name="HTTPSampler.protocol">https</stringProp>
          <stringProp name="HTTPSampler.path"/>
        </HTTPSamplerProxy>
        <hashTree>
          <JSR223PreProcessor guiclass="TestBeanGUI" testclass="JSR223PreProcessor" testname="测试java包" enabled="true">
            <stringProp name="scriptLanguage">beanshell</stringProp>
            <stringProp name="script">import qa.func.Time;
import java.lang.ClassLoader;
import java.net.URL;
import java.net.URLClassLoader;

URL[] urls = ((URLClassLoader) (Thread.currentThread().getContextClassLoader())).getURLs();
for (URL url : urls) {
  log.info(url.getFile());
}   
// 生成
log.info("currenttimestamp in java:"+Time.get_currenttimestamp(null));
</stringProp>
          </JSR223PreProcessor>
          <hashTree/>
        </hashTree>
      </hashTree>
    </hashTree>
  </hashTree>
</jmeterTestPlan
```
其中 `qa.func.Time ` 为自己的第三方包
导入包后；重启服务; 运行带脚本请求异常
```shell
2021-03-27 10:00:31,445 [Quartz Scheduler [clusterScheduler]] INFO  o.s.s.quartz.SchedulerFactoryBean ? - Starting Quartz Scheduler now, after delay of 60 seconds
2021-03-27 10:00:31,451 [Quartz Scheduler [clusterScheduler]] INFO  o.s.s.quartz.LocalDataSourceJobStore ? - ClusterManager: detected 1 failed or restarted instances.
2021-03-27 10:00:31,452 [Quartz Scheduler [clusterScheduler]] INFO  o.s.s.quartz.LocalDataSourceJobStore ? - ClusterManager: Scanning for instance "e4eac0d1c5b41616810104954"'s failed in-progress jobs.
2021-03-27 10:00:31,454 [Quartz Scheduler [clusterScheduler]] INFO  org.quartz.core.QuartzScheduler ? - Scheduler clusterScheduler_$_e4eac0d1c5b41616810358568 started.
2021-03-27 10:00:31,497 [Thread-23] INFO  org.quartz.core.QuartzScheduler ? - Scheduler clusterScheduler_$_e4eac0d1c5b41616810358568 started.
2021-03-27 10:00:32,718 [Thread-40] INFO  org.quartz.core.QuartzScheduler ? - Scheduler clusterScheduler_$_e4eac0d1c5b41616810358568 started.
2021-03-27 10:00:43,223 [qtp1027495011-52] INFO  org.apache.jmeter.save.SaveService ? - Testplan (JMX) version: 2.2. Testlog (JTL) version: 2.2
2021-03-27 10:00:43,227 [qtp1027495011-52] INFO  org.apache.jmeter.save.SaveService ? - Using SaveService properties file encoding UTF-8
2021-03-27 10:00:43,234 [qtp1027495011-52] INFO  org.apache.jmeter.save.SaveService ? - Using SaveService properties version 5.0
2021-03-27 10:00:46,663 [qtp1027495011-52] INFO  o.a.j.p.http.sampler.HTTPSamplerBase ? - Parser for text/html is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2021-03-27 10:00:46,663 [qtp1027495011-52] INFO  o.a.j.p.http.sampler.HTTPSamplerBase ? - Parser for application/xhtml+xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2021-03-27 10:00:46,664 [qtp1027495011-52] INFO  o.a.j.p.http.sampler.HTTPSamplerBase ? - Parser for application/xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2021-03-27 10:00:46,664 [qtp1027495011-52] INFO  o.a.j.p.http.sampler.HTTPSamplerBase ? - Parser for text/xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2021-03-27 10:00:46,665 [qtp1027495011-52] INFO  o.a.j.p.http.sampler.HTTPSamplerBase ? - Parser for text/vnd.wap.wml is org.apache.jmeter.protocol.http.parser.RegexpHTMLParser
2021-03-27 10:00:46,665 [qtp1027495011-52] INFO  o.a.j.p.http.sampler.HTTPSamplerBase ? - Parser for text/css is org.apache.jmeter.protocol.http.parser.CssParser
2021-03-27 10:00:46,675 [qtp1027495011-52] INFO  org.apache.jmeter.util.JMeterUtils ? - Setting Locale to en_US
2021-03-27 10:00:46,681 [qtp1027495011-52] INFO  o.a.jmeter.samplers.SampleResult ? - Note: Sample TimeStamps are START times
2021-03-27 10:00:46,682 [qtp1027495011-52] INFO  o.a.jmeter.samplers.SampleResult ? - sampleresult.default.encoding is set to UTF-8
2021-03-27 10:00:46,682 [qtp1027495011-52] INFO  o.a.jmeter.samplers.SampleResult ? - sampleresult.useNanoTime=true
2021-03-27 10:00:46,683 [qtp1027495011-52] INFO  o.a.jmeter.samplers.SampleResult ? - sampleresult.nanoThreadSleep=5000
2021-03-27 10:00:46,691 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine ? - Running the test!
2021-03-27 10:00:46,693 [StandardJMeterEngine] INFO  o.apache.jmeter.samplers.SampleEvent ? - List of sample_variables: []
2021-03-27 10:00:46,693 [StandardJMeterEngine] INFO  o.apache.jmeter.samplers.SampleEvent 64 - List of sample_variables: []
2021-03-27 10:00:46,698 [StandardJMeterEngine] INFO  o.a.j.engine.util.CompoundVariable ? - Note: Function class names must contain the string: '.functions.'
2021-03-27 10:00:46,698 [StandardJMeterEngine] INFO  o.a.j.engine.util.CompoundVariable ? - Note: Function class names must not contain the string: '.gui.'
2021-03-27 10:00:47,146 [StandardJMeterEngine] INFO  o.a.j.v.backend.BackendListener 316 - 6ac014c5: Starting worker with class: class io.metersphere.api.jmeter.APIBackendListenerClient and queue capacity: 5000
2021-03-27 10:00:47,147 [StandardJMeterEngine] INFO  o.a.j.v.backend.BackendListener ? - 6ac014c5: Started  worker with class: class io.metersphere.api.jmeter.APIBackendListenerClient
2021-03-27 10:00:47,553 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine ? - Starting ThreadGroup: 1 : 6ac014c5
2021-03-27 10:00:47,553 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine ? - Starting 1 threads for group 6ac014c5.
2021-03-27 10:00:47,554 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine ? - Thread will continue on error
2021-03-27 10:00:47,554 [StandardJMeterEngine] INFO  o.apache.jmeter.threads.ThreadGroup ? - Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false
2021-03-27 10:00:47,561 [StandardJMeterEngine] INFO  o.apache.jmeter.threads.ThreadGroup ? - Started thread group number 1
2021-03-27 10:00:47,561 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine ? - All thread groups have been started
2021-03-27 10:00:47,566 [6ac014c5 1-1] INFO  o.apache.jmeter.threads.JMeterThread ? - Thread started: 6ac014c5 1-1
2021-03-27 10:00:47,689 [6ac014c5 1-1] INFO  o.apache.jmeter.threads.JMeterThread ? - Thread finished: 6ac014c5 1-1
2021-03-27 10:00:47,690 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine ? - Notifying test listeners of end of test
2021-03-27 10:00:47,694 [StandardJMeterEngine] INFO  o.apache.jmeter.services.FileServer ? - Default base='/deployments'
2021-03-27 10:00:47,694 [Thread-74] INFO  o.a.j.v.backend.BackendListener ? - Worker ended
2021-03-27 10:00:47,711 [StandardJMeterEngine] WARN  o.a.j.engine.StandardJMeterEngine 223 - Error encountered during shutdown of org.apache.jmeter.visualizers.backend.BackendListener@2e810c13
java.lang.IllegalStateException: Failed calling teardownTest
	at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:378)
	at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:384)
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:218)
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:492)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at io.metersphere.api.jmeter.APIBackendListenerClient.teardownTest(APIBackendListenerClient.java:221)
	at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:376)
	... 4 common frames omitted

```
注释脚本最后一行再次执行
```shell
2021-03-27 10:07:35,480 [qtp1027495011-551] INFO  org.apache.jmeter.util.JMeterUtils ? - Setting Locale to en_US
2021-03-27 10:07:35,481 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine ? - Running the test!
2021-03-27 10:07:35,482 [StandardJMeterEngine] INFO  o.apache.jmeter.samplers.SampleEvent ? - List of sample_variables: []
2021-03-27 10:07:35,486 [StandardJMeterEngine] INFO  o.a.j.v.backend.BackendListener ? - 67c25d99-b72a-3214-5f95-9981586a7fa7: Starting worker with class: class io.metersphere.api.jmeter.APIBackendListenerClient and queue capacity: 5000
2021-03-27 10:07:35,486 [StandardJMeterEngine] INFO  o.a.j.v.backend.BackendListener ? - 67c25d99-b72a-3214-5f95-9981586a7fa7: Started  worker with class: class io.metersphere.api.jmeter.APIBackendListenerClient
2021-03-27 10:07:36,139 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine ? - Starting ThreadGroup: 1 : ThreadGroup
2021-03-27 10:07:36,139 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine ? - Starting 1 threads for group ThreadGroup.
2021-03-27 10:07:36,139 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine ? - Thread will continue on error
2021-03-27 10:07:36,140 [StandardJMeterEngine] INFO  o.apache.jmeter.threads.ThreadGroup 220 - Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false
2021-03-27 10:07:36,141 [StandardJMeterEngine] INFO  o.apache.jmeter.threads.ThreadGroup ? - Started thread group number 1
2021-03-27 10:07:36,141 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine ? - All thread groups have been started
2021-03-27 10:07:36,142 [ThreadGroup 1-1] INFO  o.apache.jmeter.threads.JMeterThread ? - Thread started: ThreadGroup 1-1
2021-03-27 10:07:36,190 [ThreadGroup 1-1] INFO  o.a.j.m.JSR223PreProcessor.测试java包 ? - /opt/jmeter/lib/ext/ApacheJMeter_functions.jar
2021-03-27 10:07:36,190 [ThreadGroup 1-1] INFO  o.a.j.m.JSR223PreProcessor.测试java包 ? - /opt/jmeter/lib/ext/jython-standalone.jar
2021-03-27 10:07:36,190 [ThreadGroup 1-1] INFO  o.a.j.m.JSR223PreProcessor.测试java包 ? - /opt/metersphere/data/jar/checkout-sdk-java-2.3.1.jar
2021-03-27 10:07:36,191 [ThreadGroup 1-1] INFO  o.a.j.m.JSR223PreProcessor.测试java包 ? - /opt/metersphere/data/jar/pay_jmeter_utils-0.0.3-all.jar
2021-03-27 10:07:36,191 [ThreadGroup 1-1] INFO  o.a.j.m.JSR223PreProcessor.测试java包 ? - /opt/metersphere/data/jar/gson-2.8.2.jar
2021-03-27 10:07:36,215 [ThreadGroup 1-1] INFO  o.a.j.p.h.sampler.HTTPHCAbstractImpl ? - Local host = e4eac0d1c5b4
2021-03-27 10:07:36,221 [ThreadGroup 1-1] INFO  o.a.j.p.http.sampler.HTTPHC4Impl ? - HTTP request retry count = 0
2021-03-27 10:07:36,279 [ThreadGroup 1-1] INFO  o.a.j.p.h.s.h.LazyLayeredConnectionSocketFactory ? - Setting up HTTPS TrustAll Socket Factory
2021-03-27 10:07:36,283 [ThreadGroup 1-1] INFO  o.apache.jmeter.util.JsseSSLManager ? - Using default SSL protocol: TLS
2021-03-27 10:07:36,284 [ThreadGroup 1-1] INFO  o.apache.jmeter.util.JsseSSLManager ? - SSL session context: per-thread
2021-03-27 10:07:36,292 [ThreadGroup 1-1] INFO  org.apache.jmeter.util.SSLManager ? - JmeterKeyStore Location:  type JKS
2021-03-27 10:07:36,294 [ThreadGroup 1-1] INFO  org.apache.jmeter.util.SSLManager ? - KeyStore created OK
2021-03-27 10:07:36,294 [ThreadGroup 1-1] WARN  org.apache.jmeter.util.SSLManager ? - Keystore file not found, loading empty keystore
2021-03-27 10:07:36,443 [ThreadGroup 1-1] INFO  o.apache.jmeter.threads.JMeterThread ? - Thread is done: ThreadGroup 1-1
2021-03-27 10:07:36,443 [ThreadGroup 1-1] INFO  o.apache.jmeter.threads.JMeterThread 328 - Thread finished: ThreadGroup 1-1
2021-03-27 10:07:36,444 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine ? - Notifying test listeners of end of test
2021-03-27 10:07:36,445 [Thread-78] INFO  o.a.j.v.backend.BackendListener ? - Worker ended
2021-03-27 10:07:36,464 [StandardJMeterEngine] WARN  o.a.j.engine.StandardJMeterEngine 223 - Error encountered during shutdown of org.apache.jmeter.visualizers.backend.BackendListener@5f26c639
java.lang.IllegalStateException: Failed calling teardownTest
	at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:378)
	at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:384)
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:218)
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:492)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at io.metersphere.api.jmeter.APIBackendListenerClient.sendTask(APIBackendListenerClient.java:262)
	at io.metersphere.api.jmeter.APIBackendListenerClient.teardownTest(APIBackendListenerClient.java:253)
	at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:376)
	... 4 common frames omitted

```
可以在日志中看到已经导入的包
进入容器查看
![image](https://user-images.githubusercontent.com/5517369/112707212-aeb95000-8ee4-11eb-9719-eda8a84c7cb9.png)

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by guhan121** [comment]
@zyyfit 1.9.0才能解决么

**Comment by youliyuan-fit2cloud** [comment]
> @zyyfit 1.9.0才能解决么

v1.8.1解决，预计今天发布~

**Comment by guhan121** [comment]
原因是我的java包用了org/slf4j/LoggerFactory 打包的时候因为担心包体积太大和冲突把这个排除了

前面看不到是因为系统的日志里面看不到；本地用idea测试也是一直正常；
最后我mvn package了一个包在本地运行发现在 console里面有显示 

E`xception in thread "ThreadGroup 1-1" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory`

但是服务的info.log的日志里面没有这方面的报错;是报错
```
java.lang.IllegalStateException: Failed calling teardownTest
 at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:378)
 at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:384)
 at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:218)
 at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:492)
 at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.metersphere.commons.exception.MSException: Not Support Key: test_not_found
```



@youliyuan-fit2cloud 建议修改一下日志打印 实际上在控制台日志有打印失败原因 但是ms的info.log里面看不到
