### ISSUE TITLE
[BUG] 相同的脚本，平台执行提示no model named exception，在服务器的虚拟环境执行正常

### ISSUE THREAD

**Issue by bobo-wk** [metersphere/metersphere#17478]
### 联系方式

1136912596@qq.com

### MeterSphere 版本

v2.0.0-b4

### 使用外置数据库

否

### 问题描述

相同的脚本，平台执行提示nomodel named exception，在服务器的虚拟环境执行正常

import sys
sys.path.append("/opt/metersphere/data/python/lib/python2.7/site-packages")

from rediscluster import RedisCluster
r = RedisCluster(startup_nodes=[{"host":'172.16.6.50', "port":"7000"}], decode_responses=True)
consume = r.get("fat_acct:Futu:${act_id}:consume:orderSum")
produce = r.get("fat_acct:Futu:${act_id}:produce:orderSum")
robot = '0' 
if consume != produce:
    robot = '1'  

### 重现步骤

1、服务器虚拟环境进行脚本执行，正常
![image](https://user-images.githubusercontent.com/75885014/186799682-9b7364a3-017f-40f6-ab4e-d22d2b073d93.png)
2、平台执行，报异常
![image](https://user-images.githubusercontent.com/75885014/186799710-b5c0be91-dfad-4fcb-a664-5ab60746332c.png)

### 期待的正确结果

执行正常

### 相关日志输出

```shell
ImportError: No module named exceptions in <script> at line number 4
javax.script.ScriptException
   at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:202)
   at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:42)
   at org.python.jsr223.PyScriptEngine.access$300(PyScriptEngine.java:20)
   at org.python.jsr223.PyScriptEngine$PyCompiledScript.eval(PyScriptEngine.java:231)
   at java.scripting/javax.script.CompiledScript.eval(CompiledScript.java:89)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:250)
   at org.apache.jmeter.extractor.JSR223PostProcessor.process(JSR223PostProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPostProcessors(JMeterThread.java:989)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:603)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:500)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:264)
   at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by youliyuan-fit2cloud** [comment]
你好，感谢反馈，这个问题在v2.1.0中已修复，请升级一下吧。
