### ISSUE TITLE
[BUG]后置操作-添加脚本执行失败

### ISSUE THREAD

**Issue by lihulanxx** [metersphere/metersphere#17681]
### 联系方式

lvxiaoshu123@163.com

### MeterSphere 版本

v1.20.13

### 使用外置数据库

是

### 问题描述

后置操作 脚本
import json

def dataAssert(sqlData, key, value):
    data = vars.getObject(sqlData)
    size = len(data)
    if size == 0:
        msg = "数据库未查到数据"
        AssertionResult.setFailure(true)
        AssertionResult.setFailure(msg.decode("utf-8"))
    else:
        info = data.get(0)
        re = info[key]
        msg = "key --:" + key + " --value --: " + str(re)
        log.info(msg)
        if re != value:
            msg_1 = " ---预期值 ："
            msg_2 =" 实际值为 ："
            msg = key.encode("utf-8") + msg_1 + str(value).encode("utf-8") + msg_2 + str(re).encode("utf-8")
            AssertionResult.setFailure(true)
            AssertionResult.setFailure(msg.decode("utf-8"))

log.info("-----init--------")
sqlData = "result"
data = vars.getObject(sqlData)
size = len(data)
if size > 0:
    info = data.get(0)
    log.info(str(info))
dataAssert(sqlData, "fState", 1)    

执行后报错

NameError: name 'AssertionResult' is not defined in <script> at line number 24
javax.script.ScriptException
   at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:222)
   at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:59)
   at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:263)
   at org.apache.jmeter.extractor.JSR223PostProcessor.process(JSR223PostProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPostProcessors(JMeterThread.java:975)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:590)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:487)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:251)
   at java.base/java.lang.Thread.run(Thread.java:829)

### 重现步骤

一直报错

**Comment by youliyuan-fit2cloud** [comment]
请记得写bug的标题哈，我们方便快速处理。

**Comment by zyyfit** [comment]
您好，没有复现这个问题，只有一个nonetype的报错
![image](https://user-images.githubusercontent.com/73461316/189292495-cb6ff751-b00e-4a7d-a33b-4e663726b71f.png)
