### ISSUE TITLE
[QUESTION]当接口数据量比较大时或场景中接口步骤比较多，报 TruncatedChunkException异常，是否为MeterSphere的bug？

### ISSUE THREAD

**Issue by Faerie1999** [metersphere/metersphere#17939]
### 请描述您的问题

当接口数据量比较大时，调试场景，有时候会报以下异常（不是每次都报），设置了超时时间和响应时间，但是还是会报这个问题
```
org.apache.http.TruncatedChunkException: Truncated chunk (expected size: 8,192; actual size: 1,143)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:197)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:148)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.readResponse(HTTPSamplerBase.java:1936)
	at org.apache.jmeter.protocol.http.sampler.HTTPAbstractImpl.readResponse(HTTPAbstractImpl.java:476)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.sample(HTTPHC4Impl.java:673)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:119)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1296)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1285)
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:656)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:575)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:487)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:251)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

![image](https://user-images.githubusercontent.com/31870788/190622803-37adc781-e271-4620-91a5-4613364914c7.png)

**Comment by Hyyfit** [comment]
这种应该是 jmeter 执行过程中结果没收完就关闭了线程组导致的。
操作上是点击了停止，然后出现的吗？ 
具体是什么操作呢？有丢包吗？

**Comment by Faerie1999** [comment]
- 没有点击停止，是等它执行完成的。
- 如果数据量少，就不会报错。
- nginx缓存应该是默认关闭的

**Comment by youliyuan-fit2cloud** [comment]
你好，使用时MS哪个版本？接口数量大是多大？多少个场景？包含多少个请求呢？

**Comment by Faerie1999** [comment]
版本：1.20.7
接口响应的结果中包含一个list字段，list字段下有168条数据
一个场景，其中大概两三个请求，但要执行一个查询数据列表的接口（即响应结果包含168条数据的接口）就会有一定的概率报这个问题

**Comment by youliyuan-fit2cloud** [comment]
> 版本：1.20.7 接口响应的结果中包含一个list字段，list字段下有168条数据 一个场景，其中大概两三个请求，但要执行一个查询数据列表的接口（即响应结果包含168条数据的接口）就会有一定的概率报这个问题

建议升级到最新的v1.20.15-lts版本再看看，如果还会出现麻烦反馈给我们，我们会继续跟进复现该问题。

**Comment by Faerie1999** [comment]
好的

**Comment by youkuzazazazaza** [comment]
> 好的

请问解决了吗
