### ISSUE TITLE
[BUG] 某用户的Swagger2.0的接口文档在接口定义模块下导入抛出异常 "autoType is not support"

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#18202]
### 联系方式

王进

### MeterSphere 版本

1.20.x, cloud, 2.1

### 使用外置数据库

否

### 问题描述

某用户的Swagger2.0的接口文档在接口定义模块下导入抛出异常 "autoType is not support"

### 重现步骤

1. 接口测试，接口定义，更多操作》导入，选择Swagger格式
2. 上传文件
3. 保存，报错，用户给的测试文件如下

链接: https://pan.baidu.com/s/1JLWPfIXuSm9P2J1x2PonaA 提取码: yssp 

### 相关日志输出

```shell
]
2022-09-22 14:43:07,487 [XNIO-1 task-49] ERROR i.m.api.service.ApiDefinitionService ? - Method[apiTestImport][autoType is not support.           ]
com.alibaba.fastjson.JSONException: autoType is not support.           
        at com.alibaba.fastjson.parser.ParserConfig.checkAutoType(ParserConfig.java:1542)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:343)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:581)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:581)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:581)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1430)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1390)
        at com.alibaba.fastjson.JSON.parse(JSON.java:181)
        at com.alibaba.fastjson.JSON.parse(JSON.java:191)
        at com.alibaba.fastjson.JSON.parse(JSON.java:147)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:252)
        at io.metersphere.api.dto.definition.parse.Swagger2Parser.parse(Swagger2Parser.java:50)
        at io.metersphere.api.dto.definition.parse.Swagger2Parser.parse(Swagger2Parser.java:30)
        at io.metersphere.api.service.ApiDefinitionService.apiTestImport(ApiDefinitionService.java:1374)
        at io.metersphere.api.service.ApiDefinitionService$$FastClassBySpringCGLIB$$72d8ca15.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.pr
```

### 附加信息

相同的swagger文件，如果用postman是可以导入的，再导出，就可以导入到MS平台。

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by youliyuan-fit2cloud** [comment]
v1.20.15-lts中已修复。
