### ISSUE TITLE
[BUG]使用测试计划导入场景执行，或者接口自动化批量执行场景，结果报告必有未执行的接口

### ISSUE THREAD

**Issue by conansharp** [metersphere/metersphere#18379]
### MeterSphere 版本

v2.1.0-2de48bb8
v2.2.0

### 使用外置数据库

否

### 问题描述

1.测试计划导入场景用例（几十个场景），然后执行测试计划，结束后查看报告，发现有未执行的接口
2.接口自动化模块，批量勾选场景，一起执行，结束后查看报告，发现有未执行的接口
![image](https://user-images.githubusercontent.com/111938588/194810137-5fcdd760-3fa0-4d3b-a4a6-ace1f16741ed.png)

### 重现步骤

问题必现的，一起跑就会出现未执行的，如果一个个场景单独调试，都是可以成功的，是有什么性能的问题吗？？？
**感觉是条件控制器的使用也有问题，碰到条件控制器就不往下执行了，明明是满足条件的**
![image](https://user-images.githubusercontent.com/111938588/194813024-9f8f5ede-1e5c-48d0-b6f6-bc4e7b8c4463.png)

### 相关日志输出

2022-10-10 14:51:29,727 [StandardJMeterEngine] ERROR i.m.commons.utils.SessionUtils ? - Method[getUser][No SecurityManager accessible to the calling code, either bound to the org.apache.shiro.util.ThreadContext or as a vm static singleton.  This is an invalid application configuration.]
org.apache.shiro.UnavailableSecurityManagerException: No SecurityManager accessible to the calling code, either bound to the org.apache.shiro.util.ThreadContext or as a vm static singleton.  This is an invalid application configuration.
        at org.apache.shiro.SecurityUtils.getSecurityManager(SecurityUtils.java:123)
        at org.apache.shiro.subject.Subject$Builder.<init>(Subject.java:626)
        at org.apache.shiro.SecurityUtils.getSubject(SecurityUtils.java:56)
        at io.metersphere.commons.utils.SessionUtils.getUser(SessionUtils.java:37)
        at io.metersphere.commons.utils.SessionUtils.getCurrentProjectId(SessionUtils.java:139)
        at io.metersphere.api.dto.definition.request.processors.post.MsJSR223PostProcessor.toHashTree(MsJSR223PostProcessor.java:91)
        at io.metersphere.api.dto.definition.request.sampler.MsHTTPSamplerProxy.toHashTree(MsHTTPSamplerProxy.java:274)
        at io.metersphere.api.dto.definition.request.MsScenario.toHashTree(MsScenario.java:183)
        at io.metersphere.api.dto.definition.request.MsThreadGroup.toHashTree(MsThreadGroup.java:47)
        at io.metersphere.api.dto.definition.request.MsTestPlan.lambda$toHashTree$0(MsTestPlan.java:37)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at io.metersphere.api.dto.definition.request.MsTestPlan.toHashTree(MsTestPlan.java:36)
        at io.metersphere.api.exec.utils.GenerateHashTreeUtil.generateHashTree(GenerateHashTreeUtil.java:173)
        at io.metersphere.api.exec.scenario.ApiScenarioSerialService.serial(ApiScenarioSerialService.java:75)
        at io.metersphere.api.exec.scenario.ApiScenarioSerialService$$FastClassBySpringCGLIB$$abec098c.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at io.metersphere.api.exec.scenario.ApiScenarioSerialService$$EnhancerBySpringCGLIB$$4d16a477.serial(<generated>)
        at io.metersphere.api.exec.scenario.ApiScenarioSerialService$$FastClassBySpringCGLIB$$abec098c.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at io.metersphere.api.exec.scenario.ApiScenarioSerialService$$EnhancerBySpringCGLIB$$4d935f9d.serial(<generated>)
        at io.metersphere.api.service.ApiExecutionQueueService.queueNext(ApiExecutionQueueService.java:373)
        at io.metersphere.api.service.ApiExecutionQueueService$$FastClassBySpringCGLIB$$d7e5fe4f.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
        at io.metersphere.api.service.ApiExecutionQueueService$$EnhancerBySpringCGLIB$$c25614a0.queueNext(<generated>)
        at io.metersphere.api.service.ApiExecutionQueueService$$FastClassBySpringCGLIB$$d7e5fe4f.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
        at io.metersphere.api.service.ApiExecutionQueueService$$EnhancerBySpringCGLIB$$638d1da8.queueNext(<generated>)
        at io.metersphere.api.jmeter.MsApiBackendListener.teardownTest(MsApiBackendListener.java:74)
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:375)
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:383)
        at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:230)
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:507)
        at java.base/java.lang.Thread.run(Thread.java:829)
2022-10-10 14:51:29,782 [StandardJMeterEngine] ERROR i.m.commons.utils.SessionUtils ? - Method[getCurrentProjectId][No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.]
java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
        at org.springframework.web.context.request.RequestContextHolder.currentRequestAttributes(RequestContextHolder.java:131)
        at io.metersphere.commons.utils.SessionUtils.getCurrentProjectId(SessionUtils.java:131)
        at io.metersphere.api.dto.definition.request.processors.post.MsJSR223PostProcessor.toHashTree(MsJSR223PostProcessor.java:91)
        at io.metersphere.api.dto.definition.request.sampler.MsHTTPSamplerProxy.toHashTree(MsHTTPSamplerProxy.java:274)
        at io.metersphere.api.dto.definition.request.MsScenario.toHashTree(MsScenario.java:183)
        at io.metersphere.api.dto.definition.request.MsThreadGroup.toHashTree(MsThreadGroup.java:47)
        at io.metersphere.api.dto.definition.request.MsTestPlan.lambda$toHashTree$0(MsTestPlan.java:37)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at io.metersphere.api.dto.definition.request.MsTestPlan.toHashTree(MsTestPlan.java:36)
        at io.metersphere.api.exec.utils.GenerateHashTreeUtil.generateHashTree(GenerateHashTreeUtil.java:173)
        at io.metersphere.api.exec.scenario.ApiScenarioSerialService.serial(ApiScenarioSerialService.java:75)
        at io.metersphere.api.exec.scenario.ApiScenarioSerialService$$FastClassBySpringCGLIB$$abec098c.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at io.metersphere.api.exec.scenario.ApiScenarioSerialService$$EnhancerBySpringCGLIB$$4d16a477.serial(<generated>)
        at io.metersphere.api.exec.scenario.ApiScenarioSerialService$$FastClassBySpringCGLIB$$abec098c.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at io.metersphere.api.exec.scenario.ApiScenarioSerialService$$EnhancerBySpringCGLIB$$4d935f9d.serial(<generated>)
        at io.metersphere.api.service.ApiExecutionQueueService.queueNext(ApiExecutionQueueService.java:373)
        at io.metersphere.api.service.ApiExecutionQueueService$$FastClassBySpringCGLIB$$d7e5fe4f.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
        at io.metersphere.api.service.ApiExecutionQueueService$$EnhancerBySpringCGLIB$$c25614a0.queueNext(<generated>)
        at io.metersphere.api.service.ApiExecutionQueueService$$FastClassBySpringCGLIB$$d7e5fe4f.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
        at io.metersphere.api.service.ApiExecutionQueueService$$EnhancerBySpringCGLIB$$638d1da8.queueNext(<generated>)
        at io.metersphere.api.service.RemakeReportService.remake(RemakeReportService.java:143)
        at io.metersphere.api.exec.utils.GenerateHashTreeUtil.remakeException(GenerateHashTreeUtil.java:187)
        at io.metersphere.api.exec.utils.GenerateHashTreeUtil.generateHashTree(GenerateHashTreeUtil.java:177)
        at io.metersphere.api.exec.scenario.ApiScenarioSerialService.serial(ApiScenarioSerialService.java:75)
        at io.metersphere.api.exec.scenario.ApiScenarioSerialService$$FastClassBySpringCGLIB$$abec098c.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at io.metersphere.api.exec.scenario.ApiScenarioSerialService$$EnhancerBySpringCGLIB$$4d16a477.serial(<generated>)
        at io.metersphere.api.exec.scenario.ApiScenarioSerialService$$FastClassBySpringCGLIB$$abec098c.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at io.metersphere.api.exec.scenario.ApiScenarioSerialService$$EnhancerBySpringCGLIB$$4d935f9d.serial(<generated>)
        at io.metersphere.api.service.ApiExecutionQueueService.queueNext(ApiExecutionQueueService.java:373)
        at io.metersphere.api.service.ApiExecutionQueueService$$FastClassBySpringCGLIB$$d7e5fe4f.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
        at io.metersphere.api.service.ApiExecutionQueueService$$EnhancerBySpringCGLIB$$c25614a0.queueNext(<generated>)
        at io.metersphere.api.service.ApiExecutionQueueService$$FastClassBySpringCGLIB$$d7e5fe4f.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
        at io.metersphere.api.service.ApiExecutionQueueService$$EnhancerBySpringCGLIB$$638d1da8.queueNext(<generated>)
        at io.metersphere.api.jmeter.MsApiBackendListener.teardownTest(MsApiBackendListener.java:74)
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:375)
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:383)
        at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:230)
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:507)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by minnn0306** [comment]
单个场景执行，场景中的每个接口都会执行的。但是批量执行多个场景，每次都是不同场景、不同接口会出现不执行的现象

**Comment by liushuneng** [comment]
@xulinde 
![d64a928a93c793c9e78cd9a632d6b90](https://user-images.githubusercontent.com/45531073/203723662-8f62a7b6-a0ce-43af-84fd-e256e9639f33.png)
1.20.16版本也有客户反馈测试计划接口有未执行问题

**Comment by conansharp** [comment]
> 您超过30天未反馈信息，我们将关闭此Issue，如有需要您可以重新打开或提交新的Issue

怎么重新打开？

**Comment by zyyfit** [comment]
您好，最新版2.6版本没有复现这个问，可以详细描述一下具体的操作步骤和具体的场景信息吗？如果方便的话可以上传一下复现场景

**Comment by xulinde** [comment]
由于长时间未反馈，将关闭该issue，如果再次遇到请 重新打开或提交新issue，感谢您的理解和支持～
