### ISSUE TITLE
[BUG]TCP请求抛出异常，相同的jmeter脚本在本地执行是好的

### ISSUE THREAD

**Issue by 35plus** [metersphere/metersphere#18892]
### 联系方式

王进

### MeterSphere 版本

1.20.15

### 使用外置数据库

否

### 问题描述

客户用tcp请求测试生产环境，抛出如下 异常：
org.apache.jmeter.protocol.tcp.sampler.TCPSampler@d1386cc Exception creating: BinaryTCPClientImpl 
class org.apache.jmeter.protocol.tcp.sampler.BinaryTCPClientImpl cannot be cast to class org.apache.jmeter.protocol.tcp.sampler.MsTCPClientImpl (org.apache.jmeter.protocol.tcp.sampler.BinaryTCPClientImpl and org.apache.jmeter.protocol.tcp.sampler.MsTCPClientImpl are in unnamed module of loader 'app')
java.lang.ClassCastException
   at org.apache.jmeter.protocol.tcp.sampler.TCPSampler.getProtocol(TCPSampler.java:329)
   at org.apache.jmeter.protocol.tcp.sampler.TCPSampler.initSampling(TCPSampler.java:481)
   at org.apache.jmeter.protocol.tcp.sampler.TCPSampler.sample(TCPSampler.java:348)
   at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:656)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:575)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:487)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:251)
   at java.base/java.lang.Thread.run(Thread.java:829)

### 重现步骤

1. 本地在jmeter里调试好tcp请求，测试成功：
![1666594371993](https://user-images.githubusercontent.com/76033005/197465087-dd343173-a9fd-4b80-81f2-d98cb57fee54.png)
2. 上传jmeter中用的自定义生成token的jar包到MS项目设置下的文件管理
3. 在jmeter上新建一个接口自动化场景，添加自定义请求，输入 jmeter里面的ip和端口号，请求内容，前置脚本：
![1666594519774](https://user-images.githubusercontent.com/76033005/197465473-47b75166-9943-4248-a6ea-6ed0fa1907f4.png)
4. 点调试，抛出如下异常：
org.apache.jmeter.protocol.tcp.sampler.TCPSampler@d1386cc Exception creating: BinaryTCPClientImpl 
class org.apache.jmeter.protocol.tcp.sampler.BinaryTCPClientImpl cannot be cast to class org.apache.jmeter.protocol.tcp.sampler.MsTCPClientImpl (org.apache.jmeter.protocol.tcp.sampler.BinaryTCPClientImpl and org.apache.jmeter.protocol.tcp.sampler.MsTCPClientImpl are in unnamed module of loader 'app')
java.lang.ClassCastException
   at org.apache.jmeter.protocol.tcp.sampler.TCPSampler.getProtocol(TCPSampler.java:329)
   at org.apache.jmeter.protocol.tcp.sampler.TCPSampler.initSampling(TCPSampler.java:481)
   at org.apache.jmeter.protocol.tcp.sampler.TCPSampler.sample(TCPSampler.java:348)
   at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:656)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:575)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:487)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:251)
   at java.base/java.lang.Thread.run(Thread.java:829)

### 附加信息

1. jar确定已上传并生效
2. 在MS平台上引用客户自己的jar生成token是可以的，确定没有问题
3. 第三本地调试确定是可以的。
4. 因为是企业客户，文件不便上传，如有需要请联系我。

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by 35plus** [comment]
zyy，帮忙把这个缺陷 排高点，感谢，最好能在1.20.16上修复。 再次感谢

**Comment by xulinde** [comment]
> zyy，帮忙把这个缺陷 排高点，感谢，最好能在1.20.16上修复。 再次感谢

1.20.16-lts会修复

**Comment by zyyfit** [comment]
1.20.16 和 2.3.0 都已修复
