### ISSUE TITLE
[BUG]groovy无法使用JsonOutput.toJson将 Groovy 对象序列化为 JSON 字符串

### ISSUE THREAD

**Issue by milesCorgi** [metersphere/metersphere#1928]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.8.2
**Bug 描述**
简要描述您碰到的问题
执行以下groovy代码段

// 导入json转化包
import groovy.json.JsonOutput
// req为一个map
Object req = vars.getObject("req")
req["bizContent"] = JsonOutput.toJson(req["bizContent"])

报错
javax.script.ScriptException: java.lang.RuntimeException: Unable to load FastStringService
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:320)
	at org.codehaus.groovy.jsr223.GroovyCompiledScript.eval(GroovyCompiledScript.java:71)
	at javax.script.CompiledScript.eval(CompiledScript.java:92)
	at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:243)
	at org.apache.jmeter.modifiers.JSR223PreProcessor.process(JSR223PreProcessor.java:45)
	at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:965)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:549)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Unable to load FastStringService
	at org.apache.groovy.json.internal.FastStringUtils.getService(FastStringUtils.java:57)
	at org.apache.groovy.json.internal.FastStringUtils.toCharArray(FastStringUtils.java:67)
	at org.apache.groovy.json.internal.CharBuf.addJsonFieldName(CharBuf.java:524)
	at groovy.json.DefaultJsonGenerator.writeMapEntry(DefaultJsonGenerator.java:386)
	at groovy.json.DefaultJsonGenerator.writeMap(DefaultJsonGenerator.java:375)
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:200)
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:164)
	at groovy.json.DefaultJsonGenerator.toJson(DefaultJsonGenerator.java:98)
	at groovy.json.JsonOutput.toJson(JsonOutput.java:153)
	at groovy.json.JsonOutput$toJson.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at Script177.run(Script177.groovy:4)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:317)
	... 9 common frames omitted

**期待的正确结果**
JsonOutput.toJson正常执行，输出 JSON 字符串

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，将在后续版本修复这个问题

**Comment by zyyfit** [comment]
您好，1.9版本修复了这个问题，目前最新版是1.10，请升级后试一下
