### ISSUE TITLE
[BUG]前置脚本中引入外部文件未成功

### ISSUE THREAD

**Issue by xiaochongzi-ling** [metersphere/metersphere#19298]
### 联系方式

微信17321336962

### MeterSphere 版本

v1.20.14-lts-83677fba

### 使用外置数据库

是

### 问题描述

前置脚本中引入外部文件未成功:
![图片](https://user-images.githubusercontent.com/23067502/198913261-f1adafa4-b650-4520-9eaf-c8cbedb608c6.png)

![图片](https://user-images.githubusercontent.com/23067502/198913306-b66c5af0-ea1d-4063-846e-90c80aba549a.png)

### 重现步骤

1.项目设置-文件管理中上传jpg;
2.接口自动化-前置脚本中引用jpg。
import org.apache.commons.codec.binary.Base64;

import java.io.FileInputStream;
import java.io.InputStream;

String imgFile = "jiangtao.jpg";
InputStream inputStream = null;
byte[] data = null;
inputStream = new FileInputStream(imgFile);
data = new byte[inputStream.available()];
inputStream.read(data);
inputStream.close();
Base64 encoder = new Base64();
vars.put("encoder_data", encoder.encodeToString(data));

### 期待的正确结果

package test;

import org.apache.commons.codec.binary.Base64;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

public class png_to_base641 {
    public static String imageToBase64Str() {
        String imgFile = "D:\\资料\\身份证30\\江涛\\jiangtao.jpg";
        InputStream inputStream = null;
        byte[] data = null;
        try {
            inputStream = new FileInputStream(imgFile);
            data = new byte[inputStream.available()];
            inputStream.read(data);
            inputStream.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        // 加密
        Base64 encoder = new Base64();
        System.out.println( encoder.encodeToString(data));
        return encoder.encodeToString(data);
    }

    public static void main(String[] args) {
        png_to_base641.imageToBase64Str();
    }
}

![图片](https://user-images.githubusercontent.com/23067502/198915461-9615a9ea-1c67-40e7-bc7e-42b1d2d25bd7.png)

### 相关日志输出

```shell
2022-10-31 09:44:22 INFO 3a0c919f 1-1 Thread started: 3a0c919f 1-1
2022-10-31 09:44:22 ERROR 3a0c919f 1-1 Problem in JSR223 script, JSR223PreProcessor
Sourced file: inline evaluation of: ``import org.apache.commons.codec.binary.Base64;  import java.io.FileInputStream;  . . . '' : Object constructor : at Line: 9 : in file: inline evaluation of: ``import org.apache.commons.codec.binary.Base64;  import java.io.FileInputStream;  . . . '' : new FileInputStream ( imgFile ) 

Target exception: java.io.FileNotFoundException: jiangtao.jpg (No such file or directory)
 in inline evaluation of: ``import org.apache.commons.codec.binary.Base64;  import java.io.FileInputStream;  . . . '' at line number 9
javax.script.ScriptException
   at bsh.engine.BshScriptEngine.evalSource(BshScriptEngine.java:87)
   at bsh.engine.BshScriptEngine.eval(BshScriptEngine.java:46)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:263)
   at org.apache.jmeter.modifiers.JSR223PreProcessor.process(JSR223PreProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:985)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:547)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:487)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:251)
   at java.base/java.lang.Thread.run(Thread.java:829)
2022-10-31 09:44:22 INFO 3a0c919f 1-1 Thread is done: 3a0c919f 1-1
2022-10-31 09:44:22 INFO 3a0c919f 1-1 Thread finished: 3a0c919f 1-1
2022-10-31 09:44:22 INFO StandardJMeterEngine Notifying test listeners of end of test
2022-10-31 09:44:22 INFO Thread-67390 Worker ended
```

**Comment by youliyuan-fit2cloud** [comment]
你好，这样直接调用还不支持。可以把这个文件（图片）放在/opt/data 某个目录下，然后再指定这个位置读取文件。
