### ISSUE TITLE
[BUG]【接口测试】-自动化场景循环执行-后置脚本报unable to resolve class

### ISSUE THREAD

**Issue by liushuneng** [metersphere/metersphere#19539]
### 联系方式

82973834@qq.com

### MeterSphere 版本

1.20.15

### 使用外置数据库

否

### 问题描述

1.接口是rsa加密，上传jar包做加解密操作，自动化场景不加循环控制器，脚本可以正常执行，加循环控制器后，脚本第一次循环是正常的，从第二次循环后置脚本解密失败，控制台提示unable to resolve class错误信息

### 重现步骤

1.上传jar包
2.创建自动化场景
3.加入循环控制器-按次数执行
4.引用接口case(case有前后置脚本做加解密)
5.点保存并执行

### 期待的正确结果

脚本循环执行可以正常通过

### 相关日志输出

```shell
1.第一次循环控制台日志
2022-11-07 10:27:57 INFO StandardJMeterEngine Running the test!
2022-11-07 10:27:57 INFO StandardJMeterEngine List of sample_variables: []
2022-11-07 10:27:57 INFO StandardJMeterEngine 25e6ce9e_25e6ce9e: Starting worker with class: class io.metersphere.jmeter.MsBackendListenerClient and queue capacity: 5000
2022-11-07 10:27:57 INFO StandardJMeterEngine 25e6ce9e_25e6ce9e: Started  worker with class: class io.metersphere.jmeter.MsBackendListenerClient
2022-11-07 10:27:59 INFO StandardJMeterEngine Starting ThreadGroup: 1 : 25e6ce9e
2022-11-07 10:27:59 INFO StandardJMeterEngine Starting 1 threads for group 25e6ce9e.
2022-11-07 10:27:59 INFO StandardJMeterEngine Thread will continue on error
2022-11-07 10:27:59 INFO StandardJMeterEngine Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false
2022-11-07 10:27:59 INFO StandardJMeterEngine Started thread group number 1
2022-11-07 10:27:59 INFO StandardJMeterEngine All thread groups have been started
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 Thread started: 25e6ce9e 1-1
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 登录前置查询-前置返回：org.apache.jmeter.threads.JMeterVariables@1edb541a
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 登录后置查询-后置返回：{"userStatus":"1"}
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 登录后置查询-获取userStatus：1
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 随机手机号_短信注册接口-前置返回：[area:86, smsCode:666888, mobile:15366308080, inventCode:U2167]
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 随机手机号_短信注册接口-后置返回：{"expiresIn":86399,"additionalInformation":{},"expired":false,"scope":["all"],"inviteCode":"55QY0","name":null,"expiration":"2022-11-08T02:27:59.638+00:00","tokenType":"bearer","userName":"86+15366308080","value":"df9f70bf-0b58-4fc3-8af2-76dbc9e45c1d","userId":"18555","refreshToken":{"expiration":"2022-11-12T02:27:59.638+00:00","value":"d23fee88-6998-4848-bd88-a9a5a463d23b"}}
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 随机手机号_短信注册接口token：df9f70bf-0b58-4fc3-8af2-76dbc9e45c1d
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 随机手机号_短信注册接口userNameMobile：15366308080
2022-11-07 10:27:59 ERROR 25e6ce9e 1-1 Problem in JSR223 script, JSR223PostProcessor
javax.script.ScriptException: groovy.lang.MissingMethodException: No signature of method: static top.auntie.Input.userId() is applicable for argument types: (org.apache.jmeter.protocol.http.sampler.HTTPSampleResult, String) values: [随机手机号_短信注册接口, userId]
Possible solutions: every(), grep(), stream(), use([Ljava.lang.Object;), use(java.lang.Class, groovy.lang.Closure), use(java.util.List, groovy.lang.Closure)
javax.script.ScriptException
   at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:158)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:263)
   at org.apache.jmeter.extractor.JSR223PostProcessor.process(JSR223PostProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPostProcessors(JMeterThread.java:975)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:590)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:487)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:251)
   at java.base/java.lang.Thread.run(Thread.java:829)
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 随机手机号注册_设置密码-前置返回：[area:86, password:aaa11111, repeatPassword:aaa11111, mobile:15366308080, type:1]
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 随机手机号注册_设置密码-后置返回：{"actualControlDescription":null,"country":null,"isActualControl":null,"gender":null,"city":null,"badCreditDescription":null,"customerSubject":"P","operateTime":null,"channel":"01","isRead":null,"remark":null,"careerCategory":null,"title":null,"isQua":"N","isShareBdata":"Y","mode":null,"post":null,"province":null,"customerId":17527,"isTrade":null,"value":null,"email":null,"address":null,"operateId":null,"mobile":"15366308080","customerNumber":"","beneficiaryDescription":null,"customerName":null,"isBadCredit":null,"birthRegion":null,"areaCode":"86","pc":null,"recordTime":1667788079785,"beneficiary":null,"createTime":1667788079785,"firstPy":null}
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 用户登录-前置返回:[area:86, password:aaa11111, username:15366308080]
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 用户登录-后置返回：{"expiresIn":86399,"additionalInformation":{},"expired":false,"scope":["all"],"inviteCode":"55QY0","name":null,"expiration":"2022-11-08T02:27:59.942+00:00","tokenType":"bearer","userName":"86+15366308080","value":"249a1e10-c825-4a6a-a6c2-8d58fa2efdda","userId":"18555","refreshToken":{"expiration":"2022-11-12T02:27:59.940+00:00","value":"eeb6d565-68f9-49b1-a174-8b115d76e1ba"}}
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 用户登录-获取登录token：249a1e10-c825-4a6a-a6c2-8d58fa2efdda
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 用户登录-获取登录userId：18555



第二次循环控制台日志：
2022-11-07 10:27:57 INFO StandardJMeterEngine Running the test!
2022-11-07 10:27:57 INFO StandardJMeterEngine List of sample_variables: []
2022-11-07 10:27:57 INFO StandardJMeterEngine 25e6ce9e_25e6ce9e: Starting worker with class: class io.metersphere.jmeter.MsBackendListenerClient and queue capacity: 5000
2022-11-07 10:27:57 INFO StandardJMeterEngine 25e6ce9e_25e6ce9e: Started  worker with class: class io.metersphere.jmeter.MsBackendListenerClient
2022-11-07 10:27:59 INFO StandardJMeterEngine Starting ThreadGroup: 1 : 25e6ce9e
2022-11-07 10:27:59 INFO StandardJMeterEngine Starting 1 threads for group 25e6ce9e.
2022-11-07 10:27:59 INFO StandardJMeterEngine Thread will continue on error
2022-11-07 10:27:59 INFO StandardJMeterEngine Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false
2022-11-07 10:27:59 INFO StandardJMeterEngine Started thread group number 1
2022-11-07 10:27:59 INFO StandardJMeterEngine All thread groups have been started
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 Thread started: 25e6ce9e 1-1
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 登录前置查询-前置返回：org.apache.jmeter.threads.JMeterVariables@1edb541a
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 登录后置查询-后置返回：{"userStatus":"1"}
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 登录后置查询-获取userStatus：1
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 随机手机号_短信注册接口-前置返回：[area:86, smsCode:666888, mobile:15366308080, inventCode:U2167]
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 随机手机号_短信注册接口-后置返回：{"expiresIn":86399,"additionalInformation":{},"expired":false,"scope":["all"],"inviteCode":"55QY0","name":null,"expiration":"2022-11-08T02:27:59.638+00:00","tokenType":"bearer","userName":"86+15366308080","value":"df9f70bf-0b58-4fc3-8af2-76dbc9e45c1d","userId":"18555","refreshToken":{"expiration":"2022-11-12T02:27:59.638+00:00","value":"d23fee88-6998-4848-bd88-a9a5a463d23b"}}
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 随机手机号_短信注册接口token：df9f70bf-0b58-4fc3-8af2-76dbc9e45c1d
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 随机手机号_短信注册接口userNameMobile：15366308080
2022-11-07 10:27:59 ERROR 25e6ce9e 1-1 Problem in JSR223 script, JSR223PostProcessor
javax.script.ScriptException: groovy.lang.MissingMethodException: No signature of method: static top.auntie.Input.userId() is applicable for argument types: (org.apache.jmeter.protocol.http.sampler.HTTPSampleResult, String) values: [随机手机号_短信注册接口, userId]
Possible solutions: every(), grep(), stream(), use([Ljava.lang.Object;), use(java.lang.Class, groovy.lang.Closure), use(java.util.List, groovy.lang.Closure)
javax.script.ScriptException
   at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:158)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:263)
   at org.apache.jmeter.extractor.JSR223PostProcessor.process(JSR223PostProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPostProcessors(JMeterThread.java:975)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:590)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:487)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:251)
   at java.base/java.lang.Thread.run(Thread.java:829)
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 随机手机号注册_设置密码-前置返回：[area:86, password:aaa11111, repeatPassword:aaa11111, mobile:15366308080, type:1]
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 随机手机号注册_设置密码-后置返回：{"actualControlDescription":null,"country":null,"isActualControl":null,"gender":null,"city":null,"badCreditDescription":null,"customerSubject":"P","operateTime":null,"channel":"01","isRead":null,"remark":null,"careerCategory":null,"title":null,"isQua":"N","isShareBdata":"Y","mode":null,"post":null,"province":null,"customerId":17527,"isTrade":null,"value":null,"email":null,"address":null,"operateId":null,"mobile":"15366308080","customerNumber":"","beneficiaryDescription":null,"customerName":null,"isBadCredit":null,"birthRegion":null,"areaCode":"86","pc":null,"recordTime":1667788079785,"beneficiary":null,"createTime":1667788079785,"firstPy":null}
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 用户登录-前置返回:[area:86, password:aaa11111, username:15366308080]
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 用户登录-后置返回：{"expiresIn":86399,"additionalInformation":{},"expired":false,"scope":["all"],"inviteCode":"55QY0","name":null,"expiration":"2022-11-08T02:27:59.942+00:00","tokenType":"bearer","userName":"86+15366308080","value":"249a1e10-c825-4a6a-a6c2-8d58fa2efdda","userId":"18555","refreshToken":{"expiration":"2022-11-12T02:27:59.940+00:00","value":"eeb6d565-68f9-49b1-a174-8b115d76e1ba"}}
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 用户登录-获取登录token：249a1e10-c825-4a6a-a6c2-8d58fa2efdda
2022-11-07 10:27:59 INFO 25e6ce9e 1-1 用户登录-获取登录userId：18555
2022-11-07 10:28:00 INFO 25e6ce9e 1-1 登录前置查询-前置返回：org.apache.jmeter.threads.JMeterVariables@1edb541a
2022-11-07 10:28:00 ERROR 25e6ce9e 1-1 Problem in JSR223 script, JSR223PostProcessor
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script65842.groovy: 1: unable to resolve class top.auntie.Input
 @ line 1, column 1.
   import top.auntie.Input;
   ^

1 error

javax.script.ScriptException
   at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:158)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:263)
   at org.apache.jmeter.extractor.JSR223PostProcessor.process(JSR223PostProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPostProcessors(JMeterThread.java:975)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:590)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:487)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:251)
   at java.base/java.lang.Thread.run(Thread.java:829)
2022-11-07 10:28:00 INFO MS-JMETER-RUN-TASK：2 Setting Locale to en_US
2022-11-07 10:28:00 ERROR 25e6ce9e 1-1 Problem in JSR223 script: JSR223split==Assertionsplit==${data.userStatus} == '1'split&&import top.auntie.Input;

value = Input.decryptAndTake(prev, "userStatus");

result = "1".equals(value);
if (!result){
	msg = "assertion [" + value + " == '1']: false;";
	AssertionResult.setFailureMessage(msg);
	AssertionResult.setFailure(true);
}
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script65843.groovy: 1: unable to resolve class top.auntie.Input
 @ line 1, column 1.
   import top.auntie.Input;
   ^

1 error

javax.script.ScriptException
   at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:158)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:263)
   at org.apache.jmeter.assertions.JSR223Assertion.getResult(JSR223Assertion.java:50)
   at org.apache.jmeter.threads.JMeterThread.processAssertion(JMeterThread.java:951)
   at org.apache.jmeter.threads.JMeterThread.checkAssertions(JMeterThread.java:920)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:591)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:487)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:251)
   at java.base/java.lang.Thread.run(Thread.java:829)
2022-11-07 10:28:00 INFO StandardJMeterEngine Running the test!
2022-11-07 10:28:00 INFO StandardJMeterEngine List of sample_variables: []
2022-11-07 10:28:00 INFO StandardJMeterEngine 9c04220a-294b-4b59-9b5a-152563fa3000_12aae5d6-59de-47cd-a3ac-fa30bfaa11d5: Starting worker with class: class io.metersphere.jmeter.MsBackendListenerClient and queue capacity: 5000
2022-11-07 10:28:00 INFO StandardJMeterEngine 9c04220a-294b-4b59-9b5a-152563fa3000_12aae5d6-59de-47cd-a3ac-fa30bfaa11d5: Started  worker with class: class io.metersphere.jmeter.MsBackendListenerClient
2022-11-07 10:28:01 INFO StandardJMeterEngine Starting ThreadGroup: 1 : 9c04220a-294b-4b59-9b5a-152563fa3000
2022-11-07 10:28:01 INFO StandardJMeterEngine Starting 1 threads for group 9c04220a-294b-4b59-9b5a-152563fa3000.
2022-11-07 10:28:01 INFO StandardJMeterEngine Thread will continue on error
2022-11-07 10:28:01 INFO StandardJMeterEngine Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false
2022-11-07 10:28:01 INFO StandardJMeterEngine Started thread group number 1
2022-11-07 10:28:01 INFO StandardJMeterEngine All thread groups have been started
2022-11-07 10:28:01 INFO 9c04220a-294b-4b59-9b5a-152563fa3000 1-1 Thread started: 9c04220a-294b-4b59-9b5a-152563fa3000 1-1
2022-11-07 10:28:01 ERROR 25e6ce9e 1-1 Problem in JSR223 script, JSR223PreProcessor
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script65844.groovy: 2: unable to resolve class top.auntie.Input
 @ line 2, column 1.
   import top.auntie.Input;
   ^

1 error

javax.script.ScriptException
   at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:158)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:263)
   at org.apache.jmeter.modifiers.JSR223PreProcessor.process(JSR223PreProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:985)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:547)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:487)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:251)
   at java.base/java.lang.Thread.run(Thread.java:829)
2022-11-07 10:28:01 ERROR 25e6ce9e 1-1 Problem in JSR223 script, JSR223PostProcessor
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script65846.groovy: 1: unable to resolve class top.auntie.Input
 @ line 1, column 1.
   import top.auntie.Input;
   ^

1 error

javax.script.ScriptException
   at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:158)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:263)
   at org.apache.jmeter.extractor.JSR223PostProcessor.process(JSR223PostProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPostProcessors(JMeterThread.java:975)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:590)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:487)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:251)
   at java.base/java.lang.Thread.run(Thread.java:829)
2022-11-07 10:28:01 ERROR 25e6ce9e 1-1 Problem in JSR223 script, JSR223PreProcessor
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script65847.groovy: 2: unable to resolve class top.auntie.Input
 @ line 2, column 1.
   import top.auntie.Input;
   ^

1 error

javax.script.ScriptException
   at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:158)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:263)
   at org.apache.jmeter.modifiers.JSR223PreProcessor.process(JSR223PreProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:985)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:547)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:487)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:251)
   at java.base/java.lang.Thread.run(Thread.java:829)
2022-11-07 10:28:01 INFO 9c04220a-294b-4b59-9b5a-152563fa3000 1-1 产品列表查询-后置返回：[{"nowDate":"2022-11-07 10:28:01","applyStartDate":"2022-11-01","raiseEndDate":"2022-11-23 15:00","applyEndDate":"2022-11-23 15:00","title":{"titles":[{"type":"mainTitle","value":"Regan Global All Weather Strategy Fund II SP","key":"enName","seq":0},{"type":"subTitle","value":"雷根全球全天候策略基金 II SP","key":"productName","seq":1},{"type":"subTitle","value":"RGAWSP2","key":"productCode","seq":2}]},"content":[{"name":"成立以来收益率","type":"content","value":"24.74%","key":"yeild","seq":0},{"name":"投资策略","type":"content","value":"海外型基金","key":"strategy","seq":1},{"name":"锁定期","type":"content","value":"12个月","key":"lockUpPeriod","seq":2},{"name":"单位净值","type":"content","value":"124.7433","key":"lastNav","seq":3}],"tagList":{"tags":[{"type":"tag","value":"高风险","key":"risk","seq":4},{"type":"tag","value":"10万美元起投","key":"startUp","seq":5},{"type":"tag","value":"海外型基金","key":"strategy","seq":6}]},"availableTime":"2022-11-01至2022-11-23可预约购买","productCode":"RGAWSP2","raiseStartDate":"2022-11-01","detailUrl":"https://app.reganky.com/#/privateFundv2/fundDetails","productType":"OF"},{"nowDate":"2022-11-07 10:28:01","stampStatus":"7","title":{"titles":[{"type":"mainTitle","value":"Regan Global All Weather Strategy Fund I SP","key":"enName","seq":0},{"type":"subTitle","value":"雷根全球全天候策略基金 I SP","key":"productName","seq":1},{"type":"subTitle","value":"RGAWSP1","key":"productCode","seq":2}]},"content":[{"name":"成立以来收益率","type":"content","value":"95.12%","key":"yeild","seq":0},{"name":"投资策略","type":"content","value":"海外型基金","key":"strategy","seq":1},{"name":"锁定期","type":"content","value":"12个月","key":"lockUpPeriod","seq":2},{"name":"单位净值","type":"content","value":"195.1224","key":"lastNav","seq":3}],"tagList":{"tags":[{"type":"tag","value":"高风险","key":"risk","seq":4},{"type":"tag","value":"10万美元起投","key":"startUp","seq":5},{"type":"tag","value":"海外型基金","key":"strategy","seq":6}]},"availableTime":"可购买：长期开放","productCode":"RGAWSP1","detailUrl":"https://app.reganky.com/#/privateFundv2/fundDetails","productType":"OF"},{"nowDate":"2022-11-07 10:28:01","applyStartDate":"2022-11-01","raiseEndDate":"2022-11-23 15:00","applyEndDate":"2022-11-23 15:00","title":{"titles":[{"type":"mainTitle","value":"Regan International Growth Fund VI SP","key":"enName","seq":0},{"type":"subTitle","value":"雷根国际增长基金 VI SP","key":"productName","seq":1},{"type":"subTitle","value":"RIGFSP6","key":"productCode","seq":2}]},"content":[{"name":"成立以来收益率","type":"content","value":"15.95%","key":"yeild","seq":0},{"name":"投资策略","type":"content","value":"海外型基金","key":"strategy","seq":1},{"name":"锁定期","type":"content","value":"12个月","key":"lockUpPeriod","seq":2},{"name":"单位净值","type":"content","value":"115.9505","key":"lastNav","seq":3}],"tagList":{"tags":[{"type":"tag","value":"高风险","key":"risk","seq":4},{"type":"tag","value":"100万美元起投","key":"startUp","seq":5},{"type":"tag","value":"海外型基金","key":"strategy","seq":6}]},"availableTime":"2022-11-01至2022-11-23可预约购买","productCode":"RIGFSP6","raiseStartDate":"2022-11-01","detailUrl":"https://app.reganky.com/#/privateFundv2/fundDetails","productType":"OF"},{"nowDate":"2022-11-07 10:28:01","applyStartDate":"2022-11-01","raiseEndDate":"2022-11-23 15:00","applyEndDate":"2022-11-23 15:00","title":{"titles":[{"type":"mainTitle","value":"Regan International Growth Fund VII SP","key":"enName","seq":0},{"type":"subTitle","value":"雷根国际增长基金 VII SP","key":"productName","seq":1},{"type":"subTitle","value":"RIGFSP7","key":"productCode","seq":2}]},"content":[{"name":"成立以来收益率","type":"content","value":"3.94%","key":"yeild","seq":0},{"name":"投资策略","type":"content","value":"海外型基金","key":"strategy","seq":1},{"name":"锁定期","type":"content","value":"6个月","key":"lockUpPeriod","seq":2},{"name":"单位净值","type":"content","value":"103.9385","key":"lastNav","seq":3}],"tagList":{"tags":[{"type":"tag","value":"高风险","key":"risk","seq":4},{"type":"tag","value":"10万美元起投","key":"startUp","seq":5},{"type":"tag","value":"海外型基金","key":"strategy","seq":6}]},"availableTime":"2022-11-01至2022-11-23可预约购买","productCode":"RIGFSP7","raiseStartDate":"2022-11-01","detailUrl":"https://app.reganky.com/#/privateFundv2/fundDetails","productType":"OF"},{"nowDate":"2022-11-07 10:28:01","stampStatus":"2","title":{"titles":[{"type":"mainTitle","value":"Regan International Growth Fund V SP","key":"enName","seq":0},{"type":"subTitle","value":"雷根国际增长基金 V SP","key":"productName","seq":1},{"type":"subTitle","value":"RIGFSPV","key":"productCode","seq":2}]},"content":[{"name":"成立以来收益率","type":"content","value":"5.70%","key":"yeild","seq":0},{"name":"投资策略","type":"content","value":"海外型基金","key":"strategy","seq":1},{"name":"锁定期","type":"content","value":"12个月","key":"lockUpPeriod","seq":2},{"name":"单位净值","type":"content","value":"108.1667","key":"lastNav","seq":3}],"tagList":{"tags":[{"type":"tag","value":"高风险","key":"risk","seq":4},{"type":"tag","value":"10万美元起投","key":"startUp","seq":5},{"type":"tag","value":"海外型基金","key":"strategy","seq":6}]},"availableTime":"不可购买","productCode":"RIGFSPV","detailUrl":"https://app.reganky.com/#/privateFundv2/fundDetails","productType":"OF"}]
2022-11-07 10:28:01 INFO 9c04220a-294b-4b59-9b5a-152563fa3000 1-1 Thread is done: 9c04220a-294b-4b59-9b5a-152563fa3000 1-1
2022-11-07 10:28:01 INFO 9c04220a-294b-4b59-9b5a-152563fa3000 1-1 Thread finished: 9c04220a-294b-4b59-9b5a-152563fa3000 1-1
2022-11-07 10:28:01 INFO StandardJMeterEngine Notifying test listeners of end of test
2022-11-07 10:28:01 INFO Thread-14009 Worker ended
2022-11-07 10:28:01 ERROR 25e6ce9e 1-1 Problem in JSR223 script, JSR223PostProcessor
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script65849.groovy: 1: unable to resolve class top.auntie.Input
 @ line 1, column 1.
   import top.auntie.Input;
   ^

1 error

javax.script.ScriptException
   at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:158)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:263)
   at org.apache.jmeter.extractor.JSR223PostProcessor.process(JSR223PostProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPostProcessors(JMeterThread.java:975)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:590)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:487)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:251)
   at java.base/java.lang.Thread.run(Thread.java:829)
2022-11-07 10:28:01 ERROR 25e6ce9e 1-1 Problem in JSR223 script, JSR223PreProcessor
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script65850.groovy: 1: unable to resolve class top.auntie.Input
 @ line 1, column 1.
   import top.auntie.Input;
   ^

1 error

javax.script.ScriptException
   at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:158)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:263)
   at org.apache.jmeter.modifiers.JSR223PreProcessor.process(JSR223PreProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:985)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:547)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:487)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:251)
   at java.base/java.lang.Thread.run(Thread.java:829)
2022-11-07 10:28:01 ERROR 25e6ce9e 1-1 Problem in JSR223 script, JSR223PostProcessor
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script65851.groovy: 1: unable to resolve class top.auntie.Input
 @ line 1, column 1.
   import top.auntie.Input;
   ^

1 error

javax.script.ScriptException
   at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:158)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:263)
   at org.apache.jmeter.extractor.JSR223PostProcessor.process(JSR223PostProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPostProcessors(JMeterThread.java:975)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:590)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:487)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:251)
   at java.base/java.lang.Thread.run(Thread.java:829)
2022-11-07 10:28:01 INFO MS-JMETER-RUN-TASK：3 Setting Locale to en_US
```

### 附加信息

循环1：

循环2：
![Uploading fa8fe95449038725ba11c733f4b0dd8.jpg…]()

**Comment by liushuneng** [comment]
在1.20.15环境已复现，复现步骤如下：
第一步:上传jar包
[encrypt.zip](https://github.com/metersphere/metersphere/files/9948814/encrypt.zip)

第二步：在ms新建一个接口并设置mock，返回如下代码
{
    "data": "AE9zHpk7rFx4YyINzZdi6ujxKS11ijPea8djVkdRgbttDT6tD1iug0nOWPF4bJqzvUVdMneu+xLIqomJ0q6PQQ=="
}
![image](https://user-images.githubusercontent.com/45531073/200243585-3072b728-6619-458f-afba-b26a1a35c8e6.png)

第三步：创建一个场景
![image](https://user-images.githubusercontent.com/45531073/200243982-00726ea2-2427-4399-8f88-43ca08ab6301.png)

第四步：在场景中添加循环控制器 ，并按次数执行3次
![image](https://user-images.githubusercontent.com/45531073/200243935-446c700a-5fa7-4ba4-817d-4b3dded21c45.png)

第五步：添加自定义请求，请求地址设置为刚刚设置mock的接口，测试环境选择mock环境

第六步：接口中添加前后置脚本，代码如下：
![image](https://user-images.githubusercontent.com/45531073/200244640-b1148d10-9318-475c-b8a0-6d8af684bd0f.png)
![image](https://user-images.githubusercontent.com/45531073/200244700-ae7986b4-b031-4069-ae22-988cce44055b.png)

第七步：执行测试，对比结果
![image](https://user-images.githubusercontent.com/45531073/200244856-c3cb3d0a-30fe-4831-8f2f-dcbad2d66e18.png)

![image](https://user-images.githubusercontent.com/45531073/200244943-9f3b2514-05bc-4f02-8034-c3fdb0bace1e.png)

![image](https://user-images.githubusercontent.com/45531073/200245089-b6415f48-0ae1-4eba-9773-076c2334968b.png)
