### ISSUE TITLE
[BUG]k8s方式部署的metersphere，压测时ms-server日志有报错：没有 ms-prometheus监控

### ISSUE THREAD

**Issue by tengxunchao** [metersphere/metersphere#19609]
### 联系方式

376110722@qq.com

### MeterSphere 版本

1.20.3-lts

### 使用外置数据库

是

### 问题描述

k8s方式部署的metersphere，压测时ms-server日志有报错：没有 ms-prometheus监控

vi /opt/metersphere/logs/metersphere/error.log

2022-11-09 09:39:43,857 [XNIO-1 task-2] ERROR i.m.p.service.MetricQueryService ? - Method[queryPrometheusMetric][query prometheus metric fail.]
2022-11-09 09:39:43,857 [XNIO-1 task-2] ERROR i.m.p.service.MetricQueryService 176 - Method[queryPrometheusMetric][I/O error on GET request for "http://ms-prometheus:9090/api/v1/query_range": ms-prometh
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://ms-prometheus:9090/api/v1/query_range": ms-prometheus; nested exception is java.net.UnknownHostException: ms-
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:785)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)
        at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:334)
        at io.metersphere.performance.service.MetricQueryService.queryPrometheusMetric(MetricQueryService.java:91)
        at io.metersphere.performance.service.MetricQueryService.lambda$queryMetricData$0(MetricQueryService.java:77)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at io.metersphere.performance.service.MetricQueryService.lambda$queryMetricData$1(MetricQueryService.java:71)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.metersphere.performance.service.MetricQueryService.queryMetricData(MetricQueryService.java:71)
        at io.metersphere.performance.service.MetricQueryService.queryMetric(MetricQueryService.java:215)
        at io.metersphere.performance.service.MetricQueryService$$FastClassBySpringCGLIB$$77f36134.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethod

![image](https://user-images.githubusercontent.com/54707265/200730861-aa55c1b1-f01e-44bb-a18b-4f226b92e1c0.png)

![image](https://user-images.githubusercontent.com/54707265/200730895-d674ecce-b389-4403-806f-042a7fc298c1.png)

### 重现步骤

k8s方式部署的metersphere， 开启压测任务后，ms-server的日志就会有这个报错

### 期待的正确结果

无报错信息。 或 k8s部署方式支持默认的 ms-prometheus监控

**Comment by youliyuan-fit2cloud** [comment]
你好，K8s部署的MeterSphere 的默认资源池没有监控，但是不影响压测。可以通过性能用例-高级设置添加自定义监控节点方式获取节点的监控信息。
