### ISSUE TITLE
[BUG]在自动化场景加解密的jar包能正常使用，添加到测试计划后批量执行报找不到jar包，版本2.3.1

### ISSUE THREAD

**Issue by Buken-Lin** [metersphere/metersphere#19700]
### 联系方式

debin.lin@kdlins.com.cn

### MeterSphere 版本

版本:   v2.3.1-845ff07b

### 使用外置数据库

否

### 问题描述

在自动化场景加解密的jar包能正常使用，添加到测试计划后批量执行报找不到jar包，版本2.3.1

### 重现步骤

在自动化场景加解密的jar包能正常使用，添加到测试计划后批量执行报找不到jar包，版本2.3.1

### 相关日志输出

```shell
2022-11-14 10:18:40 ERROR 4bab0395-09f9-4274-8f0b-6f951cfb7841 1-1 Problem in JSR223 script, 加密
Sourced file: inline evaluation of: ``import com.sdb.demo.AesUtilQN; import com.sdb.demo.CommonUtil;  var parameterDat . . . '' : Typed variable declaration : Attempt to resolve method: encryptForOpen() on undefined variable or class name: AesUtilQN : at Line: 8 : in file: inline evaluation of: ``import com.sdb.demo.AesUtilQN; import com.sdb.demo.CommonUtil;  var parameterDat . . . '' : AesUtilQN .encryptForOpen ( parameterData , AES_key ) 
 in inline evaluation of: ``import com.sdb.demo.AesUtilQN; import com.sdb.demo.CommonUtil;  var parameterDat . . . '' at line number 8
javax.script.ScriptException
   at bsh.engine.BshScriptEngine.evalSource(BshScriptEngine.java:93)
   at bsh.engine.BshScriptEngine.eval(BshScriptEngine.java:46)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:235)
   at org.apache.jmeter.modifiers.JSR223PreProcessor.process(JSR223PreProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:999)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:560)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:500)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:264)
   at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Buken-Lin** [comment]
ms-jmeter-run-log.log
2022-11-11 09:00:00,052 [qtp1612539426-32] INFO  ms-jmeter-run-log ? - Method[runStart][开始同步上传的JAR：http://192.168.166.92:8081/api/jmeter/download/jar]
2022-11-11 09:00:00,314 [qtp1612539426-32] INFO  ms-jmeter-run-log ? - Method[downloadFile][文件下载成功！]
2022-11-11 09:00:00,316 [qtp1612539426-32] INFO  ms-jmeter-run-log ? - Method[unzip][/opt/metersphere/data/node/jar/f5acf4d8-1e31-4080-bcd1-d3630ed08c94/json-20220320.jar解压成功]
2022-11-11 09:00:00,326 [qtp1612539426-32] INFO  ms-jmeter-run-log ? - Method[unzip][/opt/metersphere/data/node/jar/f5acf4d8-1e31-4080-bcd1-d3630ed08c94/sdb-demo.jar解压成功]
2022-11-11 09:00:00,458 [qtp1612539426-32] INFO  ms-jmeter-run-log ? - Method[unzip][/opt/metersphere/data/node/jar/f5acf4d8-1e31-4080-bcd1-d3630ed08c94/bcprov-jdk15on-1.70.jar解压成功]
2022-11-11 09:00:00,460 [qtp1612539426-32] INFO  ms-jmeter-run-log ? - Method[unzip][/opt/metersphere/data/node/jar/f5acf4d8-1e31-4080-bcd1-d3630ed08c94/jrescloud-common-gm-3.0.17.jar解压成功]
2022-11-11 09:00:00,461 [qtp1612539426-32] INFO  ms-jmeter-run-log ? - Method[invoke][REPORT-ID: aee29272-c05b-4b6a-86a0-eca8152737a5] 开始同步插件JAR：http://192.168.166.92:8081/api/jmeter/download/plug/jar
2022-11-11 09:00:00,467 [qtp1612539426-32] INFO  ms-jmeter-run-log ? - Method[downloadFile][文件下载成功！]
2022-11-11 09:00:00,469 [qtp1612539426-32] INFO  ms-jmeter-run-log ? - Method[invoke][REPORT-ID: aee29272-c05b-4b6a-86a0-eca8152737a5]

**Comment by Buken-Lin** [comment]
ms-jmeter-run.log
2022-11-14 10:18:45,516 qtp67928167-912 INFO  ms-jmeter-run-log ? - Method[runStart][开始同步上传的JAR：http://192.168.166.92:8081/api/jmeter/download/jar]
2022-11-14 10:18:45,526 qtp67928167-912 INFO  ms-jmeter-run-log ? - Method[downloadJar][REPORT-ID: null] http://192.168.166.92:8081/api/jmeter/download/jar/f5acf4d8-1e31-4080-bcd1-d3630ed08c94 下载的文件名称为空
2022-11-14 10:18:45,526 qtp67928167-912 ERROR ms-jmeter-run-log ? - Method[downloadFile][java.io.FileNotFoundException: /opt/metersphere/data/node/jar/f5acf4d8-1e31-4080-bcd1-d3630ed08c94 (Is a directory)]
java.io.FileNotFoundException: /opt/metersphere/data/node/jar/f5acf4d8-1e31-4080-bcd1-d3630ed08c94 (Is a directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
	at io.metersphere.api.service.utils.ZipSpider.downloadFile(ZipSpider.java:158)
	at io.metersphere.api.jmeter.MsDriverManager.download(MsDriverManager.java:74)
	at io.metersphere.api.jmeter.MsDriverManager.downloadJar(MsDriverManager.java:57)
	at io.metersphere.api.service.JMeterExecuteService.runStart(JMeterExecuteService.java:46)
	at io.metersphere.api.controller.JmeterExecuteController.apiStartRun(JmeterExecuteController.java:30)
	at jdk.internal.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at

**Comment by Buken-Lin** [comment]
f5acf4d8-1e31-4080-bcd1-d3630ed08c94
这个文件夹下的jar重新上传还是显示为空

**Comment by Buken-Lin** [comment]
> ms-jmeter-run-log.log 2022-11-11 09:00:00,052 [qtp1612539426-32] INFO ms-jmeter-run-log ? - Method[runStart][开始同步上传的JAR：http://192.168.166.92:8081/api/jmeter/download/jar] 2022-11-11 09:00:00,314 [qtp1612539426-32] INFO ms-jmeter-run-log ? - Method[downloadFile][文件下载成功！] 2022-11-11 09:00:00,316 [qtp1612539426-32] INFO ms-jmeter-run-log ? - Method[unzip][/opt/metersphere/data/node/jar/f5acf4d8-1e31-4080-bcd1-d3630ed08c94/json-20220320.jar解压成功] 2022-11-11 09:00:00,326 [qtp1612539426-32] INFO ms-jmeter-run-log ? - Method[unzip][/opt/metersphere/data/node/jar/f5acf4d8-1e31-4080-bcd1-d3630ed08c94/sdb-demo.jar解压成功] 2022-11-11 09:00:00,458 [qtp1612539426-32] INFO ms-jmeter-run-log ? - Method[unzip][/opt/metersphere/data/node/jar/f5acf4d8-1e31-4080-bcd1-d3630ed08c94/bcprov-jdk15on-1.70.jar解压成功] 2022-11-11 09:00:00,460 [qtp1612539426-32] INFO ms-jmeter-run-log ? - Method[unzip][/opt/metersphere/data/node/jar/f5acf4d8-1e31-4080-bcd1-d3630ed08c94/jrescloud-common-gm-3.0.17.jar解压成功] 2022-11-11 09:00:00,461 [qtp1612539426-32] INFO ms-jmeter-run-log ? - Method[invoke][REPORT-ID: aee29272-c05b-4b6a-86a0-eca8152737a5] 开始同步插件JAR：http://192.168.166.92:8081/api/jmeter/download/plug/jar 2022-11-11 09:00:00,467 [qtp1612539426-32] INFO ms-jmeter-run-log ? - Method[downloadFile][文件下载成功！] 2022-11-11 09:00:00,469 [qtp1612539426-32] INFO ms-jmeter-run-log ? - Method[invoke][REPORT-ID: aee29272-c05b-4b6a-86a0-eca8152737a5]

升级前的版本2.2.0的日志能正常批量跑

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
2.4.0版本已修复，请等待版本发布后验证
