### ISSUE TITLE
[BUG]接口自动化执行是，环境地址设置全局前置执行脚本，获取token，偶现无法获取token报错

### ISSUE THREAD

**Issue by guolei19910508** [metersphere/metersphere#19854]
### 联系方式

847314573@qq.com

### MeterSphere 版本

v1.20.10-lts-787c5294

### 使用外置数据库

否

### 问题描述

接口自动化定时执行时，环境地址设置全局前置执行脚本，获取token，偶现无法获取token报错，一天执100次，大概有两三次提示前置脚本获取token失败

### 重现步骤

1.设置接口自动化执行场景
2.环境配置全局前置执脚本设置，用于接口执行前获取token
3.定时执行接口自动化场景

### 相关日志输出

```shell
测试报告控制台输出报错日志：
2022-11-18 08:40:02 INFO StandardJMeterEngine Running the test!
2022-11-18 08:40:02 INFO StandardJMeterEngine List of sample_variables: []
2022-11-18 08:40:02 INFO StandardJMeterEngine f3a2c53e-b379-44c7-a4fa-f773fdf790fd_90117147-b700-43bb-bcc3-fb615868becf: Starting worker with class: class io.metersphere.jmeter.MsBackendListenerClient and queue capacity: 5000
2022-11-18 08:40:02 INFO StandardJMeterEngine f3a2c53e-b379-44c7-a4fa-f773fdf790fd_90117147-b700-43bb-bcc3-fb615868becf: Started  worker with class: class io.metersphere.jmeter.MsBackendListenerClient
2022-11-18 08:40:04 INFO StandardJMeterEngine Starting ThreadGroup: 1 : f3a2c53e-b379-44c7-a4fa-f773fdf790fd
2022-11-18 08:40:04 INFO StandardJMeterEngine Starting 1 threads for group f3a2c53e-b379-44c7-a4fa-f773fdf790fd.
2022-11-18 08:40:04 INFO StandardJMeterEngine Thread will continue on error
2022-11-18 08:40:04 INFO StandardJMeterEngine Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false
2022-11-18 08:40:04 INFO StandardJMeterEngine Started thread group number 1
2022-11-18 08:40:04 INFO StandardJMeterEngine All thread groups have been started
2022-11-18 08:40:04 INFO f3a2c53e-b379-44c7-a4fa-f773fdf790fd 1-1 Thread started: f3a2c53e-b379-44c7-a4fa-f773fdf790fd 1-1
2022-11-18 08:40:09 ERROR f3a2c53e-b379-44c7-a4fa-f773fdf790fd 1-1 Problem in JSR223 script PRE_PROCESSOR_ENV_false, message: {}
IndexError: index out of range: 0 in <script> at line number 13
javax.script.ScriptException
   at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:202)
   at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:42)
   at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
   at java.scripting/javax.script.AbstractScriptEngine.eval(Unknown Source)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:258)
   at org.apache.jmeter.protocol.java.sampler.JSR223Sampler.sample(JSR223Sampler.java:72)
   at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:670)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:588)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:500)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:264)
   at java.base/java.lang.Thread.run(Unknown Source)
2022-11-18 08:40:21 INFO f3a2c53e-b379-44c7-a4fa-f773fdf790fd 1-1 Thread is done: f3a2c53e-b379-44c7-a4fa-f773fdf790fd 1-1
2022-11-18 08:40:21 INFO f3a2c53e-b379-44c7-a4fa-f773fdf790fd 1-1 Thread finished: f3a2c53e-b379-44c7-a4fa-f773fdf790fd 1-1
2022-11-18 08:40:21 INFO StandardJMeterEngine Notifying test listeners of end of test
2022-11-18 08:40:21 INFO Thread-67 Worker ended


### 附加信息

全局执行脚本：
import re
import httplib,urllib
params = {} #例 {'username':'test'}
headers = {'Content-Type':'application/json;charset=UTF-8'} #例 {'Content-Type':'application/json'} 或 {'Content-type': 'application/x-www-form-urlencoded', 'Accept': 'text/plain'}
host = 'xxxxxxx.com'
path = '/bussuser/auth/tokenPwd?mobile=1xxxxxxxxxxxx&deviceType=0&loginType=1&deviceToken=88-D7-F6-3D-95-58&clientip=192.168.3.142&pwd=xxxxxxxxx
method = 'GET' # POST/GET

conn = httplib.HTTPSConnection(host)
conn.request(method, path, params, headers)
res = conn.getresponse()
data = unicode(res.read(), 'utf-8')
token = re.findall('"token":"(.*?)"',data)[0]
log.info(token)
vars.put("token",token);

**Comment by guolei19910508** [comment]
自定义代码片段，就十几行，测试代码片段，30多秒才返回token，返回结果很慢

**Comment by zyyfit** [comment]
您好，我们1.20版本最新版已经是1.20.16了，您可以升级到最新版试试，
然后：
1、我在最新版1.20.16环境，修改了一下您代码里的host和token提取，没有复现您说的30多秒才返回的问题
2、您这个报错是13行，应该是token没提取到，是不是登录出现什么问题了呢？
![image](https://user-images.githubusercontent.com/73461316/203200958-2adafa57-cbf5-4367-a287-7733b0a183d9.png)
