### ISSUE TITLE
[BUG]接口自动化定时执行场景时偶然出现请求失败的报错

### ISSUE THREAD

**Issue by hinagaryou** [metersphere/metersphere#20222]
### 联系方式

395215647@qq.com

### MeterSphere 版本

v1.20.15-lts-6dc0c1ce

### 使用外置数据库

否

### 问题描述

问题简述：
 我们项目的一个接口自动化定时任务执行过程中，最近会偶然（两天出现了五次）出现接口请求有下图的一个报错，然而我们在日志监控中都没有抓取到测试报告中显示的时间段该接口的请求记录，所以我们猜测有可能会是metersphere在执行接口自动化定时任务时偶然出现的错误导致该请求没有成功发起。
![image](https://user-images.githubusercontent.com/50445174/203925383-04a32025-0f68-49f0-bdce-e8b2d1af757f.png)

### 重现步骤

目前没有办法主动重现该问题，已知的规律是每次都是该定时任务中的某一同一接口，报错内容是相同的，下图为最近几次报错的时间，看起来也不是连续性的。
![image](https://user-images.githubusercontent.com/50445174/203929817-d6654b4f-dca5-49a5-8182-8244c7dc8dc4.png)

### 期待的正确结果

由于我们这里的定时任务使用场景是定时检测我们部分接口业务是否正常，在一出现该错误的时候，我们难以控制其进行重试，同时也无法过滤该类型错误导致的断言不通过，使测试报告误报错误的情况。

### 相关日志输出

```shell
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.executeRequest(HTTPHC4Impl.java:935)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.sample(HTTPHC4Impl.java:646)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:128)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1296)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1285)
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:656)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:575)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:487)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:251)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，有其他用户遇到同样问题，但是也一直没有找到原因，我们会尽量尝试复现。如果你这边有进一步发现请随时联系我们。

**Comment by fit2-zhao** [comment]
请检查一下环境吧，看着错误日志像是环境没有选协议导致的。

**Comment by hinagaryou** [comment]
> 请检查一下环境吧，看着错误日志像是环境没有选协议导致的。

这是一个定时任务执行时出现的问题，接口的功能都很单一，每次请求都是相同的参数，每天都会执行几十次。如果是环境问题的话，大概率是每次运行都会报错，但是实际是只会非常偶然的报这个错，每天最多的时候出现过三次。

**Comment by youliyuan-fit2cloud** [comment]
把失败前后时间点日志给我们一份分析下，感谢～
