### ISSUE TITLE
[BUG]接口测试-接口编辑，开启同步case或者变更通知保存后报错

### ISSUE THREAD

**Issue by kaijie-yu** [metersphere/metersphere#20376]
### 联系方式

kaijie.yu@fit2cloud.com

### MeterSphere 版本

v2.2.1 v2.4.0

### 使用外置数据库

否

### 问题描述

1.v2.2.1，开启同步case或者变更通知，修改接口保存就会报错。
![image](https://user-images.githubusercontent.com/55130444/204956505-5ed3dbab-566c-4dcf-b3c4-9e667a6ecf77.png)

2.v2.4.0都没有页面提示报错，不能知道是否保存成功。
但f12抓接口发现是update更新失败了。
![image](https://user-images.githubusercontent.com/55130444/204957295-d4f36602-29eb-4882-a5a4-91db9156df30.png)

### 重现步骤

1.接口测试-导入接口，
![image](https://user-images.githubusercontent.com/55130444/204956985-6850055b-a7fc-4e33-a06e-1811273286a9.png)
2.编辑接口，开启同步case或者通知，点击保存会报错。

### 期待的正确结果

能够完成接口和case的同步修改不报错。

### 相关日志输出

```shell
2022-12-01 10:47:42,576  WARN     org.eclipse.jetty.server.HttpChannel: 776 - /api/definition/update
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.util.ConcurrentModificationException
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:517)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:292)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
        at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:67)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
```

**Comment by zyyfit** [comment]
您好，2.2.1 和 2.4.0 都没有复现这个问题，可以把您的接口导出来给我们看一下吗
![image](https://user-images.githubusercontent.com/73461316/204997363-fda2ade7-fc28-4c04-acdb-587becb2739d.png)

**Comment by kaijie-yu** [comment]
> 您好，2.2.1 和 2.4.0 都没有复现这个问题，可以把您的接口导出来给我们看一下吗 ![image](https://user-images.githubusercontent.com/73461316/204997363-fda2ade7-fc28-4c04-acdb-587becb2739d.png)

这个接口文件已经给到由老师了。

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
