### ISSUE TITLE
[BUG]API-test的info日志有error

### ISSUE THREAD

**Issue by legend818** [metersphere/metersphere#20427]
### MeterSphere 版本

v2.4.0

### 使用外置数据库

否

### 问题描述

接口自动化-设置4的定时任务，看api-info日志有error

### 重现步骤

1、接口自动化设置4点定时任务

### 相关日志输出

```shell
2022-12-03 04:00:00,461 SCENARIO-THREAD INFO  ms-jmeter-run-log ? - Method[invoke][REPORT-ID: 1626aa4e-a1fb-43fb-bdb7-c2469df65972] 进入串行模式，准备执行资源：[ （冒烟）热网监控系统 ]
2022-12-03 04:00:01,286 SCENARIO-THREAD ERROR ms-jmeter-run-log ? - Method[parseJonBodyMock][json mock value is abnormal]
java.lang.RuntimeException: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.LinkedHashMap<java.lang.Object,java.lang.Object>` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (String)"[
    {
        "uniqueId": 839,
        "stationBranchId": 532,
        "equId": 264,
        "storageCode": "Flt_1TG_A",
        "stationBranchName": "一次侧",
        "stationName": null,
        "position": "站一次总",
        "deviceName": "一次供水温度传感器",
        "alarmScriptDes": "一网供温度传感器故障",
        "alarmLevel": "下位1级报警",
        "isEnable": false,
        "generate": false,
        "valueEnum": "{\"false\": \"正常\",\"true\": \"故障\"}",
        "problemDefine": "true",
        "_XID": "row_334"
   "[truncated 4 chars]; line: 1, column: 1]
	at io.metersphere.commons.utils.JSONUtil.parseObject(JSONUtil.java:203)
	at io.metersphere.api.dto.scenario.Body.parseJonBodyMock(Body.java:103)
	at io.metersphere.api.dto.scenario.Body.getBodyParams(Body.java:84)
	at io.metersphere.api.dto.definition.request.sampler.MsHTTPSamplerProxy.toHashTree(MsHTTPSamplerProxy.java:143)
	at io.metersphere.api.dto.definition.request.MsScenario.toHashTree(MsScenario.java:153)
	at io.metersphere.api.dto.definition.request.MsThreadGroup.toHashTree(MsThreadGroup.java:47)
	at io.metersphere.api.dto.definition.request.MsTestPlan.lambda$toHashTree$0(MsTestPlan.java:37)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.metersphere.api.dto.definition.request.MsTestPlan.toHashTree(MsTestPlan.java:36)
	at io.metersphere.commons.utils.GenerateHashTreeUtil.generateHashTree(GenerateHashTreeUtil.java:178)
	at io.metersphere.api.exec.scenario.ApiScenarioSerialService.serial(ApiScenarioSerialService.java:81)
	at io.metersphere.api.exec.scenario.ApiScenarioSerialService$$FastClassBySpringCGLIB$$abec098c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at io.metersphere.api.exec.scenario.ApiScenarioSerialService$$EnhancerBySpringCGLIB$$5e787cb5.serial(<generated>)
	at io.metersphere.api.exec.scenario.ApiScenarioSerialService$$FastClassBySpringCGLIB$$abec098c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at io.metersphere.api.exec.scenario.ApiScenarioSerialService$$EnhancerBySpringCGLIB$$5ef537db.serial(<generated>)
	at io.metersphere.api.exec.scenario.ApiScenarioExecuteService.lambda$execute$0(ApiScenarioExecuteService.java:200)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.LinkedHashMap<java.lang.Object,java.lang.Object>` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (String)"[
    {
        "uniqueId": 839,
        "stationBranchId": 532,
        "equId": 264,
        "storageCode": "Flt_1TG_A",
        "stationBranchName": "一次侧",
        "stationName": null,
        "position": "站一次总",
        "deviceName": "一次供水温度传感器",
        "alarmScriptDes": "一网供温度传感器故障",
        "alarmLevel": "下位1级报警",
        "isEnable": false,
        "generate": false,
        "valueEnum": "{\"false\": \"正常\",\"true\": \"故障\"}",
        "problemDefine": "true",
        "_XID": "row_334"
   "[truncated 4 chars]; line: 1, column: 1]
	at io.metersphere.commons.utils.JSON.parseObject(JSON.java:48)
	at io.metersphere.commons.utils.JSONUtil.parseObject(JSONUtil.java:200)
	... 36 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.LinkedHashMap<java.lang.Object,java.lang.Object>` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (String)"[
    {
        "uniqueId": 839,
        "stationBranchId": 532,
        "equId": 264,
```

**Comment by xulinde** [comment]
这个报错是json 格式化失败，没有影响的

**Comment by legend818** [comment]
是我的哪个接口有错误么，

**Comment by xulinde** [comment]
> 是我的哪个接口有错误么，

你可以用在线json格式化校验工具看看
