### ISSUE TITLE
[BUG]Meterspherer从2.1升级到2.4，服务启动会报错

### ISSUE THREAD

**Issue by ouyanghuangrunda** [metersphere/metersphere#21025]
### MeterSphere 版本

2.4

### 使用外置数据库

是

### 问题描述

meterspherer从2.1升级到2.4，服务启动会报错：
报错如下：Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-12-29 10:47:38,166 ERROR g.springframework.boot.SpringApplication: 824 - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'schedulerStarter': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Schema `metersphere` contains a failed migration to version 125 !
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:332)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:270)
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:762)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:567)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at io.metersphere.SettingApplication.main(SettingApplication.java:29)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Schema `metersphere` contains a failed migration to version 125 !
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:544)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:520)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:673)
	at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:228)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:329)
	... 17 common frames omitted
Caused by: org.flywaydb.core.api.FlywayException: Schema `metersphere` contains a failed migration to version 125 !
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:217)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141)
	at org.flywaydb.core.internal.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:60)
	at org.flywaydb.core.internal.database.mysql.MySQLConnection.lock(MySQLConnection.java:154)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:141)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:101)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:219)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:170)
	at org.flywaydb.core.Flyway.execute(Flyway.java:586)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:170)
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	... 34 common frames omitted
10:47:38,170 |-INFO in ch.qos.logback.classic.AsyncAppender[infoAsyncAppender] - Worker thread will flush remaining events before exiting.
10:47:38,170 |-INFO in ch.qos.logback.classic.AsyncAppender[infoAsyncAppender] - Queue flush finished successfully within timeout.
10:47:38,171 |-INFO in ch.qos.logback.classic.AsyncAppender[warnAsyncAppender] - Worker thread will flush remaining events before exiting.
10:47:38,171 |-INFO in ch.qos.logback.classic.AsyncAppender[warnAsyncAppender] - Queue flush finished successfully within timeout.

### 重现步骤

meterspherer从2.1升级到2.4

### 期待的正确结果

服务能启动成功

### 相关日志输出

```shell
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-12-29 10:47:38,166 ERROR g.springframework.boot.SpringApplication: 824 - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'schedulerStarter': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Schema `metersphere` contains a failed migration to version 125 !
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:332)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:270)
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:762)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:567)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at io.metersphere.SettingApplication.main(SettingApplication.java:29)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Schema `metersphere` contains a failed migration to version 125 !
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:544)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:520)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:673)
	at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:228)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:329)
	... 17 common frames omitted
Caused by: org.flywaydb.core.api.FlywayException: Schema `metersphere` contains a failed migration to version 125 !
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:217)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141)
	at org.flywaydb.core.internal.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:60)
	at org.flywaydb.core.internal.database.mysql.MySQLConnection.lock(MySQLConnection.java:154)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:141)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:101)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:219)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:170)
	at org.flywaydb.core.Flyway.execute(Flyway.java:586)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:170)
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	... 34 common frames omitted
10:47:38,170 |-INFO in ch.qos.logback.classic.AsyncAppender[infoAsyncAppender] - Worker thread will flush remaining events before exiting.
10:47:38,170 |-INFO in ch.qos.logback.classic.AsyncAppender[infoAsyncAppender] - Queue flush finished successfully within timeout.
10:47:38,171 |-INFO in ch.qos.logback.classic.AsyncAppender[warnAsyncAppender] - Worker thread will flush remaining events before exiting.
10:47:38,171 |-INFO in ch.qos.logback.classic.AsyncAppender[warnAsyncAppender] - Queue flush finished successfully within timeout.
```

### 附加信息

无

**Comment by shenkaibo** [comment]
flyway 执行失败，可以 参考 https://metersphere.io/docs/v2.x/faq/installation/#10-schema-metersphere-contains-a-faied-migration-to-version-86 这个方式处理下

**Comment by ouyanghuangrunda** [comment]
我这里报Schema `metersphere` contains a failed migration to version 125 !这个错误。就要执行V125__2.0.0_ddl__release.sql这个数据库语句吧

**Comment by shenkaibo** [comment]
是的

**Comment by ouyanghuangrunda** [comment]
Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

ERROR 1060 (42S21): Duplicate column name 'third_part'
ERROR 1060 (42S21): Duplicate column name 'retry_enable'
ERROR 1060 (42S21): Duplicate column name 'retry_number'
ERROR 1060 (42S21): Duplicate column name 'env_config'
ERROR 1060 (42S21): Duplicate column name 'env_config'
ERROR 1060 (42S21): Duplicate column name 'to_be_updated'
ERROR 1060 (42S21): Duplicate column name 'to_be_updated'
Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.01 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

ERROR 1060 (42S21): Duplicate column name 'update_user'
ERROR 1060 (42S21): Duplicate column name 'module_path'
ERROR 1060 (42S21): Duplicate column name 'module_path'
ERROR 1060 (42S21): Duplicate column name 'last_execute_result'
ERROR 1060 (42S21): Duplicate column name 'run_info'
Query OK, 0 rows affected, 1 warning (0.00 sec)

ERROR 1060 (42S21): Duplicate column name 'api_base_count'
ERROR 1060 (42S21): Duplicate column name 'env_info'
ERROR 1060 (42S21): Duplicate column name 'env_info'
ERROR 1050 (42S01): Table 'test_plan_ui_scenario' already exists
Query OK, 0 rows affected (0.19 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (0.17 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (0.05 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (1.41 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected (0.62 sec)
Records: 0  Duplicates: 0  Warnings: 0

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected (0.09 sec)

**Comment by ouyanghuangrunda** [comment]
执行修复语句报了这些错误

**Comment by ouyanghuangrunda** [comment]
服务是可以启动，但是不确定系统有没有影响

**Comment by ouyanghuangrunda** [comment]
![image](https://user-images.githubusercontent.com/46988702/209899774-415837be-ac78-43a2-8ddb-440958a8a1b4.png)

**Comment by shenkaibo** [comment]
可以找一下 V125__2.0.0_ddl__release.sql 中 具体是哪行 sql 执行失败了，然后 从那行 sql 起把之后的 sql 手动一条条 执行，最后 修改下 metersphere_version 对应记录的 success 为 1，然后重启服务

**Comment by ouyanghuangrunda** [comment]
mysql> ALTER TABLE custom_field
    ->     ADD third_part TINYINT(1) DEFAULT 0 NOT NULL;
ERROR 1060 (42S21): Duplicate column name 'third_part'
mysql> ALTER TABLE `api_execution_queue_detail`
    ->     ADD retry_enable TINYINT(1) DEFAULT 0 COMMENT '是否开启失败重试';
ERROR 1060 (42S21): Duplicate column name 'retry_enable'
mysql> ALTER TABLE `api_execution_queue_detail`
    ->     ADD retry_number BIGINT(13) COMMENT '失败重试次数';
ERROR 1060 (42S21): Duplicate column name 'retry_number'
mysql> ALTER TABLE `api_definition_exec_result`
    ->     ADD env_config LONGTEXT COMMENT '执行环境配置';
ERROR 1060 (42S21): Duplicate column name 'env_config'
mysql> 
手动一条一条执行跟全部一起执行的效果是一样的额

**Comment by shenkaibo** [comment]
> mysql> ALTER TABLE custom_field -> ADD third_part TINYINT(1) DEFAULT 0 NOT NULL; ERROR 1060 (42S21): Duplicate column name 'third_part' mysql> ALTER TABLE `api_execution_queue_detail` -> ADD retry_enable TINYINT(1) DEFAULT 0 COMMENT '是否开启失败重试'; ERROR 1060 (42S21): Duplicate column name 'retry_enable' mysql> ALTER TABLE `api_execution_queue_detail` -> ADD retry_number BIGINT(13) COMMENT '失败重试次数'; ERROR 1060 (42S21): Duplicate column name 'retry_number' mysql> ALTER TABLE `api_definition_exec_result` -> ADD env_config LONGTEXT COMMENT '执行环境配置'; ERROR 1060 (42S21): Duplicate column name 'env_config' mysql> 手动一条一条执行跟全部一起执行的效果是一样的额

这个表示这条 sql 已经执行成功了，可以看下 后边的 sql ,如果 都执行完了，可以直接修改 metersphere_version 对应记录的 success 为 1

**Comment by ouyanghuangrunda** [comment]
ALTER TABLE的语句都显示ERROR 1060 (42S21): Duplicate column name，CREATE TABLE的语句都显示OK。系统暂时只有这个服务metersphere-gateway还有点报错。

**Comment by shenkaibo** [comment]
![image](https://user-images.githubusercontent.com/30038088/209906782-07c2badf-28c0-4545-904f-569b8fbb5c29.png)
麻烦加一下这个社区群吧，直接在群里沟通。

**Comment by ouyanghuangrunda** [comment]
好的，感谢
