### ISSUE TITLE
[BUG]接口自动化执行的时候报Connection prematurely close sed BEFORE response

### ISSUE THREAD

**Issue by cainiao-test** [metersphere/metersphere#21268]
### 联系方式

153818712@qq.com

### MeterSphere 版本

v2.5.1-8e5455a0

### 使用外置数据库

否

### 问题描述

![Uploading df879a15a4db799b893792a37f79e60.png…]()
执行接口自动化计划的时候，报错了

### 重现步骤

![微信图片_20230111112910](https://user-images.githubusercontent.com/62981097/211711242-2eb773e8-7bd4-409a-87a3-f93140669820.png)

### 相关日志输出

```shell
at java.base/java.lang.Thread.run(Thread.java:829)
2023-01-11 11:20:32,883  WARN ctor.netty.http.client.HttpClientConnect:   ? - [5606af11-4, L:/172.30.10.7:56012 ! R:172.30.10.14/172.30.10.14:8004] The connection observed an error
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
2023-01-11 11:20:32,884 ERROR e.error.AbstractErrorWebExceptionHandler:   ? - [5db39cde-1643]  500 Server Error for HTTP POST "/api/api/automation/run/debug"
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
        *__checkpoint ⇢ org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ io.metersphere.gateway.filter.SessionFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ HTTP POST "/api/api/automation/run/debug" [ExceptionHandlingWebHandler]
Original Stack Trace:
2023-01-11 11:22:05,308  WARN ctor.netty.http.client.HttpClientConnect: 304 - [bb547fad-1, L:/172.30.10.7:56458 ! R:172.30.10.14/172.30.10.14:8004] The connection observed an error
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
2023-01-11 11:22:05,309 ERROR e.error.AbstractErrorWebExceptionHandler: 102 - [80b6637f-1660]  500 Server Error for HTTP POST "/api/api/automation/run/debug"
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
        *__checkpoint ⇢ org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ io.metersphere.gateway.filter.SessionFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ HTTP POST "/api/api/automation/run/debug" [ExceptionHandlingWebHandler]
Original Stack Trace:
2023-01-11 11:22:24,930 ERROR e.error.AbstractErrorWebExceptionHandler: 102 - [ca3ad464-1661]  500 Server Error for HTTP POST "/api/api/automation/stop/batch"
io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /172.30.10.14:8004
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
        *__checkpoint ⇢ org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ io.metersphere.gateway.filter.SessionFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ HTTP POST "/api/api/automation/stop/batch" [ExceptionHandlingWebHandler]
Original Stack Trace:
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
        at io.netty.channel.unix.Errors.newConnectException0(Errors.java:155)
        at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128)
        at io.netty.channel.unix.Socket.finishConnect(Socket.java:359)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:489)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
2023-01-11 11:22:31,737 ERROR e.error.AbstractErrorWebExceptionHandler: 102 - [ca3ad464-1662]  500 Server Error for HTTP GET "/api/api/definition/get/a1776316-d788-9950-4e13-e0259a9a2638"
io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /172.30.10.14:8004
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
        *__checkpoint ⇢ org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ io.metersphere.gateway.filter.SessionFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ HTTP GET "/api/api/definition/get/a1776316-d788-9950-4e13-e0259a9a2638" [ExceptionHandlingWebHandler]
Original Stack Trace:
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
        at io.netty.channel.unix.Errors.newConnectException0(Errors.java:155)
        at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128)
        at io.netty.channel.unix.Socket.finishConnect(Socket.java:359)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:489)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by zyyfit** [comment]
您看一下这个文章有没有帮助
https://blog.csdn.net/rickiyeat/article/details/107900585
