### ISSUE TITLE
[BUG] 测试计划运行场景用例执行失败

### ISSUE THREAD

**Issue by adenzhong** [metersphere/metersphere#22269]
### 联系方式

zjd168@qq.com

### MeterSphere 版本

v2.6.1-2e5b7801

### 使用外置数据库

否

### 问题描述

测试计划执行场景用例失败，一直pending中

### 重现步骤

1. 创建测试计划
2. 添加接口场景用例
3. 执行测试计划

### 期待的正确结果

所有接口场景用例可以正常执行

### 相关日志输出

```shell
2023-02-25 18:41:01,752 [main] ERROR i.m.service.BaseScheduleService 177 - Method[lambda$startEnableSchedules$2][初始化任务失败]
java.lang.ClassNotFoundException: io.metersphere.job.sechedule.ApiScenarioTestJob
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at io.metersphere.service.BaseScheduleService.lambda$startEnableSchedules$2(BaseScheduleService.java:146)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at io.metersphere.service.BaseScheduleService.startEnableSchedules(BaseScheduleService.java:141)
        at io.metersphere.service.BaseScheduleService$$FastClassBySpringCGLIB$$e2b3614.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at io.metersphere.service.BaseScheduleService$$EnhancerBySpringCGLIB$$4be8a121.startEnableSchedules(<generated>)
        at io.metersphere.service.BaseScheduleService$$FastClassBySpringCGLIB$$e2b3614.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at io.metersphere.service.BaseScheduleService$$EnhancerBySpringCGLIB$$279482f7.startEnableSchedules(<generated>)
        at io.metersphere.listener.ApiAppStartListener.run(ApiAppStartListener.java:95)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:759)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:749)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
```

**Comment by fit2-zhao** [comment]
您好，未能复现这个问题，这段日志和您提的这个问题关联不大，如果方便可以把出现问题前后的完整日志放上来，感谢。

**Comment by fit2-zhao** [comment]
非常感谢您提供的日志，从日志分析已经定位到相关问题，会在下个小版本修复。
