### ISSUE TITLE
[BUG] 无法导入python模块：redis

### ISSUE THREAD

**Issue by Stephen0910** [metersphere/metersphere#22335]
### 联系方式

281016636@qq.com

### MeterSphere 版本

v2.7.0-6b1a66f0

### 使用外置数据库

否

### 问题描述

安装第三方包redis后，在python脚本中导入模块后， 无法使用模块功能
分析是因为ms本身使用了redis，造成冲突
<img width="669" alt="10f4771e043fdf18c86cff237641726" src="https://user-images.githubusercontent.com/26613645/221775091-8d74dcab-a63e-431e-ab1b-f8e635cc0b2b.png">

### 重现步骤

1、 根据教程安装第三方包-redis
https://blog.fit2cloud.com/?p=3110
2、 新建python脚本，import redis
![image](https://user-images.githubusercontent.com/26613645/221775476-d1a316c9-3a65-400c-a281-68a332fc5775.png)

3、 查看是否能连上，是否报错

### 期待的正确结果

可以连上redis

### 相关日志输出

```shell
2023-02-28 14:46:13 INFO StandardJMeterEngine Running the test!
2023-02-28 14:46:13 INFO StandardJMeterEngine List of sample_variables: []
2023-02-28 14:46:14 INFO StandardJMeterEngine Starting ThreadGroup: 1 : io.metersphere.api.dto.definition.request.MsThreadGroup
2023-02-28 14:46:14 INFO StandardJMeterEngine Starting 1 threads for group io.metersphere.api.dto.definition.request.MsThreadGroup.
2023-02-28 14:46:14 INFO StandardJMeterEngine Thread will continue on error
2023-02-28 14:46:14 INFO StandardJMeterEngine Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false
2023-02-28 14:46:14 INFO StandardJMeterEngine Started thread group number 1
2023-02-28 14:46:14 INFO StandardJMeterEngine All thread groups have been started
2023-02-28 14:46:14 INFO io.metersphere.api.dto.definition.request.MsThreadGroup 1-1 Thread started: io.metersphere.api.dto.definition.request.MsThreadGroup 1-1
2023-02-28 14:46:14 ERROR io.metersphere.api.dto.definition.request.MsThreadGroup 1-1 Problem in JSR223 script JSR223Sampler, message: {}
NameError: name 'StrictRedis' is not defined in <script> at line number 10
javax.script.ScriptException
   at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:202)
   at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:42)
   at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:231)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:237)
   at org.apache.jmeter.protocol.java.sampler.JSR223Sampler.sample(JSR223Sampler.java:72)
   at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:670)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:588)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:500)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:264)
   at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by fit2-zhao** [comment]
感谢反馈，非常抱歉给您带来了不好的使用体验，目前这类冲突是因为受限于jython 的一些处理方式，暂时没有特别好的解决方案，建议您尝试一下beanshell，如果您有好的处理方式，也欢迎给我们提建议。
