### ISSUE TITLE
[BUG]字段值太长报错 ：Data too long for column 'value' at row 1

### ISSUE THREAD

**Issue by liuming6518** [metersphere/metersphere#22694]
### 联系方式

liuming6518@163.com

### MeterSphere 版本

v2.7.1-b1

### 使用外置数据库

否

### 问题描述

字段值太长报错
Data too long for column 'value' at row 1

### 重现步骤

org.apache.ibatis.exceptions.PersistenceException: ### Error committing transaction. Cause: org.apache.ibatis.executor.BatchExecutorException: io.metersphere.base.mapper.ext.BaseCustomFieldResourceMapper.updateByPrimaryKeySelective (batch index #1) failed. Cause: java.sql.BatchUpdateException: Data truncation: Data too long for column 'value' at row 1 ### Cause: org.apache.ibatis.executor.BatchExecutorException: io.metersphere.base.mapper.ext.BaseCustomFieldResourceMapper.updateByPrimaryKeySelective (batch index #1) failed. Cause: java.sql.BatchUpdateException: Data truncation: Data too long for column 'value' at row 1

### 相关日志输出

```shell
org.apache.ibatis.exceptions.PersistenceException: ### Error committing transaction. Cause: org.apache.ibatis.executor.BatchExecutorException: io.metersphere.base.mapper.ext.BaseCustomFieldResourceMapper.updateByPrimaryKeySelective (batch index #1) failed. Cause: java.sql.BatchUpdateException: Data truncation: Data too long for column 'value' at row 1 ### Cause: org.apache.ibatis.executor.BatchExecutorException: io.metersphere.base.mapper.ext.BaseCustomFieldResourceMapper.updateByPrimaryKeySelective (batch index #1) failed. Cause: java.sql.BatchUpdateException: Data truncation: Data too long for column 'value' at row 1
```

**Comment by youliyuan-fit2cloud** [comment]
您好，日志信息不够全，没办法确认是哪个表，请把更详细的日志贴一下吧。

**Comment by liuming6518** [comment]
--
Caused by: org.apache.ibatis.executor.BatchExecutorException: io.metersphere.base.mapper.ext.ExtCustomFieldResourceMapper.updateByPrimaryKeySelective (batch index #1) failed. Cause: java.sql.BatchUpdateException: Data truncation: Data too long for column 'value' at row 1
	at org.apache.ibatis.executor.BatchExecutor.doFlushStatements(BatchExecutor.java:149)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:129)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:122)
	at org.apache.ibatis.executor.CachingExecutor.flushStatements(CachingExecutor.java:114)
	at jdk.internal.reflect.GeneratedMethodAccessor958.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64)
	at com.sun.proxy.$Proxy432.flushStatements(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor958.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64)
	at com.sun.proxy.$Proxy432.flushStatements(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor958.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64)
	at com.sun.proxy.$Proxy432.flushStatements(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.flushStatements(DefaultSqlSession.java:249)

**Comment by liuming6518** [comment]
> 您好，日志信息不够全，没办法确认是哪个表，请把更详细的日志贴一下吧。

--
Caused by: org.apache.ibatis.executor.BatchExecutorException: io.metersphere.base.mapper.ext.ExtCustomFieldResourceMapper.updateByPrimaryKeySelective (batch index #1) failed. Cause: java.sql.BatchUpdateException: Data truncation: Data too long for column 'value' at row 1
	at org.apache.ibatis.executor.BatchExecutor.doFlushStatements(BatchExecutor.java:149)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:129)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:122)
	at org.apache.ibatis.executor.CachingExecutor.flushStatements(CachingExecutor.java:114)
	at jdk.internal.reflect.GeneratedMethodAccessor958.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64)
	at com.sun.proxy.$Proxy432.flushStatements(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor958.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64)
	at com.sun.proxy.$Proxy432.flushStatements(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor958.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64)
	at com.sun.proxy.$Proxy432.flushStatements(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.flushStatements(DefaultSqlSession.java:249)

**Comment by youliyuan-fit2cloud** [comment]
具体场景是什么？导入的功能用例，有自定义字段吗？还是编辑用例的自定义字段？

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未反馈，关闭。如果后续有问题请重新提issue，感谢理解和支持～
