### ISSUE TITLE
[BUG]idea插件无法与ms服务连接失败

### ISSUE THREAD

**Issue by yangstones** [metersphere/metersphere#22799]
### 联系方式

silverleo@163.com

### MeterSphere 版本

2.7.1

### 使用外置数据库

否

### 问题描述

idea插件与ms连接失败

### 重现步骤

idea插件版本：1.2.3
idea版本：
IntelliJ IDEA 2022.3.2 (Ultimate Edition)
Build #IU-223.8617.56, built on January 26, 2023

1. 安装插件
2. 配置如下：
![c21b71cb9eee6a77d046f902d828bcd](https://user-images.githubusercontent.com/2188338/225536889-960d26e3-feed-49a7-9a60-ad030dd94120.png)

3. 无法获取到workspace信息，idea日志异常：

23-03-16 13:59:26,489 [ 192601] SEVERE - #org.metersphere.utils.MSApiUtil - IntelliJ IDEA 2022.3.2  Build #IU-223.8617.56
2023-03-16 13:59:26,489 [ 192601] SEVERE - #org.metersphere.utils.MSApiUtil - JDK: 17.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-03-16 13:59:26,489 [ 192601] SEVERE - #org.metersphere.utils.MSApiUtil - OS: Windows 11
2023-03-16 13:59:26,490 [ 192602] SEVERE - #org.metersphere.utils.MSApiUtil - Plugin to blame: MeterSphere version: 1.2.3
2023-03-16 13:59:30,877 [ 196989] SEVERE - #org.metersphere.gui.AppSettingComponent - get workspace failed!
java.lang.Throwable: get workspace failed!
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at org.metersphere.gui.AppSettingComponent.initWorkSpaceWithProject(AppSettingComponent.java:367)
	at org.metersphere.gui.AppSettingComponent.lambda$new$3(AppSettingComponent.java:92)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.p

**Comment by youliyuan-fit2cloud** [comment]
感谢您的反馈，该问题在 插件 v1.2.4版本中修复了，待发布后更新下插件。
