### ISSUE TITLE
[BUG]后置脚本导致接口不运行

### ISSUE THREAD

**Issue by xiaoguiliu** [metersphere/metersphere#2285]
**MeterSphere 版本**
1.8.2

**Bug 描述**
在接口中添加后置脚本，且后置脚本在for循环中增加if判断后运行场景。该接口不会被运行。

**Bug 重现步骤**
1.  后置脚本
```java
import org.json.*;

public static void getValue(){
    String response_data = prev.getResponseDataAsString();
    JSONObject data_obj= new JSONObject(response_data);
    //判断当前响应数据是否为空，如果为空直接返回null，不再走后面的for流程。
     if ((data_obj.get("data").get("list")).equals(null)){
        log.info("接口返回数据列表为空");
        vars.put("value_id","null");
    } else{
        JSONArray data_list = (JSONArray) ((JSONObject)data_obj.get("data")).get("list");
        for(int i=0;i<data_list.length();i++){
            String  user_id= ((JSONObject)data_list.get(i)).get("user").get("userId").toString();
            log.info("接口返回数据列表user_id" + user_id);
             if (user_id == 9098786494906544){
                log.info("===============找到了userId："+ user_id);
                vars.put("circle_user", ((JSONObject)data_list.get(i)).get("id").toString());
                log.info("===============circle_user" + vars.get("circle_user"));
                break;
            } else{
                log.info("没有找到user_id");
                vars.put("value_id","null");
            }
            
        }
    } 
}

getValue();

```

2. 日志报错
```shell
java.lang.NullPointerException: null
        at bsh.ParseException.getErrorLineNumber(ParseException.java:296)
        at bsh.engine.BshScriptEngine.evalSource(BshScriptEngine.java:82)
        at bsh.engine.BshScriptEngine.eval(BshScriptEngine.java:46)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
        at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:245)
        at org.apache.jmeter.extractor.JSR223PostProcessor.process(JSR223PostProcessor.java:45)
        at org.apache.jmeter.threads.JMeterThread.runPostProcessors(JMeterThread.java:955)
        at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:573)
        at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489)
        at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256)
        at java.lang.Thread.run(Thread.java:748)
```
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，if (user_id == 9098786494906544) 这行代码您给user_id的值加个引号试试？if (user_id == "9098786494906544")
