### ISSUE TITLE
[BUG]在脑图模式下编写测试用例，会存在偶发数据保存不成功的情况

### ISSUE THREAD

**Issue by yjc1020** [metersphere/metersphere#23091]
### 联系方式

dejavu.yang@vevor.net

### MeterSphere 版本

 v1.20.20-lts-79d354a6

### 使用外置数据库

否

### 问题描述

在脑图模式下编写测试用例，会存在偶发数据保存不成功的情况。如下图视频所示；并且会报空指针异常

### 重现步骤

无

### 期待的正确结果

每次保存都可以成功；并且建议增加脑图实时保存功能呢

### 相关日志输出

```shell
2023-03-23 13:56:48,706 [XNIO-1 task-10] ERROR i.m.commons.utils.ServiceUtils 176 - Method[updateOrderField][null]
java.lang.NullPointerException: null
        at java.base/java.lang.reflect.Method.invoke(Method.java:559)
        at io.metersphere.commons.utils.ServiceUtils.updateOrderField(ServiceUtils.java:240)
        at io.metersphere.track.service.TestCaseService.updateOrder(TestCaseService.java:2510)
        at io.metersphere.track.service.TestCaseService.changeOrder(TestCaseService.java:2057)
        at io.metersphere.track.service.TestCaseService.minderEdit(TestCaseService.java:2042)
        at io.metersphere.track.service.TestCaseService$$FastClassBySpringCGLIB$$7f4a1e57.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at io.metersphere.track.service.TestCaseService$$EnhancerBySpringCGLIB$$3f4412e8.minderEdit(<generated>)
        at io.metersphere.track.service.TestCaseService$$FastClassBySpringCGLIB$$7f4a1e57.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
```

### 附加信息

https://user-images.githubusercontent.com/128673692/227126626-221c339f-e458-454e-94a0-3c5f1cae52ce.mp4

**Comment by youliyuan-fit2cloud** [comment]
你好，这个偶发问题，我们暂时没有复现，具体原因不好定位，有没有更详细的日志？

**Comment by youliyuan-fit2cloud** [comment]
该问题长时间未回复，且无法复现，建议升级到最新版本v2.10.0-lts，如果再次出现请重新提issue，感谢理解和支持～
