### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by leonXtt** [metersphere/metersphere#23252]
### MeterSphere 版本

v2.7.0

### 使用外置数据库

否

### 问题描述

性能测试，高级配置中新增自定义变量后，脚本执行一直卡在starting状态

### 重现步骤

1. 性能测试-测试-脚本编辑 -高级配置页面，新增自定义变量并启用
![image](https://user-images.githubusercontent.com/129242317/228410422-3742baf7-25c9-432e-bfa3-dade048e2182.png)
2. jmx脚本中引用自定义变量，点击保存并执行；执行状态一直卡在starting
![image](https://user-images.githubusercontent.com/129242317/228410539-8c8a7ca9-6ec9-45db-830c-67f792a41ccb.png)
3./opt/metersphere/logs/performance-test/error.log中有报错 
![image](https://user-images.githubusercontent.com/129242317/228410217-04ce1d29-2b24-4847-ac3a-a6bb9edc8a77.png)
4./opt/metersphere/logs/node-controller/ms-jmeter-run.log中有报错
![image](https://user-images.githubusercontent.com/129242317/228411116-3e01076c-e307-4b80-8f9c-92cf5db37768.png)
5.删除高级配置中的自定义变量，脚本可以正常执行

### 期待的正确结果

性能脚本正确执行，自定义变量正确赋值

### 相关日志输出

```shell
2023-03-28 17:36:42,732 [qtp1380688171-7159] ERROR i.m.service.JmeterFileService 177 - Method[downloadZip][java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Unexpected character ('n' (code 110)): was expecting double-quote to start field name
 at [Source: (String)"[{name=hostNumber, enable=true, value=10, edit=true}]"; line: 1, column: 4] (through reference chain: java.util.ArrayList[0])]
io.metersphere.commons.exception.MSException: java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Unexpected character ('n' (code 110)): was expecting double-quote to start field name
 at [Source: (String)"[{name=hostNumber, enable=true, value=10, edit=true}]"; line: 1, column: 4] (through reference chain: java.util.ArrayList[0])
        at io.metersphere.commons.exception.MSException.throwException(MSException.java:22)
        at io.metersphere.engine.EngineFactory.createContext(EngineFactory.java:206)
        at io.metersphere.service.JmeterFileService.downloadZip(JmeterFileService.java:47)
        at io.metersphere.controller.JmeterFileController.downloadJmeterFiles(JmeterFileController.java:52)
        at jdk.internal.reflect.GeneratedMethodAccessor911.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:752)
        at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:752)
        at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:58)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:752)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:752)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703)
        at io.metersphere.controller.JmeterFileController$$SpringCGLIB$$0.downloadJmeterFiles(<generated>)
        at jdk.internal.reflect.GeneratedMethodAccessor911.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1080)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:973)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
```

**Comment by youliyuan-fit2cloud** [comment]
v2.8.1中已修复。
