### ISSUE TITLE
[BUG] 前置脚本 JSR223 脚本语法错误，前端控制台没有输出任何报错信息

### ISSUE THREAD

**Issue by abeelan** [metersphere/metersphere#23550]
### MeterSphere 版本

2.8

### 使用外置数据库

否

### 问题描述

编写前置脚本然后复制到 MS 前置脚本中，复制过程中可能出现了什么问题...（粗心大意了没有再去检查）导致出现了这么一段错误代码：

`public import org.apache.jmeter.protocol.http.util.HTTPArgument;`

执行发起请求，控制台没有任何输出，实际也没有发出请求，一脸懵逼。。。
<img width="935" alt="image" src="https://user-images.githubusercontent.com/34361264/231045488-be63021b-2243-4355-a137-2027118aa739.png">

今天早上脑子刷新后检查代码找到了这个错误... 

提个小小的请求：**出现任何异常，可否把日志输出到控制台呀？**

附容器里的执行异常日志：
```
api-test              | Exception in thread "2b4ca467-6477-b3f9-5b49-1e46048b464f 1-1" bsh.Parser$LookaheadSuccess
api-test              | 	at bsh.Parser.<init>(Parser.java:5981)
api-test              | 	at bsh.Interpreter.<init>(Interpreter.java:181)
api-test              | 	at bsh.Interpreter.eval(Interpreter.java:629)
api-test              | 	at bsh.Interpreter.eval(Interpreter.java:750)
api-test              | 	at bsh.Interpreter.eval(Interpreter.java:739)
api-test              | 	at bsh.engine.BshScriptEngine.evalSource(BshScriptEngine.java:78)
api-test              | 	at bsh.engine.BshScriptEngine.eval(BshScriptEngine.java:46)
api-test              | 	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:231)
api-test              | 	at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:237)
api-test              | 	at org.apache.jmeter.modifiers.JSR223PreProcessor.process(JSR223PreProcessor.java:45)
api-test              | 	at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:999)
api-test              | 	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:560)
api-test              | 	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:500)
api-test              | 	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:264)
api-test              | 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by 13290445582** [comment]
您好，这个不是bug，为了更快的精准定位报错在哪，我们平台目前只收集线程组的日志。感谢反馈
