### ISSUE TITLE
[BUG]2022.2版本的idea无法使用metersphere-idea-plugin 1.2.x版本的插件

### ISSUE THREAD

**Issue by lhklyj** [metersphere/metersphere#23592]
### 联系方式

1486859531@qq.com

### MeterSphere 版本

v1.20

### 使用外置数据库

是

### 问题描述

2022.2版本的idea无法使用metersphere-idea-plugin 1.2.x版本的插件，具体问题截图已在MeterSphere 交流群38 反馈过

### 重现步骤

无

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/231401790-f9c0125b-df9e-42f6-91ee-1ac5fc5e72ac.png)


请看下apiserver的信息提示，不要加 “/api”，去掉后再试试吧。

**Comment by lhklyj** [comment]
也试过了呢，会报sync fail这个错



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: MatataYou ***@***.***&gt;
发送时间: 2023年4月12日 16:39
收件人: metersphere/metersphere ***@***.***&gt;
抄送: lhklyj ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [metersphere/metersphere] [BUG]2022.2版本的idea无法使用metersphere-idea-plugin 1.2.x版本的插件 (Issue #23592)





 

 
请看下apiserver的信息提示，不要加 “/api”，去掉后再试试吧。

**Comment by lhklyj** [comment]
是1.2.4版本的，idea版本是2022.2版本的，日志见附件。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月12日(星期三) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]2022.2版本的idea无法使用metersphere-idea-plugin 1.2.x版本的插件 (Issue #23592)





 
idea 插件版本用v1.2.4吗？如果是这个版本还是失败，请反馈下idea 的异常日志信息。

**Comment by youliyuan-fit2cloud** [comment]
你好，MeterSphere v1.20 以下版本和idea版本应该不匹配，后续我们会在idea 插件库更新下对应匹配版本，感谢理解和支持～

**Comment by lhklyj** [comment]
但现在我用的是1.2.0以上的1.2.4呀，是也不匹配吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: MatataYou ***@***.***&gt;
发送时间: 2023年4月12日 17:29
收件人: metersphere/metersphere ***@***.***&gt;
抄送: lhklyj ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [metersphere/metersphere] [BUG]2022.2版本的idea无法使用metersphere-idea-plugin 1.2.x版本的插件 (Issue #23592)





 
你好，MeterSphere v1.20 以下版本和idea版本应该不匹配，后续我们会在idea 插件库更新下对应匹配版本，感谢理解和支持～

**Comment by youliyuan-fit2cloud** [comment]
> 但现在我用的是1.2.0以上的1.2.4呀，是也不匹配吗 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: MatataYou ***@***.***&gt; 发送时间: 2023年4月12日 17:29 收件人: metersphere/metersphere ***@***.***&gt; 抄送: lhklyj ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [metersphere/metersphere] [BUG]2022.2版本的idea无法使用metersphere-idea-plugin 1.2.x版本的插件 (Issue #23592) 你好，MeterSphere v1.20 以下版本和idea版本应该不匹配，后续我们会在idea 插件库更新下对应匹配版本，感谢理解和支持～ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

MeterSphere版本不是1.20吗？

**Comment by lhklyj** [comment]
是1.20的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: MatataYou ***@***.***&gt;
发送时间: 2023年4月12日 17:44
收件人: metersphere/metersphere ***@***.***&gt;
抄送: lhklyj ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [metersphere/metersphere] [BUG]2022.2版本的idea无法使用metersphere-idea-plugin 1.2.x版本的插件 (Issue #23592)





  
但现在我用的是1.2.0以上的1.2.4呀，是也不匹配吗 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: MatataYou @.&gt; 发送时间: 2023年4月12日 17:29 收件人: metersphere/metersphere @.&gt; 抄送: lhklyj @.&gt;, Author @.&gt; 主题: Re: [metersphere/metersphere] [BUG]2022.2版本的idea无法使用metersphere-idea-plugin 1.2.x版本的插件 (Issue #23592) 你好，MeterSphere v1.20 以下版本和idea版本应该不匹配，后续我们会在idea 插件库更新下对应匹配版本，感谢理解和支持～ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
MeterSphere版本不是1.20吗？

**Comment by youliyuan-fit2cloud** [comment]
> 是1.20的 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: MatataYou ***@***.***&gt; 发送时间: 2023年4月12日 17:44 收件人: metersphere/metersphere ***@***.***&gt; 抄送: lhklyj ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [metersphere/metersphere] [BUG]2022.2版本的idea无法使用metersphere-idea-plugin 1.2.x版本的插件 (Issue #23592) 但现在我用的是1.2.0以上的1.2.4呀，是也不匹配吗 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: MatataYou @.&gt; 发送时间: 2023年4月12日 17:29 收件人: metersphere/metersphere @.&gt; 抄送: lhklyj @.&gt;, Author @.&gt; 主题: Re: [metersphere/metersphere] [BUG]2022.2版本的idea无法使用metersphere-idea-plugin 1.2.x版本的插件 (Issue #23592) 你好，MeterSphere v1.20 以下版本和idea版本应该不匹配，后续我们会在idea 插件库更新下对应匹配版本，感谢理解和支持～ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; MeterSphere版本不是1.20吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

嗯，那就是了，和idea版本不匹配。请等我们更新下匹配列表。

**Comment by lhklyj** [comment]
MeterSphere的版本应该不用和idea的版本匹配吧，比如我idea中的项目是别的项目A，不是MeterSphere平台的项目，那么是不是idea装了插件后就可以将项目A中的接口导出了，所以问题应该还是idea版本和插件的版本不匹配吧。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月12日(星期三) 晚上6:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]2022.2版本的idea无法使用metersphere-idea-plugin 1.2.x版本的插件 (Issue #23592)





  
是1.20的 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: MatataYou @.&gt; 发送时间: 2023年4月12日 17:44 收件人: metersphere/metersphere @.&gt; 抄送: lhklyj @.&gt;, Author @.&gt; 主题: Re: [metersphere/metersphere] [BUG]2022.2版本的idea无法使用metersphere-idea-plugin 1.2.x版本的插件 (Issue #23592) 但现在我用的是1.2.0以上的1.2.4呀，是也不匹配吗 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: MatataYou @.&gt; 发送时间: 2023年4月12日 17:29 收件人: metersphere/metersphere @.&gt; 抄送: lhklyj @.&gt;, Author @.&gt; 主题: Re: [metersphere/metersphere] [BUG]2022.2版本的idea无法使用metersphere-idea-plugin 1.2.x版本的插件 (Issue #23592) 你好，MeterSphere v1.20 以下版本和idea版本应该不匹配，后续我们会在idea 插件库更新下对应匹配版本，感谢理解和支持～ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; MeterSphere版本不是1.20吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
嗯，那就是了，和idea版本不匹配。请等我们更新下匹配列表。

**Comment by youliyuan-fit2cloud** [comment]
> 是1.2.4版本的，idea版本是2022.2版本的，日志见附件。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "metersphere/metersphere" ***@***.***&gt;; 发送时间:&nbsp;2023年4月12日(星期三) 下午5:06 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [metersphere/metersphere] [BUG]2022.2版本的idea无法使用metersphere-idea-plugin 1.2.x版本的插件 (Issue #23592) idea 插件版本用v1.2.4吗？如果是这个版本还是失败，请反馈下idea 的异常日志信息。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你好，日志收不到，请上传到github

**Comment by lhklyj** [comment]
2023-04-12 17:03:11,633 [23013071] SEVERE - #o.m.u.MSApiUtil - test failed! response:【{"allHeaders":[{"buffer":{"empty":false,"full":false},"elements":[{"name":"keep-alive","parameterCount":0,"parameters":[]}],"name":"Connection","value":"keep-alive","valuePos":11},{"buffer":{"empty":false,"full":false},"elements":[{"name":"Origin","parameterCount":0,"parameters":[]}],"name":"Vary","value":"Origin","valuePos":5},{"buffer":{"empty":false,"full":false},"elements":[{"name":"Access-Control-Request-Method","parameterCount":0,"parameters":[]}],"name":"Vary","value":"Access-Control-Request-Method","valuePos":5},{"buffer":{"empty":false,"full":false},"elements":[{"name":"Access-Control-Request-Headers","parameterCount":0,"parameters":[]}],"name":"Vary","value":"Access-Control-Request-Headers","valuePos":5},{"buffer":{"empty":false,"full":false},"elements":[{"name":"rememberMe","parameterCount":3,"parameters":[{"name":"Path","value":"/"},{"name":"Max-Age","value":"0"},{"name":"Expires","value":"Tue"}],"value":"deleteMe"},{"name":"11-Apr-2023 09:08:41 GMT","parameterCount":1,"parameters":[{"name":"SameSite","value":"lax"}]}],"name":"Set-Cookie","value":"rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Tue, 11-Apr-2023 09:08:41 GMT; SameSite=lax","valuePos":11},{"buffer":{"empty":false,"full":false},"elements":[{"name":"rememberMe","parameterCount":3,"parameters":[{"name":"Path","value":"/"},{"name":"Max-Age","value":"0"},{"name":"Expires","value":"Tue"}],"value":"deleteMe"},{"name":"11-Apr-2023 09:08:41 GMT","parameterCount":1,"parameters":[{"name":"SameSite","value":"lax"}]}],"name":"Set-Cookie","value":"rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Tue, 11-Apr-2023 09:08:41 GMT; SameSite=lax","valuePos":11},{"buffer":{"empty":false,"full":false},"elements":[{"name":"chunked","parameterCount":0,"parameters":[]}],"name":"Transfer-Encoding","value":"chunked","valuePos":18},{"buffer":{"empty":false,"full":false},"elements":[{"name":"application/json","parameterCount":1,"parameters":[{"name":"charset","value":"UTF-8"}]}],"name":"Content-Type","value":"application/json;charset=UTF-8","valuePos":13},{"buffer":{"empty":false,"full":false},"elements":[{"name":"Wed","parameterCount":0,"parameters":[]},{"name":"12 Apr 2023 09:08:41 GMT","parameterCount":0,"parameters":[]}],"name":"Date","value":"Wed, 12 Apr 2023 09:08:41 GMT","valuePos":5}],"entity":{"chunked":true,"contentLength":-1,"contentType":{"$ref":"$.allHeaders[7]"},"repeatable":false,"streaming":true},"locale":"zh_CN","params":{"names":[]},"protocolVersion":{"major":1,"minor":1,"protocol":"HTTP"},"statusLine":{"protocolVersion":{"$ref":"$.protocolVersion"},"reasonPhrase":"Not Found","statusCode":404}}】
java.lang.Throwable: test failed! response:【{"allHeaders":[{"buffer":{"empty":false,"full":false},"elements":[{"name":"keep-alive","parameterCount":0,"parameters":[]}],"name":"Connection","value":"keep-alive","valuePos":11},{"buffer":{"empty":false,"full":false},"elements":[{"name":"Origin","parameterCount":0,"parameters":[]}],"name":"Vary","value":"Origin","valuePos":5},{"buffer":{"empty":false,"full":false},"elements":[{"name":"Access-Control-Request-Method","parameterCount":0,"parameters":[]}],"name":"Vary","value":"Access-Control-Request-Method","valuePos":5},{"buffer":{"empty":false,"full":false},"elements":[{"name":"Access-Control-Request-Headers","parameterCount":0,"parameters":[]}],"name":"Vary","value":"Access-Control-Request-Headers","valuePos":5},{"buffer":{"empty":false,"full":false},"elements":[{"name":"rememberMe","parameterCount":3,"parameters":[{"name":"Path","value":"/"},{"name":"Max-Age","value":"0"},{"name":"Expires","value":"Tue"}],"value":"deleteMe"},{"name":"11-Apr-2023 09:08:41 GMT","parameterCount":1,"parameters":[{"name":"SameSite","value":"lax"}]}],"name":"Set-Cookie","value":"rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Tue, 11-Apr-2023 09:08:41 GMT; SameSite=lax","valuePos":11},{"buffer":{"empty":false,"full":false},"elements":[{"name":"rememberMe","parameterCount":3,"parameters":[{"name":"Path","value":"/"},{"name":"Max-Age","value":"0"},{"name":"Expires","value":"Tue"}],"value":"deleteMe"},{"name":"11-Apr-2023 09:08:41 GMT","parameterCount":1,"parameters":[{"name":"SameSite","value":"lax"}]}],"name":"Set-Cookie","value":"rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Tue, 11-Apr-2023 09:08:41 GMT; SameSite=lax","valuePos":11},{"buffer":{"empty":false,"full":false},"elements":[{"name":"chunked","parameterCount":0,"parameters":[]}],"name":"Transfer-Encoding","value":"chunked","valuePos":18},{"buffer":{"empty":false,"full":false},"elements":[{"name":"application/json","parameterCount":1,"parameters":[{"name":"charset","value":"UTF-8"}]}],"name":"Content-Type","value":"application/json;charset=UTF-8","valuePos":13},{"buffer":{"empty":false,"full":false},"elements":[{"name":"Wed","parameterCount":0,"parameters":[]},{"name":"12 Apr 2023 09:08:41 GMT","parameterCount":0,"parameters":[]}],"name":"Date","value":"Wed, 12 Apr 2023 09:08:41 GMT","valuePos":5}],"entity":{"chunked":true,"contentLength":-1,"contentType":{"$ref":"$.allHeaders[7]"},"repeatable":false,"streaming":true},"locale":"zh_CN","params":{"names":[]},"protocolVersion":{"major":1,"minor":1,"protocol":"HTTP"},"statusLine":{"protocolVersion":{"$ref":"$.protocolVersion"},"reasonPhrase":"Not Found","statusCode":404}}】
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
	at org.metersphere.utils.MSApiUtil.test(MSApiUtil.java:49)
	at org.metersphere.gui.AppSettingComponent.lambda$new$3(AppSettingComponent.java:91)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:121)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1080)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:712)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:453)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1672)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1630)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:90)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:56)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:43)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:315)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:294)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:337)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:294)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$performAction$4(ActionMenuItem.java:293)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:227)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.java:286)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$0(ActionMenuItem.java:67)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$3(ActionMenuItem.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:546)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:578)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2023-04-12 17:03:11,642 [23013080] SEVERE - #o.m.u.MSApiUtil - IntelliJ IDEA 2022.2.1  Build #IC-222.3739.54
2023-04-12 17:03:11,643 [23013081] SEVERE - #o.m.u.MSApiUtil - JDK: 17.0.3; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-04-12 17:03:11,643 [23013081] SEVERE - #o.m.u.MSApiUtil - OS: Windows 11
2023-04-12 17:03:11,644 [23013082] SEVERE - #o.m.u.MSApiUtil - Plugin to blame: MeterSphere version: 1.2.4
2023-04-12 17:05:09,419 [23130857]   WARN - #c.i.o.o.e.ConfigurableCardPanel - auto-dispose 'Plugins' id=preferences.pluginManager
2023-04-12 17:05:14,145 [23135583]   INFO - #c.i.i.a.RevealFileAction - Exit code 1

**Comment by lhklyj** [comment]
[idea.log](https://github.com/metersphere/metersphere/files/11217809/idea.log)

**Comment by youliyuan-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/54612864/231641637-f729cb9b-6d96-4134-810b-9841d971af85.png)

看起来是你配置的MeterSphere环境哪里写错了，请检查一下吧。

**Comment by lhklyj** [comment]
我刚才看了下，我这边的metersphere服务的版本是1.9，比1.20的版本还要低很多，应该是因为metersphere服务版本太低吧，你们后续可以提供这个低版本服务的插件吗

**Comment by youliyuan-fit2cloud** [comment]
> 我刚才看了下，我这边的metersphere服务的版本是1.9，比1.20的版本还要低很多，应该是因为metersphere服务版本太低吧，你们后续可以提供这个低版本服务的插件吗

抱歉， 建议升级一下吧。我们暂时不支持这个版本的。这个idea插件从v1.20才开始有的～ ～
