### ISSUE TITLE
[BUG]前置脚本中使用python实现获取时间报错

### ISSUE THREAD

**Issue by xiaochongzi-ling** [metersphere/metersphere#23639]
### 联系方式

2297310871@qq.com

### MeterSphere 版本

v2.8.0-ac76fee1

### 使用外置数据库

是

### 问题描述

import datetime

today = datetime.date.today(); # 获取当天日期
yesterday = today - datetime.timedelta(days=1); # 获取前一天日期
yesterday2 = today - datetime.timedelta(days=7); # 获取前七天日期
print(yesterday);
print(yesterday2);
在pycharm中运行通过的脚本在metersphere前置中使用报错：
![图片](https://user-images.githubusercontent.com/23067502/231703164-62046713-8cf6-45c4-b3ca-95da89c44f31.png)
![图片](https://user-images.githubusercontent.com/23067502/231703201-8b1a8ff2-b26a-42dc-9133-b6352040ffd3.png)

### 重现步骤

import datetime

today = datetime.date.today(); # 获取当天日期
yesterday = today - datetime.timedelta(days=1); # 获取前一天日期
yesterday2 = today - datetime.timedelta(days=7); # 获取前一天日期

log.info(last_week_before);
log.info(last_week_after);
vars.put("begindate",last_week_before);
vars.put("enddate",last_week_after);

### 期待的正确结果

2023-04-12
2023-04-06

### 相关日志输出

```shell
2023-04-13 16:34:28 INFO d65a4916 1-1 Thread started: d65a4916 1-1
2023-04-13 16:34:28 ERROR d65a4916 1-1 Problem in JSR223 script, JSR223PreProcessor
TypeError: unsupported operand type(s) for -: 'java.sql.Date' and 'timedelta' in <script> at line number 4
javax.script.ScriptException
   at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:202)
   at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:42)
   at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:231)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:237)
   at org.apache.jmeter.modifiers.JSR223PreProcessor.process(JSR223PreProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:999)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:560)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:500)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:264)
   at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by scarletyyh** [comment]
您好，该功能的我们是基于jmeter实现的，在jmeter中执行也有相同错误，建议您检查一下脚本是否正确。
