### ISSUE TITLE
[BUG]接口测试导入时，通过swagger URL导入，当url中带group=xxxx参数时，提示无法解析（浏览器中带该参数请求正常）

### ISSUE THREAD

**Issue by hslzyd** [metersphere/metersphere#23669]
### 联系方式

企业微信：MeterSphere 交流群59

### MeterSphere 版本

V2.8.1

### 使用外置数据库

否

### 问题描述

接口测试导入时，通过swagger URL导入，当url中带group=xxxx参数时，提示无法解析（浏览器中带该参数请求正常）
![image](https://user-images.githubusercontent.com/8504229/231985791-cb57b9bd-98ac-4f27-b3ab-078f17cddc57.png)
![image](https://user-images.githubusercontent.com/8504229/231985828-4504c3a6-296b-41bc-95ec-5a3146a4bff5.png)

### 重现步骤

1、swagger中设置了分组
![image](https://user-images.githubusercontent.com/8504229/231986022-3498e691-4416-472a-a0c0-af759c18f56f.png)
2、在metersphere中用url方式导入，直接在url中加?group=xxx参数，提示解析失败
3、导入弹窗选择自定义参数，把group参数写在自定义参数中，也提示解析失败

### 期待的正确结果

url导入支持带参数

### 附加信息

![image](https://user-images.githubusercontent.com/8504229/231989553-e808d33f-278b-46bb-8a81-3d270e96b801.png)

**Comment by zrfit** [comment]
您好，感谢您的反馈！1、将group=xxx放到请求头中试下是否可以导入 2、如果也不行后端报错日志截图发下。

**Comment by hslzyd** [comment]
1、放到请求头？是指上述重现步骤中第3点吗？
2、logs/api-test/error.log报错日志如下：
`2023-04-21 00:00:02,834 [apiScheduler_Worker-8] ERROR i.m.s.d.ApiDefinitionService ? - Method[apiTestImport][java.lang.NullPointerException: Cannot invoke "io.metersphere.base.domain.ApiModule.getId()" because "apiModule" is null]
java.lang.NullPointerException: Cannot invoke "io.metersphere.base.domain.ApiModule.getId()" because "apiModule" is null
	at io.metersphere.service.definition.ApiDefinitionImportUtilService.lambda$removeSameData$30(ApiDefinitionImportUtilService.java:1108)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at io.metersphere.service.definition.ApiDefinitionImportUtilService.removeSameData(ApiDefinitionImportUtilService.java:1099)
	at io.metersphere.service.definition.ApiDefinitionImportUtilService.dealHttpUrlNoRepeat(ApiDefinitionImportUtilService.java:506)
	at io.metersphere.service.definition.ApiDefinitionImportUtilService.importApi(ApiDefinitionImportUtilService.java:214)
	at io.metersphere.service.definition.ApiDefinitionService.apiTestImport(ApiDefinitionService.java:558)
	at jdk.internal.reflect.GeneratedMethodAccessor870.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:702)
	at io.metersphere.service.definition.ApiDefinitionService$$SpringCGLIB$$1.apiTestImport(<generated>)
	at jdk.internal.reflect.GeneratedMethodAccessor870.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:702)
	at io.metersphere.service.definition.ApiDefinitionService$$SpringCGLIB$$2.apiTestImport(<generated>)
	at io.metersphere.sechedule.SwaggerUrlImportJob.businessExecute(SwaggerUrlImportJob.java:47)
	at io.metersphere.sechedule.MsScheduleJob.execute(MsScheduleJob.java:25)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)`

**Comment by zrfit** [comment]
您好，通过您的日志看是导入的时候apiModule为空导致的，我们这边没有复现，可能是历史数据或者导入覆盖数据造成，如果能提供导入数据信息可留下联系方式我们私下沟通下，便于研发根据您的数据定位进行修复，如果不方便提供数据，我们就尝试优化下代码，版本发布后您再升级尝试，计划v2.9.1修复。

**Comment by hslzyd** [comment]
浏览器直接访问导入链接，响应的json另存为json文件后再用文件导入是正常的，只有直接用链接导入的方式有问题

**Comment by zrfit** [comment]
您好，v2.9已优化该问题，建议升级尝试。

**Comment by hslzyd** [comment]
2.9.0问题一样存在的，可以试下这种方式看能否复现：
1、http://swagger-host/api-docs?group=xxxx设置响应json为正常json
2、用上述url导入
