### ISSUE TITLE
[BUG]一键安装后主要服务相关容器报错，提示logback配置错误，权限不足

### ISSUE THREAD

**Issue by yoobin0709** [metersphere/metersphere#23797]
### 联系方式

yoobin@126.com

### MeterSphere 版本

v1.20.21-lts-3915a433

### 使用外置数据库

否

### 问题描述

一键安装完成后 ms-data-streaming、ms-server、ms-node-controller 这3个容器一直重启，查看日志报错信息均为logback的错误。

### 重现步骤

一键安装后启动docker之后就开始无限重启报错

### 相关日志输出

```shell
ms-data-streaming容器报错如下：
Logging system failed to initialize using configuration from 'null'
java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[debugAppender] - openFile(/opt/metersphere/logs/data-streaming/debug.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/data-streaming/debug.log (Permission denied)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[infoAppender] - openFile(/opt/metersphere/logs/data-streaming/info.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/data-streaming/info.log (Permission denied)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[errorAppender] - openFile(/opt/metersphere/logs/data-streaming/error.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/data-streaming/error.log (Permission denied)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[warnAppender] - openFile(/opt/metersphere/logs/data-streaming/warn.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/data-streaming/warn.log (Permission denied)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:179)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.reinitialize(LogbackLoggingSystem.java:232)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:73)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:132)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:313)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:282)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:240)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:216)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:85)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:66)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:65)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:344)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at io.metersphere.streaming.Application.main(Application.java:23)
-------------- Application Start Failed --------------

ms-server容器报错如下：
Exception in thread "main" java.lang.IllegalStateException: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[debugAppender] - Failed to create parent directories for [/opt/metersphere/logs/metersphere/debug.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[debugAppender] - openFile(/opt/metersphere/logs/metersphere/debug.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/metersphere/debug.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[infoAppender] - Failed to create parent directories for [/opt/metersphere/logs/metersphere/info.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[infoAppender] - openFile(/opt/metersphere/logs/metersphere/info.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/metersphere/info.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[errorAppender] - Failed to create parent directories for [/opt/metersphere/logs/metersphere/error.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[errorAppender] - openFile(/opt/metersphere/logs/metersphere/error.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/metersphere/error.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[warnAppender] - Failed to create parent directories for [/opt/metersphere/logs/metersphere/warn.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[warnAppender] - openFile(/opt/metersphere/logs/metersphere/warn.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/metersphere/warn.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[backendApiAppender] - Failed to create parent directories for [/opt/metersphere/logs/metersphere/api/info.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[backendApiAppender] - openFile(/opt/metersphere/logs/metersphere/api/info.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/metersphere/api/info.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[infoTestPlanAppender] - Failed to create parent directories for [/opt/metersphere/logs/metersphere/testPlan/info.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[infoTestPlanAppender] - openFile(/opt/metersphere/logs/metersphere/testPlan/info.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/metersphere/testPlan/info.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[apiRunLogAppender] - Failed to create parent directories for [/opt/metersphere/logs/metersphere/ms-jmeter-run-log.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[apiRunLogAppender] - openFile(/opt/metersphere/logs/metersphere/ms-jmeter-run-log.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/metersphere/ms-jmeter-run-log.log (No such file or directory)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:344)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:298)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:246)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:223)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:85)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:66)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:65)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:344)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at io.metersphere.Application.main(Application.java:32)

ms-node-controller容器报错：
2023-04-19 13:20:52,222 ERROR g.springframework.boot.SpringApplication: 824 - Application run failed
java.lang.IllegalStateException: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[debugAppender] - Failed to create parent directories for [/opt/metersphere/logs/node-controller/debug.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[debugAppender] - openFile(/opt/metersphere/logs/node-controller/debug.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/node-controller/debug.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[infoAppender] - Failed to create parent directories for [/opt/metersphere/logs/node-controller/info.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[infoAppender] - openFile(/opt/metersphere/logs/node-controller/info.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/node-controller/info.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[errorAppender] - Failed to create parent directories for [/opt/metersphere/logs/node-controller/error.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[errorAppender] - openFile(/opt/metersphere/logs/node-controller/error.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/node-controller/error.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[warnAppender] - Failed to create parent directories for [/opt/metersphere/logs/node-controller/warn.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[warnAppender] - openFile(/opt/metersphere/logs/node-controller/warn.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/node-controller/warn.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[apiRunLogAppender] - Failed to create parent directories for [/opt/metersphere/logs/node-controller/ms-jmeter-run-log.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[apiRunLogAppender] - openFile(/opt/metersphere/logs/node-controller/ms-jmeter-run-log.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/node-controller/ms-jmeter-run-log.log (No such file or directory)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:328)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:282)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:240)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:216)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:85)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:66)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:65)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:344)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at io.metersphere.Application.main(Application.java:26)
Caused by: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[debugAppender] - Failed to create parent directories for [/opt/metersphere/logs/node-controller/debug.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[debugAppender] - openFile(/opt/metersphere/logs/node-controller/debug.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/node-controller/debug.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[infoAppender] - Failed to create parent directories for [/opt/metersphere/logs/node-controller/info.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[infoAppender] - openFile(/opt/metersphere/logs/node-controller/info.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/node-controller/info.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[errorAppender] - Failed to create parent directories for [/opt/metersphere/logs/node-controller/error.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[errorAppender] - openFile(/opt/metersphere/logs/node-controller/error.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/node-controller/error.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[warnAppender] - Failed to create parent directories for [/opt/metersphere/logs/node-controller/warn.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[warnAppender] - openFile(/opt/metersphere/logs/node-controller/warn.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/node-controller/warn.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[apiRunLogAppender] - Failed to create parent directories for [/opt/metersphere/logs/node-controller/ms-jmeter-run-log.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[apiRunLogAppender] - openFile(/opt/metersphere/logs/node-controller/ms-jmeter-run-log.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/node-controller/ms-jmeter-run-log.log (No such file or directory)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:179)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.reinitialize(LogbackLoggingSystem.java:232)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:73)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:132)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:313)
	... 18 common frames omitted
```

**Comment by youliyuan-fit2cloud** [comment]
你好，安装目录/opt/metersphere/logs 目录不存在吗？如果没有建议删除 /opt/metersphere 目录，重新安装试试吧。

**Comment by yoobin0709** [comment]
你好！我删除了所有的镜像和容器，重新安装之后正常了，怀疑是网络问题
