### ISSUE TITLE
[BUG]python脚本datetime类型都转换成了java.sql.Timestamp，函数内部的datetime正常

### ISSUE THREAD

**Issue by ryanrain2016** [metersphere/metersphere#24352]
### 联系方式

ryan@top365.ml

### MeterSphere 版本

 v2.7.0-34d44a5e

### 使用外置数据库

否

### 问题描述

在python脚本中使用datetime.strptime方法返回值的类型是java.sql.Timestamp，而在函数内部使用datetime.strptime方法格式化时间返回值才是python的datetime类型。

### 重现步骤

新建自动化用例，在前置脚本/后置脚本/断言中添加python脚本断言，代码如下：
```python
from datetime import datetime
format = '%Y-%m-%d %H:%M:%S'
d1 = datetime.strptime('2023-05-12 12:00:00', format)

log.info("d1: %s, %s" % (d1, type(d1)))

def checkDate(d):
    d = datetime.strptime(d, format)
    return d < d1
    
log.info(str(checkDate('2023-05-11 12:00:00')))
```

### 期待的正确结果

脚本正常执行

### 相关日志输出

```shell
2023-05-12 11:52:28 INFO 658e3888 1-1 d1: 2023-05-12 20:00:00.0, <type 'java.sql.Timestamp'>
2023-05-12 11:52:28 ERROR 658e3888 1-1 Problem in JSR223 script: JSR223split==Assertionsplit==测试时间split&&from datetime import datetime
format = '%Y-%m-%d %H:%M:%S'
d1 = datetime.strptime('2023-05-12 12:00:00', format)

log.info("d1: %s, %s" % (d1, type(d1)))

def checkDate(d):
    d = datetime.strptime(d, format)
    return d < d1
    
log.info(str(checkDate('2023-05-11 12:00:00')))

TypeError: can't compare 'datetime' to 'Timestamp' in <script> at line number 11
javax.script.ScriptException
   at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:202)
   at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:42)
   at org.python.jsr223.PyScriptEngine.access$300(PyScriptEngine.java:20)
   at org.python.jsr223.PyScriptEngine$PyCompiledScript.eval(PyScriptEngine.java:231)
   at java.scripting/javax.script.CompiledScript.eval(CompiledScript.java:93)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:235)
   at org.apache.jmeter.assertions.JSR223Assertion.getResult(JSR223Assertion.java:50)
   at org.apache.jmeter.threads.JMeterThread.processAssertion(JMeterThread.java:965)
   at org.apache.jmeter.threads.JMeterThread.checkAssertions(JMeterThread.java:934)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:604)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:500)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:264)
   at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by zrfit** [comment]
您好，感谢您的反馈！脚本类型转化问题，请上网查询下相关转换和使用方法优化您的脚本。

**Comment by ryanrain2016** [comment]
？这就尴尬了，这脚本有啥问题，明明就是你们魔改了jython的解析器导致的类型错误，这个类型`java.sql.Timestamp`在python里面就不存在怎么转？只能自己去改变写法避免这个坑，要不就改掉，要不就在文档中把这个说清楚，避免别人踩坑

**Comment by luty2018** [comment]
1.我们没有改Jython。
2.Jython兼容大部分python ，但本质不是python。
3.至于怎么转换，或者是否考虑用其他语言脚本，这个是需要你自己解决的呢。

**Comment by ryanrain2016** [comment]
python没有对应的类型，在python语言内部是转不了，但是你可以看到同样的datetime.strptime在checkDate函数内部这个类型是正常的，在函数外部类型不对。
这个段代码在jython中执行也是完全正常的，不会有问题。感觉这个和jython的兼容性没有太大关系
要解决我遇到的单个问题，解决起来很简单，我自己就可以搞定。
如果改不了，解决也很简单，至少在文档说明下，避免别人踩坑。

**Comment by BigDarkOrange** [comment]
应该是jython的问题，放到函数里就可以执行了，建议你们更新到官网文档里
参考：https://forum.image.sc/t/datetime-works-only-inside-a-function-in-a-jython-script-fiji/69072
![image](https://github.com/metersphere/metersphere/assets/112859774/77d0b875-a2d2-4f10-83eb-120d36d95180)
![image](https://github.com/metersphere/metersphere/assets/112859774/620f7c99-90ad-4ad0-872b-ac35e3ffabe8)

**Comment by ryanrain2016** [comment]
> 应该是jython的问题，放到函数里就可以执行了，建议你们更新到官网文档里 参考：https://forum.image.sc/t/datetime-works-only-inside-a-function-in-a-jython-script-fiji/69072 ![image](https://user-images.githubusercontent.com/112859774/261521405-77d0b875-a2d2-4f10-83eb-120d36d95180.png) ![image](https://user-images.githubusercontent.com/112859774/261521439-620f7c99-90ad-4ad0-872b-ac35e3ffabe8.png)
也不是jython的问题,这个脚本在jython中单独执行的时候没有任何问题，一定是集成的过程出现的问题，可能fiji也是采用同样的方式。
![image](https://github.com/metersphere/metersphere/assets/22925589/88f75431-d44e-4ad0-ac6d-7ed04a209017)
