### ISSUE TITLE
[BUG] 禁用本地资源池环境，API自动化场景中的并行控制器不能使用

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#24537]
### 联系方式

群14-亲山留水

### MeterSphere 版本

V2.9.1

### 使用外置数据库

是

### 问题描述

 禁用本地资源池环境，API自动化场景中的并行控制器不能使用（重新上传也不能正常使用）
![image](https://github.com/metersphere/metersphere/assets/82088551/67a4460f-7d72-41e7-a997-176485c76d63)

但debug插件可正常使用
![image](https://github.com/metersphere/metersphere/assets/82088551/2e7e32f8-ad5a-4d49-9292-19197f5ad06b)
![image](https://github.com/metersphere/metersphere/assets/82088551/d658c502-0f2b-4606-8aef-d480027c2a6b)

node节点的对应目录下的插件jar包
![image](https://github.com/metersphere/metersphere/assets/82088551/80952fc5-b42b-42ab-a001-2d04b4f702c2)

### 重现步骤

1、 禁用本地资源池环境，指定node资源池
2、调试好的用例 添加并行控制器 ，执行用例 失败

### 相关日志输出

```shell
2023-05-23 11:29:04,524 [StandardJMeterEngine] WARN  o.apache.jorphan.reflect.ClassFinder ? - Can not open the jar /opt/metersphere/data/api-folder/jar/node/fc7de6ce-ca99-437c-b157-f1e16d6e85ec/27661d92-bf51-11ed-bc9e-000c298865ff/1648084261257.jar, message: zip file is empty
java.util.zip.ZipException: zip file is empty
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1598)
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1382)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
        at org.apache.jorphan.reflect.ClassFinder.findClassesInOnePath(ClassFinder.java:359)
        at org.apache.jorphan.reflect.ClassFinder.findClasses(ClassFinder.java:326)
        at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:299)
        at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:231)
        at io.metersphere.utils.CustomizeFunctionUtil.initCustomizeClass(CustomizeFunctionUtil.java:51)
        at org.apache.jmeter.engine.PreCompiler.addNode(PreCompiler.java:99)
        at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:971)
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:377)
        at java.base/java.lang.Thread.run(Thread.java:833)
2023-05-23 11:29:04,525 [StandardJMeterEngine] WARN  o.apache.jorphan.reflect.ClassFinder 368 - Can not open the jar /opt/metersphere/data/api-folder/jar/node/fc7de6ce-ca99-437c-b157-f1e16d6e85ec/27664371-bf51-11ed-bc9e-000c298865ff/1648084319923.jar, message: zip file is empty
java.util.zip.ZipException: zip file is empty
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1598)
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1382)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
        at org.apache.jorphan.reflect.ClassFinder.findClassesInOnePath(ClassFinder.java:359)
        at org.apache.jorphan.reflect.ClassFinder.findClasses(ClassFinder.java:326)
        at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:299)
        at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:231)
        at io.metersphere.utils.CustomizeFunctionUtil.initCustomizeClass(CustomizeFunctionUtil.java:51)
        at org.apache.jmeter.engine.PreCompiler.addNode(PreCompiler.java:99)
        at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:971)
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:377)
        at java.base/java.lang.Thread.run(Thread.java:833)
2023-05-23 11:29:04,525 [StandardJMeterEngine] WARN  o.apache.jorphan.reflect.ClassFinder ? - Can not open the jar /opt/metersphere/data/api-folder/jar/node/fc7de6ce-ca99-437c-b157-f1e16d6e85ec/27665b19-bf51-11ed-bc9e-000c298865ff/1648084279968.jar, message: zip file is empty
java.util.zip.ZipException: zip file is empty
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1598)
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1382)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
        at org.apache.jorphan.reflect.ClassFinder.findClassesInOnePath(ClassFinder.java:359)
        at org.apache.jorphan.reflect.ClassFinder.findClasses(ClassFinder.java:326)
        at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:299)
        at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:231)
        at io.metersphere.utils.CustomizeFunctionUtil.initCustomizeClass(CustomizeFunctionUtil.java:51)
        at org.apache.jmeter.engine.PreCompiler.addNode(PreCompiler.java:99)
        at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:971)
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:377)
        at java.base/java.lang.Thread.run(Thread.java:833)
2023-05-23 11:29:04,526 [StandardJMeterEngine] WARN  o.apache.jorphan.reflect.ClassFinder ? - Can not open the jar /opt/metersphere/data/api-folder/jar/node/fc7de6ce-ca99-437c-b157-f1e16d6e85ec/27663099-bf51-11ed-bc9e-000c298865ff/1648084299914.jar, message: zip file is empty
java.util.zip.ZipException: zip file is empty
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1598)
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1382)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
        at org.apache.jorphan.reflect.ClassFinder.findClassesInOnePath(ClassFinder.java:359)
        at org.apache.jorphan.reflect.ClassFinder.findClasses(ClassFinder.java:326)
        at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:299)
        at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:231)
        at io.metersphere.utils.CustomizeFunctionUtil.initCustomizeClass(CustomizeFunctionUtil.java:51)
        at org.apache.jmeter.engine.PreCompiler.addNode(PreCompiler.java:99)
        at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:971)
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:377)
        at java.base/java.lang.Thread.run(Thread.java:833)
2023-05-23 11:29:04,526 [StandardJMeterEngine] WARN  o.apache.jorphan.reflect.ClassFinder 368 - Can not open the jar /opt/metersphere/data/api-folder/jar/node/fc7de6ce-ca99-437c-b157-f1e16d6e85ec/27666dcd-bf51-11ed-bc9e-000c298865ff/1659661160770.jar, message: zip file is empty
java.util.zip.ZipException: zip file is empty
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1598)
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1382)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
        at org.apache.jorphan.reflect.ClassFinder.findClassesInOnePath(ClassFinder.java:359)
        at org.apache.jorphan.reflect.ClassFinder.findClasses(ClassFinder.java:326)
        at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:299)
        at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:231)
        at io.metersphere.utils.CustomizeFunctionUtil.initCustomizeClass(CustomizeFunctionUtil.java:51)
        at org.apache.jmeter.engine.PreCompiler.addNode(PreCompiler.java:99)
        at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:971)
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:377)
        at java.base/java.lang.Thread.run(Thread.java:833)
2023-05-23 11:29:04,527 [StandardJMeterEngine] WARN  o.apache.jorphan.reflect.ClassFinder 368 - Can not open the jar /opt/metersphere/data/api-folder/jar/node/fc7de6ce-ca99-437c-b157-f1e16d6e85ec/276607ab-bf51-11ed-bc9e-000c298865ff/1659661189971.jar, message: zip file is empty
java.util.zip.ZipException: zip file is empty
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1598)
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1382)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
        at org.apache.jorphan.reflect.ClassFinder.findClassesInOnePath(ClassFinder.java:359)
        at org.apache.jorphan.reflect.ClassFinder.findClasses(ClassFinder.java:326)
        at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:299)
        at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:231)
        at io.metersphere.utils.CustomizeFunctionUtil.initCustomizeClass(CustomizeFunctionUtil.java:51)
        at org.apache.jmeter.engine.PreCompiler.addNode(PreCompiler.java:99)
        at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:971)
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:377)
        at java.base/java.lang.Thread.run(Thread.java:833)
2023-05-23 11:29:04,530 [StandardJMeterEngine] INFO  JMETER 227 - JMETER-LOG
2023-05-23 11:29:04,530 [StandardJMeterEngine] INFO  JMETER 227 - JMETER-LOG
2023-05-23 11:29:04,901 [StandardJMeterEngine] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:04,902 [StandardJMeterEngine] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:04,902 [StandardJMeterEngine] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:04,902 [StandardJMeterEngine] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:04,903 [StandardJMeterEngine] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:04,904 [StandardJMeterEngine] INFO  JMETER 227 - JMETER-LOG
2023-05-23 11:29:04,904 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:04,926 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:04,927 [efd829f3 1-1] INFO  JMETER 227 - JMETER-LOG
2023-05-23 11:29:04,928 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:04,931 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:04,931 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:04,932 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:04,933 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:04,933 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:04,948 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:04,956 [efd829f3 1-1] INFO  JMETER 227 - JMETER-LOG
2023-05-23 11:29:05,428 [efd829f3 1-1] INFO  JMETER 227 - JMETER-LOG
2023-05-23 11:29:05,429 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,429 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,431 [efd829f3 1-1] INFO  JMETER 227 - JMETER-LOG
2023-05-23 11:29:05,432 [efd829f3 1-1] INFO  JMETER 227 - JMETER-LOG
2023-05-23 11:29:05,432 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,433 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,433 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,433 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,576 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,576 [efd829f3 1-1] INFO  JMETER 227 - JMETER-LOG
2023-05-23 11:29:05,577 [efd829f3 1-1] INFO  JMETER 227 - JMETER-LOG
2023-05-23 11:29:05,580 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,581 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,582 [efd829f3 1-1] INFO  JMETER 227 - JMETER-LOG
2023-05-23 11:29:05,582 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,583 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,583 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,583 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,584 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,584 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,585 [efd829f3 1-1] INFO  JMETER 227 - JMETER-LOG
2023-05-23 11:29:05,649 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,652 [efd829f3 1-1] INFO  JMETER 227 - JMETER-LOG
2023-05-23 11:29:05,676 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,677 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,677 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,680 [efd829f3 1-1] INFO  JMETER 227 - JMETER-LOG
2023-05-23 11:29:05,680 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,681 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,681 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,682 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,682 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,682 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,683 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,683 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,683 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:05,684 [efd829f3 1-1] INFO  JMETER 227 - JMETER-LOG
2023-05-23 11:29:05,684 [efd829f3 1-1] INFO  JMETER 227 - JMETER-LOG
2023-05-23 11:29:05,684 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:06,419 [efd829f3 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:06,419 [efd829f3 1-1] INFO  JMETER 227 - JMETER-LOG
2023-05-23 11:29:06,420 [StandardJMeterEngine] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:29:06,423 [Thread-1466] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:30:00,184 [qtp1514723919-1721] INFO  JMETER 227 - JMETER-LOG
2023-05-23 11:30:00,193 [MS-JMETER-RUN-TASK：1210] INFO  JMETER 227 - JMETER-LOG
2023-05-23 11:30:00,195 [StandardJMeterEngine] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:30:00,195 [StandardJMeterEngine] INFO  JMETER 227 - JMETER-LOG
2023-05-23 11:30:00,199 [StandardJMeterEngine] WARN  o.apache.jorphan.reflect.ClassFinder ? - Can not open the jar /opt/metersphere/data/api-folder/jar/node/63575e70-2235-41ce-9173-0a67f6c63064/276822e7-bf51-11ed-bc9e-000c298865ff/1682652652544.jar, message: zip file is empty
java.util.zip.ZipException: zip file is empty
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1598)
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1382)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
        at org.apache.jorphan.reflect.ClassFinder.findClassesInOnePath(ClassFinder.java:359)
        at org.apache.jorphan.reflect.ClassFinder.findClasses(ClassFinder.java:326)
        at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:299)
        at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:231)
        at io.metersphere.utils.CustomizeFunctionUtil.initCustomizeClass(CustomizeFunctionUtil.java:51)
        at org.apache.jmeter.engine.PreCompiler.addNode(PreCompiler.java:99)
        at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:971)
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:377)
        at java.base/java.lang.Thread.run(Thread.java:833)
2023-05-23 11:30:00,200 [StandardJMeterEngine] WARN  o.apache.jorphan.reflect.ClassFinder 368 - Can not open the jar /opt/metersphere/data/api-folder/jar/node/63575e70-2235-41ce-9173-0a67f6c63064/2768c35d-bf51-11ed-bc9e-000c298865ff/1682652648373.jar, message: zip file is empty
java.util.zip.ZipException: zip file is empty
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1598)
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1382)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
        at org.apache.jorphan.reflect.ClassFinder.findClassesInOnePath(ClassFinder.java:359)
        at org.apache.jorphan.reflect.ClassFinder.findClasses(ClassFinder.java:326)
        at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:299)
        at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:231)
        at io.metersphere.utils.CustomizeFunctionUtil.initCustomizeClass(CustomizeFunctionUtil.java:51)
        at org.apache.jmeter.engine.PreCompiler.addNode(PreCompiler.java:99)
        at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:971)
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:377)
        at java.base/java.lang.Thread.run(Thread.java:833)
2023-05-23 11:30:00,200 [StandardJMeterEngine] WARN  o.apache.jorphan.reflect.ClassFinder 368 - Can not open the jar /opt/metersphere/data/api-folder/jar/node/63575e70-2235-41ce-9173-0a67f6c63064/27678303-bf51-11ed-bc9e-000c298865ff/1660463661784.jar, message: zip file is empty
java.util.zip.ZipException: zip file is empty
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1598)
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1382)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
        at org.apache.jorphan.reflect.ClassFinder.findClassesInOnePath(ClassFinder.java:359)
        at org.apache.jorphan.reflect.ClassFinder.findClasses(ClassFinder.java:326)
        at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:299)
        at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:231)
        at io.metersphere.utils.CustomizeFunctionUtil.initCustomizeClass(CustomizeFunctionUtil.java:51)
        at org.apache.jmeter.engine.PreCompiler.addNode(PreCompiler.java:99)
        at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:971)
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:377)
        at java.base/java.lang.Thread.run(Thread.java:833)
2023-05-23 11:30:00,207 [StandardJMeterEngine] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:30:00,208 [StandardJMeterEngine] INFO  JMETER 227 - JMETER-LOG
2023-05-23 11:30:00,546 [StandardJMeterEngine] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:30:00,563 [StandardJMeterEngine] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:30:00,564 [StandardJMeterEngine] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:30:00,566 [StandardJMeterEngine] INFO  JMETER 227 - JMETER-LOG
2023-05-23 11:30:00,568 [StandardJMeterEngine] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:30:00,568 [StandardJMeterEngine] INFO  JMETER 227 - JMETER-LOG
2023-05-23 11:30:00,569 [a6976ec1-aa28-42e3-903a-a03d9861ca7d 1-1] INFO  JMETER 227 - JMETER-LOG
2023-05-23 11:30:00,591 [a6976ec1-aa28-42e3-903a-a03d9861ca7d 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:30:00,604 [a6976ec1-aa28-42e3-903a-a03d9861ca7d 1-1] INFO  JMETER 227 - JMETER-LOG
2023-05-23 11:30:00,606 [a6976ec1-aa28-42e3-903a-a03d9861ca7d 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:30:00,608 [a6976ec1-aa28-42e3-903a-a03d9861ca7d 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:30:00,621 [a6976ec1-aa28-42e3-903a-a03d9861ca7d 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:30:02,217 [a6976ec1-aa28-42e3-903a-a03d9861ca7d 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:30:02,217 [a6976ec1-aa28-42e3-903a-a03d9861ca7d 1-1] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:30:02,218 [StandardJMeterEngine] INFO  JMETER ? - JMETER-LOG
2023-05-23 11:30:02,219 [Thread-1469] INFO  JMETER ? - JMETER-LOG
```

**Comment by zrfit** [comment]
您好，感谢您的反馈！未复现该问题，插件上传后需要重启下api-test和node服务再试下，或待本周发布v2.10后升级尝试。

**Comment by zhangzhaox** [comment]
Can not open the jar /opt/metersphere/data/api-folder/jar/node/63575e70-2235-41ce-9173-0a67f6c63064/2768c35d-bf51-11ed-bc9e-000c298865ff/1682652648373.jar,     这个错误日志中的jar 指的那个jar

**Comment by fit2-zhao** [comment]
文件管理中对接口测试启用的jar包

> 无法打开 jar /opt/metersphere/data/api-folder/jar/node/63575e70-2235-41ce-9173-0a67f6c63064/2768c35d-bf51-11ed-bc9e-000c298865ff/1682652648373.jar，这个错误错误日志中的罐子指的那个罐子

**Comment by zhangzhaox** [comment]
> 您好，感谢您的反馈！未复现该问题，插件上传后需要重启下api-test和node服务再试下，或待本周发布v2.10后升级尝试。
原以为时jar包的引用问题，目前从日志看详细日志如下，希望有所帮助，v2.10版本验证后再反馈
2023-05-25 09:27:24,429 [qtp1235662640-24559] INFO  i.m.p.p.c.MsParallelController ? - Method[toHashTree][===========开始转换MsDummySampler ==================]
2023-05-25 09:27:24,430 [qtp1235662640-24559] ERROR i.m.p.p.c.MsParallelController ? - Method[toHashTree][Connect Sampler 生成失败]
