### ISSUE TITLE
[BUG]场景用例中的引用的场景用例，不能获取到引用用列设置的场景变量

### ISSUE THREAD

**Issue by chase001** [metersphere/metersphere#24540]
### 联系方式

MeterSphere 微信 31群

### MeterSphere 版本

 v2.9.1-32da5112

### 使用外置数据库

否

### 问题描述

场景用例中引用的场景用例，不能获取到引用用列设置的场景变量

### 重现步骤

1、 场景用例设置的场景变量-->num

![image](https://github.com/metersphere/metersphere/assets/23476281/fdb49e01-b886-44d3-a733-3eb5790fe87b)

2、在场景用例中引用该场景用例，该场景用例需设置场景变量-->num才能执行
![image](https://github.com/metersphere/metersphere/assets/23476281/60100c93-7139-48da-ac0c-666ed4b42010)

### 期待的正确结果

引用场景用例，引用的场景用例的变量-->num也可以此用

### 相关日志输出

```shell
javax.script.ScriptException: groovy.lang.MissingPropertyException: No such property: num for class: Script68
javax.script.ScriptException
   at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:158)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:231)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:237)
   at org.apache.jmeter.assertions.JSR223Assertion.getResult(JSR223Assertion.java:50)
   at org.apache.jmeter.threads.JMeterThread.processAssertion(JMeterThread.java:965)
   at org.apache.jmeter.threads.JMeterThread.checkAssertions(JMeterThread.java:934)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:604)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:500)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:264)
   at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by zrfit** [comment]
您好，感谢您的反馈！可点击引用场景...通过场景设置-勾选优选使用原场景变量，没有则使用当前场景变量，即可使用引用原场的原场景变量执行。
