### ISSUE TITLE
版本从v2.2升级到v2.10.0-lts-89acace0后beanshell脚本原来可正常使用的jar包不能使用了

### ISSUE THREAD

**Issue by sowfe** [metersphere/metersphere#24774]
### 请描述您的问题

beanshell脚本：
import net.sf.json.JSONObject;
String payload = "{\"head\": \"a\"}";
responseJson = JSONObject.fromObject(payload);
执行报错：
2023-06-02 18:03:06 INFO 0661afd6 1-1 Thread started: 0661afd6 1-1
2023-06-02 18:03:06 ERROR 0661afd6 1-1 Problem in JSR223 script JSR223Sampler, message: {}
Sourced file: inline evaluation of: ``import net.sf.json.JSONObject;  String payload = "{\"head\": \"a\"}"; responseJs . . . '' : Attempt to resolve method: fromObject() on undefined variable or class name: JSONObject : at Line: 4 : in file: inline evaluation of: ``import net.sf.json.JSONObject;  String payload = "{\"head\": \"a\"}"; responseJs . . . '' : JSONObject .fromObject ( payload ) 
 in inline evaluation of: ``import net.sf.json.JSONObject;  String payload = "{\"head\": \"a\"}"; responseJs . . . '' at line number 4
javax.script.ScriptException
   at bsh.engine.BshScriptEngine.evalSource(BshScriptEngine.java:93)
   at bsh.engine.BshScriptEngine.eval(BshScriptEngine.java:46)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:231)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:237)
   at org.apache.jmeter.protocol.java.sampler.JSR223Sampler.sample(JSR223Sampler.java:72)
   at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:670)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:588)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:500)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:264)
   at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by luty2018** [comment]
你好， 在 v2.10 中，我们去掉了这个内置包， 建议不要使用系统内置的 jar 包，随着版本升级，我们会对内置 jar 包进行整理和抽离，用户需要用到的 jar 包都需要自己上传。

**Comment by sowfe** [comment]
那好吧，只能换个工具包了
