### ISSUE TITLE
[QUESTION]Unable to instantiate factory class [com.ctrip.framework.apollo.spring.boot.ApolloApplicationContextInitializer] for factory type [org.springframework.context.ApplicationContextInitializer]

### ISSUE THREAD

**Issue by wangpanwangpan** [metersphere/metersphere#24787]
### 请描述您的问题

描述：
你好，我启动node服务的时候出现如下提示，请问如何解决呢

堆栈信息：
Exception in thread "main" java.lang.IllegalArgumentException: Unable to instantiate factory class [com.ctrip.framework.apollo.spring.boot.ApolloApplicationContextInitializer] for factory type [org.springframework.context.ApplicationContextInitializer]
	at org.springframework.core.io.support.SpringFactoriesLoader$FailureHandler.lambda$throwing$0(SpringFactoriesLoader.java:651)
	at org.springframework.core.io.support.SpringFactoriesLoader$FailureHandler.lambda$handleMessage$3(SpringFactoriesLoader.java:675)
	at org.springframework.core.io.support.SpringFactoriesLoader.instantiateFactory(SpringFactoriesLoader.java:231)
	at org.springframework.core.io.support.SpringFactoriesLoader.load(SpringFactoriesLoader.java:206)
	at org.springframework.core.io.support.SpringFactoriesLoader.load(SpringFactoriesLoader.java:160)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:461)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:457)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:273)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:252)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293)
	at io.metersphere.Application.main(Application.java:26)

**Comment by liuruibin** [comment]
您好，我们自己并没用到ctrip的相关jar，您是如何加入的呢

**Comment by wangpanwangpan** [comment]
在本地启动node-controller之后就提示上述报错信息

**Comment by luty2018** [comment]
不好意思， 请问该问题还存在吗？

**Comment by huangbaiming** [comment]
这个错误是由于在Java平台模块系统（JPMS）中，java.base 模块不允许将 java.lang 包下的 ClassLoader.defineClass 方法设置为可访问的。这是因为在 JPMS 中引入了更加严格的封装机制，对于模块内部的类和成员，默认是不允许其他模块访问的，除非明确地通过 exports 或 opens 语句在模块声明中指定。

在这里，错误发生在尝试通过反射来设置 defineClass 方法的可访问性时。InaccessibleObjectException 异常表示由于模块封装限制，无法更改该成员的可访问性。module java.base does not "opens java.lang" 表示 java.base 模块没有对 java.lang 包进行开放，以允许未命名模块（unnamed module）访问此方法。

如要解决这个问题，你需要检查代码中使用的库是否适配了JPMS的新特性，确保它们正确处理模块化系统的访问限制。一些旧的库可能尚未更新以兼容JPMS，可能会遇到这样的问题。

此外，如果你确实需要通过反射访问这种受限的方法，你可以尝试以下解决方案之一：

通过添加命令行参数来放宽对反射的限制，例如使用 --add-opens java.base/java.lang=ALL-UNNAMED，允许所有未命名模块(ALL-UNNAMED)访问 java.lang 包内的类和成员。

更新或更换不兼容的库，使用兼容JPMS的版本。

如果是在开发中，并且对代码的安全性要求不高，可以考虑回滚到早期的Java版本（Java 8或更早），在其中JPMS尚未引入。

但是，请注意，放宽访问限制可能会带来安全风险，因为它允许代码绕过封装和访问控制。所以应当谨慎使用，并且应当在完全了解潜在后果的情况下采用。
