### ISSUE TITLE
[BUG]性能测试，调用脚本写入文件报错”Permission denied“

### ISSUE THREAD

**Issue by leonXtt** [metersphere/metersphere#24842]
### MeterSphere 版本

v2.10.x-lts

### 使用外置数据库

否

### 问题描述

执行性能测试，脚本中调用beanshell写文件，报错” java.io.FileNotFoundException: /test/deviceIds_saas.txt (Permission denied)“

PS:  脚本在本地jmeter客户端可以正常执行，metersphere平台升级前为2.7.0版本，执行也无报错，升级后出现以上报错

### 重现步骤

1.创建性能测试，上传jmx脚本，脚本中调用beanshell写文件deviceIds_saas.txt
脚本内容如下
![image](https://github.com/metersphere/metersphere/assets/129242317/705cd12e-db10-42cd-ac06-6d9f4e86df1b)
2. 资源文件中加载deviceIds_saas.txt 文件
3. 保存测试并执行
![image](https://github.com/metersphere/metersphere/assets/129242317/d759f274-a5de-4e21-9474-34954e9f93a1)

### 期待的正确结果

脚本正确执行无异常

### 相关日志输出

```shell
summary + 1 in 00:00:00 = 6.1/s Avg: 119 Min: 119 Max: 119 Err: 0 (0.00%) Active: 1 Started: 1 Finished: 0
2023-06-07 14:25:04,492 *******************************************/test/
2023-06-07 14:25:04,496 *******************************************/test/deviceIds_saas.txt
2023-06-07 14:25:04,513 文件名：/test/deviceIds_saas.txt
2023-06-07 14:25:04,518 文件大小：515000
2023-06-07 14:25:04,539 Problem in JSR223 script 批量生成deviceId-JSR223, message: javax.script.ScriptException: Sourced file: inline evaluation of: ``import java.util.*; import org.apache.commons.io.FileUtils; import org.apache.jm . . . '' : Typed variable declaration : Object constructor : at Line: 29 : in file: inline evaluation of: ``import java.util.*; import org.apache.commons.io.FileUtils; import org.apache.jm . . . '' : new FileWriter ( file )

Target exception: java.io.FileNotFoundException: /test/deviceIds_saas.txt (Permission denied)
in inline evaluation of: ``import java.util.*; import org.apache.commons.io.FileUtils; import org.apache.jm . . . '' at line number 29 javax.script.ScriptException: Sourced file: inline evaluation of: ``import java.util.*; import org.apache.commons.io.FileUtils; import org.apache.jm . . . '' : Typed variable declaration : Object constructor : at Line: 29 : in file: inline evaluation of: ``import java.util.*; import org.apache.commons.io.FileUtils; import org.apache.jm . . . '' : new FileWriter ( file )

Target exception: java.io.FileNotFoundException: /test/deviceIds_saas.txt (Permission denied)
in inline evaluation of: ``import java.util.*; import org.apache.commons.io.FileUtils; import org.apache.jm . . . '' at line number 29
at bsh.engine.BshScriptEngine.evalSource(BshScriptEngine.java:87) ~[bsh-2.0b6.jar:2.0b6 2016-02-05 05:16:19]
at bsh.engine.BshScriptEngine.eval(BshScriptEngine.java:46) ~[bsh-2.0b6.jar:2.0b6 2016-02-05 05:16:19]
at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:231) ~[java.scripting:?]
at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:252) ~[ms-jmeter-core.jar:5.5]
at org.apache.jmeter.protocol.java.sampler.JSR223Sampler.sample(JSR223Sampler.java:72) ~[ApacheJMeter_java.jar:5.5]
at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:670) ~[ms-jmeter-core.jar:5.5]
at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:588) ~[ms-jmeter-core.jar:5.5]
at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:500) ~[ms-jmeter-core.jar:5.5]
at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:264) ~[ms-jmeter-core.jar:5.5]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.io.FileNotFoundException: /test/deviceIds_saas.txt (Permission denied)
at java.io.FileOutputStream.open0(Native Method) ~[?:?]
at java.io.FileOutputStream.open(FileOutputStream.java:293) ~[?:?]
at java.io.FileOutputStream.<init>(FileOutputStream.java:235) ~[?:?]
at java.io.FileOutputStream.<init>(FileOutputStream.java:184) ~[?:?]
at java.io.FileWriter.<init>(FileWriter.java:96) ~[?:?]
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
at bsh.Reflect.constructObject(Reflect.java:621) ~[bsh-2.0b6.jar:2.0b6 2016-02-05 05:16:19]
at bsh.BSHAllocationExpression.constructObject(BSHAllocationExpression.java:117) ~[bsh-2.0b6.jar:2.0b6 2016-02-05 05:16:19]
at bsh.BSHAllocationExpression.objectAllocation(BSHAllocationExpression.java:108) ~[bsh-2.0b6.jar:2.0b6 2016-02-05 05:16:19]
at bsh.BSHAllocationExpression.eval(BSHAllocationExpression.java:56) ~[bsh-2.0b6.jar:2.0b6 2016-02-05 05:16:19]
at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:96) ~[bsh-2.0b6.jar:2.0b6 2016-02-05 05:16:19]
at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:41) ~[bsh-2.0b6.jar:2.0b6 2016-02-05 05:16:19]
at bsh.BSHVariableDeclarator.eval(BSHVariableDeclarator.java:80) ~[bsh-2.0b6.jar:2.0b6 2016-02-05 05:16:19]
at bsh.BSHTypedVariableDeclaration.eval(BSHTypedVariableDeclaration.java:78) ~[bsh-2.0b6.jar:2.0b6 2016-02-05 05:16:19]
at bsh.Interpreter.eval(Interpreter.java:659) ~[bsh-2.0b6.jar:2.0b6 2016-02-05 05:16:19]
at bsh.Interpreter.eval(Interpreter.java:750) ~[bsh-2.0b6.jar:2.0b6 2016-02-05 05:16:19]
at bsh.Interpreter.eval(Interpreter.java:739) ~[bsh-2.0b6.jar:2.0b6 2016-02-05 05:16:19]
at bsh.engine.BshScriptEngine.evalSource(BshScriptEngine.java:78) ~[bsh-2.0b6.jar:2.0b6 2016-02-05 05:16:19]
... 9 more
```

**Comment by leonXtt** [comment]
![1d345e61-ece7-4508-9202-e8e0327a5f91](https://github.com/metersphere/metersphere/assets/129242317/912fc524-4f03-4226-a3e9-f87f83d52be6)

**Comment by liqiang-fit2cloud** [comment]
由于用户在自定义脚本中调用本地资源可能造成不可预知的后果，所以在v2.10 LTS版本中的进程已改为非root用户运行，并且限制了本地命令的执行和本地文件的读写。
相关的安全公告已经发布：
https://github.com/metersphere/metersphere/security/advisories/GHSA-5473-9v2g-rpqm
https://mp.weixin.qq.com/s/vSs7GkZ7deGV1Pmfmpp9RQ
建议考虑别的方式实现，比如对象存储或者远程文件之类的。

**Comment by muwednesday** [comment]
![non_root](https://github.com/metersphere/metersphere/assets/34086410/48783120-e7ab-4115-8333-b72eaea5d5e9)
docker-compose-node-controller.yml 配置文件，把这个配置注释掉，重启一下就好🌶
