### ISSUE TITLE
[BUG]v1.19版本，无法查看测试报告

### ISSUE THREAD

**Issue by zolibra** [metersphere/metersphere#24867]
### MeterSphere 版本

v1.19

### 使用外置数据库

否

### 问题描述

![图片](https://github.com/metersphere/metersphere/assets/1215079/2cc65946-7d38-49d5-805e-a28474abe97b)

### 重现步骤

1. 运行测试计划
2. 查看测试报告

### 期待的正确结果

不报错，可能正常展示报告
<img width="1273" alt="图片" src="https://github.com/metersphere/metersphere/assets/1215079/a3595f74-cec8-480f-89d7-b8f6e3184eb8">

### 相关日志输出

```shell
Caused by: java.lang.ClassCastException: java.util.HashMap cannot be cast to io.metersphere.base.domain.Project
at io.metersphere.track.service.TestPlanTestCaseService.lambda$buildCaseInfo$182(TestPlanTestCaseService.java:424)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at io.metersphere.track.service.TestPlanTestCaseService.buildCaseInfo(TestPlanTestCaseService.java:423)
at io.metersphere.track.service.TestPlanTestCaseService.getAllCases(TestPlanTestCaseService.java:415)
at io.metersphere.track.service.TestPlanTestCaseService$$FastClassBySpringCGLIB$$4b2f95fc.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
```

### 附加信息

这里的resultType错误，导致类型转换错误，java.util.Map应该修改为Project对象：
<select id="queryNameByIds" resultType="java.util.Map">
        SELECT id, name
        FROM project
                WHERE id IN
        <foreach collection="ids" item="id" index="index"
                 open="(" close=")" separator=",">
            #{id}
        </foreach>
    </select>

**Comment by zrfit** [comment]
您好，感谢反馈！最新版本v2.10.1-lts未复现该问题，建议升级尝试。
