### ISSUE TITLE
[BUG]对接禅道配置解决方案和重复ID字段后，MS能正常同步解决方案和重复ID，但是MS无法正常提交bug了

### ISSUE THREAD

**Issue by weishuo6** [metersphere/metersphere#25007]
### 联系方式

1373916729@qq.com

### MeterSphere 版本

v2.10.1-lts版本

### 使用外置数据库

否

### 问题描述

场景：研发在禅道解决缺陷后，会确定缺陷的解决方案，如果是重复bug，会添加重复ID。测试人员需要在MS里面能够看到解决方案，如果是重复bug，需要看到重复ID。

问题：配置解决方案和重复ID后，MS能正常同步解决方案和重复ID，但是测试人员无法正常提交bug了

### 重现步骤

1、添加禅道自定义字段“解决方案”，添加其他选项和重复bug选项
![image](https://github.com/metersphere/metersphere/assets/35896106/8f036baa-da76-409d-a373-74bdd0c26428)
2、模板添加字段“解决方案”和“重启ID”
![image](https://github.com/metersphere/metersphere/assets/35896106/8bb8c6b0-9052-4076-b3d2-2a5ff347172d)
3、点击同步缺陷可以同步“解决方案”和“重启ID”到MS
![image](https://github.com/metersphere/metersphere/assets/35896106/6cc0a7b1-29e4-417e-bdbf-610c7bf19159)
4、测试人员在MS提交缺陷，不填写“解决方案”和“重启ID”，无法提交，报错500
![image](https://github.com/metersphere/metersphere/assets/35896106/0c044795-96b7-4fe7-9746-3debcd6c9469)

### 期待的正确结果

可以正常提交bug

**Comment by youliyuan-fit2cloud** [comment]
你好，请在zentao中检查下这个新增的字段是不是必填项？再把后台错误日志发出来看看。

**Comment by weishuo6** [comment]
@youliyuan-fit2cloud 字段非必填项，日志报错如下：
2023-06-19 00:00:05,368 [trackScheduler_Worker-1] ERROR i.metersphere.service.IssuesService 149 - Method[saveAttachmentModuleRelation][java.lang.NullPointerException: Cannot invoke "io.metersphere.base.domain.FileAttachmentMetadata.getId()" because "fileAttachmentMetadata" is null]
java.lang.NullPointerException: Cannot invoke "io.metersphere.base.domain.FileAttachmentMetadata.getId()" because "fileAttachmentMetadata" is null
	at io.metersphere.service.IssuesService.lambda$saveAttachmentModuleRelation$35(IssuesService.java:1191)
	at io.metersphere.platform.client.ZentaoClient.lambda$getAttachmentBytes$1(ZentaoClient.java:307)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:865)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:764)
	at io.metersphere.platform.client.ZentaoClient.getAttachmentBytes(ZentaoClient.java:305)
	at io.metersphere.platform.impl.ZentaoPlatform.getAttachmentContent(ZentaoPlatform.java:631)
	at io.metersphere.service.IssuesService.saveAttachmentModuleRelation(IssuesService.java:1184)
	at io.metersphere.service.IssuesService.syncPluginIssueAttachment(IssuesService.java:1109)
	at io.metersphere.service.IssuesService.syncPluginIssueAttachment(IssuesService.java:1080)
	at jdk.internal.reflect.GeneratedMethodAccessor3213.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:702)
	at io.metersphere.service.IssuesService$$SpringCGLIB$$1.syncPluginIssueAttachment(<generated>)
	at jdk.internal.reflect.GeneratedMethodAccessor3213.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:702)
	at io.metersphere.service.IssuesService$$SpringCGLIB$$2.syncPluginIssueAttachment(<generated>)
	at jdk.internal.reflect.GeneratedMethodAccessor5389.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.metersphere.xpack.track.utils.ReflectUtil.invokeMethod(o:328)
	at io.metersphere.xpack.track.service.XpackIssueServiceImpl.invokeIssueServiceMethod(d:151)
	at io.metersphere.xpack.track.service.XpackIssueServiceImpl.ALLATORIxDEMO(d:268)
	at io.metersphere.platform.impl.ZentaoPlatform.syncAllIssues(ZentaoPlatform.java:335)
	at io.metersphere.service.IssuesService.execSyncAll(IssuesService.java:1975)
	at jdk.internal.reflect.GeneratedMethodAccessor1117.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:702)
	at io.metersphere.service.IssuesService$$SpringCGLIB$$1.execSyncAll(<generated>)
	at jdk.internal.reflect.GeneratedMethodAccessor1117.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:702)
	at io.metersphere.service.IssuesService$$SpringCGLIB$$2.execSyncAll(<generated>)
	at jdk.internal.reflect.GeneratedMethodAccessor5387.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.metersphere.xpack.track.utils.ReflectUtil.invokeMethod(o:328)
	at io.metersphere.xpack.track.service.XpackIssueServiceImpl.invokeIssueServiceMethod(d:151)
	at io.metersphere.xpack.track.service.XpackIssueServiceImpl.syncThirdPartyIssues(d:428)
	at jdk.internal.reflect.GeneratedMethodAccessor1116.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:702)
	at io.metersphere.xpack.track.service.XpackIssueServiceImpl$$SpringCGLIB$$1.syncThirdPartyIssues(<generated>)
	at jdk.internal.reflect.GeneratedMethodAccessor1116.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:702)
	at io.metersphere.xpack.track.service.XpackIssueServiceImpl$$SpringCGLIB$$2.syncThirdPartyIssues(<generated>)
	at jdk.internal.reflect.GeneratedMethodAccessor1116.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at io.metersphere.xpack.track.service.XpackIssueServiceImpl$$SpringCGLIB$$0.syncThirdPartyIssues(<generated>)
	at io.metersphere.xpack.track.service.XpackIssueServiceImpl.ALLATORIxDEMO(d:65)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at io.metersphere.xpack.track.service.XpackIssueServiceImpl.syncThirdPartyIssues(d:468)
	at jdk.internal.reflect.GeneratedMethodAccessor3207.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:702)
	at io.metersphere.xpack.track.service.XpackIssueServiceImpl$$SpringCGLIB$$1.syncThirdPartyIssues(<generated>)
	at jdk.internal.reflect.GeneratedMethodAccessor3207.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:702)
	at io.metersphere.xpack.track.service.XpackIssueServiceImpl$$SpringCGLIB$$2.syncThirdPartyIssues(<generated>)
	at io.metersphere.job.schedule.IssueSyncJob.businessExecute(IssueSyncJob.java:32)
	at io.metersphere.sechedule.MsScheduleJob.execute(MsScheduleJob.java:25)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

**Comment by youliyuan-fit2cloud** [comment]
你好，该问题已复现，计划下个版本修复。
ps：日志和问题不相关性。

**Comment by youliyuan-fit2cloud** [comment]
v2.10.3-lts中已修复。
