### ISSUE TITLE
[BUG] 接口测试返回数据超过5m时，无法正常显示，api-test项目报错。

### ISSUE THREAD

**Issue by easayliu** [metersphere/metersphere#25156]
### MeterSphere 版本

v2.10.1

### 使用外置数据库

否

### 问题描述

- 页面现象：接口测试的快速调试执行未返回数据
----
- api-test的ms-jmeter-run.log存在报错信息，关联问题可以查看https://github.com/FasterXML/jackson-core/issues/1014

### 重现步骤

返回数据超过5m

### 相关日志输出

```shell
Caused by: com.fasterxml.jackson.databind.JsonMappingException: String length (5046272) exceeds the maximum length (5000000) (through reference chain: io.metersphere.api.dto.MsgDTO["content"])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1830)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:316)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740)
        at io.metersphere.commons.utils.JSONUtil.parseObject(JSONUtil.java:53)
        ... 25 common frames omitted
Caused by: com.fasterxml.jackson.core.exc.StreamConstraintsException: String length (5046272) exceeds the maximum length (5000000)
        at com.fasterxml.jackson.core.StreamReadConstraints.validateStringLength(StreamReadConstraints.java:290)
        at com.fasterxml.jackson.core.util.ReadConstrainedTextBuffer.validateStringLength(ReadConstrainedTextBuffer.java:27)
        at com.fasterxml.jackson.core.util.TextBuffer.finishCurrentSegment(TextBuffer.java:931)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString2(ReaderBasedJsonParser.java:2240)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString(ReaderBasedJsonParser.java:2206)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.getText(ReaderBasedJsonParser.java:323)
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:42)
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        ... 31 common frames omitted
```

**Comment by fit2-zhao** [comment]
感谢反馈，在下个小版本会升级 jackson 到 2.15.2 并调整DEFAULT_MAX_STRING_LEN 为 200m。

**Comment by youliyuan-fit2cloud** [comment]
v2.10.3-lts中已修复。
