### ISSUE TITLE
[BUG]接口自动化前置处理引入js文件报错文件不存在

### ISSUE THREAD

**Issue by beachone** [metersphere/metersphere#25506]
### 联系方式

交流群58:beachone

### MeterSphere 版本

v2.8.1-b1

### 使用外置数据库

否

### 问题描述

接口自动化前置处理引入js文件报错文件不存在

### 重现步骤

1.脚本前置步骤load js文件
![image](https://github.com/metersphere/metersphere/assets/43975871/1a98ce94-700e-4cff-bf11-31e1ccaea157)
2.引用路径下有对应的js文件
![image](https://github.com/metersphere/metersphere/assets/43975871/f6e17411-a7e2-4bc2-b51a-a7a09417e8eb)

### 期待的正确结果

引用成功

### 相关日志输出

```shell
2023-07-11 15:43:01 INFO 6a3ec4b6 1-1 Thread started: 6a3ec4b6 1-1
2023-07-11 15:43:01 ERROR 6a3ec4b6 1-1 Problem in JSR223 script, BeanShellPreProcessor
Couldn't read source file "/data/msroot/metersphere/data/body/crypto-js.js": /data/msroot/metersphere/data/body/crypto-js.js (No such file or directory). (eval#2) in eval at line number 2 at column number 0
javax.script.ScriptException
   at org.mozilla.javascript.engine.RhinoScriptEngine.eval(RhinoScriptEngine.java:122)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:231)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:237)
   at org.apache.jmeter.modifiers.JSR223PreProcessor.process(JSR223PreProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:999)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:560)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:500)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:264)
   at java.base/java.lang.Thread.run(Thread.java:833)
```

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/43975871/ae500f4c-211a-4be8-84d8-0edd6771fdf9)

**Comment by zrfit** [comment]
您好，感谢反馈！最新版本v2.10.3-lts是可以引用成功的。
1、执行的资源池是local资源池吗？
2、请检查执行时选择的资源池是否挂载了js文件的路径？

**Comment by beachone** [comment]
1.执行的资源池是local资源池
2.怎么查看local资源池是否挂在了js文件路径

**Comment by zrfit** [comment]
核对下配置文件docker-compose-node-controller.yml中挂载的文件路径和引用的js文件路径是否一致？
安装在/opt下的默认配置是
volumes:
      - ms-conf:/opt/metersphere/conf
      - ms-data:/opt/metersphere/data
      - ms-logs:/opt/metersphere/logs
看截图您的是/data/msroot/metersphere/data/，核对下您的docker-compose-node-controller.yml中的文件路径和引用的js文件路径是否一致。

**Comment by beachone** [comment]
docker-compose-node-controller.yml中的文件路径是使用的默认配置， 把ms-conf、ms-data、ms-logs修改成我截图的路径就可以了吗？需要重启或者别的操作吗？

**Comment by zrfit** [comment]
1、将docker-compose-node-controller.yml中的默认文件路径改为：
volumes:
- ms-conf:/data/msroot/metersphere/conf
- ms-data:/data/msroot/metersphere/data
- ms-logs:/data/msroot/metersphere/logs
2、执行msctl reload 
3、进入容器检查看下js文件是否挂载成功
docker exec -it ms-node-controller sh
cd /data/msroot/metersphere/data/body/
4、js文件挂载成功-执行场景-js文件引用成功

**Comment by beachone** [comment]
修改配置reload之后进入容器可以看到js文件，但是引用还是报错
![image](https://github.com/metersphere/metersphere/assets/43975871/8dc364ed-aee3-4087-95fe-5cb4ff5d2f44)
![image](https://github.com/metersphere/metersphere/assets/43975871/64aab17e-226a-4fd1-a958-6f05a417dcac)
![image](https://github.com/metersphere/metersphere/assets/43975871/63286bef-3594-4c77-b947-63ed3a17ec98)
![image](https://github.com/metersphere/metersphere/assets/43975871/c60536ad-76c3-4c3d-9e17-4663e7278ddf)

**Comment by zrfit** [comment]
您好，暂时未复现该问题，后续最新版本如果再遇到该问题，可再打开并提供详细的日志信息、配置信息和复现步骤。
