### ISSUE TITLE
[BUG]两个接口名称只差一个字母s时，后加的接口总是提示org.apache.http.NoHttpResponseException

### ISSUE THREAD

**Issue by AnneXie01** [metersphere/metersphere#25944]
### 联系方式

17372609288

### MeterSphere 版本

v2.10.1-lts-65fad062

### 使用外置数据库

否

### 问题描述

新建场景
1、访问接口1 http://*/ss
2、访问接口2 http://*/sss
接口2 无法访问

### 重现步骤

新建场景
1、访问接口1 http://*/ss
2、访问接口2 http://*/sss
接口2访问：
org.apache.http.NoHttpResponseException

### 期待的正确结果

接口2正常访问

### 相关日志输出

```shell
org.apache.http.NoHttpResponseException: 10.10.38.75:9091 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.executeRequest(HTTPHC4Impl.java:939)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.sample(HTTPHC4Impl.java:650)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:128)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1301)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1290)
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:670)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:588)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:500)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by zrfit** [comment]
您好，感谢反馈！最新版本未复现该问题，请升级到最新版本尝试。
<img width="705" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/a6b647e8-8442-4323-bdcc-e090296735a9">
<img width="697" alt="image" src="https://github.com/metersphere/metersphere/assets/75963100/07fe033e-d91b-473f-b04b-7048458552bf">
