### ISSUE TITLE
[QUESTION] 接口测试自定义脚本调用的Jar包是否支持访问文件管理中上传的文件

### ISSUE THREAD

**Issue by dan-kuroto** [metersphere/metersphere#26857]
### 请描述您的问题

我正尝试在【接口测试-接口自动化】中通过自定义脚本来测试一个Jar包的功能（Jar包已通过文件管理功能上传并能够引入自定义脚本中）（这个Jar包需要读取本地的pfx文件，也已通过文件管理功能上传了）

但我不知道这种情况下，Jar包是否能读到【文件管理】里的pfx文件，如果能读到，应该传的路径是怎样的？
我试过了`直接传文件名`和`传【文件管理】表格里显示的文件路径`这两种方式，但是都报错了。

报错信息如下：
```bash
2023-09-21 17:29:40 INFO 811a6df6 1-1 Thread started: 811a6df6 1-1
2023-09-21 17:29:40 ERROR 811a6df6 1-1 Problem in JSR223 script 测试 queryInExpDetail, message: {}
java.security.InvalidKeyException: java.security.InvalidKeyException: Supplied key (null) is not a RSAPrivateKey instance in <script> at line number 14
javax.script.ScriptException
   at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:202)
   at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:42)
   at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:231)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:237)
   at org.apache.jmeter.protocol.java.sampler.JSR223Sampler.sample(JSR223Sampler.java:72)
   at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:672)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:590)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:502)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:265)
   at java.base/java.lang.Thread.run(Thread.java:833)
```

我自己在本地开发机上也尝试复现了一下，当我把pfx文件的路径故意改成错的，本地测试那个jar包也会报相同的错误（即`java.security.InvalidKeyException: Supplied key (null) is not a RSAPrivateKey instance
`）也就是说上面的报错原因是jar包没有读到文件，但我应该怎么改才能让它能读到pfx文件呢？

**Comment by dan-kuroto** [comment]
已参考[这个issue](https://github.com/metersphere/metersphere/issues/23799)解决问题。思路如下：
- `/opt/metersphere/data` 下的文件是可以被自定义脚本访问到的
- `/opt/metersphere/data/minio/metersphere/{项目id}/{文件名}` 这个路径是文件管理对应的文件，但是它是个目录，而该目录下的`xl.meta`文件并不是原本的文件
- 通过ftp工具，手动将需要直接访问的文件上传到 `/opt/metersphere/data/`这个目录下，然后在使用自定义脚本时传入绝对路径，就可以访问了！

**Comment by Somebody-JIAN** [comment]
👍🏻    真棒！
