### ISSUE TITLE
[BUG]接口自动化脚本转成性能测试脚本后，找不到csv参数文件

### ISSUE THREAD

**Issue by xiaochongzi-ling** [metersphere/metersphere#26870]
### 联系方式

2297310871@qq.com

### MeterSphere 版本

v2.10.0-lts-89acace0

### 使用外置数据库

否

### 问题描述

![图片](https://github.com/metersphere/metersphere/assets/23067502/095ed1b0-4b2e-48dd-9a39-30bed779279c)

### 重现步骤

1.接口自动化-带有csv参数文件（关联项目设置-文件管理）中的文件；
2.一键转成性能测试脚本后，csv参数文件存在，但是执行找不到文件，删除后也无法重新添加；
3.执行性能测试脚本。

### 期待的正确结果

能够正确执行。

### 相关日志输出

```shell
2023-09-22 14:41:59,559 Problem in JSR223 script 沪市-买入-测试数据, message: javax.script.ScriptException: IOError: [Errno 2] No such file or directory: u'/opt/metersphere/data/api-folder/file/ms/a523dc16-30f0-4d8b-a525-ef2c182150c9/01d444d7-7fbd-4f11-a79f-bb84cece4311/1682321168025/110_sh_buy_test_data.csv' in <script> at line number 3 javax.script.ScriptException: IOError: [Errno 2] No such file or directory: u'/opt/metersphere/data/api-folder/file/ms/a523dc16-30f0-4d8b-a525-ef2c182150c9/01d444d7-7fbd-4f11-a79f-bb84cece4311/1682321168025/110_sh_buy_test_data.csv' in <script> at line number 3
	at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:222) ~[jython-standalone-2.7.2.jar:2.7.2]
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:59) ~[jython-standalone-2.7.2.jar:2.7.2]
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31) ~[jython-standalone-2.7.2.jar:2.7.2]
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:231) ~[java.scripting:?]
	at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:252) ~[ms-jmeter-core.jar:5.5]
	at org.apache.jmeter.protocol.java.sampler.JSR223Sampler.sample(JSR223Sampler.java:72) ~[ApacheJMeter_java.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:670) ~[ms-jmeter-core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:588) ~[ms-jmeter-core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:500) ~[ms-jmeter-core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:264) ~[ms-jmeter-core.jar:5.5]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.python.core.PyException: IOError: [Errno 2] No such file or directory: u'/opt/metersphere/data/api-folder/file/ms/a523dc16-30f0-4d8b-a525-ef2c182150c9/01d444d7-7fbd-4f11-a79f-bb84cece4311/1682321168025/110_sh_buy_test_data.csv'
	at org.python.core.Py.IOError(Py.java:203) ~[jython-standalone-2.7.2.jar:2.7.2]
```

**Comment by zrfit** [comment]
您好！感谢反馈！最新版本v2.10.6-lts未复现该问题！请升级尝试。
<img width="1390" alt="image" src="https://github.com/metersphere/metersphere/assets/99731894/18b4518a-88a7-4495-91f5-2551eb1bb77e">
