### ISSUE TITLE
[BUG] 数据库从容器迁移到云数据库，系统设置服务启动报错

### ISSUE THREAD

**Issue by chjtester** [metersphere/metersphere#26905]
### 联系方式

交流群59：悠悠我心

### MeterSphere 版本

2.10

### 使用外置数据库

是

### 问题描述

操作流程：
1、连接容器mysql
2、将容器mysql转储到云数据库
3、修改.env文件中的mysql域名、用户名和密码
4、msctl restart

报错：
![64e8b080-3c41-4a89-ad3f-8ac80bcc7315](https://github.com/metersphere/metersphere/assets/53989235/d32175a1-8c7f-49e1-8e42-fdb414c5a6f6)

### 重现步骤

操作流程：
1、连接容器mysql
2、将容器mysql转储到云数据库
3、修改.env文件中的mysql域名、用户名和密码
4、msctl restart

### 期待的正确结果

msctl reload 或 msctl restart可以正常重启

### 相关日志输出

```shell
2023-09-26 00:10:48,139 [main] ERROR i.m.commons.utils.CompressUtils 149 - Method[unzip][java.util.zip.ZipException: invalid stored block lengths]
java.util.zip.ZipException: invalid stored block lengths
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
        at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:196)
        at io.metersphere.commons.utils.CompressUtils.unzip(CompressUtils.java:199)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.metersphere.interceptor.MybatisInterceptor.undo(MybatisInterceptor.java:170)
        at io.metersphere.interceptor.MybatisInterceptor.intercept(MybatisInterceptor.java:45)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
        at jdk.proxy2/jdk.proxy2.$Proxy294.query(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
        at io.metersphere.interceptor.UserDesensitizationInterceptor.intercept(UserDesensitizationInterceptor.java:27)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
        at jdk.proxy2/jdk.proxy2.$Proxy294.query(Unknown Source)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:151)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:145)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:76)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:425)
        at jdk.proxy2/jdk.proxy2.$Proxy131.selectOne(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:160)
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:87)
        at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:145)
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
        at jdk.proxy2/jdk.proxy2.$Proxy163.selectByPrimaryKey(Unknown Source)
        at io.metersphere.service.FileService.getFileContent(FileService.java:45)
        at io.metersphere.service.FileService.checkRsaKey(FileService.java:296)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:702)
        at io.metersphere.service.FileService$$SpringCGLIB$$0.checkRsaKey(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:702)
        at io.metersphere.service.FileService$$SpringCGLIB$$1.checkRsaKey(<generated>)
        at io.metersphere.autoconfigure.RsaConfig.run(RsaConfig.java:17)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:761)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:751)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:318)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1305)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1294)
        at io.metersphere.SettingApplication.main(SettingApplication.java:29)
```

### 附加信息

已经找社区值班的技术人员远程看过，但是没找到问题，解决的方法是：删掉数据库，重启服务生成空表，服务启动成功后，然后导入数据库数据，可正常使用。但是每次重启都要重新导入一遍数据库，太麻烦，而且风险也高，期待正确的解决方案。

**Comment by liuruibin** [comment]
云数据库的my.cnf和我们安装包里的一样吗

**Comment by youliyuan-fit2cloud** [comment]
因长期未反馈，关闭该问题。
