### ISSUE TITLE
在线部署Metersphere时system-setting容器无法启动

### ISSUE THREAD

**Issue by yangchnet** [metersphere/metersphere#27071]
### 请描述您的问题

容器log报错信息：
```
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:175)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
        at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:48)
        ... 38 common frames omitted
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150)
        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:166)
        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
        at com.mysql.cj.NativeSession.connect(NativeSession.java:121)
        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:945)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:815)
        ... 49 common frames omitted
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:153)
        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
        ... 52 common frames omitted

```

版本：v2.10.7-lts
主机环境：Linux 64位 12c16G
命令行报错信息：dependency failed to start: container system-setting is unhealthy
@liuruibin 能帮忙看下吗

**Comment by liuruibin** [comment]
日志上写的是连不上mysql，mysql容器正常吗

**Comment by yangchnet** [comment]
mysql容器正常启动
```
4b5844bbffa1   registry.cn-qingdao.aliyuncs.com/metersphere/mysql:8.0.33                         "docker-entrypoint.s…"   About an hour ago   Up About a minute (healthy)                0.0.0.0:3306->3306/tcp, :::3306->3306/tcp, 33060/tcp                                   mysql
```
![image](https://github.com/metersphere/metersphere/assets/30308940/144f8eef-a1b5-4a4f-9272-5c451ebb3d55)
数据库成功创建但未创建表

**Comment by yangchnet** [comment]
mysql容器正常启动
```
4b5844bbffa1   registry.cn-qingdao.aliyuncs.com/metersphere/mysql:8.0.33                         "docker-entrypoint.s…"   About an hour ago   Up About a minute (healthy)                0.0.0.0:3306->3306/tcp, :::3306->3306/tcp, 33060/tcp                                   mysql
```
![image](https://github.com/metersphere/metersphere/assets/30308940/144f8eef-a1b5-4a4f-9272-5c451ebb3d55)
数据库成功创建但未创建表

**Comment by liuruibin** [comment]
密码配置是对的吗
my.cnf 检查一下是不是正常的

**Comment by yangchnet** [comment]
密码正确，my.cnf也正常的

**Comment by liuruibin** [comment]
删除容器和opt/metersphere目录重新安装试试

**Comment by youliyuan-fit2cloud** [comment]
因长期未反馈，关闭该问题。
