### ISSUE TITLE
[BUG]刚安装的MeterSphere的gateway启动不了

### ISSUE THREAD

**Issue by mayou33** [metersphere/metersphere#27161]
### MeterSphere 版本

v2.10.7-lts

### 使用外置数据库

否

### 问题描述

刚安装的MeterSphere的gateway启动不了。
日志报错

2023-10-19 14:52:51,453 ERROR g.springframework.boot.SpringApplication: 827 - Application run failed
java.lang.IllegalStateException: Failed to execute ApplicationRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:768)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298)
        at io.metersphere.gateway.GatewayApplication.main(GatewayApplication.java:29)
Caused by: org.springframework.jdbc.BadSqlGrammarException: 
### Cause: java.sql.SQLSyntaxErrorException: Table 'metersphere.file_content' doesn't exist
; bad SQL grammar []
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:246)

解决方法：
mysql 里面 新建一个表file_content

但是  没有找到v2.10.7-lts版本要的对应的建表语句
v2.10.7-lts

### 重现步骤

gateway日志

**Comment by youliyuan-fit2cloud** [comment]
你好，怀疑安装过程出现意外，建议尝试重新安装一次。

**Comment by mayou33** [comment]
重新安装一次，就好了。
