### ISSUE TITLE
[BUG]引入的JavaScript脚本中如果包含三个点“...”的扩展运算符，那么运行时总报“javax.script.ScriptException”的错误

### ISSUE THREAD

**Issue by JoanQQ** [metersphere/metersphere#27296]
### 联系方式

87524112@qq.com

### MeterSphere 版本

v2.10.7-lts-b3

### 使用外置数据库

否

### 问题描述

报错的JavaScript行：  const params = { ...body.common, ...body.data };

Metersphere控制台报错信息：
2023-10-30 00:08:08 ERROR 6af46321 1-1 Problem in JSR223 script, xxx(js文件名)
invalid property id (/opt/metersphere/data/xxx.js#62) in /opt/metersphere/data/xxx.js at line number 62 at column number 21
javax.script.ScriptException
   at org.mozilla.javascript.engine.RhinoScriptEngine.eval(RhinoScriptEngine.java:122)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:231)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:237)
   at org.apache.jmeter.modifiers.JSR223PreProcessor.process(JSR223PreProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:1001)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:562)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:502)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:265)
   at java.base/java.lang.Thread.run(Thread.java:833)

### 重现步骤

1. 编写包含三个点“...”的JavaScript脚本；
2. 参考飞致云知识库：https://kb.fit2cloud.com/?p=118 在测试用例的前置脚本中引入本地JavaScript脚本；【g = new Packages.org.mozilla.javascript.tools.shell.Global(Packages.org.mozilla.javascript.Context.getCurrentContext()); this.load = g.load; load("/opt/metersphere/data/xxx.js"); log.info("===111===");】
3. 运行接口用例，查看控制台信息，报错如下：
2023-10-30 00:08:08 ERROR 6af46321 1-1 Problem in JSR223 script, xxx(js文件名)
invalid property id (/opt/metersphere/data/xxx.js#62) in /opt/metersphere/data/xxx.js at line number 62 at column number 21
javax.script.ScriptException
   at org.mozilla.javascript.engine.RhinoScriptEngine.eval(RhinoScriptEngine.java:122)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:231)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:237)
   at org.apache.jmeter.modifiers.JSR223PreProcessor.process(JSR223PreProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:1001)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:562)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:502)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:265)
   at java.base/java.lang.Thread.run(Thread.java:833)

### 期待的正确结果

在控制台中打印出脚本返回的内容

### 相关日志输出

```shell
2023-10-30 00:08:08 ERROR 6af46321 1-1 Problem in JSR223 script, xxx(js文件名)
invalid property id (/opt/metersphere/data/xxx.js#62) in /opt/metersphere/data/xxx.js at line number 62 at column number 21
javax.script.ScriptException
   at org.mozilla.javascript.engine.RhinoScriptEngine.eval(RhinoScriptEngine.java:122)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:231)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:237)
   at org.apache.jmeter.modifiers.JSR223PreProcessor.process(JSR223PreProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:1001)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:562)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:502)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:265)
   at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by liuruibin** [comment]
我们使用的是rhino engine作为js语法解析器，您可以在这里查看相关语法 https://mozilla.github.io/rhino/compat/engines.html

**Comment by fit2-zhao** [comment]
可以使用：
`var params = body.common.concat(body.data) `

... 是 ECMAScript 6中的语法，目前不支持。
