### ISSUE TITLE
[BUG]我将一个接口用frp转发到本地的127.0.0.1:13001之后请求秒失败

### ISSUE THREAD

**Issue by kslz** [metersphere/metersphere#27518]
### 联系方式

49679880

### MeterSphere 版本

v2.10.8-lts

### 使用外置数据库

否

### 问题描述

我用frp将一个接口转发到本地的127.0.0.1:13001之后请求秒失败
frp转发方式：https://gofrp.org/zh-cn/docs/examples/stcp/
请求失败：
![image](https://github.com/metersphere/metersphere/assets/54951765/6e25cafe-03f9-4523-af26-ea72dbcc78bd)
部署设备的telnet可以成功
![image](https://github.com/metersphere/metersphere/assets/54951765/90280d2e-fcfb-4dbf-865e-0119cc1184f1)

### 重现步骤

接口定义-test case请求均失败

### 相关日志输出

```shell
报错：
org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:13001 [/127.0.0.1] failed: Connection refused
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl$JMeterDefaultHttpClientConnectionOperator.connect(HTTPHC4Impl.java:408)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.executeRequest(HTTPHC4Impl.java:939)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.sample(HTTPHC4Impl.java:650)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:128)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1301)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1290)
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:672)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:590)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:502)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:547)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 19 more
```

**Comment by liqiang-fit2cloud** [comment]
MeterSphere运行在容器中，127.0.0.1是容器地址，你需要用<宿主机IP>:13001。

**Comment by 13290445582** [comment]
您好，该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
