### ISSUE TITLE
[BUG]接口自动化中添加后置脚本，使用获取随机数函数，当随机数包含特殊数字时脚本运行会报错

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#27741]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.9-lts

### 使用外置数据库

否

### 问题描述

接口自动化中添加后置脚本，使用获取随机数函数，当随机数包含特殊数字时脚本运行会报错

### 重现步骤

1. 创建接口自动化场景
2. 添加循环控制器，次数循环20次
3. 在循环控制器中导入接口
4. 调试，发现当随机数包含特殊数字时脚本运行会报错

### 期待的正确结果

接口自动化中添加后置脚本，使用获取随机数函数，脚本运行正常。

### 相关日志输出

```shell
In file: inline evaluation of: ``import org.apache.commons.codec.digest.DigestUtils;  String now = "2023112817414 . . . '' Encountered "80" at line 5, column 22.
 in inline evaluation of: ``import org.apache.commons.codec.digest.DigestUtils;  String now = "2023112817414 . . . '' at line number 5
javax.script.ScriptException
   at bsh.engine.BshScriptEngine.evalSource(BshScriptEngine.java:82)
   at bsh.engine.BshScriptEngine.eval(BshScriptEngine.java:46)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:231)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:237)
   at org.apache.jmeter.extractor.JSR223PostProcessor.process(JSR223PostProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPostProcessors(JMeterThread.java:991)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:605)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:502)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:265)
   at java.base/java.lang.Thread.run(Thread.java:833)
```

### 附加信息

![image](https://github.com/metersphere/metersphere/assets/50016789/88e05da9-097c-4fb6-b561-02d57509bf20)
![image](https://github.com/metersphere/metersphere/assets/50016789/9b237c38-8da8-430f-a89c-25fbc9d557af)

**Comment by 13290445582** [comment]
感谢反馈，计划下个版本修复该问题。

**Comment by 13290445582** [comment]
您好，非metersphere缺陷，在jmeter中运行同样出错，不处理jmeter内部问题。
![image](https://github.com/metersphere/metersphere/assets/128017892/50d32bf9-220e-41f4-b662-14204fff6545)
