### ISSUE TITLE
[BUG]修改接口定义失败，API Table的保存按钮报错500

### ISSUE THREAD

**Issue by jackieliestener** [metersphere/metersphere#27927]
### 联系方式

dongjunpeng@clincloud.com        交流群55

### MeterSphere 版本

 v2.10.9-lts-1268b1f8

### 使用外置数据库

否

### 问题描述

![image](https://github.com/metersphere/metersphere/assets/85087144/a989a64b-2289-4791-8f55-928370385044)
修改API后，点击保存按钮后未提示保存成功，其他项目未有次现象，可能与导入导入接口与场景有关

### 重现步骤

1. 新建项目，从以前的一个项目copy一份接口定义与自动化场景
2. 原项目在接口定义-API页面修改接口信息
3. 点击保存按钮
4. 
![image](https://github.com/metersphere/metersphere/assets/85087144/0294adeb-ccfa-4cbd-b00f-40353f9be60f)

### 相关日志输出

```shell
日志：
Caused by: java.lang.StackOverflowError: null
        at io.metersphere.commons.utils.JSONUtil.createJsonObject(JSONUtil.java:100)
        at io.metersphere.api.exec.generator.JSONSchemaParser.analyzeProperty(JSONSchemaParser.java:156)
        at io.metersphere.api.exec.generator.JSONSchemaParser.analyzeObject(JSONSchemaParser.java:59)
        at io.metersphere.api.exec.generator.JSONSchemaParser.analyzeProperty(JSONSchemaParser.java:158)
        at io.metersphere.api.exec.generator.JSONSchemaParser.analyzeObject(JSONSchemaParser.java:59)
        at io.metersphere.api.exec.generator.JSONSchemaParser.analyzeProperty(JSONSchemaParser.java:158)
```

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，请描述下具体场景，是不是当时服务不正常，或者是网络 ？这个原项目接口 是必现问题吗？

**Comment by ouyangkui** [comment]
v2.10.9-lts-1268b1f8 我也能复现，就应该是个bug
导入的接口不能保存，没反应
自定义的接口就可以保存。

**Comment by jackieliestener** [comment]
> 你好，没有复现该问题，请描述下具体场景，是不是当时服务不正常，或者是网络 ？这个原项目接口 是必现问题吗？

你好，是编辑导入的接口无法保存，创建新的就可以，如果你不导入接口，就可以正常保存，我是因为某个项目的部分数据需要导入到新的项目，就导致导入原来的数据也无法使用了

**Comment by fit2-zhao** [comment]
从日志来看应该是JSON处理时堆栈溢出了，应该是特殊数据触发的问题，是否方便把数据发一份来我们研究一下。

**Comment by youliyuan-fit2cloud** [comment]
> 从日志来看应该是JSON处理时堆栈溢出了，应该是特殊数据触发的问题，是否方便把数据发一份来我们研究一下。

@ouyangkui @jackieliestener 麻烦二位把导出的api接口发我们看看，非常感谢。

**Comment by ouyangkui** [comment]
[Swagger_Api_SIEM.json](https://github.com/metersphere/metersphere/files/13669545/Swagger_Api_SIEM.json)
我已经找到开发负责人，用我的失败接口复现了，哈哈，

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，下个版本修复该问题。

**Comment by youliyuan-fit2cloud** [comment]
v2.10.10-lts 中已修复。
