### ISSUE TITLE
[BUG]MS和禅道12.5.2 对接，项目id检查验证失败

### ISSUE THREAD

**Issue by x-light-ai** [metersphere/metersphere#27939]
### MeterSphere 版本

v2.10.9-lts-1268b1f8

### 使用外置数据库

否

### 问题描述
服务集成，禅道信息已经”验证通过“，但是项目管理里面，项目信息里输入禅道的项目id,检查报”验证失败“信息
禅道的 apiGetModel 已经配置，超级model调用接口 权限也已经配置

是禅道版本的问题吗？

### 重现步骤

看问题描述

**Comment by youliyuan-fit2cloud** [comment]
![image](https://github.com/metersphere/metersphere/assets/54612864/1c44ccb5-1243-4685-92f6-2c5b0d414e45)

你好，先参考上图查看下zentao的“项目ID”还是“产品ID”，创建的流程不一样，MS里面需要输入的“项目ID”不一样。

**Comment by x-light-ai** [comment]
2个ID都试了，报同样的错误 ”验证失败“

**Comment by youliyuan-fit2cloud** [comment]
后台日志截图贴上来看看

**Comment by x-light-ai** [comment]
2023-12-13 10:33:22,270 [qtp1008164226-50074] ERROR io.metersphere.service.MicroService 177 - Method[handleHttpServerErrorException][{"success":false,"message":"验证失败","data":null}]
org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 Server Error: "{"success":false,"message":"验证失败","data":null}"
	at org.springframework.web.client.HttpServerErrorException.create(HttpServerErrorException.java:102)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:186)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:137)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:915)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:864)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:764)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:646)
	at io.metersphere.service.MicroService.postForResultHolder(MicroService.java:180)
	at io.metersphere.service.MicroService.postForData(MicroService.java:219)
	at io.metersphere.service.MicroService.postForData(MicroService.java:215)
	at io.metersphere.service.RemoteService.post(RemoteService.java:50)
	at io.metersphere.controller.remote.SystemSettingController.list(SystemSettingController.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)

**Comment by youliyuan-fit2cloud** [comment]
你好，感谢反馈，上述日志没有找到具体原因，请检查一下zentao配置
1.zentao 的my.php 文件，添加$config->features->apiGetModel = true;然后重启zentao
![image](https://github.com/metersphere/metersphere/assets/54612864/598c8ac1-cf78-4dd9-bc1d-b95bd1095825)

2.开启超级model调用接口权限
![image](https://github.com/metersphere/metersphere/assets/54612864/eadde352-0f8e-41c7-98df-3865e857b82d)
3.在MeterSphere  ，登录后个人信息-第三方登录账号中添加zentao对应的账号信息
![image](https://github.com/metersphere/metersphere/assets/54612864/b999a696-4461-4a7c-a4e9-3e46c9d78fc0)

如果让存在问题，可以加如下企业微信联系我们远程看看。
![image](https://github.com/metersphere/metersphere/assets/54612864/9e2bf243-41f8-47ee-b337-9e813297e2ea)

**Comment by youliyuan-fit2cloud** [comment]
因长期未反馈，关闭该问题。
