### ISSUE TITLE
[IDEA插件1.2.6最新版本 安装后初始化报错，配置页面出不来]

### ISSUE THREAD

**Issue by ky994226161** [metersphere/metersphere#28128]
### 联系方式

994226161@qq.com

### MeterSphere 版本

v2.10.8

### 使用外置数据库

否

### 问题描述

IDEA插件1.2.6最新版本 安装后初始化报错，配置页面出不来

### 重现步骤

IDEA插件1.2.6最新版本 安装后初始化报错，配置页面出不来

### 期待的正确结果

正常加载展示

### 相关日志输出

```shell
com.intellij.diagnostic.PluginException: Cannot load class org.metersphere.actions.ExportToMSAction (
 error: org/metersphere/actions/ExportToMSAction has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0,
 classLoader=PluginClassLoader(plugin=PluginDescriptor(name=MeterSphere, id=org.metersphere.Metersphere, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2021.3\plugins\metersphere-idea-plugin, version=1.2.6, package=null, isBundled=false), packagePrefix=null, instanceId=32, state=active)
)
at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:407)
at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:256)
at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1443)
at com.intellij.serviceContainer.ComponentManagerImplKt.access$doLoadClass(ComponentManagerImpl.kt:1)
at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:886)
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:204)
```

**Comment by ky994226161** [comment]
![image](https://github.com/metersphere/metersphere/assets/38663557/1526a9f2-28fb-46be-b752-1e19fc7f9acf)

**Comment by zrfit** [comment]
您好，感谢反馈！插件v1.2.6 为了支持最新版本idea 用 的jdk 17 ，建议老版本idea 用插件v1.2.5即可。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
