### ISSUE TITLE
性能测试资源池选择多节点组成的集群，运行时出现错误[BUG]

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#2827]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.1
**Bug 描述**
性能测试场景负载 资源池选择多note节点组成的 集群负载，启动运行一直卡死，

ms服务错误日志
2021-05-14 15:32:08,554 [qtp1789110533-42] ERROR i.m.c.h.RestControllerExceptionHandler 169 - Method[sqlExceptionHandler][Duplicate entry 'ca375193-f9e6-448d-8977-8c0ea0d90b1d-1' for key 'PRIMARY']
java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'ca375193-f9e6-448d-8977-8c0ea0d90b1d-1' for key 'PRIMARY'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)

**Bug 重现步骤**
1.  
2. 
3. 
4. 

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/82088551/118251582-59f48780-b4da-11eb-8f07-1425f0f82687.png)

![image](https://user-images.githubusercontent.com/82088551/118251869-b2c42000-b4da-11eb-90bf-4bea8ab7c80b.png)

![image](https://user-images.githubusercontent.com/82088551/118251944-ca030d80-b4da-11eb-9a21-f26f49485a2c.png)

**Comment by zhangzhaox** [comment]
1.9.2版本存在  本地node节点启动失败的情况，非本地node节点的两个组合启动成功
