### ISSUE TITLE
meterSphere界面创建单个接口和修改或创建环境变量等功能，提示SQL error happened, please check logs.

### ISSUE THREAD

**Issue by mmdudu** [metersphere/metersphere#28306]
### 联系方式

微信15811284096

### MeterSphere 版本

版本:   v2.8.0-ac76fee1

### 使用外置数据库

否

### 问题描述

meterSphere界面创建单个接口和修改或创建环境变量等功能，提示SQL error happened, please check logs.

### 重现步骤

必现
进入系统设置-环境管理，创建或者修改环境时都报SQL error happened, please check logs.
备注：还有接口测试：创建单个接口和场景接口也报错，可能其他功能保存修改的也有此问题
曾经在群里咨询过，按照https://blog.csdn.net/momoringmok/article/details/104904321处理过，进入mysql容器flush-tables
但是操作完后，问题依然存在

### 期待的正确结果

正常保存或修改成功

### 相关日志输出

```shell
2024-01-12 14:08:33,228 [qtp2000824991-19756] ERROR i.m.c.h.RestControllerExceptionHandler ? - Method[sqlExceptionHandler][Table 'api_test_environment' is read only]
java.sql.SQLException: Table 'api_test_environment' is read only
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
        at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
        at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
        at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
        at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
        at jdk.internal.reflect.GeneratedMethodAccessor181.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64)
        at jdk.proxy2/jdk.proxy2.$Proxy287.update(Unknown Source)
        at jdk.internal.reflect.GeneratedMethodAccessor181.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
        at io.metersphere.interceptor.MybatisInterceptor.intercept(MybatisInterceptor.java:39)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
        at jdk.proxy2/jdk.proxy2.$Proxy287.update(Unknown Source)
        at jdk.internal.reflect.GeneratedMethodAccessor181.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64)
        at jdk.proxy2/jdk.proxy2.$Proxy287.update(Unknown Source)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:194)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:425)
        at jdk.proxy2/jdk.proxy2.$Proxy127.update(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:288)
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:67)
        at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:145)
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
        at jdk.proxy2/jdk.proxy2.$Proxy161.updateByPrimaryKeyWithBLOBs(Unknown Source)
        at io.metersphere.environment.service.BaseEnvironmentService.update(BaseEnvironmentService.java:480)
        at jdk.internal.reflect.GeneratedMethodAccessor356.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(Transacti
```

### 附加信息

![16](https://github.com/metersphere/metersphere/assets/156404008/0f54f4ae-ef95-433d-a1a7-1aac189e999f)

**Comment by mmdudu** [comment]
![17](https://github.com/metersphere/metersphere/assets/156404008/fcf65e15-2884-4b1f-ac9e-d64c13f62852)
![19](https://github.com/metersphere/metersphere/assets/156404008/23884af9-5583-4f92-8e8b-f39d35513887)

**Comment by 13290445582** [comment]
最新版本未复现该问题，建议升级至v2.10.10版本尝试。

**Comment by mmdudu** [comment]
升级会导致当前的测试数据丢失吗，升级的方法麻烦给下，如果可以的话是否可以腾讯会议帮看下这个问题呢

**Comment by fit2-zhao** [comment]
升级前做好数据备份，然后在线升级就可以了。
可以参考在线升级文档：
https://metersphere.io/docs/v2.x/installation/online_upgrade/

**Comment by mmdudu** [comment]
由于部署环境为小局域网，不能访问外网，升级是需要访问外网的吧，那这个怎么解决下呢，还有就是目前环境也在报sql问题，备份也需要sql，由于担心数据备份操作错误数据丢失，能否预约一个时间，腾讯会议帮指导下，谢谢

**Comment by mmdudu** [comment]
您好，由于环境已经一个多星期不能用了，能否帮腾讯会议看下呢，谢谢

**Comment by 13290445582** [comment]
外置数据库吗，api_test_environment 这个表怎么只有只读权限。

**Comment by mmdudu** [comment]
不是外置的数据库

**Comment by mmdudu** [comment]
今天您可以进会议帮看下吗 15811284096这是我的电话和微信

**Comment by 13290445582** [comment]
您好，非常抱歉，现在没有多余力量进行远程查看，只能参考我们的官方文档和自己查询报错的配置解决下，这边也没遇到过类似问题，很抱歉没给您提供到更多帮助。
