### ISSUE TITLE
性能测试中创建性能测试导入jmx文件后，配置好资源池后保存并执行，结果未执行，执行时间为0 

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#28407]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.10-lts

### 使用外置数据库

否

### 问题描述

性能测试中创建性能测试导入jmx文件后，配置好资源池后保存并执行，结果未执行，执行时间为0 ，查看后台日志发现是缺少csv 文件

### 重现步骤

性能测试中创建性能测试导入jmx文件后，配置好资源池后保存并执行，结果未执行，执行时间为0 

### 期待的正确结果

有执行错误结果，或者页面上有报错提示

### 相关日志输出

```shell
2024-01-18 14:04:42,400 Setting Locale to en_EN
2024-01-18 14:04:42,451 Loading user properties from: /opt/jmeter/bin/user.properties
2024-01-18 14:04:42,451 Loading system properties from: /opt/jmeter/bin/system.properties
2024-01-18 14:04:42,471 Copyright (c) 1998-2022 The Apache Software Foundation
2024-01-18 14:04:42,471 Version 5.5
2024-01-18 14:04:42,471 java.version=17.0.9
2024-01-18 14:04:42,471 java.vm.name=OpenJDK 64-Bit Server VM
2024-01-18 14:04:42,471 os.name=Linux
2024-01-18 14:04:42,471 os.arch=amd64
2024-01-18 14:04:42,471 os.version=3.10.0-957.el7.x86_64
2024-01-18 14:04:42,472 file.encoding=UTF-8
2024-01-18 14:04:42,472 java.awt.headless=true
2024-01-18 14:04:42,473 Max memory =1073741824
2024-01-18 14:04:42,473 Available Processors =8
2024-01-18 14:04:42,488 Default Locale=English (EN)
2024-01-18 14:04:42,489 JMeter Locale=English (EN)
2024-01-18 14:04:42,489 JMeterHome=/opt/jmeter
2024-01-18 14:04:42,489 user.dir =/jmeter-log
2024-01-18 14:04:42,489 PWD =/jmeter-log
2024-01-18 14:04:42,489 IP: 127.0.0.1 Name: laiyanling FullName: localhost
2024-01-18 14:04:42,490 user.classpath=/test/
2024-01-18 14:04:42,490 Adding to classpath and loader: /test/
2024-01-18 14:04:42,509 Default base='/jmeter-log'
2024-01-18 14:04:42,512 Set new base='/test'
2024-01-18 14:04:42,869 Testplan (JMX) version: 2.2. Testlog (JTL) version: 2.2
2024-01-18 14:04:42,915 Using SaveService properties version 5.0
2024-01-18 14:04:42,933 Using SaveService properties file encoding UTF-8
2024-01-18 14:04:42,943 Loading file: /test/6ea48a36-08ea-4d35-adab-335911d8db79.jmx
2024-01-18 14:04:43,026 Parser for text/html is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2024-01-18 14:04:43,026 Parser for application/xhtml+xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2024-01-18 14:04:43,026 Parser for application/xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2024-01-18 14:04:43,026 Parser for text/vnd.wap.wml is org.apache.jmeter.protocol.http.parser.RegexpHTMLParser
2024-01-18 14:04:43,026 Parser for text/xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2024-01-18 14:04:43,026 Parser for text/css is org.apache.jmeter.protocol.http.parser.CssParser
2024-01-18 14:04:43,098 Settings: Delete null: true Check: true Allow variable: true Save: true Prefix: COOKIE_
2024-01-18 14:04:43,116 Creating summariser <summary>
2024-01-18 14:04:43,133 Running the test!
2024-01-18 14:04:43,137 List of sample_variables: []
2024-01-18 14:04:43,137 List of sample_variables: []
2024-01-18 14:04:43,143 Note: Function class names must contain the string: '.functions.'
2024-01-18 14:04:43,144 Note: Function class names must not contain the string: '.gui.'
2024-01-18 14:04:43,267 Running test (1705557883267)
2024-01-18 14:04:43,296 Starting ThreadGroup: 1 : 线程组-0
2024-01-18 14:04:43,296 Starting 1 threads for group 线程组-0.
2024-01-18 14:04:43,296 Thread will start next loop on error
2024-01-18 14:04:43,297 Starting thread group... number=1 threads=1 ramp-up=5 delayedStart=false
2024-01-18 14:04:43,304 Started thread group number 1
2024-01-18 14:04:43,304 All thread groups have been started
2024-01-18 14:04:43,342 Thread started: 线程组-0 1-1
2024-01-18 14:04:43,344 Stored: /test/1-17token-devid - 副本 (2).csv
2024-01-18 14:04:43,345 Test failed! java.lang.IllegalArgumentException: File 1-17token-devid - 副本 (2).csv must exist and be readable
at org.apache.jmeter.services.FileServer.createBufferedReader(FileServer.java:418) ~[ms-jmeter-core.jar:?]
at org.apache.jmeter.services.FileServer.readLine(FileServer.java:334) ~[ms-jmeter-core.jar:?]
at org.apache.jmeter.config.CSVDataSet.iterationStart(CSVDataSet.java:185) ~[ms-jmeter-core.jar:5.5]
at org.apache.jmeter.control.GenericController.fireIterationStart(GenericController.java:399) ~[ApacheJMeter_core.jar:5.5]
at org.apache.jmeter.control.GenericController.fireIterEvents(GenericController.java:391) ~[ApacheJMeter_core.jar:5.5]
at org.apache.jmeter.control.GenericController.next(GenericController.java:160) ~[ApacheJMeter_core.jar:5.5]
at org.apache.jmeter.control.LoopController.next(LoopController.java:134) ~[ApacheJMeter_core.jar:5.5]
at org.apache.jmeter.threads.AbstractThreadGroup.next(AbstractThreadGroup.java:99) ~[ApacheJMeter_core.jar:5.5]
at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:262) ~[ms-jmeter-core.jar:5.5]
at java.lang.Thread.run(Thread.java:840) ~[?:?]
2024-01-18 14:04:43,356 Thread finished: 线程组-0 1-1
2024-01-18 14:04:43,356 Notifying test listeners of end of test
2024-01-18 14:04:43,357 Load test ended
2024-01-18 14:04:43,361 summary + 0 in 00:00:00 = ******/s Avg: 0 Min: 9223372036854775807 Max: -9223372036854775808 Err: 0 (0.00%) Active: 0 Started: 1 Finished: 1
2024-01-18 14:04:43,361 summary = 0 in 00:00:00 = ******/s Avg: 0 Min: 9223372036854775807 Max: -9223372036854775808 Err: 0 (0.00%)
2024-01-18 14:04:43,507 kafka bootstrap server: {10.1.11.23:9092}
```

### 附加信息

<img width="956" alt="a4eb48832e73c2c205c7ed43a2ed118" src="https://github.com/metersphere/metersphere/assets/50016789/754c57a9-9bc2-4c36-96e2-10c2b97cdbd3">

**Comment by liuruibin** [comment]
csv没有上传 ，我们会在后续版本中增加提示

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
