### ISSUE TITLE
[BUG]测试计划关联某个接口场景用例后，配置运行环境A，然后测试计划用例一直runing

### ISSUE THREAD

**Issue by 157571062297** [metersphere/metersphere#28491]
### 联系方式

1849828250@qq.com

### MeterSphere 版本

版本:   v2.10.10-lts-e9b6aa9e

### 使用外置数据库

否

### 问题描述

接口场景绑定运行环境A，调试的时候正常，加到测试计划中执行后，测试计划就一直runing
测试计划切换到其他运行环境B，就可以运行成功

### 重现步骤

前提：接口测试场景绑定运行环境A
1.测试计划新增关联接口测试场景
2.测试计划配置默认运行环境A
3.测试计划执行

### 期待的正确结果

运行成功

### 相关日志输出

```shell
，判断订单状态=10】 入库存储]
2024-01-23 16:19:02,179 MS-KAFKA-LISTENER-TASK：9 INFO  ms-jmeter-run-log ? - Method[getApiScenarioReportResult][报告ID [ 96709dab-1416-4390-942c-6807afcf796b ] 执行请求：【 后台登录】 入库存储]
2024-01-23 16:19:02,179 MS-KAFKA-LISTENER-TASK：9 INFO  ms-jmeter-run-log ? - Method[getApiScenarioReportResult][报告ID [ 96709dab-1416-4390-942c-6807afcf796b ] 执行请求：【 查询订单金额，校验金额正确性】 入库存储]
2024-01-23 16:19:02,279 MS-KAFKA-LISTENER-TASK：9 ERROR ms-jmeter-run-log ? - Method[run][REPORT-ID: 96709dab-1416-4390-942c-6807afcf796b] KAFKA监听消费失败
```

### 附加信息

![Uploading b690c415ed713402a5e90002ce354ba.png…]()
![Uploading c1d2e663b396ee1985484cd26f86e75.png…]()

**Comment by 13290445582** [comment]
您好，您的附加信息图片未上传成功，请重新贴一下图片，请提供下后端日志。其他用户有遇到过类似running问题，您可先参考其他issue中排查的思路以及解决问题的办法修改下，看下可以解决吗？点击issue链接跳转https://github.com/metersphere/metersphere/issues/24993

**Comment by 157571062297** [comment]
### Error flushing statements.  Cause: org.apache.ibatis.executor.BatchExecutorException: io.metersphere.base.mapper.ApiScenarioReportResultMapper.insert (batch index #1) failed. Cause: java.sql.BatchUpdateException: Data truncation: Data too long for column 'resource_id' at row 1
### Cause: org.apache.ibatis.executor.BatchExecutorException: io.metersphere.base.mapper.ApiScenarioReportResultMapper.insert (batch index #1) failed. Cause: java.sql.BatchUpdateException: Data truncation: Data too long for column 'resource_id' at row 1
        at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.flushStatements(DefaultSqlSession.java:254)
        at io.metersphere.service.scenario.ApiScenarioReportResultService.batchSave(ApiScenarioReportResultService.java:91)
        at jdk.internal.reflect.GeneratedMethodAccessor624.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:352)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:385)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717)
        at io.metersphere.service.scenario.ApiScenarioReportResultService$$SpringCGLIB$$0.batchSave(<generated>)
        at jdk.internal.reflect.GeneratedMethodAccessor624.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:352)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:385)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717)
        at io.metersphere.service.scenario.ApiScenarioReportResultService$$SpringCGLIB$$1.batchSave(<generated>)
        at io.metersphere.service.scenario.ApiScenarioReportService.batchSaveResult(ApiScenarioReportService.java:99)
        at jdk.internal.reflect.GeneratedMethodAccessor623.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:352)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:385)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717)
        at io.metersphere.service.scenario.ApiScenarioReportService$$SpringCGLIB$$0.batchSaveResult(<generated>)
        at jdk.internal.reflect.GeneratedMethodAccessor623.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:352)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:385)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717)
        at io.metersphere.service.scenario.ApiScenarioReportService$$SpringCGLIB$$1.batchSaveResult(<generated>)
        at io.metersphere.service.TestResultService.batchSaveResults(TestResultService.java:116)
        at io.metersphere.api.jmeter.KafkaListenerTask.run(KafkaListenerTask.java:73)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.ibatis.executor.BatchExecutorException: io.metersphere.base.mapper.ApiScenarioReportResultMapper.insert (batch index #1) failed. Cause: java.sql.BatchUpdateException: Data truncation: Data too long for column 'resource_id' at row 1
        at org.apache.ibatis.executor.BatchExecutor.doFlushStatements(BatchExecutor.java:148)
        at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:129)
        at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:122)
        at org.apache.ibatis.executor.CachingExecutor.flushStatements(CachingExecutor.java:115)
        at jdk.internal.reflect.GeneratedMethodAccessor504.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
        at jdk.proxy2/jdk.proxy2.$Proxy349.flushStatements(Unknown Source)
        at jdk.internal.reflect.GeneratedMethodAccessor504.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
        at jdk.proxy2/jdk.proxy2.$Proxy349.flushStatements(Unknown Source)
        at jdk.internal.reflect.GeneratedMethodAccessor504.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
        at jdk.proxy2/jdk.proxy2.$Proxy349.flushStatements(Unknown Source)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.flushStatements(DefaultSqlSession.java:252)
        ... 63 common frames omitted
Caused by: java.sql.BatchUpdateException: Data truncation: Data too long for column 'resource_id' at row 1
        at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:816)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:418)
        at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:795)
        at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
        at org.apache.ibatis.executor.BatchExecutor.doFlushStatements(BatchExecutor.java:126)
        ... 82 common frames omitted
Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'resource_id' at row 1
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)

**Comment by 157571062297** [comment]
我排查了 具体的报错信息，这是api-test的相关日志

**Comment by 13290445582** [comment]
您好，查看了您的日志信息，发现与2.10.11修复的一个issue日志相同，请升级v2.10.11尝试是否还有此报错，附相关issue链接。https://github.com/metersphere/metersphere/issues/28340

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
