### ISSUE TITLE
[BUG] 500 Server Error for HTTP GET "/is-login" java.lang.IllegalArgumentException: Source must not be null

### ISSUE THREAD

**Issue by Dannyshcn** [metersphere/metersphere#28508]
### MeterSphere 版本

版本:   v2.10.10-lts-e9b6aa9e

### 使用外置数据库

否

### 问题描述

集成LDAP（linux  open-ldap），测试ldap成功，用户测试成功。
页面使用ldap用户登录时报错。

### 重现步骤

集成LDAP（linux  open-ldap），测试ldap成功，用户测试成功。
页面使用ldap用户登录时报错。

### 相关日志输出

2024-01-25 13:52:02,512 ERROR e.error.AbstractErrorWebExceptionHandler: 102 - [6ad65d7e-15435]  500 Server Error for HTTP GET "/is-login"
java.lang.IllegalArgumentException: Source must not be null
        at org.springframework.util.Assert.notNull(Assert.java:172)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
        *__checkpoint ⇢ org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ io.metersphere.gateway.filter.SessionFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ io.metersphere.gateway.filter.SwaggerFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ io.metersphere.gateway.filter.LoginFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ HTTP GET "/is-login" [ExceptionHandlingWebHandler]
Original Stack Trace:
                at org.springframework.util.Assert.notNull(Assert.java:172)
                at org.springframework.beans.BeanUtils.copyProperties(BeanUtils.java:778)
                at org.springframework.beans.BeanUtils.copyProperties(BeanUtils.java:715)
                at io.metersphere.commons.user.SessionUser.fromUser(SessionUser.java:31)
                at io.metersphere.gateway.controller.LoginController.isLogin(LoginController.java:67)
                at jdk.internal.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:568)
                at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:352)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
                at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
                at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
                at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
                at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717)
                at io.metersphere.gateway.controller.LoginController$$SpringCGLIB$$0.isLogin(<generated>)
                at jdk.internal.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:568)
                at org.springframework.web.reactive.result.method.InvocableHandlerMethod.lambda$invoke$1(InvocableHandlerMethod.java:183)
                at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
                at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:297)
                at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:478)
                at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
                at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:122)
                at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
                at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2571)
                at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2367)
                at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2241)
                at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:193)
                at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:63)
                at reactor.core.publisher.MonoZip$ZipCoordinator.request(MonoZip.java:220)
                at reactor.core.publisher.MonoFlatMap$FlatMapMain.request(MonoFlatMap.java:194)
                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onSubscribe(MonoIgnoreThen.java:135)
                at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:117)
                at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:129)
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76)
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:241)
                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:204)
                at reactor.core.publisher.MonoFlatMap$FlatMapMain.onComplete(MonoFlatMap.java:189)
                at reactor.core.publisher.Operators.complete(Operators.java:137)
                at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:121)
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76)
                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:264)
                at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76)
                at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:165)
                at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
                at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
                at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
                at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.innerNext(FluxConcatMapNoPrefetch.java:258)
                at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:863)
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
                at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
                at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2571)
                at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:139)
                at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171)
                at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.request(Operators.java:2331)
                at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.request(FluxConcatMapNoPrefetch.java:338)
                at reactor.core.publisher.MonoNext$NextSubscriber.request(MonoNext.java:108)
                at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2367)
                at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2241)
                at reactor.core.publisher.MonoNext$NextSubscriber.onSubscribe(MonoNext.java:70)
                at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onSubscribe(FluxConcatMapNoPrefetch.java:164)
                at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:201)
                at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:83)
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76)
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76)
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76)
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76)
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76)
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76)
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76)
                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:264)
                at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76)
                at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55)
                at reactor.netty.http.server.HttpServer$HttpServerHandle.onStateChange(HttpServer.java:1169)
                at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:710)
                at reactor.netty.transport.ServerTransport$ChildObserver.onStateChange(ServerTransport.java:481)
                at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:652)
                at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
                at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:238)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
                at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
                at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
                at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
                at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
                at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
                at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:840)

### 附加信息

<img width="529" alt="image" src="https://github.com/metersphere/metersphere/assets/36431593/622da6e1-5661-44c7-b069-a171d3a2eba8">

<img width="450" alt="image" src="https://github.com/metersphere/metersphere/assets/36431593/c1067fc7-38d8-4571-ba63-d3c132159f31">

**Comment by 13290445582** [comment]
您好，本地环境未复现该问题，未看出问题所在，请尝试重启ldap环境，或者切换账号登录，后续我们将注意该登录问题，感谢理理解。

**Comment by Dannyshcn** [comment]
找到问题了，是ldap中 cn 的名字前面有个空格， 到metersphere中用户名前面没有空格。就出现着个妖怪问题。多谢支持！
