### ISSUE TITLE
[BUG]接口测试中Mock的后置脚本无法加载上传的第三方jar包

### ISSUE THREAD

**Issue by myfix** [metersphere/metersphere#28539]
### 联系方式

微信 MeterSphere 交流群62中@fox

### MeterSphere 版本

v2.10.11

### 使用外置数据库

否

### 问题描述

接口测试中，新增接口后再新增一个Mock，Mock中新增一个后置脚本，脚本编写时使用上传的第三方jar，抛异常无法引用，错误见下方日志
PS：
1.v2.10.0发现的问题，升级到最新版本仍有问题
2.第三方jar包的引用，在用例中的前置和后置脚本都是正常使用的，只有mock无法使用

### 重现步骤

前置：
第三方jar正常上传并已经激活使用。

1.进入到接口测试，新增一个接口，并新增一个mock
2.mock中点击后置脚本，编写beanshell代码
3.引用第三方jar包，比如本次加载使用gson
4.运行时抛找不到引用包的异常，见下方日志

### 期待的正确结果

Mock中可以正常引用第三方jar包

### 相关日志输出

```shell
2024-01-26 13:02:37,130 [qtp914496027-55] ERROR i.m.c.u.mock.MockScriptEngineUtils ? - Method[runScript][javax.script.ScriptException: Sourced file: inline evaluation of: ``import com.google.gson.Gson; import com.google.gson.GsonBuilder; import com.goog . . . '' : Attempt to resolve method: info() on undefined variable or class name: log : at Line: 13 : in file: inline evaluation of: ``import com.google.gson.Gson; import com.google.gson.GsonBuilder; import com.goog . . . '' : log .info ( stockId )
 in inline evaluation of: ``import com.google.gson.Gson; import com.google.gson.GsonBuilder; import com.goog . . . '' at line number 13]
javax.script.ScriptException: Sourced file: inline evaluation of: ``import com.google.gson.Gson; import com.google.gson.GsonBuilder; import com.goog . . . '' : Attempt to resolve method: info() on undefined variable or class name: log : at Line: 13 : in file: inline evaluation of: ``import com.google.gson.Gson; import com.google.gson.GsonBuilder; import com.goog . . . '' : log .info ( stockId )
 in inline evaluation of: ``import com.google.gson.Gson; import com.google.gson.GsonBuilder; import com.goog . . . '' at line number 13
        at bsh.engine.BshScriptEngine.evalSource(BshScriptEngine.java:93)
        at bsh.engine.BshScriptEngine.eval(BshScriptEngine.java:46)
        at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262)
        at io.metersphere.commons.utils.mock.MockScriptEngineUtils.runScript(MockScriptEngineUtils.java:42)
        at io.metersphere.commons.utils.mock.MockApiUtils.getResultByResponseResult(MockApiUtils.java:287)
        at io.metersphere.service.MockConfigService.updateHttpServletResponse(MockConfigService.java:580)
        at io.metersphere.service.MockConfigService.checkReturnWithMockExpectByUrlParam(MockConfigService.java:904)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Comment by 13290445582** [comment]
您好，当前版本的mock后置脚本是一个比较纯净的运行开发环境，跟前后置脚本不一样（前后置脚本里内置了部分默认jar包）。 所以暂不能做到类似于前后置脚本那样方便。 后续版本的优化方式也在讨论中。已规划在v3.0版本，附相关issue链接https://github.com/metersphere/metersphere/issues/27237

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
