### ISSUE TITLE
[BUG]node-controllor启动报错

### ISSUE THREAD

**Issue by foven** [metersphere/metersphere#28624]
### 联系方式

微信交流群 59 foven

### MeterSphere 版本

v2.10.10-lts-e9b6aa9e

### 使用外置数据库

否

### 问题描述

node-controllor启动后一直提示unhealthy。接口测试调试提示"调用资源池执行失败，请检查资源池是否配置正常"。
<img width="547" alt="17dfb9d9b47e76370f7ff1f9ddc35d8" src="https://github.com/metersphere/metersphere/assets/5477686/3d1ce9a4-560b-46f2-b59a-6232d96203c3">
controllor日志报错如下。
<img width="531" alt="8390a96e47e12186cf52c091ac2e60b" src="https://github.com/metersphere/metersphere/assets/5477686/f830ec2e-413d-4844-b85f-b45eaffd7782">
没有使用任何插件，jar包

### 重现步骤

接口 调试点击测试

### 期待的正确结果

正常调用接口

### 相关日志输出

2024-01-30 15:14:10,013 [main] INFO  io.metersphere.Application ? - Starting Application using Java 17.0.9 with PID 12 (/app started by appuser in /deployments)
2024-01-30 15:14:10,019 [main] INFO  io.metersphere.Application ? - No active profile set, falling back to 1 default profile: "default"
2024-01-30 15:14:13,010 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate 139 - Bootstrapping Spring Data LDAP repositories in DEFAULT mode.
2024-01-30 15:14:13,044 [main] INFO  o.s.d.r.c.RepositoryConfigurationDelegate 208 - Finished Spring Data repository scanning in 27 ms. Found 0 LDAP repository interfaces.
2024-01-30 15:14:15,627 [main] INFO  o.s.b.w.e.j.JettyServletWebServerFactory 184 - Server initialized with port: 8082
2024-01-30 15:14:15,634 [main] INFO  org.eclipse.jetty.server.Server 534 - jetty-12.0.3; built: 2023-10-27T03:25:22.284Z; git: a873259fd5af141dedaa6c7fa8fe8fbdedce0d61; jvm 17.0.9+8-alpine-r0
2024-01-30 15:14:15,733 [main] INFO  o.e.j.s.h.ContextHandler.application 2860 - Initializing Spring embedded WebApplicationContext
2024-01-30 15:14:15,734 [main] INFO  o.s.b.w.s.c.ServletWebServerApplicationContext 296 - Root WebApplicationContext: initialization completed in 4572 ms
2024-01-30 15:14:16,649 [main] INFO  o.e.j.s.DefaultSessionIdManager 328 - Session workerName=node0
2024-01-30 15:14:16,675 [main] INFO  o.e.j.server.handler.ContextHandler 660 - Started osbwej.JettyEmbeddedWebAppContext@418d1c03{application,/,b=file:/tmp/jetty-docbase.8082.10857898484357126200/,a=AVAILABLE,h=oeje10s.SessionHandler@395197cb{STARTED}}
2024-01-30 15:14:16,675 [main] INFO  o.e.j.e.s.ServletContextHandler 1045 - Started osbwej.JettyEmbeddedWebAppContext@418d1c03{application,/,b=file:/tmp/jetty-docbase.8082.10857898484357126200/,a=AVAILABLE,h=oeje10s.SessionHandler@395197cb{STARTED}}
2024-01-30 15:14:16,678 [main] INFO  org.eclipse.jetty.server.Server 591 - Started oejs.Server@1dbc607d{STARTING}[12.0.3,sto=0] @8872ms
2024-01-30 15:14:17,560 [main] INFO  JMETER ? - JMETER-LOG 2024-01-30 15:14:17 INFO main Setting Locale to en_US

2024-01-30 15:14:20,708 [main] INFO  o.s.b.a.e.web.EndpointLinksResolver 58 - Exposing 1 endpoint(s) beneath base path '/actuator'
2024-01-30 15:14:20,865 [main] INFO  o.e.j.s.h.ContextHandler.application ? - Initializing Spring DispatcherServlet 'dispatcherServlet'
2024-01-30 15:14:20,869 [main] INFO  o.s.web.servlet.DispatcherServlet 532 - Initializing Servlet 'dispatcherServlet'
2024-01-30 15:14:20,871 [main] INFO  o.s.web.servlet.DispatcherServlet 554 - Completed initialization in 1 ms
2024-01-30 15:14:20,970 [main] INFO  o.e.jetty.server.AbstractConnector 321 - Started ServerConnector@3b60be3{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2024-01-30 15:14:20,981 [main] INFO  o.s.b.w.e.jetty.JettyWebServer 168 - Jetty started on port 8082 (http/1.1) with context path '/'
2024-01-30 15:14:21,001 [main] INFO  io.metersphere.Application ? - Started Application in 11.64 seconds (process running for 13.196)
2024-01-30 15:14:22,404 [main] ERROR o.s.boot.SpringApplication 855 - Application run failed
java.lang.NullPointerException: Cannot read the array length because "fa" is null
        at io.metersphere.utils.JarConfigUtils.getFileNames(JarConfigUtils.java:97)
        at io.metersphere.jmeter.ProjectClassLoader.initClassLoader(ProjectClassLoader.java:51)
        at io.metersphere.config.AppStartListener.onApplicationEvent(ra:181)
        at io.metersphere.config.AppStartListener.onApplicationEvent(ra:417)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:149)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:451)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:384)
        at org.springframework.boot.context.event.EventPublishingRunListener.ready(EventPublishingRunListener.java:109)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$ready$6(SpringApplicationRunListeners.java:80)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
        at org.springframework.boot.SpringApplicationRunListeners.ready(SpringApplicationRunListeners.java:80)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:352)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1358)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1347)
        at io.metersphere.Application.main(Application.java:35)
2024-01-30 15:14:22,442 [main] INFO  o.e.jetty.server.AbstractConnector 376 - Stopped ServerConnector@3b60be3{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2024-01-30 15:14:22,451 [main] INFO  org.eclipse.jetty.server.Server ? - Stopped oejs.Server@1dbc607d{STOPPING}[12.0.3,sto=0]
2024-01-30 15:14:22,462 [main] INFO  o.e.j.s.h.ContextHandler.application 2860 - Destroying Spring FrameworkServlet 'dispatcherServlet'
2024-01-30 15:14:22,464 [main] INFO  o.e.j.e.s.ServletContextHandler 1107 - Stopped osbwej.JettyEmbeddedWebAppContext@418d1c03{application,/,b=file:/tmp/jetty-docbase.8082.10857898484357126200/,a=AVAILABLE,h=oeje10s.SessionHandler@395197cb{STOPPED}}

**Comment by fit2-zhao** [comment]
检查一下 /opt/metersphere/data/body/plugin/ 和  /opt/metersphere/data/body/local-file 文件夹是否创建出来了，再检查一下文件夹的权限是什么，尝试一下：`chmod -R 777 文件夹名称`；然后重启服务试试。

**Comment by foven** [comment]
> 检查一下 /opt/metersphere/data/body/plugin/ 和 /opt/metersphere/data/body/local-file 文件夹是否创建出来了，再检查一下文件夹的权限是什么，尝试一下：`chmod -R 777 文件夹名称`；然后重启服务试试。

![image](https://github.com/metersphere/metersphere/assets/5477686/2389ceed-cd6f-42e9-b8e5-3f447f7076d6)
没有创建，这个需要人工创建吗？

**Comment by foven** [comment]
![image](https://github.com/metersphere/metersphere/assets/5477686/00f0289f-9e95-45d7-8bba-ec872ffc8904)

**Comment by youliyuan-fit2cloud** [comment]
> > 检查一下 /opt/metersphere/data/body/plugin/ 和 /opt/metersphere/data/body/local-file 文件夹是否创建出来了，再检查一下文件夹的权限是什么，尝试一下：`chmod -R 777 文件夹名称`；然后重启服务试试。
> 
> ![image](https://private-user-images.githubusercontent.com/5477686/301057231-2389ceed-cd6f-42e9-b8e5-3f447f7076d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNjAxMDYsIm5iZiI6MTcwOTI1OTgwNiwicGF0aCI6Ii81NDc3Njg2LzMwMTA1NzIzMS0yMzg5Y2VlZC1jZDZmLTQyZTktYjhlNS0zZjQ0N2Y3MDc2ZDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDFUMDIyMzI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGEzMTJiZjQ1NTVlZWE1ODIyYjA5MjI0OTYyMTUzODk4MDZhZjhiNTY1ODcxYTg2Y2EwMzU5ZDk0YzQ5MWVhNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pW99w8qILxlmUDWm1gswDLmLL_yBdPF6EUDS92vu1bQ) 没有创建，这个需要人工创建吗？

你好，如果没有，手动创建下。

**Comment by zhangzhaox** [comment]
@youliyuan-fit2cloud 按照要求操作 新增了目录和调整了权限
依旧启动报错，错误信息如下
2024-04-07 22:19:25,633 [main] INFO  o.s.web.servlet.DispatcherServlet 532 - Initializing Servlet 'dispatcherServlet'
2024-04-07 22:19:25,634 [main] INFO  o.s.web.servlet.DispatcherServlet 554 - Completed initialization in 1 ms
2024-04-07 22:19:25,651 [main] INFO  o.e.jetty.server.AbstractConnector 326 - Started ServerConnector@733e3c19{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2024-04-07 22:19:25,652 [main] INFO  o.s.b.w.e.jetty.JettyWebServer 168 - Jetty started on port 8082 (http/1.1) with context path '/'
2024-04-07 22:19:25,673 [main] INFO  io.metersphere.Application ? - Started Application in 5.315 seconds (process running for 6.434)
2024-04-07 22:19:26,219 [main] ERROR o.s.boot.SpringApplication 851 - Application run failed
java.lang.NullPointerException: Cannot read the array length because "fa" is null
        at io.metersphere.utils.JarConfigUtils.getFileNames(JarConfigUtils.java:97)
        at io.metersphere.jmeter.ProjectClassLoader.initClassLoader(ProjectClassLoader.java:51)
        at io.metersphere.config.AppStartListener.onApplicationEvent(da:229)
        at io.metersphere.config.AppStartListener.onApplicationEvent(da:604)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:451)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:384)
        at org.springframework.boot.context.event.EventPublishingRunListener.ready(EventPublishingRunListener.java:109)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$ready$6(SpringApplicationRunListeners.java:80)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
        at org.springframework.boot.SpringApplicationRunListeners.ready(SpringApplicationRunListeners.java:80)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:348)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
        at io.metersphere.Application.main(Application.java:30)
2024-04-07 22:19:26,229 [main] INFO  o.e.jetty.server.AbstractConnector ? - Stopped ServerConnector@733e3c19{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2024-04-07 22:19:26,234 [main] INFO  org.eclipse.jetty.server.Server ? - Stopped oejs.Server@2ef913a4{STOPPING}[12.0.7,sto=0]
2024-04-07 22:19:26,238 [main] INFO  o.e.j.s.h.ContextHandler.application ? - Destroying Spring FrameworkServlet 'dispatcherServlet'
2024-04-07 22:19:26,239 [main] INFO  o.e.j.e.s.ServletContextHandler ? - Stopped osbwej.JettyEmbeddedWebAppContext@71d0b8a4{application,/,b=file:/tmp/jetty-docbase.8082.5052440440634664544/,a=AVAILABLE,h=oeje10s.SessionHandler@6d6712b7{STOPPED}}

**Comment by zhangzhaox** [comment]
![d8ba0dcb0fdc6ea29e1ccca3653d442](https://github.com/metersphere/metersphere/assets/82088551/ede3f995-1c3a-4763-8a69-379a177b6e30)
正确的解决方式是 注释调这三行
