### ISSUE TITLE
[BUG] 接口前置脚本执行报错，Jmeter 执行不报错

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#28751]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.11-lts-89acace0

### 使用外置数据库

否

### 问题描述

1. 创建接口，添加前置脚本，load("https://cdn.bootcdn.net/ajax/libs/crypto-js/4.0.0/crypto-js.min.js");
2. 调试后接口报错
3. 但是单独在Jmeter 中执行可以成功

### 重现步骤

1. 创建接口，添加前置脚本，load("https://cdn.bootcdn.net/ajax/libs/crypto-js/4.0.0/crypto-js.min.js");
2. 调试后接口报错

### 期待的正确结果

希望可以调试成功

### 相关日志输出

```shell
2024-02-02 16:50:05 INFO 8a9b7787 1-1 Thread started: 8a9b7787 1-1
2024-02-02 16:50:05 ERROR 8a9b7787 1-1 Problem in JSR223 script, JSR223PreProcessor
ReferenceError: "load" is not defined. (eval#1) in eval at line number 1 at column number 0
javax.script.ScriptException
   at org.mozilla.javascript.engine.RhinoScriptEngine.eval(RhinoScriptEngine.java:122)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:231)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:237)
   at org.apache.jmeter.modifiers.JSR223PreProcessor.process(JSR223PreProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:1001)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:562)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:502)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:265)
   at java.base/java.lang.Thread.run(Thread.java:840)
```

### 附加信息

<img width="802" alt="1706863820854" src="https://github.com/metersphere/metersphere/assets/50016789/ad375a21-25ff-4edc-b9bf-420b12d08a2a">

**Comment by liuruibin** [comment]
我们在这个版本中使用的是rhino engine， load写法不一样你按照下面的方式再试试

```
g = new Packages.org.mozilla.javascript.tools.shell.Global(Packages.org.mozilla.javascript.Context.getCurrentContext());
this.load = g.load;
load("你的js");
```

**Comment by spritelyl** [comment]
已解决
