### ISSUE TITLE
[BUG]无法启动系统默认创建的本地资源池

### ISSUE THREAD

**Issue by pneo** [metersphere/metersphere#2897]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.9.2
**Bug 描述**
简要描述您碰到的问题
使用网络脚本全新安装1.9.2, 安装过程无异常, 无法启动系统默认创建的本地资源池
**Bug 重现步骤**
/opt/metersphere/logs/metersphere/errr.log
[qtp713656449-41] ERROR i.m.service.NodeResourcePoolService ? - Method[validateNode][503 Service Unavailable: [no body]]
org.springframework.web.client.HttpServerErrorException$ServiceUnavailable: 503 Service Unavailable: [no body]
        at org.springframework.web.client.HttpServerErrorException.create(HttpServerErrorException.java:112)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:172)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:112)
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:782)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:740)

**期待的正确结果**
正确情况下应该是什么样的？
启动正常
**截图**
如果有截图，请附上截图.

![屏幕截图 2021-05-18 102121](https://user-images.githubusercontent.com/12944903/118580695-ea74e580-b7c2-11eb-8e35-55dfeb5312ca.jpg)

**Comment by xulinde** [comment]
有往资源池添加过其他节点吗
