### ISSUE TITLE
[BUG] IDEA同步的时候，出现报错：No java api was found! please change your search root

### ISSUE THREAD

**Issue by tangyin9593** [metersphere/metersphere#29135]
### 联系方式

18221797082

### MeterSphere 版本

v2.10.11-lts-a580bd0a

### 使用外置数据库

否

### 问题描述

IDEA同步的时候，出现报错：No java api was found! please change your search root

### 重现步骤

idea已经连上了MeterSphere。 但是在export的时候， 报错失败。

### 期待的正确结果

能正常同步到平台

### 相关日志输出

```shell
<img width="1472" alt="image" src="https://github.com/metersphere/metersphere/assets/19159788/abbb4caf-3cfd-4108-95fc-091de931de41">
```

**Comment by tangyin9593** [comment]
Export MeterSphere API failed !

java.lang.RuntimeException: No java api was found! please change your search root
	at org.metersphere.exporter.MeterSphereExporter.export(MeterSphereExporter.java:56)
	at org.metersphere.exporter.ExporterFactory.export(ExporterFactory.java:50)
	at org.metersphere.actions.CommonAction.lambda$export$0(CommonAction.java:34)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at org.metersphere.actions.CommonAction.lambda$export$1(CommonAction.java:32)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:287)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:518)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:84)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:86)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:81)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:464)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by 13290445582** [comment]
您好，请问使用的哪个版本的idea插件，最新的idea插件未复现该问题。

**Comment by tangyin9593** [comment]
您好， 用的最新的idea插件。
￼

**Comment by youliyuan-fit2cloud** [comment]
你好，可能原因是 Export MeterSphere时选中的目录或类文件下没有api接口，建议重新选择目录和文件尝试下。

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
