### ISSUE TITLE
[BUG]正常的单接口测试，jmeter测试的响应时间是90秒正常返回，metersphere直接返回Read timed out异常

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#2917]
**MeterSphere 版本**
1.9.2

**Bug 描述**
简要描述您碰到的问题
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)

![image](https://user-images.githubusercontent.com/82088551/118602308-12754080-b7e5-11eb-9707-27dfbda79478.png)

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by zyyfit** [comment]
您好，MeterSphere有设置默认超时时间，您可以修改一下接口超时时间再看看

**Comment by zhangzhaox** [comment]
![image](https://user-images.githubusercontent.com/82088551/118910934-e62e0100-b957-11eb-858e-9684047bc76c.png)
感谢，找到了配置 地方
