### ISSUE TITLE
[BUG]v2.1.12-lts node启动失败，详细日志如下

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#29416]
### MeterSphere 版本

v2.1.12-lts node

### 使用外置数据库

是

### 问题描述

2024-03-05 18:33:00,893 [main] INFO  o.s.b.a.e.web.EndpointLinksResolver 58 - Exposing 1 endpoint(s) beneath base path '/actuator'
2024-03-05 18:33:01,020 [main] INFO  o.e.j.s.h.ContextHandler.application ? - Initializing Spring DispatcherServlet 'dispatcherServlet'
2024-03-05 18:33:01,023 [main] INFO  o.s.web.servlet.DispatcherServlet ? - Initializing Servlet 'dispatcherServlet'
2024-03-05 18:33:01,026 [main] INFO  o.s.web.servlet.DispatcherServlet 554 - Completed initialization in 1 ms
2024-03-05 18:33:01,086 [main] INFO  o.e.jetty.server.AbstractConnector ? - Started ServerConnector@61c644fe{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2024-03-05 18:33:01,088 [main] INFO  o.s.b.w.e.jetty.JettyWebServer ? - Jetty started on port 8082 (http/1.1) with context path '/'
2024-03-05 18:33:01,129 [main] INFO  io.metersphere.Application ? - Started Application in 8.964 seconds (process running for 10.243)
2024-03-05 18:33:02,151 [main] ERROR o.s.boot.SpringApplication ? - Application run failed
java.lang.NullPointerException: Cannot read the array length because "fa" is null
        at io.metersphere.utils.JarConfigUtils.getFileNames(JarConfigUtils.java:97)
        at io.metersphere.jmeter.ProjectClassLoader.initClassLoader(ProjectClassLoader.java:51)
        at io.metersphere.config.AppStartListener.onApplicationEvent(va:282)
        at io.metersphere.config.AppStartListener.onApplicationEvent(va:339)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:149)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:451)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:384)
        at org.springframework.boot.context.event.EventPublishingRunListener.ready(EventPublishingRunListener.java:109)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$ready$6(SpringApplicationRunListeners.java:80)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
        at org.springframework.boot.SpringApplicationRunListeners.ready(SpringApplicationRunListeners.java:80)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:352)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1358)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1347)
        at io.metersphere.Application.main(Application.java:30)
2024-03-05 18:33:02,164 [main] INFO  o.e.jetty.server.AbstractConnector ? - Stopped ServerConnector@61c644fe{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2024-03-05 18:33:02,170 [main] INFO  org.eclipse.jetty.server.Server ? - Stopped oejs.Server@4ba13fed{STOPPING}[12.0.3,sto=0]
2024-03-05 18:33:02,173 [main] INFO  o.e.j.s.h.ContextHandler.application ? - Destroying Spring FrameworkServlet 'dispatcherServlet'
2024-03-05 18:33:02,175 [main] INFO  o.e.j.e.s.ServletContextHandler ? - Stopped osbwej.JettyEmbeddedWebAppContext@59b1edab{application,/,b=file:/tmp/jetty-docbase.8082.14314041962478087808/,a=AVAILABLE,h=oeje10s.SessionHandler@3855b27e{STOPPED}}

### 重现步骤

初始化升级后 启动就失败了，失败日志如问题描述

**Comment by 13290445582** [comment]
您好，可参考之前issue解决下该问题，issue链接已附给您。https://github.com/metersphere/metersphere/issues/28624

**Comment by youliyuan-fit2cloud** [comment]
你好，因为长时间未反馈，暂关闭该issue，如果后续仍遇到请随时联系我们，感谢理解和支持。
