### ISSUE TITLE
[BUG]性能测试设置指定定时任务，执行完成后，定时任务未关闭，同时后台服务会有报错日志

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#29694]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.12-lts

### 使用外置数据库

否

### 问题描述

性能测试设置指定定时任务，执行完成后，定时任务未关闭，同时后台服务服务会报错

### 重现步骤

1. 创建性能测试定时任务
2. 设置指定时间执行测试任务
3. 执行完成后
4. 定时任务还在， 未关闭，同时后台服务会有报错日志

### 期待的正确结果

指定类型的定时任务，执行完了之后，建议平台自动关闭任务，或者后台不要报错

### 相关日志输出

```shell
ERROR i.m.service.BaseScheduleService 177 - Method[lambda$startEnableSchedules$2][初始化任务失败]
io.metersphere.commons.exception.MSException: 定时任务配置异常: Based on configured schedule, the given trigger 'PERFORMANCE_TEST.83e88d3d-8f47-428a-9329-0596dd2de7a2' will never fire.
	at io.metersphere.commons.exception.MSException.throwException(MSException.java:26)
	at io.metersphere.sechedule.ScheduleManager.addCronJob(ScheduleManager.java:85)
	at io.metersphere.sechedule.ScheduleManager.addOrUpdateCronJob(ScheduleManager.java:274)
	at io.metersphere.service.BaseScheduleService.lambda$startEnableSchedules$2(BaseScheduleService.java:159)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at io.metersphere.service.BaseScheduleService.startEnableSchedules(BaseScheduleService.java:153)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:352)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:385)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717)
	at io.metersphere.service.BaseScheduleService$$SpringCGLIB$$0.startEnableSchedules(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:352)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:385)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717)
	at io.metersphere.service.BaseScheduleService$$SpringCGLIB$$1.startEnableSchedules(<generated>)
	at io.metersphere.listener.AppStartListener.run(AppStartListener.java:43)
	at org.springframework.boot.SpringApplication.lambda$callRunner$4(SpringApplication.java:794)
	at org.springframework.util.function.ThrowingConsumer$1.acceptWithException(ThrowingConsumer.java:83)
	at org.springframework.util.function.ThrowingConsumer.accept(ThrowingConsumer.java:60)
	at org.springframework.util.function.ThrowingConsumer$1.accept(ThrowingConsumer.java:88)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:806)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:794)
	at org.springframework.boot.SpringApplication.lambda$callRunners$3(SpringApplication.java:782)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:782)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:341)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1358)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1347)
	at io.metersphere.PerformanceApplication.main(PerformanceApplication.java:32)
```

### 附加信息

<img width="579" alt="8940fdfb1000e14da41574a110af5f8" src="https://github.com/metersphere/metersphere/assets/50016789/975c2354-1fd6-489e-b102-750602fe3015">

<img width="481" alt="1711013366921" src="https://github.com/metersphere/metersphere/assets/50016789/6209e32b-4b6e-4683-8ed1-07935d44086d">

**Comment by liuruibin** [comment]
感谢提醒，你输入的是永远都不会被触发的时间点，这里我们后续进行优化

**Comment by liuruibin** [comment]
算了吧，优化也没啥意义
