### ISSUE TITLE
[BUG] 首次安装2.10.13版本，无法安装成功，且V68__modify_api_test_case.sql执行失败

### ISSUE THREAD

**Issue by linjicong** [metersphere/metersphere#29980]
### MeterSphere 版本

2.10.13

### 使用外置数据库

是

### 问题描述

Kubernetes 方式无法成功部署

### 重现步骤

helm upgrade metersphere metersphere/metersphere -n ms

### 期待的正确结果

成功部署应用

### 相关日志输出

```shell
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'schedulerStarter': Unsatisfied dependency expressed through field 'scheduler': Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Schema `metersphere` contains a failed migration to version 68 !
```

### 附加信息

单独执行脚本V68__modify_api_test_case.sql，提示Can't DROP 'response'; check that column/key exists

**Comment by liuruibin** [comment]
清理ns后重新执行

helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo add metersphere https://metersphere.github.io/helm-chart/
helm repo update  # 从 chart 仓库中更新本地可用chart的信息
helm dependency update #更新依赖包
helm install metersphere metersphere/metersphere  --namespace=ms --create-namespace

**Comment by ccbuildpro** [comment]
相同问题，一样的2.10.13，一样的外置数据库。
metersphere-system-setting这个pod持续报这个错。
Schema `metersphere` contains a failed migration to version 68
<img width="2009" alt="image" src="https://github.com/metersphere/metersphere/assets/13743665/d927a1d3-187b-47b3-9789-fa7795e06110">

**Comment by hichenxinyu** [comment]
一样遇到相同的问题
aused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Schema `metersphere` contains a failed migration to version 68 !
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1806)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:313)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:785)
	... 20 common frames omitted
Caused by: org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Schema `metersphere` contains a failed migration to version 68 !
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:218)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:139)
	at org.flywaydb.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:58)
	at org.flywaydb.database.mysql.MySQLConnection.lock(MySQLConnection.java:152)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:144)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:139)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:97)
	at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:188)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:213)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:140)
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1802)
	... 32 common frames omitted
