### ISSUE TITLE
[BUG]接口自动化插件开发”中使用form-create的“数组组件”，在ms上删除保存不了

### ISSUE THREAD

**Issue by zh-ce** [metersphere/metersphere#30159]
### 联系方式

MeterSphere 交流群7（周周）

### MeterSphere 版本

metersphere-offline-installer-v2.10.8-lts

### 使用外置数据库

否

### 问题描述

“接口自动化插件开发”中使用form-create的“数组组件”，在ms上删除保存不了，会有如图报错
![2fed923828525ca7efba1e91a451dd1](https://github.com/metersphere/metersphere/assets/66996461/b9982b0f-a7a1-4655-b47d-e093df4b2e57)
注：
1、form-create的“数组组件”（在form-create中为“进阶”部分）
![bb6cf63be4bebf907a52a61f6928aa7](https://github.com/metersphere/metersphere/assets/66996461/aaa68d96-1517-4e67-9d6c-e8fcf62b5869)
2、已重启system-setting和api-test服务，其它插件可正常操作

### 重现步骤

ui.json
``[
                    {
                        type:'group',
                        field:'group',
                        title:'group',
                        value:[{field1:'aaa',field2:'sss'}, {field1:'aaa',field2:'sss'}],
                        props:{
                            defaultValue: {field1:'field1',field2:'field2'},
                            rules: [
                                {type:'input', field:'field1',title:'field1'},
                                {type:'input', field:'field2',title:'field2'},
                            ]
                        }
                    },
                ]``

### 相关日志输出

```shell
mock.js:73 
 Uncaught (in promise) TypeError: Cannot create property 'status' on string '2'
    at eval (mock.js:73:1)
    at new Promise (<anonymous>)
    at x (mock.js:73:1)
    at a.D [as $delete] (mock.js:73:1)
    at a.removeRule (form-create.min.js:7:1)
    at a.del (form-create.min.js:7:1)
    at click (form-create.min.js:7:1)
    at Rn (vue.runtime.esm.js:6:1)
    at HTMLDivElement.n (vue.runtime.esm.js:6:1)
    at Ia.o._wrapper (vue.runtime.esm.js:6:1)
2
vue.runtime.esm.js:6 
 Uncaught (in promise) TypeError: t.replace is not a function
    at e.exports (vue.runtime.esm.js:6:1)
    at e.exports (vue.runtime.esm.js:6:1)
    at eval (vue.runtime.esm.js:6:1)
    at new Promise (<anonymous>)
    at e.exports (vue.runtime.esm.js:6:1)
    at e.exports (vue.runtime.esm.js:6:1)
﻿
```

**Comment by 13290445582** [comment]
您好，第三方插件问题可根据https://www.form-create.com/v2/element-ui/研究下，感谢理解。
