### ISSUE TITLE
[BUG] api test 执行时间太久，测试报告一直显示RUNNING

### ISSUE THREAD

**Issue by ahululu** [metersphere/metersphere#30259]
### MeterSphere 版本

v2.10.10-lts-e9b6aa9e

### 使用外置数据库

否

### 问题描述

api test 每次报告时间特别久（动辄3小时以上），查看就是一直在RUNNING

### 重现步骤

每次执行接口自动化就会出现

### 相关日志输出

```shell
:/opt/metersphere/logs/api-test/error.log
2024-04-12 09:51:19,715 [Timer-66] ERROR i.m.w.NotificationWebSocket$NotificationCenter 177 - Method[lambda$run$0][java.nio.channels.ClosedChannelException]
java.io.IOException: java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.util.FutureCallback.block(FutureCallback.java:163)
	at org.eclipse.jetty.util.FutureCallback.block(FutureCallback.java:139)
	at org.eclipse.jetty.ee10.websocket.jakarta.common.JakartaWebSocketBasicRemote.sendText(JakartaWebSocketBasicRemote.java:120)
	at io.metersphere.websocket.NotificationWebSocket$NotificationCenter.lambda$run$0(NotificationWebSocket.java:123)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.metersphere.websocket.NotificationWebSocket$NotificationCenter.run(NotificationWebSocket.java:121)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
Caused by: java.nio.channels.ClosedChannelException: null
	at org.eclipse.jetty.websocket.core.internal.WebSocketSessionState.onOutgoingFrame(WebSocketSessionState.java:183)
	at org.eclipse.jetty.websocket.core.WebSocketCoreSession.sendFrame(WebSocketCoreSession.java:487)
	at org.eclipse.jetty.ee10.websocket.jakarta.common.JakartaWebSocketRemoteEndpoint.sendFrame(JakartaWebSocketRemoteEndpoint.java:140)
	at org.eclipse.jetty.ee10.websocket.jakarta.common.JakartaWebSocketBasicRemote.sendText(JakartaWebSocketBasicRemote.java:119)
	... 5 common frames omitted


/opt/metersphere/logs/api-test/ms-jmeter-run.log就是特别多的这种日志：
2024-04-12 09:52:18,540 qtp855277552-43234 INFO  ms-jmeter-run-log ? - Method[lambda$onOpen$6][REPORT-ID: 2aafd843] 客户端: [2aafd843] : 连接成功！1
2024-04-12 09:52:19,481 qtp855277552-45713 INFO  ms-jmeter-run-log ? - Method[invoke][REPORT-ID: 2aafd843-2aafd843] 获取执行脚本
2024-04-12 09:52:21,991 ms-api-debug-consume-0-C-1 INFO  ms-jmeter-run-log ? - Method[debugConsume][接收到执行结果：]
2024-04-12 09:52:23,918 ms-api-debug-consume-0-C-1 INFO  ms-jmeter-run-log ? - Method[debugConsume][接收到执行结果：]
2024-04-12 09:52:25,434 ms-api-debug-consume-0-C-1 INFO  ms-jmeter-run-log ? - Method[debugConsume][接收到执行结果：]
2024-04-12 09:52:25,555 ms-api-debug-consume-0-C-1 INFO  ms-jmeter-run-log ? - Method[debugConsume][接收到执行结果：]


/opt/metersphere/logs/api-test/info.log：
2024-04-12 09:51:40,481 [qtp1954526385-43121] INFO  i.m.websocket.NotificationWebSocket ? - Method[onOpen][建立一个socket链接: admin - 4a987df6-434b-4cae-a816-aff66c040064]
2024-04-12 09:51:40,482 [qtp1954526385-43121] INFO  i.m.websocket.NotificationWebSocket ? - Method[onOpen][在线socket链接: admin, size: 1]
2024-04-12 09:52:19,931 [qtp1954526385-45526] INFO  i.m.service.ApiJMeterFileService ? - Method[zipLocalFilesToByteArray][开始下载执行报告为[2aafd843]的文件。]
2024-04-12 09:52:19,937 [qtp1954526385-45526] INFO  i.m.service.ApiJMeterFileService ? - Method[zipLocalFilesToByteArray][下载执行报告为[2aafd843]的文件结束。]
2024-04-12 09:54:25,378 [qtp1954526385-43074] INFO  i.m.websocket.NotificationWebSocket ? - Method[onClose][剔除一个socket链接: admin - 4a987df6-434b-4cae-a816-aff66c040064]
2024-04-12 09:54:25,378 [qtp1954526385-43074] INFO  i.m.websocket.NotificationWebSocket ? - Method[onClose][在线socket链接: admin, size: 0]
2024-04-12 09:54:25,378 [qtp1954526385-43074] INFO  i.m.websocket.NotificationWebSocket ? - Method[onClose][关闭socket: admin ]
2024-04-12 10:02:40,077 [task-1335] INFO  i.m.n.sender.AbstractNoticeSender ? - Method[handleFollows][FOLLOW_PEOPLE: []]
2024-04-12 10:12:17,283 [task-1338] INFO  i.m.n.sender.AbstractNoticeSender ? - Method[handleFollows][FOLLOW_PEOPLE: []]
2024-04-12 10:16:19,264 [task-1341] INFO  i.m.n.sender.AbstractNoticeSender ? - Method[handleFollows][FOLLOW_PEOPLE: []]
2024-04-12 10:16:32,533 [task-1344] INFO  i.m.n.sender.AbstractNoticeSender ? - Method[handleFollows][FOLLOW_PEOPLE: []]
2024-04-12 10:41:47,242 [qtp1954526385-45519] INFO  i.m.websocket.NotificationWebSocket ? - Method[onOpen][建立一个socket链接: admin - 6ea72ad0-4baa-4cc4-93bd-eeaf5d3b4b4e]
2024-04-12 10:41:47,242 [qtp1954526385-45519] INFO  i.m.websocket.NotificationWebSocket ? - Method[onOpen][在线socket链接: admin, size: 1]
2024-04-12 10:48:20,747 [qtp1954526385-43073] INFO  i.m.websocket.NotificationWebSocket ? - Method[onClose][剔除一个socket链接: admin - 6ea72ad0-4baa-4cc4-93bd-eeaf5d3b4b4e]
2024-04-12 10:48:20,747 [qtp1954526385-43073] INFO  i.m.websocket.NotificationWebSocket ? - Method[onClose][在线socket链接: admin, size: 0]
2024-04-12 10:48:20,747 [qtp1954526385-43073] INFO  i.m.websocket.NotificationWebSocket ? - Method[onClose][关闭socket: admin ]
2024-04-12 10:48:56,103 [qtp1954526385-45526] INFO  i.m.websocket.NotificationWebSocket ? - Method[onOpen][建立一个socket链接: admin - 066444c4-e03f-446b-9109-a5d2d9d8ee85]
2024-04-12 10:48:56,103 [qtp1954526385-45526] INFO  i.m.websocket.NotificationWebSocket ? - Method[onOpen][在线socket链接: admin, size: 1]
2024-04-12 10:49:45,656 [qtp1954526385-45758] INFO  i.m.websocket.NotificationWebSocket ? - Method[onClose][剔除一个socket链接: admin - 066444c4-e03f-446b-9109-a5d2d9d8ee85]
2024-04-12 10:49:45,656 [qtp1954526385-45758] INFO  i.m.websocket.NotificationWebSocket ? - Method[onClose][在线socket链接: admin, size: 0]
2024-04-12 10:49:45,656 [qtp1954526385-45758] INFO  i.m.websocket.NotificationWebSocket ? - Method[onClose][关闭socket: admin ]
2024-04-12 11:45:33,116 [qtp1954526385-45526] INFO  i.m.websocket.NotificationWebSocket ? - Method[onOpen][建立一个socket链接: admin - 31314ade-2e46-4ed6-8689-3b8834f9a3de]
2024-04-12 11:45:33,116 [qtp1954526385-45526] INFO  i.m.websocket.NotificationWebSocket ? - Method[onOpen][在线socket链接: admin, size: 1]
2024-04-12 12:10:20,418 [qtp1954526385-45759] INFO  i.m.websocket.NotificationWebSocket ? - Method[onClose][剔除一个socket链接: admin - 31314ade-2e46-4ed6-8689-3b8834f9a3de]
2024-04-12 12:10:20,418 [qtp1954526385-45759] INFO  i.m.websocket.NotificationWebSocket ? - Method[onClose][在线socket链接: admin, size: 0]
2024-04-12 12:10:20,418 [qtp1954526385-45759] INFO  i.m.websocket.NotificationWebSocket ? - Method[onClose][关闭socket: admin ]
2024-04-12 13:46:10,802 [qtp1954526385-45996] INFO  i.m.websocket.NotificationWebSocket ? - Method[onOpen][建立一个socket链接: admin - e8cdd5dd-c940-4c7f-9fb9-9add4e442402]
2024-04-12 13:46:10,802 [qtp1954526385-45996] INFO  i.m.websocket.NotificationWebSocket ? - Method[onOpen][在线socket链接: admin, size: 1]
2024-04-12 13:46:19,604 [qtp1954526385-45759] INFO  i.m.websocket.NotificationWebSocket ? - Method[onClose][剔除一个socket链接: admin - e8cdd5dd-c940-4c7f-9fb9-9add4e442402]
2024-04-12 13:46:19,605 [qtp1954526385-45759] INFO  i.m.websocket.NotificationWebSocket ? - Method[onClose][在线socket链接: admin, size: 0]
2024-04-12 13:46:19,605 [qtp1954526385-45759] INFO  i.m.websocket.NotificationWebSocket ? - Method[onClose][关闭socket: admin ]
2024-04-12 13:46:20,417 [qtp1954526385-45759] INFO  i.m.websocket.NotificationWebSocket ? - Method[onOpen][建立一个socket链接: admin - adf4c124-195c-45ad-a8ea-c0861948d947]
2024-04-12 13:46:20,417 [qtp1954526385-45759] INFO  i.m.websocket.NotificationWebSocket ? - Method[onOpen][在线socket链接: admin, size: 1]
```

**Comment by LukaDoncic-Magic** [comment]
您好，未复现该问题，可以提供录屏看看嘛？

**Comment by ahululu** [comment]
> 您好，未复现该问题，可以提供录屏看看嘛？
就是运行场景就报错了，现在我加了node-controller的内存出现了新的报错：

`
2024-04-23 09:52:21,880  INFO                                   JMETER: 227 - JMETER-LOG 2024-04-23 09:52:21 ERROR c4060438 1-1 Problem in JSR223 script, JSR223PreProcessor
javax.script.ScriptException: groovy.lang.MissingMethodException: No signature of method: org.apache.jmeter.protocol.jdbc.sampler.JDBCSampler.getArguments() is applicable for argument types: () values: []
Possible solutions: getComment(), getQueryArguments()
javax.script.ScriptException
   at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:158)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:231)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:237)
   at org.apache.jmeter.modifiers.JSR223PreProcessor.process(JSR223PreProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:1001)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:562)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:502)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:265)
   at java.base/java.lang.Thread.run(Thread.java:840)

2024-04-23 09:52:23,434  INFO                                   JMETER: 227 - JMETER-LOG 2024-04-23 09:52:23 ERROR c4060438 1-1 Problem in JSR223 script, JSR223PreProcessor
javax.script.ScriptException: groovy.lang.MissingMethodException: No signature of method: org.apache.jmeter.protocol.jdbc.sampler.JDBCSampler.getArguments() is applicable for argument types: () values: []
Possible solutions: getComment(), getQueryArguments()
javax.script.ScriptException
   at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:158)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:231)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:237)
   at org.apache.jmeter.modifiers.JSR223PreProcessor.process(JSR223PreProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:1001)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:562)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:502)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:265)
   at java.base/java.lang.Thread.run(Thread.java:840)
`

**Comment by youliyuan-fit2cloud** [comment]
你好，上诉日志错误的原因是在 JSR223 脚本中调用了 getArguments() 方法，但是 JDBCSampler 类中并不存在这个方法。根据错误信息提供的可能解决方案，可以尝试使用 getComment() 或 getQueryArguments() 方法替代 getArguments() 方法。

请确保在脚本中调用的方法与 JDBCSampler 类的方法相匹配，或者查阅相关文档以了解 JDBCSampler 类的可用方法和参数。此外，还可以检查脚本中是否存在其他语法错误或逻辑错误导致该问题的出现。
