### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by juewuer** [metersphere/metersphere#307]
**MeterSphere 版本**
1.2

**Bug 描述**
java.sql.SQLSyntaxErrorException: Table 'metersphere_dev.QRTZ_LOCKS' doesn't exist

**Bug 重现步骤**
1.  通过源码安装启动
2.  log里有错误
================= 应用启动 =================
2020-08-31 11:24:52,882  INFO k.scheduling.quartz.SchedulerFactoryBean: 748 - Starting Quartz Scheduler now, after delay of 60 seconds
2020-08-31 11:24:54,900 ERROR cheduling.quartz.LocalDataSourceJobStore:3941 - ClusterManager: Error managing cluster: Failure obtaining db row lock: Table 'metersphere_dev.QRTZ_LOCKS' doesn't exist
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: Table 'metersphere_dev.QRTZ_LOCKS' doesn't exist
        at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
        at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.initialize(JobStoreSupport.java:3920)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.schedulerStarted(JobStoreSupport.java:692)
        at org.quartz.core.QuartzScheduler.start(QuartzScheduler.java:539)
        at org.quartz.impl.StdScheduler.start(StdScheduler.java:142)
        at org.springframework.scheduling.quartz.SchedulerFactoryBean$1.run(SchedulerFactoryBean.java:751)
Caused by: java.sql.SQLSyntaxErrorException: Table 'metersphere_dev.QRTZ_LOCKS' doesn't exist
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
        at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
        ... 8 common frames omitted
2020-08-31 11:24:54,901  INFO          org.quartz.core.QuartzScheduler: 547 - Scheduler clusterScheduler_$_pool-100-1-3-8.nwrknj.fios.verizon.net1598844201467 started.
2020-08-31 11:24:54,904 ERROR cheduling.quartz.LocalDataSourceJobStore:4017 - MisfireHandler: Error handling misfires: Database error recovering from misfires.
org.quartz.JobPersistenceException: Database error recovering from misfires.
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3274)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:4012)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4033)
Caused by: java.sql.SQLSyntaxErrorException: Table 'metersphere_dev.QRTZ_TRIGGERS' doesn't exist
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
3.  进入mysql查看
mysql> show tables;
+---------------------------+
| Tables_in_metersphere_dev |
+---------------------------+
| api_test                  |
| api_test_environment      |
| api_test_file             |
| api_test_report           |
| api_test_report_detail    |
| file_content              |
| file_metadata             |
| issues                    |
| load_test                 |
| load_test_file            |
| load_test_report          |
| load_test_report_detail   |
| load_test_report_log      |
| load_test_report_result   |
| metersphere_version       |
| organization              |
| project                   |
| qrtz_blob_triggers        |
| qrtz_calendars            |
| qrtz_cron_triggers        |
| qrtz_fired_triggers       |
| qrtz_job_details          |
| qrtz_locks                |
| qrtz_paused_trigger_grps  |
| qrtz_scheduler_state      |
| qrtz_simple_triggers      |
| qrtz_simprop_triggers     |
| qrtz_triggers             |
4.  大小写配置
mysql> show global variables like '%lower_case%';
+------------------------+-------+
| Variable_name          | Value |
+------------------------+-------+
| lower_case_file_system | OFF   |
| lower_case_table_names | 0     |
+------------------------+-------+
**期待的正确结果**

**截图**

**Comment by wangzhen-fit2cloud** [comment]
你好，请参考开发文档中的数据库配置，修改数据库配置后再重新运行
