### ISSUE TITLE
[BUG]接口断言JSONPath断言失败  java.lang.IllegalStateException: JSONPath is indefinite

### ISSUE THREAD

**Issue by Wei-Xue-Song** [metersphere/metersphere#31230]
### 联系方式

MeterSphere 交流群61 杭州-测试-记夕忆沧澜

### MeterSphere 版本

v3.0.0-beta

### 使用外置数据库

否

### 问题描述

接口定义编写JSONPath断言并测试验证通过
![Snipaste_2024-06-01_10-44-58](https://github.com/metersphere/metersphere/assets/61076866/b34fcf0d-4dd1-4a72-a426-df05bffc3310)

在进行接口定义的断言调试时失败 java.lang.IllegalStateException: JSONPath is indefinite
![Snipaste_2024-06-01_10-45-17](https://github.com/metersphere/metersphere/assets/61076866/6318b289-9a39-4c52-8699-9b3b2b4f382a)

### 重现步骤

直接编写带有过滤表达式的JSONPath断言进行测试即可

**Comment by Wei-Xue-Song** [comment]
2024-06-01 11:12:53 INFO 50822002-75f6-4963-a274-95b6134c4fe7 1-1 Thread started: 50822002-75f6-4963-a274-95b6134c4fe7 1-1
2024-06-01 11:12:53 INFO 50822002-75f6-4963-a274-95b6134c4fe7 1-1 args.getArgumentCount():0
2024-06-01 11:12:53 ERROR 50822002-75f6-4963-a274-95b6134c4fe7 1-1 Exception processing Assertion.
JSONPath is indefinite
java.lang.IllegalStateException
   at io.metersphere.assertions.JSONPathAssertion.getResult(JSONPathAssertion.java:99)
   at org.apache.jmeter.threads.JMeterThread.processAssertion(JMeterThread.java:968)
   at org.apache.jmeter.threads.JMeterThread.checkAssertions(JMeterThread.java:936)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:604)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:502)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:266)
   at java.base/java.lang.Thread.run(Unknown Source)

**Comment by 13290445582** [comment]
感谢反馈，在V3正式版会修复该问题。

**Comment by 13290445582** [comment]
您好，您提供的这种用法，在最新发布的3.0正式版已修复。需要注意的是，目前提取时，数组的值格式未提取正确，在测试时若看到该断言报错，请查看下返回值与匹配值是否一致，关于提取数组时格式的问题，会在下个版本修复，感谢理解。
