### ISSUE TITLE
[BUG]3.0离线安装 kafka  Error

### ISSUE THREAD

**Issue by paddy235** [metersphere/metersphere#31603]
### MeterSphere 版本

v3.0.0-beta

### 使用外置数据库

否

## 环境

[root@euler metersphere-ce-offline-installer-v3.0.0-beta]# hostnamectl
 Static hostname: euler
       Icon name: computer-vm
         Chassis: vm 🖴
      Machine ID: 373af5a307ea49609b147c4aac0db3c7
         Boot ID: 58f099e8032d47c9b4abe7daaf0362c0
  Virtualization: vmware
Operating System: openEuler 24.03 (LTS)
          Kernel: Linux 6.6.0-28.0.0.34.oe2403.x86_64
    Architecture: x86-64
 Hardware Vendor: VMware, Inc.
  Hardware Model: VMware7,1
Firmware Version: VMW71.00V.13989454.B64.1906190538
   Firmware Date: Wed 2019-06-19
    Firmware Age: 5y 1d                              

## docker版本

```
[root@euler metersphere-ce-offline-installer-v3.0.0-beta]# docker version
Client:
 Version:           26.1.3
 API version:       1.45
 Go version:        go1.21.10
 Git commit:        b72abbb
 Built:             Thu May 16 08:32:30 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.3
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.10
  Git commit:       8e96db1
  Built:            Thu May 16 08:33:58 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.15
  GitCommit:        926c9586fe4a6236699318391cd44976a98e31f1
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

## 安装环境

纯净操作系统

修改配置：  MS_BASE=/opt/eccl

## 安装过程
```
 Container task-runner  Starting
 Container redis  Started
 Container mysql  Started
 Container mysql  Waiting
 Container redis  Waiting
 Container kafka  Started
 Container kafka  Waiting
 Container task-runner  Started
 Container minio  Started
 Container kafka  Error
 Container redis  Healthy
 Container mysql  Healthy
 Container metersphere  Starting
 Container metersphere  Started
dependency failed to start: container kafka is unhealthy
```

### 重现步骤

下载离线安装包，解压缩。

## 安装环境

纯净操作系统

修改配置：  `MS_BASE=/opt/eccl`

执行 `install.sh`

### 相关日志输出

```shell
## kafka日志


[root@euler metersphere-ce-offline-installer-v3.0.0-beta]# docker logs -f d749e44b4da6
===> User
uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
===> Setting default values of environment variables if not already set.
===> Configuring ...
Running in KRaft mode...
===> Launching ... 
===> Using provided cluster id 4L6g3nShT-eMCtK--X86sw ...
Exception in thread "main" java.lang.IllegalArgumentException: Error creating broker listeners from 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092': No security protocol defined for listener CONTROLLER at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:243) at kafka.server.KafkaConfig.listeners(KafkaConfig.scala:2177) at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1845) at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1638) at kafka.tools.StorageTool$.$anonfun$main$1(StorageTool.scala:52) at scala.Option.flatMap(Option.scala:283) at kafka.tools.StorageTool$.main(StorageTool.scala:52) at kafka.docker.KafkaDockerWrapper$.main(KafkaDockerWrapper.scala:47) at kafka.docker.KafkaDockerWrapper.main(KafkaDockerWrapper.scala) Caused by: java.lang.IllegalArgumentException: No security protocol defined for listener CONTROLLER at kafka.cluster.EndPoint$.$anonfun$createEndPoint$2(EndPoint.scala:49) at scala.collection.immutable.Map$Map4.getOrElse(Map.scala:548) at kafka.cluster.EndPoint$.securityProtocol$1(EndPoint.scala:49) at kafka.cluster.EndPoint$.createEndPoint(EndPoint.scala:54) at kafka.utils.CoreUtils$.$anonfun$listenerListToEndPoints$10(CoreUtils.scala:240) at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:100) at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:87) at scala.collection.mutable.ArraySeq.map(ArraySeq.scala:35) at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:240) ... 8 more
===> User
uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
===> Setting default values of environment variables if not already set.
===> Configuring ...
Running in KRaft mode...
===> Launching ... 
===> Using provided cluster id 4L6g3nShT-eMCtK--X86sw ...
Exception in thread "main" java.lang.IllegalArgumentException: Error creating broker listeners from 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092': No security protocol defined for listener CONTROLLER at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:243) at kafka.server.KafkaConfig.listeners(KafkaConfig.scala:2177) at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1845) at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1638) at kafka.tools.StorageTool$.$anonfun$main$1(StorageTool.scala:52) at scala.Option.flatMap(Option.scala:283) at kafka.tools.StorageTool$.main(StorageTool.scala:52) at kafka.docker.KafkaDockerWrapper$.main(KafkaDockerWrapper.scala:47) at kafka.docker.KafkaDockerWrapper.main(KafkaDockerWrapper.scala) Caused by: java.lang.IllegalArgumentException: No security protocol defined for listener CONTROLLER at kafka.cluster.EndPoint$.$anonfun$createEndPoint$2(EndPoint.scala:49) at scala.collection.immutable.Map$Map4.getOrElse(Map.scala:548) at kafka.cluster.EndPoint$.securityProtocol$1(EndPoint.scala:49) at kafka.cluster.EndPoint$.createEndPoint(EndPoint.scala:54) at kafka.utils.CoreUtils$.$anonfun$listenerListToEndPoints$10(CoreUtils.scala:240) at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:100) at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:87) at scala.collection.mutable.ArraySeq.map(ArraySeq.scala:35) at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:240) ... 8 more
===> User
uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
===> Setting default values of environment variables if not already set.
===> Configuring ...


```
## registry.fit2cloud.com/metersphere/metersphere-ce:v3.0.0-beta 运行日志：

```
2024-06-19 17:05:58,879 ERROR g.springframework.boot.SpringApplication: 859 - Application run failed
java.lang.IllegalStateException: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.model.processor.PropertyModelHandler - Could not find properties file [/opt/metersphere/conf/metersphere.properties].
        at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:347)
        at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:298)
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:246)
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:223)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
        at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:81)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:64)
        at java.base/java.lang.Iterable.forEach(Unknown Source)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:63)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:370)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:330)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
        at io.metersphere.Application.main(Application.java:30)
Caused by: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.model.processor.PropertyModelHandler - Could not find properties file [/opt/metersphere/conf/metersphere.properties].
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.reportConfigurationErrorsIfNecessary(LogbackLoggingSystem.java:277)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:255)
        at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:81)
        at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:61)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:189)
        at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:332)
        ... 19 common frames omitted
Exception in thread "main" java.lang.IllegalStateException: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.model.processor.PropertyModelHandler - Could not find properties file [/opt/metersphere/conf/metersphere.properties].
        at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:347)
        at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:298)
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:246)
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:223)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
        at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:81)
        at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:64)
        at java.base/java.lang.Iterable.forEach(Unknown Source)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:63)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:370)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:330)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
        at io.metersphere.Application.main(Application.java:30)
Caused by: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.model.processor.PropertyModelHandler - Could not find properties file [/opt/metersphere/conf/metersphere.properties].
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.reportConfigurationErrorsIfNecessary(LogbackLoggingSystem.java:277)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:255)
        at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:81)
        at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:61)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:189)
        at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:332)
        ... 19 more
exec java -Dfile.encoding=utf-8 -Djava.awt.headless=true --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED -Xmx410m -XX:+ExitOnOutOfMemoryError -cp /metersphere:/opt/jmeter/lib/ext/*:/metersphere/lib/*:/standalone/lib/* io.metersphere.Application
17:07:01,274 |-ERROR in ch.qos.logback.core.model.processor.PropertyModelHandler - Could not find properties file [/opt/metersphere/conf/metersphere.properties].
17:07:01,279 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [console]
17:07:01,280 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
17:07:01,289 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
17:07:01,327 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [debugAppender]
17:07:01,327 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
17:07:01,361 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@79290250 - Archive files will be limited to [50 MB] each.
17:07:01,370 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@79290250 - No compression will be used
17:07:01,372 |-INFO in c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@79290250 - Will use the pattern /opt/metersphere/logs/metersphere/history/debug.%d{yyyyMMdd}-%i.log for the active file
17:07:01,423 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@47a5b70d - The date pattern is 'yyyyMMdd' from file name pattern '/opt/metersphere/logs/metersphere/history/debug.%d{yyyyMMdd}-%i.log'.
```

**Comment by liuruibin** [comment]
日志上写缺失配置文件/opt/metersphere/conf/metersphere.properties 你检查volume挂载是否有问题
