### ISSUE TITLE
[BUG]测试计划场景自动化用例达到一定数量，例如700条，测试计划执行报错

### ISSUE THREAD

**Issue by lol666666** [metersphere/metersphere#31848]
### 联系方式

13716054767

### MeterSphere 版本

 v2.10.14

### 使用外置数据库

是

### 问题描述

测试一个测试计划，该测试计划包含至少七百条以上接口场景自动化测试用例，然后执行该测试计划，测试报告直接completed，但是测试计划实际还未触发或者执行中

### 重现步骤

在测试计划创建一个包含700多条的接口场景下的自动化接口测试用例，全部加到这个计划中
选择这个测试计划并行全部执行
测试计划执行页面一直loading，一段时间后报上面错误，但是点击测试报告，发现该计划的测试报告已经completed，实际测试计划还在执行中

### 期待的正确结果

测试计划报告正确展示测试计划的执行结果和状态

### 相关日志输出

```shell
2024-07-01 10:17:08,047  INFO                        ms-jmeter-run-log:  55 - Method[runTestPlan][预生成测试计划报告【回归测试计划-2024-07-01 10:17:08】计划报告ID[b7bf1547-0337-416e-889e-3e54baaec105]]
2024-07-01 10:17:08,283  INFO                        ms-jmeter-run-log:  55 - Method[executeScenarioCase][开始执行测试计划场景用例 b7bf1547-0337-416e-889e-3e54baaec105]
10:20:29,398 |-INFO in c.q.l.co.rolling.helper.RenameUtil - Renaming file [/opt/metersphere/logs/test-track/error.log] to [/opt/metersphere/logs/test-track/history/error.20240628-0.log]
10:20:29,400 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - Multiple periods, i.e. 3 periods, seem to have elapsed. This is expected at application start.
2024-07-01 10:20:29,408  INFO                        ms-jmeter-run-log:  55 - Method[execute][开始生成测试计划报告内容 b7bf1547-0337-416e-889e-3e54baaec105]
4381:12 ERROR: 执行测试计划失败!
io.metersphere.commons.exception.MSException: 测试计划执行失败，不存在可执行的用例！报告ID:[b84b4fc5-c5f9-4b6d-861f-68374fb34b70]
        at io.metersphere.commons.exception.MSException.throwException(MSException.java:26)
        at io.metersphere.plan.service.execute.TestPlanExecuteService.execute(TestPlanExecuteService.java:115)
        at io.metersphere.plan.service.execute.TestPlanExecuteService.runTestPlan(TestPlanExecuteService.java:79)
        at jdk.internal.reflect.GeneratedMethodAccessor2044.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:392)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717)
        at io.metersphere.plan.service.execute.TestPlanExecuteService$$SpringCGLIB$$0.runTestPlan(<generated>)
        at jdk.internal.reflect.GeneratedMethodAccessor2044.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
```

**Comment by lol666666** [comment]
![image](https://github.com/metersphere/metersphere/assets/10813359/a4ef250d-814e-4f05-a1a2-dcbe4a5f622a)
test_plan_report表的测试报告run_info执行用例的内容中，这个为空串，

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，我们研究下是咋回事，大概率是bug。

**Comment by Somebody-JIAN** [comment]
您好，目前没有复现这个问题。包括您代码中截图的问题，也不会造成您描述的缺陷。

所以希望您能提供更多信息：

1.测试计划报告已经失败的话，您是通过什么判断测试计划还在执行中呢？ 

2.api服务，有没有报错信息？

**Comment by lol666666** [comment]
1.测试计划报告已经失败的话，您是通过什么判断测试计划还在执行中呢？
 这个根据运行的node- controller的日志发现还在进行中，另外测试计划的进度条的进度也在更新，但是测试报告确是completed
2.api服务，有没有报错信息？
本地debug 发现 api-test没任何报错信息

![Uploading image.png…]()

**Comment by lol666666** [comment]
![image](https://github.com/user-attachments/assets/b4734e97-7519-49c1-9f5c-2cf7a9951e1c)
这个为api-test的日志

**Comment by Somebody-JIAN** [comment]
若是能够本地Debug的话，可以看看

**Comment by Somebody-JIAN** [comment]
本地有debug条件的话，可以看看io.metersphere.plan.service.execute.TestPlanExecuteService#executeScenarioCase 这个方法能不能正常执行，是不是在某个环节出现了什么异常

**Comment by Somebody-JIAN** [comment]
看了下你的日志，猜测相关代码的执行顺序是这样的：

![image](https://github.com/user-attachments/assets/4326d36e-c9ca-4223-9524-4cc2b0f00340)


是不是有什么原因导致了场景报告map没有拿到，

亦或是数据较多（而且场景的结构也比较复杂），导致api服务处理过长，**服务调用超时**。这种情况下也会出现你描述的情况。

**Comment by lol666666** [comment]
api服务处理过长，服务调用超时这个现象可能性比较大，有sockerttimeout的报错，像这种一般建议如何修改？

**Comment by lol666666** [comment]
服务调用出错[serviceId:api,url:/test/plan/api/case/plan/exec/result/b620f770-c7cf-490f-aa0f-acfd459854f4],错误信息:I/O error on GET request for "http://172.30.10.13:8004/test/plan/api/case/plan/exec/result/b620f770-c7cf-490f-aa0f-acfd459854f4": Connect to http://172.30.10.13:8004 [/172.30.10.13] failed: Connection refused


服务调用出错[serviceId:api,url:/test/plan/api/case/get/env/44862383-7167-4cf8-a94a-622771f0b031],错误信息:No available instance for service: api

**Comment by Somebody-JIAN** [comment]
通过修改 /opt/metersphere/conf/metersphere.properties , 修改完之后重启

![image](https://github.com/user-attachments/assets/153ddfa3-3003-46f8-97c0-bca9fbeef677)

**Comment by lol666666** [comment]
api 日志频繁刷“处理断言数据，只有一个，不需要合并”
<img width="1268" alt="image" src="https://github.com/user-attachments/assets/382c1ba0-c64a-468e-a239-e476e352edd4">
<img width="1215" alt="image" src="https://github.com/user-attachments/assets/23e3f288-f459-41bf-a3eb-2565e0354551">

**Comment by lol666666** [comment]
API- test影响的代码:

**Comment by lol666666** [comment]
那我试下超时时间设置

**Comment by youliyuan-fit2cloud** [comment]
如有任何后续问题请及时反馈，感谢～

**Comment by lol666666** [comment]
增加超时设置后，跟未添加参数的变化，测试报告不会立即completed，但是结果是0运行，
api服务日志一直刷
<img width="1197" alt="image" src="https://github.com/user-attachments/assets/03027838-4d72-459d-bd62-72f50c489e9b">

测试报告展示完成，但是0运行
<img width="1325" alt="image" src="https://github.com/user-attachments/assets/bac1d4d7-a07b-4bca-aa3a-7b5b7e94c7f0">

报告内容展示运行0%
<img width="1558" alt="image" src="https://github.com/user-attachments/assets/c407fefe-fda0-404d-8c25-20febcf52ab3">

metersphere.properties添加的参数
<img width="1570" alt="image" src="https://github.com/user-attachments/assets/cb006d0d-ddfa-41aa-be3e-1c826cfa098c">

**Comment by lol666666** [comment]
### 测试计划加入的测试用例多的时候，从测试计划下面的报告可以查看到结果，但是从报告tab下无法查看结果**
<img width="1500" alt="image" src="https://github.com/user-attachments/assets/b8e54915-1448-4aac-904b-6d118c9a02ec">
<img width="1452" alt="image" src="https://github.com/user-attachments/assets/e631020a-b9cc-42e1-9437-939d82b4d029">
### **但是从报告tab下进入无法查看，如下**
<img width="1507" alt="image" src="https://github.com/user-attachments/assets/a11ff83f-3a91-40a4-a5b6-fbce430c57e6">
<img width="1495" alt="image" src="https://github.com/user-attachments/assets/214b3458-ffb4-4827-99b3-14a4b78ee17b">

**Comment by liuruibin** [comment]
这个和另一个issue https://github.com/metersphere/metersphere/issues/32557 重复了，这个先关闭
