### ISSUE TITLE
[QUESTION] 源码部署后端报错

### ISSUE THREAD

**Issue by wangbingfei** [metersphere/metersphere#31980]
### 请描述您的问题

v3.0.1版本，后端启动报错，gaInstalledTime()这个方法一直有的，却报错找不到
![Uploading 1720523644146.jpg…]()

**Comment by wangbingfei** [comment]
xception in thread "main" java.lang.IllegalStateException: java.lang.NoSuchMethodError: 'java.lang.Long io.metersphere.system.mapper.ExtUserMapper.gaInstalledTime()'
	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:825)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
	at io.metersphere.Application.main(Application.java:30)
Caused by: java.lang.NoSuchMethodError: 'java.lang.Long io.metersphere.system.mapper.ExtUserMapper.gaInstalledTime()'
	at io.metersphere.engine.CFTTaskService.handleHistoricalData(CFTTaskService.java:99)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:392)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at io.metersphere.engine.CFTTaskService$$SpringCGLIB$$0.handleHistoricalData(<generated>)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:392)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at io.metersphere.engine.CFTTaskService$$SpringCGLIB$$1.handleHistoricalData(<generated>)
	at io.metersphere.engine.MsCommandLineRunner.run(a:125)
	at org.springframework.boot.SpringApplication.lambda$callRunner$5(SpringApplication.java:790)
	at org.springframework.util.function.ThrowingConsumer$1.acceptWithException(ThrowingConsumer.java:83)
	at org.springframework.util.function.ThrowingConsumer.accept(ThrowingConsumer.java:60)
	at org.springframework.util.function.ThrowingConsumer$1.accept(ThrowingConsumer.java:88)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:789)
	at org.springframework.boot.SpringApplication.lambda$callRunners$3(SpringApplication.java:774)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:774)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:342)
	... 3 more

**Comment by liuruibin** [comment]
我们已经修复这个问题，这并不影响执行

**Comment by wangbingfei** [comment]
> 修订问题，但不影响执行

就是启动不了才请教你们，还有一直报这个错
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    io.metersphere.engine.CFTTaskService.handleHistoricalData(CFTTaskService.java:99)

The following method did not exist:

    'java.lang.Long io.metersphere.system.mapper.ExtUserMapper.gaInstalledTime()'

The calling method's class, io.metersphere.engine.CFTTaskService, was loaded from the following location:

    jar:file:/Users/admin/.m2/repository/io/metersphere/monitoring-engine/3.0/monitoring-engine-3.0.jar!/io/metersphere/engine/CFTTaskService.class

The called method's class, io.metersphere.system.mapper.ExtUserMapper, is available from the following locations:

    file:/Users/admin/IdeaProjects/qtt-test-backend/backend/services/system-setting/target/classes/io/metersphere/system/mapper/ExtUserMapper.class

The called method's class hierarchy was loaded from the following locations:

    io.metersphere.system.mapper.ExtUserMapper: file:/Users/admin/IdeaProjects/qtt-test-backend/backend/services/system-setting/target/classes/


Action:

Correct the classpath of your application so that it contains compatible versions of the classes io.metersphere.engine.CFTTaskService and io.metersphere.system.mapper.ExtUserMapper

**Comment by wangbingfei** [comment]
> 修订问题，但不影响执行

一直启动不了，还有报个错
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-07-10 10:21:52,199 ERROR agnostics.LoggingFailureAnalysisReporter:  40 - 

***************************
APPLICATION FAILED TO START
***************************
Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    io.metersphere.engine.CFTTaskService.handleHistoricalData(CFTTaskService.java:99)

The following method did not exist:

    'java.lang.Long io.metersphere.system.mapper.ExtUserMapper.gaInstalledTime()'

The calling method's class, io.metersphere.engine.CFTTaskService, was loaded from the following location:

    jar:file:/Users/admin/.m2/repository/io/metersphere/monitoring-engine/3.0/monitoring-engine-3.0.jar!/io/metersphere/engine/CFTTaskService.class

**Comment by ltt12345** [comment]
我也遇到这个问题了，怎么解决呢Exception in thread "main" java.lang.IllegalStateException: java.lang.NoSuchMethodError: 'long io.metersphere.system.mapper.ExtUserMapper.gaInstalledTime()'

**Comment by liuruibin** [comment]
把本地maven仓库的 io/metersphere/monitoring-engine 删除后，重新import
