### ISSUE TITLE
[BUG]接口mock 中添加后置脚本使用第三方Jar包编写Mock期望不生效

### ISSUE THREAD

**Issue by spritelyl** [metersphere/metersphere#32121]
### 联系方式

14707070227

### MeterSphere 版本

v2.10.16-lts

### 使用外置数据库

否

### 问题描述

接口mock 中添加后置脚本使用第三方Jar包编写Mock期望不生效

### 重现步骤

1. 文件管理中上传jar 包并打开了加载jar 包按钮
2. 创建接口添加后置脚本使用可以生效
3. 但是在mock 服务中添加后置脚本使用不生效，后台直接报错

### 期待的正确结果

接口mock 中添加后置脚本使用第三方Jar包编写Mock期望生效

### 相关日志输出

```shell
2024-07-16 16:49:59,184 [qtp934377784-68172] INFO  i.m.service.MockConfigService ? - Method[checkReturnWithMockExpectByUrlParam][Mock [http://172.30.10.18:8004/mock/100001/] request:{"isPost":false,"paramType":null,"restParamsObj":null,"queryParamsObj":{"map":{},"mapType":"java.util.HashMap","empty":true},"jsonParam":null,"xmlToJsonParam":null,"raw":null,"tcpParam":null,"post":false,"empty":true}]
2024-07-16 16:49:59,210 [qtp934377784-68172] ERROR i.m.c.u.mock.MockScriptEngineUtils ? - Method[runScript][javax.script.ScriptException: Sourced file: inline evaluation of: ``import com.tude.gettoken.demos.GetToken; import java.sql.*;  //获取token GetToken  . . . '' : Typed variable declaration : Class: GetToken not found in namespace : at Line: 5 : in file: inline evaluation of: ``import com.tude.gettoken.demos.GetToken; import java.sql.*;  //获取token GetToken  . . . '' : GetToken 
 in inline evaluation of: ``import com.tude.gettoken.demos.GetToken; import java.sql.*;  //获取token GetToken  . . . '' at line number 5]
javax.script.ScriptException: Sourced file: inline evaluation of: ``import com.tude.gettoken.demos.GetToken; import java.sql.*;  //获取token GetToken  . . . '' : Typed variable declaration : Class: GetToken not found in namespace : at Line: 5 : in file: inline evaluation of: ``import com.tude.gettoken.demos.GetToken; import java.sql.*;  //获取token GetToken  . . . '' : GetToken 
 in inline evaluation of: ``import com.tude.gettoken.demos.GetToken; import java.sql.*;  //获取token GetToken  . . . '' at line number 5
	at bsh.engine.BshScriptEngine.evalSource(BshScriptEngine.java:93)
	at bsh.engine.BshScriptEngine.eval(BshScriptEngine.java:46)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262)
	at io.metersphere.commons.utils.mock.MockScriptEngineUtils.runScript(MockScriptEngineUtils.java:42)
	at io.metersphere.commons.utils.mock.MockApiUtils.getResultByResponseResult(MockApiUtils.java:287)
	at io.metersphere.service.MockConfigService.updateHttpServletResponse(MockConfigService.java:580)
	at io.metersphere.service.MockConfigService.checkReturnWithMockExpectByUrlParam(MockConfigService.java:904)
	at jdk.internal.reflect.GeneratedMethodAccessor2578.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:392)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at io.metersphere.service.MockConfigService$$SpringCGLIB$$1.checkReturnWithMockExpectByUrlParam(<generated>)
	at jdk.internal.reflect.GeneratedMethodAccessor2578.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:392)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at io.metersphere.service.MockConfigService$$SpringCGLIB$$2.checkReturnWithMockExpectByUrlParam(<generated>)
	at io.metersphere.controller.mock.MockApiController.getRequest(MockApiController.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor2577.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:58)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at io.metersphere.controller.mock.MockApiController$$SpringCGLIB$$0.getRequest(<generated>)
	at jdk.internal.reflect.GeneratedMethodAccessor2577.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831)
```

### 附加信息
![1721120147035](https://github.com/user-attachments/assets/8124dfcc-9e5f-4e31-a0f8-c67ddecf3678)
mock 环境运行时：
 
<img width="524" alt="1721120309810" src="https://github.com/user-attachments/assets/5d82e5df-fd41-4c50-b936-154a3643754f">
![1721120147064](https://github.com/user-attachments/assets/867b99a4-2de6-481a-ba40-7067c77c7aa7)

_No response_

**Comment by Somebody-JIAN** [comment]
目前的设计中，Mock的后置脚本环境是很纯净的运行环境。 如果使用Jar包，要把**有关联的Jar都加进去**。

在请求的前后置脚本可以直接使用，是因为那个环境内置了很多基础Jar包。

两种环境不一样。
