### ISSUE TITLE
[BUG]测试计划的结果报告较大时导出html报错

### ISSUE THREAD

**Issue by ywang9-12** [metersphere/metersphere#32141]
### 联系方式

ywang9_12@qq.com

### MeterSphere 版本

v2.10.16-lts-3d047b2d

### 使用外置数据库

是

### 问题描述

通过api调用测试计划生成报告id后，使用/track/test/plan/report/db/export/{id}/zh_CN接口存储html，返回{"success":false,"message":"Connection prematurely closed BEFORE response","data":null}
此测试计划用例较多，其他计划导出报告正常，怀疑文件太大超时。

### 重现步骤

1、测试计划共关联了176个功能用例，功能用例均关联了场景，共67个场景。通过api或者界面执行测试计划等待结果。
2、进入url /track/testPlan/reportList可正常显示测试结果。
3、界面在【测试跟踪】-【报告】找到测试报告，点击【导出报告】，界面显示Network error。检查发现响应超出15s
![导出时长超出15s](https://github.com/user-attachments/assets/152554cd-e1e8-4530-b032-d94833fc5673)
![报错日志](https://github.com/user-attachments/assets/494fa900-b5aa-4cfa-bfa5-4fbe5c4074c5)

### 期待的正确结果

可正常导出测试报告

### 相关日志输出

```shell
2024-07-17 14:21:44,913 [AsyncResolver-bootstrap-executor-0] INFO  c.n.d.s.r.aws.ConfigClusterResolver ? - Resolving eureka endpoints via configuration
2024-07-17 14:26:50,536 [reactor-http-epoll-12] ERROR r.n.http.server.HttpServerOperations ? - [45144da1-68, L:/172.30.10.7:8000 - R:/55.241.105.102:63725] Error finishing response. Closing connection
reactor.netty.http.client.PrematureCloseException: Connection prematurely closed DURING response
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
        *__checkpoint ⇢ org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ io.metersphere.gateway.filter.SessionFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ io.metersphere.gateway.filter.SwaggerFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ io.metersphere.gateway.filter.LoginFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ HTTP GET "/track/test/plan/report/db/export/0f94a854-5cb2-459b-ad34-2b50533435c4/zh_CN" [ExceptionHandlingWebHandler]
Original Stack Trace:
2024-07-17 14:26:51,765 [reactor-http-epoll-12] ERROR o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler 102 - [62f90fc9-499008]  500 Server Error for HTTP GET "/track"
io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /172.30.10.14:8005
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
        *__checkpoint ⇢ org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ io.metersphere.gateway.filter.SessionFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ io.metersphere.gateway.filter.SwaggerFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ io.metersphere.gateway.filter.LoginFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ HTTP GET "/track" [ExceptionHandlingWebHandler]
Original Stack Trace:
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
        at io.netty.channel.unix.Errors.newConnectException0(Errors.java:166)
        at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:131)
        at io.netty.channel.unix.Socket.finishConnect(Socket.java:359)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:715)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:692)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:491)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
2024-07-17 14:27:05,930 [reactor-http-epoll-13] ERROR o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler ? - [62f90fc9-499013]  500 Server Error for HTTP GET "/track/test/plan/report/db/0f94a854-5cb2-459b-ad34-2b50533435c4"
io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /172.30.10.14:8005
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
        *__checkpoint ⇢ org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ io.metersphere.gateway.filter.SessionFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ io.metersphere.gateway.filter.SwaggerFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ io.metersphere.gateway.filter.LoginFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ HTTP GET "/track/test/plan/report/db/0f94a854-5cb2-459b-ad34-2b50533435c4" [ExceptionHandlingWebHandler]
Original Stack Trace:
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
        at io.netty.channel.unix.Errors.newConnectException0(Errors.java:166)
        at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:131)
        at io.netty.channel.unix.Socket.finishConnect(Socket.java:359)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:715)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:692)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:491)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by youliyuan-fit2cloud** [comment]
你好，感谢反馈该问题，看日志是服务不正常了，因为导出的报告太大，服务器配置怎么样？可以通过将test-track模块的最大可使用内存改善这个问题。

**Comment by ywang9-12** [comment]
你好，
&nbsp; &nbsp; &nbsp; 服务器配置是16核，60G内存，200G硬盘，请问在哪里设置test-track模块的最大可使用内存？是UI界面还是.env配置文件？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月17日(星期三) 晚上6:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]测试计划的结果报告较大时导出html报错 (Issue #32141)





 
你好，感谢反馈该问题，看日志是服务不正常了，因为导出的报告太大，服务器配置怎么样？可以通过将test-track模块的最大可使用内存改善这个问题。

**Comment by youliyuan-fit2cloud** [comment]
安装目录的 docker-compose-test-track.yml 文件，修改内存配置，如下图，然后执行msctl reload  重载服务
<img width="656" alt="image" src="https://github.com/user-attachments/assets/1f70776d-d835-49c3-8b03-dc739e478aa9">

**Comment by ywang9-12** [comment]
感谢，问题已解决。html导出大小是48M，接口响应时间约26s，这个报告再大点会不会有响应超时隐患？

**Comment by youliyuan-fit2cloud** [comment]
> 感谢，问题已解决。html导出大小是48M，接口响应时间约26s，这个报告再大点会不会有响应超时隐患？

会有。目前解决办法是增大内存，这里还涉及到接口用例和场景用例的话，还需要增加api-test 容器的最大可使用内存，可以同步增大配置。（考虑到你的服务器配置比较豪横～）

**Comment by ywang9-12** [comment]
确实涉及场景用例，后面会在这个测试计划中不断扩充场景用例。这个有建议一个计划关联多少用例数之类的吗？豪横也有吃不消的一天~当内存达到上限时该如何处理，拆分成多个测试计划吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "metersphere/metersphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月18日(星期四) 中午11:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [metersphere/metersphere] [BUG]测试计划的结果报告较大时导出html报错 (Issue #32141)





  
感谢，问题已解决。html导出大小是48M，接口响应时间约26s，这个报告再大点会不会有响应超时隐患？
  
会有。目前解决办法是增大内存，这里还涉及到接口用例和场景用例的话，还需要增加api-test 容器的最大可使用内存，可以同步增大配置。（考虑到你的服务器配置比较豪横～）

**Comment by youliyuan-fit2cloud** [comment]
> 确实涉及场景用例，后面会在这个测试计划中不断扩充场景用例。这个有建议一个计划关联多少用例数之类的吗？豪横也有吃不消的一天~当内存达到上限时该如何处理，拆分成多个测试计划吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "metersphere/metersphere" ***@***.***&gt;; 发送时间:&nbsp;2024年7月18日(星期四) 中午11:30 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [metersphere/metersphere] [BUG]测试计划的结果报告较大时导出html报错 (Issue #32141) 感谢，问题已解决。html导出大小是48M，接口响应时间约26s，这个报告再大点会不会有响应超时隐患？ 会有。目前解决办法是增大内存，这里还涉及到接口用例和场景用例的话，还需要增加api-test 容器的最大可使用内存，可以同步增大配置。（考虑到你的服务器配置比较豪横～） — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

抱歉，才发现你的问题。
这个要看你的场景用例里面包含多少个步骤，测试计划能关联1～2k个用例是可以的，然后配置越大相应的也增加用例。
拆分多个测试计划确实可以。

**Comment by youliyuan-fit2cloud** [comment]
因长时间未反馈后续信息，故关闭该issue，如果有最新进展请重新打开，感谢理解和支持。

**Comment by ttsiii** [comment]
limit扩展后：
![image](https://github.com/user-attachments/assets/9c907dd2-601b-4faa-98f1-900165265eba)

还是有这个问题
![image](https://github.com/user-attachments/assets/36475154-c3e7-4331-8b50-4ba84c6d64bf)
