### ISSUE TITLE
metersphere V3 脚本用python import paramiko 报错cannot import name 'exceptions' from 'cryptography.hazmat.bindings._rust'，重新pip install cryptography还是一样

### ISSUE THREAD

**Issue by qiuxue-boop** [metersphere/metersphere#32815]
我的metersphere版本是这个 v3.1.0-a8910b83 。
我安装了paramiko 这个库
然后我在项目管理 - 公共脚本 import paramiko，点【测试】，执行报错，完整task-runner/info.log已上传
我找到了GitHub上cryptography库的issue #[10569](https://github.com/pyca/cryptography/issues/10569) ，看到回复说是安装的cryptography有问题。所以我重新安装了这个包，并且本地导入正常。但是在脚本执行结果还是报错，求助，请问**这种情况应该怎么进一步定位和解决 ？**
![image](https://github.com/user-attachments/assets/1ed73817-d159-491e-b315-ea16ab0dc386)

![image](https://github.com/user-attachments/assets/280823e5-f101-4cd4-8fb5-83fe67c0502c)

[task_runner_info2.log](https://github.com/user-attachments/files/16726180/task_runner_info2.log)

页面点【测试】报错
![image](https://github.com/user-attachments/assets/cd9b00ba-0e32-4684-a5e1-cd6bb1ac188f)

**Comment by qiuxue-boop** [comment]
刚换了个组件试了下，有新报错，但还是同一个包的问题。这次import的组件是pymysql
`org.graalvm.polyglot.PolyglotException: AttributeError: module 'cryptography.hazmat.bindings._rust.openssl' has no attribute 'hashes'
javax.script.ScriptException
   at io.metersphere.python.scriptengine.PolyglotEngine.eval(PolyglotEngine.java:57)
   at io.metersphere.python.scriptengine.PolyglotEngine.eval(PolyglotEngine.java:86)
   at io.metersphere.python.scriptengine.PolyglotEngine.eval(PolyglotEngine.java:97)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:269)
   at org.apache.jmeter.protocol.java.sampler.JSR223Sampler.sample(JSR223Sampler.java:72)
   at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:669)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:588)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:502)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:266)
   at java.base/java.lang.Thread.run(Unknown Source)`
![image](https://github.com/user-attachments/assets/3585c36a-7c55-4307-9652-1b386f038812)

**Comment by liuruibin** [comment]
paramiko的问题我们在置顶issue已经说明了https://github.com/metersphere/metersphere/issues/31811#issuecomment-2205076798

出于安全的因素，我们的容器用的是alpine作为基础镜像，少了很多底层的libc，你可以在上面的回复中找到用ubuntu重制的task-runner镜像，自己替换掉

**Comment by qiuxue-boop** [comment]
替换了task-runner镜像，但无法解决不能用 paramiko的问题，因为内置的python解释器缺少很多底层libc？（我试了import paramiko没有报错，但是实际使用还是会提示这不对那不对）
最后我们用了python的第三方库subprocess，两台机器做免密登录，实现在远程机器执行命令的操作。
谢谢！
