### ISSUE TITLE
[BUG]使用对接jira（jira版本：v9.17.0）的插件 （插件版本：2.10.7），缺陷模版选择Jira默认模版，切换到缺陷页面报错:404 : "{"errorMessages":["问题不存在"],"errors":{}}"

### ISSUE THREAD

**Issue by yycarry1994** [metersphere/metersphere#32877]
### 联系方式

1140966186@qq.com

### MeterSphere 版本

v2.10.16-lts-3d047b2d

### 使用外置数据库

否

### 问题描述

使用对接jira（jira版本：v9.17.0）的插件 （插件版本：2.10.7），缺陷模版选择Jira默认模版，切换到缺陷页面报错:404 : "{"errorMessages":["问题不存在"],"errors":{}}"

### 重现步骤

选择模板
![Uploading 20240829170640.jpg…](https://img2024.cnblogs.com/blog/1726012/202408/1726012-20240829171509907-1151069948.jpg)
打开缺陷管理页面
![Uploading 20240829170710.jpg…](https://img2024.cnblogs.com/blog/1726012/202408/1726012-20240829171519201-2000130020.jpg)

### 相关日志输出

```shell
2024-08-29 16:03:58,528 [qtp1677312717-177735] ERROR i.m.platform.impl.JiraPlatform 147 - Method[setSpecialParam][io.metersphere.commons.exception.MSException: 404 : "{"errorMessages":["问题不存在"],"errors":{}}"]
io.metersphere.commons.exception.MSException: 404 : "{"errorMessages":["问题不存在"],"errors":{}}"
 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
 at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
```

**Comment by ijwstl** [comment]
要勾使用jira模板，而不是使用默认jira模板，另外记得绑定jira的项目key

**Comment by song-cc-rock** [comment]
> 环境:  全新Jira版本环境-v9.17.0  MS插件版本-2.10.7

使用以上环境, 暂时未复现问题,  正常对接并使用Jira默认模板可以提交缺陷, 如下图; 请检查Jira环境, 或使用新的Jira环境来对接.

![image](https://github.com/user-attachments/assets/073ebe86-8f0b-4dcf-8f97-1c24ca9bb15c)

![image](https://github.com/user-attachments/assets/542b31db-e891-4aa3-a949-be967e94d8d5)

![image](https://github.com/user-attachments/assets/e393884f-caef-4f70-9af8-31ec796c8405)

![image](https://github.com/user-attachments/assets/e785d9d8-de5e-4851-b7f9-ccf5ff203a5a)

**Comment by 13290445582** [comment]
该问题长时间未反馈，关闭。建议升级到最新版本，如果后续有问题请重新提issue，感谢理解和支持～
