### ISSUE TITLE
[BUG]  资源池修改最大并发数，并行执行测试计划，设置的最大并发数不生效

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#32913]
### MeterSphere 版本

v2.10.17

### 使用外置数据库

否

### 问题描述

想通过修改资源池最大并发数控制测试计划并行执行用例数量， 修改参数不生效

### 重现步骤

1、进入系统-资源池，修改最大并发数
2、手动执行测试计划，选择并行执行

### 期待的正确结果

修改资源池并发数能生效

### 相关日志输出

```shell
2024-09-02 17:19:27,318 qtp10559673-31 INFO  ms-jmeter-run-log ? - Method[apiStartRun][REPORT-ID: c6aace55-5b0e-4cac-829b-e7b83323b57b] 支持重试下载
2024-09-02 17:19:27,322 qtp10559673-35 INFO  ms-jmeter-run-log ? - Method[unzip][/opt/metersphere/data/body/6bf80536-a3e1-439d-8bcb-77feb5227893_ea045287-9c5b-4271-820c-0ad38ad5f78d.jmx解压成功]
2024-09-02 17:19:27,322 qtp10559673-35 INFO  ms-jmeter-run-log ? - Method[invoke0][REPORT-ID: 6bf80536-a3e1-439d-8bcb-77feb5227893] 下载执行脚本完成：6bf80536-a3e1-439d-8bcb-77feb5227893_ea045287-9c5b-4271-820c-0ad38ad5f78d.jmx
2024-09-02 17:19:27,324 qtp10559673-35 INFO  ms-jmeter-run-log ? - Method[ALLATORIxDEMO][本次执行[6bf80536-a3e1-439d-8bcb-77feb5227893]在文件库中需要下载[0]个文件，已下载完毕。]
2024-09-02 17:19:27,324 qtp10559673-35 INFO  ms-jmeter-run-log ? - Method[invoke0][REPORT-ID: 6bf80536-a3e1-439d-8bcb-77feb5227893] 开始加入队列执行
2024-09-02 17:19:27,324 qtp10559673-35 ERROR ms-jmeter-run-log ? - Method[setCorePoolSize][设置线程参数异常]
java.lang.IllegalArgumentException: null
	at java.base/java.util.concurrent.ThreadPoolExecutor.setMaximumPoolSize(ThreadPoolExecutor.java:1670)
	at io.metersphere.api.jmeter.queue.ExecThreadPoolExecutor.setCorePoolSize(uc:261)
	at io.metersphere.api.jmeter.JMeterService.run(sc:518)
	at io.metersphere.api.service.JMeterExecuteService.runStart(bb:438)
	at io.metersphere.api.controller.JmeterExecuteController.apiStartRun(JmeterExecuteController.java:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:547)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)
	at org.eclipse.jetty.ee10.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:195)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
	at io.metersphere.config.JettyFilter.doFilter(pa:568)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:208)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
	at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:107)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:824)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
	at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:703)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:851)
	at org.eclipse.jetty.server.Server.handle(Server.java:181)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:635)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:403)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-09-02 17:19:27,325 qtp10559673-35 INFO  ms-jmeter-run-log ? - Method[outApiThreadPoolExecutorLogger][API 并发队列详情：
 核心线程数：10
 活动线程数：4
 最大线程数：10
 系统当前线程数：50
 线程池活跃度：40.00%
 任务完成数：108
 队列大小：10000
 当前排队线程数：0
 队列剩余大小：10000
 执行队列大小：11
 队列使用度：0.00%]
```

### 附加信息

<img width="773" alt="60a80f93f62720c49eb9d3b41579877" src="https://github.com/user-attachments/assets/89b4f76b-5d90-402d-8bcf-4cf4fceacd86">

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，后续版本修复。

**Comment by 13290445582** [comment]
您好，该问题在v2.10.21版本已修复，请升级。
