### ISSUE TITLE
[BUG]【接口测试】安装python 第三方库openpyxl，接口测试脚本中导入openpyxl 报错

### ISSUE THREAD

**Issue by Larson13** [metersphere/metersphere#32925]
### MeterSphere 版本

1.20.19

### 使用外置数据库

否

### 问题描述

使用知识库介绍安装 python 第三方库openpyxl，在服务器 python 环境可以使用 import openpyxl 导入 openpyxl库，但在 MeterSphere 脚本中无法import
https://kb.fit2cloud.com/?p=27

### 重现步骤

1、参考知识库安装openpyxl 库
https://kb.fit2cloud.com/?p=27
2、在接口脚本中导入openpyxl库

### 期待的正确结果

接口脚本中可以正常导入 openpyxl库

### 相关日志输出

```shell
2024-09-03 13:28:53 INFO ea1120ee 1-1 Thread started: ea1120ee 1-1
2024-09-03 13:28:57 ERROR ea1120ee 1-1 Problem in JSR223 script JSR223Sampler, message: {}
ImportError: No module named base in <script> at line number 3
javax.script.ScriptException
   at org.python.jsr223.PyScriptEngine.scriptException(PyScriptEngine.java:202)
   at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:42)
   at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:231)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:237)
   at org.apache.jmeter.protocol.java.sampler.JSR223Sampler.sample(JSR223Sampler.java:72)
   at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:672)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:590)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:502)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:265)
   at java.base/java.lang.Thread.run(Thread.java:840)
```

### 附加信息

1、服务器安装的 openpyxl库
![image](https://github.com/user-attachments/assets/6743e0ec-1449-4454-9b55-8223b2fe4035)
2、服务器python 环境import  openpyxl库
![image](https://github.com/user-attachments/assets/c27aba6a-b779-41ef-943b-0cdc2c280e80)

3、在metersphere 脚本中导入openpyxl 报错

![image](https://github.com/user-attachments/assets/0761710a-102d-4c9b-90dc-be5407348191)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，v2 版本中已复现，后续版本修复。（当前问题使用v1 版本不再更新）

**Comment by youliyuan-fit2cloud** [comment]
v3版本没有这个问题，建议使用v3版本，感谢理解和支持。
