### ISSUE TITLE
[BUG]一台物理机部署多个node-controller节点，并在资源池中加入这些节点，压测时node-controller动态创建jmeter容器进程冲突导致压测启动失败

### ISSUE THREAD

**Issue by wangxingxi** [metersphere/metersphere#33181]
### 联系方式

MeterSphere交流群69  兴习 277618103@qq.com

### MeterSphere 版本

v2.10.17-lts

### 使用外置数据库

否

### 问题描述

版本：v2.10.17-lts
功能：性能压测
同一台物理机，部署多个node-controller，将多个node-controller对应ip加入到资源池中之后，使用该资源池压测，启动压测时每个node-controller会动态创建jmeter容器，因为这些jmeter容器在同一台物理机上相互冲突，导致失败：
![image](https://github.com/user-attachments/assets/97be9004-7015-4d92-aa43-341a980a1a85)

### 重现步骤

1. 使用官网在线方式，一键安装metersphere
2. 再使用一台新物理机，部署多个node-controller(将 install.conf 中修改安装模式 MS_INSTALL_MODE 的值(由原先的 allinone 改为 node-controller))，每个node-controller对应一个虚拟IP
![image](https://github.com/user-attachments/assets/a6aa049e-2adc-454e-be4b-d536f1a1dc2e)
3. 然后加入到资源池中：
![image](https://github.com/user-attachments/assets/abc2d35c-dc49-405b-aea2-d8a24aed3021)
4. 压测时，选择该资源池进行压测，压测机分配策略三种方式任选一种：
![image](https://github.com/user-attachments/assets/295f082b-1755-424f-a30c-d7af10d09247)
5. 启动后失败，能看到服务器上只创建了一个jmeter容器，且未能启动成功：
![image](https://github.com/user-attachments/assets/9e95a725-d358-475c-8a28-c3179b657603)

### 期待的正确结果
支持一台物理机部署多个node-controller并添加到一个资源池中进行压测

### 相关日志输出

```shell
2024-09-18 17:09:39,536 docker-java-stream-662964650 INFO  ms-jmeter-run-log ? - Method[onNext][java.lang.IllegalArgumentException: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input]
2024-09-18 17:09:39,536 docker-java-stream-662964650 INFO  ms-jmeter-run-log ? - Method[onNext][at [Source: (String)""; line: 1, column: 0]]
2024-09-18 17:09:39,536 docker-java-stream-662964650 INFO  ms-jmeter-run-log ? - Method[onNext][at com.hikvision.ezviz.json.JsonUtils.parseObject(JsonUtils.java:84)]
2024-09-18 17:09:39,536 docker-java-stream-662964650 INFO  ms-jmeter-run-log ? - Method[onNext][at com.hikvision.ezviz.json.JsonUtils.parseObject(JsonUtils.java:73)]
2024-09-18 17:09:39,536 docker-java-stream-662964650 INFO  ms-jmeter-run-log ? - Method[onNext][at com.ezviz.test.util.KafkaMsgUtils.makeHeader(KafkaMsgUtils.java:25)]
2024-09-18 17:09:39,536 docker-java-stream-662964650 INFO  ms-jmeter-run-log ? - Method[onNext][at com.ezviz.test.kafkaRequest.KafkaRequestPftest.runTest(KafkaRequestPftest.java:84)]
2024-09-18 17:09:39,536 docker-java-stream-662964650 INFO  ms-jmeter-run-log ? - Method[onNext][at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:197)]
2024-09-18 17:09:39,536 docker-java-stream-662964650 INFO  ms-jmeter-run-log ? - Method[onNext][at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:670)]
2024-09-18 17:09:39,536 docker-java-stream-662964650 INFO  ms-jmeter-run-log ? - Method[onNext][at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:588)]
2024-09-18 17:09:39,536 docker-java-stream-662964650 INFO  ms-jmeter-run-log ? - Method[onNext][at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:500)]
2024-09-18 17:09:39,536 docker-java-stream-662964650 INFO  ms-jmeter-run-log ? - Method[onNext][at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:264)]
2024-09-18 17:09:39,536 docker-java-stream-662964650 INFO  ms-jmeter-run-log ? - Method[onNext][at java.base/java.lang.Thread.run(Thread.java:840)]
2024-09-18 17:09:39,536 docker-java-stream-662964650 INFO  ms-jmeter-run-log ? - Method[onNext][Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input]
2024-09-18 17:09:39,536 docker-java-stream-662964650 INFO  ms-jmeter-run-log ? - Method[onNext][at [Source: (String)""; line: 1, column: 0]]
2024-09-18 17:09:39,536 docker-java-stream-662964650 INFO  ms-jmeter-run-log ? - Method[onNext][at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)]
2024-09-18 17:09:39,536 docker-java-stream-662964650 INFO  ms-jmeter-run-log ? - Method[onNext][at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4765)]
2024-09-18 17:09:39,536 docker-java-stream-662964650 INFO  ms-jmeter-run-log ? - Method[onNext][at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4667)]
2024-09-18 17:09:39,536 docker-java-stream-662964650 INFO  ms-jmeter-run-log ? - Method[onNext][at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)]
2024-09-18 17:09:39,536 docker-java-stream-662964650 INFO  ms-jmeter-run-log ? - Method[onNext][at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3612)]
2024-09-18 17:09:39,536 docker-java-stream-662964650 INFO  ms-jmeter-run-log ? - Method[onNext][at com.hikvision.ezviz.json.JsonUtils.parseObject(JsonUtils.java:82)]
2024-09-18 17:09:39,536 docker-java-stream-662964650 INFO  ms-jmeter-run-log ? - Method[onNext][... 9 more]
2024-09-18 17:09:39,887 docker-java-stream--888804497 ERROR ms-jmeter-run-log ? - Method[onComplete][Remove container error: ]
com.github.dockerjava.api.exception.ConflictException: Status 409: {"message":"removal of container 73dbcdfce2e9e293495311f1ead81223959de745889dc94082b55c84a5eb7a94 is already in progress"}

        at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:245)
        at com.github.dockerjava.core.DefaultInvocationBuilder.delete(DefaultInvocationBuilder.java:56)
        at com.github.dockerjava.core.exec.RemoveContainerCmdExec.execute(RemoveContainerCmdExec.java:28)
        at com.github.dockerjava.core.exec.RemoveContainerCmdExec.execute(RemoveContainerCmdExec.java:11)
        at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
        at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
        at com.github.dockerjava.core.command.RemoveContainerCmdImpl.exec(RemoveContainerCmdImpl.java:66)
        at io.metersphere.node.util.DockerClientService.removeContainer(ja:523)
        at io.metersphere.node.service.JmeterOperateService$2.onComplete(na:357)
        at com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec$1.onComplete(AbstrAsyncDockerCmdExec.java:51)
        at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:276)
        at java.base/java.lang.Thread.run(Thread.java:840)
2024-09-18 17:09:39,887 docker-java-stream--888804497 INFO  ms-jmeter-run-log ? - Method[onComplete][completed....]
```

### 附加信息

原因初步分析：
1. 压测时node-controller会动态创建jmeter容器，且该容器名称取自压测任务ID(testId)，而我们是在一台物理机上创建了多个node-controller，就会在压测时创建多个相同名称的jmeter容器，容器之间相互冲突导致启动失败
2. 我们也验证过这种多node-controller单独使用的情况，如果资源池中只添加一台是可以成功的

一台物理机部署多个node-controller的使用背景：
1. 我们的物理机资源比较紧张，且配置较高40C 160G，我们希望在物理机上部署多个node-controller分配给不同的业务使用，从资源池层面隔离开，避免不同业务之间相互争抢压测机
2. 还有部分场景，我们需要验证多台压测机建立连接压向服务端，物理机数量太少，无法达到业务要求

**Comment by liuruibin** [comment]
我们设计上不支持一台服务器部署多个node-controller的，建议分散放置

建议使用4c8g的小服务器单独部署node-controller。

**Comment by wangxingxi** [comment]
> 我们设计上不支持一台服务器部署多个node-controller的，建议分散放置
> 
> 建议使用4c8g的小服务器单独部署node-controller。

这种后续能支持吗，现在物理机很少有这种4c8g的小服务器了，我在查询问题的过程中也碰到了一些和我一样有这种需求的

**Comment by wangxingxi** [comment]
> 我们设计上不支持一台服务器部署多个node-controller的，建议分散放置
> 
> 建议使用4c8g的小服务器单独部署node-controller。

或者这部分代码考虑开源吗，我们尝试自己改也行

**Comment by liuruibin** [comment]
1. 物理机上安装一个虚拟机软件 
2. 创建linux虚拟机分配4c8g
3. 虚拟机上安装node-controller
4. 复制多个步骤2中的虚拟机
5. 在metersphere中配置资源池，选择步骤4中的虚拟机ip和端口

**Comment by wangxingxi** [comment]
> 1. 物理机上安装一个虚拟机软件
> 2. 创建linux虚拟机分配4c8g
> 3. 虚拟机上安装node-controller
> 4. 复制多个步骤2中的虚拟机
> 5. 在metersphere中配置资源池，选择步骤4中的虚拟机ip和端口

好的
