### ISSUE TITLE
[BUG] 接口测试post请求传入body格式为json时，实际请求body为空

### ISSUE THREAD

**Issue by dd0gring** [metersphere/metersphere#33260]
### MeterSphere 版本

V3.2.0-89e02f6f

### 使用外置数据库

否

### 问题描述

接口测试post请求传入body格式为json时，实际请求body为空
![Snipaste_2024-09-23_18-26-54](https://github.com/user-attachments/assets/01afa549-f8ca-4bd7-bfb8-23b58ddd60e4)

### 重现步骤

创建post请求接口测试，请求体为json时，实际传入参数为空字符串
![2](https://github.com/user-attachments/assets/fe636c8c-8332-454b-ac67-69026c5b1d4d)
![3](https://github.com/user-attachments/assets/142313bc-b106-4bf1-868c-efceadad4b7e)

### 期待的正确结果

postman正常
![4](https://github.com/user-attachments/assets/4d4e65a7-c244-4c5e-b243-d13fa682d1bd)

### 相关日志输出

```shell
org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public org.jeecg.common.api.vo.Result<com.alibaba.fastjson.JSONObject> org.jeecg.modules.system.controller.LoginController.passwordAging(org.jeecg.modules.system.model.SysLoginModel,javax.servlet.http.HttpServletResponse)
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:163)
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:133)
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:122)
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:179)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:146)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.jeecg.modules.filter.RuntimeCheckFilter.doFilter(RuntimeCheckFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.jeecg.modules.filter.RuntimeCheckFilter.doFilter(RuntimeCheckFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
	at org.apache.catalina.core.StandardContextValve.__invoke(StandardContextValve.java:90)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:41002)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现该问题，请先检查一下 这个接口的是否有重定向或者请求体内容格式是否正确，感谢支持。

**Comment by dd0gring** [comment]
没有重定向，请求体格式是正确的。我试了通过请求体那一栏选择json添加的参数，无论是post还是put都会出现Required request body is missing的情况，不知道是不是我添加json参数的方式有问题

**Comment by dd0gring** [comment]
![1](https://github.com/user-attachments/assets/937fe5a7-01ca-4387-92d3-4bfa4eb851d0)
![2](https://github.com/user-attachments/assets/d18af3a2-0527-4a78-8f09-3b2b42217962)
![3](https://github.com/user-attachments/assets/761e02f5-7eca-4ca1-a73d-dd329b07592e)

**Comment by youliyuan-fit2cloud** [comment]
<img width="1012" alt="image" src="https://github.com/user-attachments/assets/cf1195f5-5b72-4c11-95ea-4cff1b85ab51">

Schema格式数据添加好了之后，再在Json 例自动生成数据试试。

**Comment by dd0gring** [comment]
我在接口 接口测试->调试 中使用请求体就会报请求体丢失，但是我在 接口测试->定义 中使用Schema格式数据自动生成后的json不会报错，这是什么原因呢，json是相同的json
![image](https://github.com/user-attachments/assets/4dfd046b-2457-4ee6-a765-9a2d66312578)
![image](https://github.com/user-attachments/assets/6701d701-0c77-4c4c-9366-c9c6a3456c65)

**Comment by youliyuan-fit2cloud** [comment]
你好，调试这边看起来有bug，下个版本修复。

**Comment by JAINKRE** [comment]
+1 同样遇到post请求格式为json时请求错误问题

**Comment by youliyuan-fit2cloud** [comment]
在v3.3版本调试页面问题已修复，修改了支持json格式。

**Comment by youliyuan-fit2cloud** [comment]
> +1 同样遇到post请求格式为json时请求错误问题

请描述你具体问题是指哪个？
如果是 接口定义-请求体中，参考下图json格式下自动生成json内容。
![image](https://github.com/user-attachments/assets/cf507513-6fb4-4019-88eb-9c1d2a16191a)

**Comment by JAINKRE** [comment]
> > +1 同样遇到post请求格式为json时请求错误问题
> 
> 请描述你具体问题是指哪个？ 如果是 接口定义-请求体中，参考下图json格式下自动生成json内容。 ![image](https://private-user-images.githubusercontent.com/54612864/371034188-cf507513-6fb4-4019-88eb-9c1d2a16191a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDQ5MjUsIm5iZiI6MTcyNzM0NDYyNSwicGF0aCI6Ii81NDYxMjg2NC8zNzEwMzQxODgtY2Y1MDc1MTMtNmZiNC00MDE5LTg4ZWItOWMxZDJhMTYxOTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA5NTcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZDY4NTVmZTk2MDE3MjBiNmJkZGYyYmMyYjA3YTA0Y2U3ZDE5ZWQ4MzE3OGM3NmY1ZjkwMjY1ODQ0YmQ4MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DmrzCIvwvujGNF86Q9110vVUO2M04HYJ2KpL7pUTGX0)

是和issue作者完全一样的问题
