### ISSUE TITLE
[BUG]从低版本2.1.0升级到2.10.20后，原先导入文件中的jar包方法和文件均无法被识别，重启了node容器也不行

### ISSUE THREAD

**Issue by liangsc-test** [metersphere/metersphere#33457]
### 联系方式

Metersphere交流群49：梁世聪

### MeterSphere 版本

v2.10.20-lts-9feb97b3

### 使用外置数据库

否

### 问题描述

从低版本2.1.0升级到2.10.20后。调用了前置、后置的beanshell脚本，结果发现之前引用的jar方法提示找不到了。我重新导入了jar包并启用，且重启了node节点容器。仍无法读取到jar包

### 重现步骤

首先在2.1.0导入一个自定义jar包，然后编写beanshell方法，调用该jar包
升级到2.10.20，然后再次跑这个场景用例

### 期待的正确结果

期望能跑成功，实际跑失败了，提示找不到方法。实际上这个方法没问题，在另一个项目里可用
![image](https://github.com/user-attachments/assets/d03df396-8435-4b5b-b53f-c6c3287d61b2)

但是在一个包含有HashMap方法的beanshell中就是失败的
![image](https://github.com/user-attachments/assets/70959587-d04d-48bd-94f7-20e9f8f58af6)

仔细看可以看到用到的这个方法是java1.8中的自带方法，现在怀疑是2.10.20用到的java版本太高导致无法读取到该方法

### 相关日志输出

```shell
2024-10-12 16:00:10 INFO 4bb65b17 1-1 Thread started: 4bb65b17 1-1
2024-10-12 16:00:10 ERROR 4bb65b17 1-1 Problem in JSR223 script, JSR223PreProcessor
Sourced file: inline evaluation of: ``import com.fadada.qinzc.parameterization.*;  import javax.xml.bind.DatatypeConve . . . '' : Method Invocation FddCryptUtil.sign : at Line: 21 : in file: inline evaluation of: ``import com.fadada.qinzc.parameterization.*;  import javax.xml.bind.DatatypeConve . . . '' : FddCryptUtil .sign ( FddCryptUtil .sortParameters ( requestHeaders ) , timestamp , key ) 

Target exception: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
 in inline evaluation of: ``import com.fadada.qinzc.parameterization.*;  import javax.xml.bind.DatatypeConve . . . '' at line number 21
javax.script.ScriptException
   at bsh.engine.BshScriptEngine.evalSource(BshScriptEngine.java:87)
   at bsh.engine.BshScriptEngine.eval(BshScriptEngine.java:46)
   at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:231)
   at org.apache.jmeter.util.JSR223TestElement.processFileOrScript(JSR223TestElement.java:237)
   at org.apache.jmeter.modifiers.JSR223PreProcessor.process(JSR223PreProcessor.java:45)
   at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:1001)
   at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:562)
   at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:502)
   at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:265)
   at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by fit2-zhao** [comment]
MeterSphere 从 2.10 之后全部使用 JDK 17 ，这个包应该从 JDK 9 开始，Java 的模块化系统（Project Jigsaw）移除了，如果需要使用相关方法，可以尝试手动导入相关依赖。

**Comment by liangsc-test** [comment]
问题已解决，我们这边去兼容这个JDK17。不再使用这个DatatypeConverter方法

**Comment by xchnshi** [comment]
@fit2-zhao @liangsc-test 这个问题类似情况我们也遇到了，开发给出的建议是多加一个参数如下，之前的--add-opens不完整
 --add-opens java.base/java.nio=ALL-UNNAMED
