### ISSUE TITLE
[BUG]发送接口请求，无响应，看日志kafka显示连接超时

### ISSUE THREAD

**Issue by zxz0x01** [metersphere/metersphere#34012]
### MeterSphere 版本

v3.4.0-5291ac9a

### 使用外置数据库

是

### 问题描述

发送接口请求一直在加载中
![image](https://github.com/user-attachments/assets/47e37812-32da-47a0-aaef-03698f09cb22)

### 重现步骤

在接口测试模块，随便发送一个http请求

### 期待的正确结果

接口请求正确返回

### 相关日志输出

```shell
cat /opt/metersphere/logs/metersphere/info.log 
2024-11-06 08:41:13,640 [jetty-138] INFO  i.m.api.socket.WebSocketHandler ? - Method[openSession][客户端: [173085367366500000] : 连接成功！1]
2024-11-06 08:41:13,695 [jetty-139] INFO  i.m.api.service.ApiExecuteService ? - 开始发送请求【 173085367366500000_debug-1730853607846 】到 http://task-runner:8000 节点执行
2024-11-06 08:41:13,703 [jetty-141] INFO  i.m.a.s.ApiExecuteResourceService ? - Method[getRunScript][生成并获取执行脚本: 173085367366500000]
2024-11-06 08:41:23,242 [kafka-1] INFO  o.apache.kafka.clients.NetworkClient ? - [Consumer clientId=consumer-plugin_consumer_d61fd431-c154-47cb-8133-c58297276282-1, groupId=plugin_consumer_d61fd431-c154-47cb-8133-c58297276282] Disconnecting from node -1 due to socket connection setup timeout. The timeout value is 26458 ms.
2024-11-06 08:41:23,242 [kafka-1] WARN  o.apache.kafka.clients.NetworkClient ? - [Consumer clientId=consumer-plugin_consumer_d61fd431-c154-47cb-8133-c58297276282-1, groupId=plugin_consumer_d61fd431-c154-47cb-8133-c58297276282] Bootstrap broker 192.168.2.12:9092 (id: -1 rack: null) disconnected
2024-11-06 08:41:25,483 [kafka-4] INFO  o.apache.kafka.clients.NetworkClient ? - [Consumer clientId=consumer-export_consume_fcacc043-e8b4-4830-b377-10f728c66c7b-4, groupId=export_consume_fcacc043-e8b4-4830-b377-10f728c66c7b] Disconnecting from node -1 due to socket connection setup timeout. The timeout value is 29882 ms.
2024-11-06 08:41:25,483 [kafka-4] WARN  o.apache.kafka.clients.NetworkClient ? - [Consumer clientId=consumer-export_consume_fcacc043-e8b4-4830-b377-10f728c66c7b-4, groupId=export_consume_fcacc043-e8b4-4830-b377-10f728c66c7b] Bootstrap broker 192.168.2.12:9092 (id: -1 rack: null) disconnected
2024-11-06 08:41:25,931 [kafka-3] INFO  o.apache.kafka.clients.NetworkClient ? - [Consumer clientId=consumer-MS-API-MESSAGE-CONSUME-3, groupId=MS-API-MESSAGE-CONSUME] Disconnecting from node -1 due to socket connection setup timeout. The timeout value is 25395 ms.
2024-11-06 08:41:25,931 [kafka-3] WARN  o.apache.kafka.clients.NetworkClient 1144 - [Consumer clientId=consumer-MS-API-MESSAGE-CONSUME-3, groupId=MS-API-MESSAGE-CONSUME] Bootstrap broker 192.168.2.12:9092 (id: -1 rack: null) disconnected
2024-11-06 08:41:27,639 [kafka-2] INFO  o.apache.kafka.clients.NetworkClient ? - [Consumer clientId=consumer-MS-API-DEBUG-CONSUME_b7f35266-6223-41a6-830a-586375fb5d29-2, groupId=MS-API-DEBUG-CONSUME_b7f35266-6223-41a6-830a-586375fb5d29] Disconnecting from node -1 due to socket connection setup timeout. The timeout value is 30000 ms.
2024-11-06 08:41:27,640 [kafka-2] WARN  o.apache.kafka.clients.NetworkClient ? - [Consumer clientId=consumer-MS-API-DEBUG-CONSUME_b7f35266-6223-41a6-830a-586375fb5d29-2, groupId=MS-API-DEBUG-CONSUME_b7f35266-6223-41a6-830a-586375fb5d29] Bootstrap broker 192.168.2.12:9092 (id: -1 rack: null) disconnected
2024-11-06 08:41:52,040 [kafka-3] INFO  o.apache.kafka.clients.NetworkClient ? - [Consumer clientId=consumer-MS-API-MESSAGE-CONSUME-3, groupId=MS-API-MESSAGE-CONSUME] Disconnecting from node -1 due to socket connection setup timeout. The timeout value is 25184 ms.
2024-11-06 08:41:52,040 [kafka-3] WARN  o.apache.kafka.clients.NetworkClient ? - [Consumer clientId=consumer-MS-API-MESSAGE-CONSUME-3, groupId=MS-API-MESSAGE-CONSUME] Bootstrap broker 192.168.2.12:9092 (id: -1 rack: null) disconnected
2024-11-06 08:41:52,750 [kafka-4] INFO  o.apache.kafka.clients.NetworkClient ? - [Consumer clientId=consumer-export_consume_fcacc043-e8b4-4830-b377-10f728c66c7b-4, groupId=export_consume_fcacc043-e8b4-4830-b377-10f728c66c7b] Disconnecting from node -1 due to socket connection setup timeout. The timeout value is 26346 ms.
2024-11-06 08:41:52,750 [kafka-4] WARN  o.apache.kafka.clients.NetworkClient ? - [Consumer clientId=consumer-export_consume_fcacc043-e8b4-4830-b377-10f728c66c7b-4, groupId=export_consume_fcacc043-e8b4-4830-b377-10f728c66c7b] Bootstrap broker 192.168.2.12:9092 (id: -1 rack: null) disconnected
2024-11-06 08:41:54,150 [kafka-1] INFO  o.apache.kafka.clients.NetworkClient ? - [Consumer clientId=consumer-plugin_consumer_d61fd431-c154-47cb-8133-c58297276282-1, groupId=plugin_consumer_d61fd431-c154-47cb-8133-c58297276282] Disconnecting from node -1 due to socket connection setup timeout. The timeout value is 30000 ms.
2024-11-06 08:41:54,150 [kafka-1] WARN  o.apache.kafka.clients.NetworkClient ? - [Consumer clientId=consumer-plugin_consumer_d61fd431-c154-47cb-8133-c58297276282-1, groupId=plugin_consumer_d61fd431-c154-47cb-8133-c58297276282] Bootstrap broker 192.168.2.12:9092 (id: -1 rack: null) disconnected
2024-11-06 08:41:56,481 [kafka-2] INFO  o.apache.kafka.clients.NetworkClient ? - [Consumer clientId=consumer-MS-API-DEBUG-CONSUME_b7f35266-6223-41a6-830a-586375fb5d29-2, groupId=MS-API-DEBUG-CONSUME_b7f35266-6223-41a6-830a-586375fb5d29] Disconnecting from node -1 due to socket connection setup timeout. The timeout value is 28126 ms.
2024-11-06 08:41:56,482 [kafka-2] WARN  o.apache.kafka.clients.NetworkClient ? - [Consumer clientId=consumer-MS-API-DEBUG-CONSUME_b7f35266-6223-41a6-830a-586375fb5d29-2, groupId=MS-API-DEBUG-CONSUME_b7f35266-6223-41a6-830a-586375fb5d29] Bootstrap broker 192.168.2.12:9092 (id: -1 rack: null) disconnected
2024-11-06 08:42:18,447 [kafka-3] INFO  o.apache.kafka.clients.NetworkClient ? - [Consumer clientId=consumer-MS-API-MESSAGE-CONSUME-3, groupId=MS-API-MESSAGE-CONSUME] Disconnecting from node -1 due to socket connection setup timeout. The timeout value is 25404 ms.
2024-11-06 08:42:18,447 [kafka-3] WARN  o.apache.kafka.clients.NetworkClient ? - [Consumer clientId=consumer-MS-API-MESSAGE-CONSUME-3, groupId=MS-API-MESSAGE-CONSUME] Bootstrap broker 192.168.2.12:9092 (id: -1 rack: null) disconnected

cat /opt/metersphere/logs/task-runner/error.log 
2024-11-06 08:36:23,392 173085332321600000 1-1 ERROR i.m.r.api.listener.ApiSampleListener 181 - Method[sampleStarted][消息推送失败：]
org.springframework.kafka.KafkaException: Send failed
        at org.springframework.kafka.core.KafkaTemplate.doSend(KafkaTemplate.java:836)
        at org.springframework.kafka.core.KafkaTemplate.observeSend(KafkaTemplate.java:793)
        at org.springframework.kafka.core.KafkaTemplate.send(KafkaTemplate.java:576)
        at io.metersphere.runner.api.kafka.ProducerService.debugSend(sb:100)
        at io.metersphere.runner.api.listener.ApiSampleListener.sampleStarted(qb:46)
        at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:579)
        at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:502)
        at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:266)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.kafka.common.errors.TimeoutException: Topic API_REPORT_DEBUG_TOPIC not present in metadata after 60000 ms.
```

### 附加信息
各个组件也都是成功启动状态
![image](https://github.com/user-attachments/assets/3cc5c8b3-41db-472a-9f8b-48b145765857)

**Comment by zxz0x01** [comment]
破案，防火墙没开放9092端口
![image](https://github.com/user-attachments/assets/6f0b2f9f-2dd9-4123-bf6d-a5023db84609)

**Comment by fit2-zhao** [comment]
感谢您提交的问题及解决思路，这对有类似问题的用户很有帮助！
