### ISSUE TITLE
[BUG] Request method 'POST' is not supported

### ISSUE THREAD

**Issue by Halecoder** [metersphere/metersphere#34028]
### MeterSphere 版本

 v2.10.20-lts-9feb97b3

### 使用外置数据库

否

### 问题描述

添加缺陷报错

2024-11-06 15:39:55 2024-11-06 15:39:55,509  WARN .support.DefaultHandlerExceptionResolver: 247 - Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' is not supported]

### 重现步骤

![image](https://github.com/user-attachments/assets/5bfeb8a5-2358-4dbb-83ab-a0b05b7a3364)

**Comment by youliyuan-fit2cloud** [comment]
你好，没有复现，请详细描述下你复现的步骤，包括环境是否集成第三方，使用的缺陷模版配置。

**Comment by Halecoder** [comment]
> 你好，没有复现，请详细描述下你复现的步骤，包括环境是否集成第三方，使用的缺陷模版配置。


集成了jira、zentao,
![image](https://github.com/user-attachments/assets/23eb1ec9-8dfb-46b7-a4a1-861b9cf21f6d)

缺陷模板如下：

```
[步骤]
<br/>
<br/>
<br/>

[结果]
<br/>
<br/>
<br/>

[期望]
<br/>
<br/>
<br/>

**请在自己的环境中完成自测（包括部署），自测结果请备注在 BUG 单中！**
```

**Comment by Halecoder** [comment]
测试了一下，我在项目管理里把集成第三方平台改为local,缺陷模板改为default，是能够添加缺陷并保存的，但是改为集成zentao并使用zentao的模板就会报Request method 'POST' is not supported的错误。不知道怎么解决。。。

我配置的模板，配置并保存：

![image](https://github.com/user-attachments/assets/0f62f568-e1c5-46bc-a7f6-be666bc4f088)


然后选中：
![image](https://github.com/user-attachments/assets/f95c612f-9d19-42f6-adaa-899e49c52b49)


打开新建缺陷：

![image](https://github.com/user-attachments/assets/fb2381f1-26df-4104-86df-c54ec25ddae3)

似乎并没有生效，而且我发现个问题，我保存缺陷模板后，模板名字并没有改变：

![image](https://github.com/user-attachments/assets/e2b81d2c-c6c3-41b8-b307-1a33549f903c)

**Comment by Halecoder** [comment]
新配置的模板名称为 禅道123123，但是保存后，还是禅道-默认模板

**Comment by Halecoder** [comment]
点击创建缺陷，日志为
```java
test-track          | 2024-11-06 18:58:19,320  WARN clipse.jetty.ee10.servlet.ServletChannel: 661 - /issues/plugin/custom/fields/735abb12-9b60-11ef-b1f6-0242ac1e0a07
2024-11-06 18:58:19 test-track          | jakarta.servlet.ServletException: Request processing failed: java.lang.NullPointerException: Cannot throw exception because the return value of "io.metersphere.plugin.exception.MSPluginException.getException(Object)" is null
2024-11-06 18:58:19 test-track          |       at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1022)
2024-11-06 18:58:19 test-track          |       at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
2024-11-06 18:58:19 test-track          |       at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
2024-11-06 18:58:19 test-track          |       at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
2024-11-06 18:58:19 test-track          |       at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.ee10.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:195)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:65)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:109)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:138)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:156)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:70)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:109)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:138)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:156)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:70)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:109)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:138)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:156)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:70)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:109)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:138)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:156)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:70)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:463)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.web.servlet.AbstractShiroFilter.lambda$doFilterInternal$0(AbstractShiroFilter.java:378)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:91)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:84)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:389)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:376)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:156)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
2024-11-06 18:58:19 test-track          |       at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
2024-11-06 18:58:19 test-track          |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
2024-11-06 18:58:19 test-track          |       at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
2024-11-06 18:58:19 test-track          |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
2024-11-06 18:58:19 test-track          |       at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:142)
2024-11-06 18:58:19 test-track          |       at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:82)
2024-11-06 18:58:19 test-track          |       at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
2024-11-06 18:58:19 test-track          |       at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
2024-11-06 18:58:19 test-track          |       at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:113)
2024-11-06 18:58:19 test-track          |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
2024-11-06 18:58:19 test-track          |       at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
2024-11-06 18:58:19 test-track          |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:824)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:703)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:597)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.server.Server.handle(Server.java:181)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:648)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:403)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
2024-11-06 18:58:19 test-track          |       at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
2024-11-06 18:58:19 test-track          |       at java.base/java.lang.Thread.run(Thread.java:840)
2024-11-06 18:58:19 test-track          | Caused by: java.lang.NullPointerException: Cannot throw exception because the return value of "io.metersphere.plugin.exception.MSPluginException.getException(Object)" is null
2024-11-06 18:58:19 test-track          |       at io.metersphere.plugin.exception.MSPluginException.throwException(MSPluginException.java:31)
2024-11-06 18:58:19 test-track          |       at io.metersphere.platform.api.AbstractPlatform.getFormOptions(AbstractPlatform.java:65)
2024-11-06 18:58:19 test-track          |       at io.metersphere.platform.impl.ZentaoPlatform.getFormOptions(ZentaoPlatform.java:162)
2024-11-06 18:58:19 test-track          |       at io.metersphere.service.IssuesService.getPluginCustomFields(IssuesService.java:1627)
2024-11-06 18:58:19 test-track          |       at jdk.internal.reflect.GeneratedMethodAccessor272.invoke(Unknown Source)
2024-11-06 18:58:19 test-track          |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-11-06 18:58:19 test-track          |       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
2024-11-06 18:58:19 test-track          |       at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:379)
2024-11-06 18:58:19 test-track          |       at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
2024-11-06 18:58:19 test-track          |       at io.metersphere.service.IssuesService$$SpringCGLIB$$1.getPluginCustomFields(<generated>)
2024-11-06 18:58:19 test-track          |       at jdk.internal.reflect.GeneratedMethodAccessor272.invoke(Unknown Source)
2024-11-06 18:58:19 test-track          |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-11-06 18:58:19 test-track          |       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
2024-11-06 18:58:19 test-track          |       at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:379)
2024-11-06 18:58:19 test-track          |       at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
2024-11-06 18:58:19 test-track          |       at io.metersphere.service.IssuesService$$SpringCGLIB$$2.getPluginCustomFields(<generated>)
2024-11-06 18:58:19 test-track          |       at io.metersphere.controller.IssuesController.getPluginCustomFields(IssuesController.java:236)
2024-11-06 18:58:19 test-track          |       at jdk.internal.reflect.GeneratedMethodAccessor207.invoke(Unknown Source)
2024-11-06 18:58:19 test-track          |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-11-06 18:58:19 test-track          |       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:58)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.spring.security.interceptor.AopAllianceAnnotationsAuthorizingMethodInterceptor$1.proceed(AopAllianceAnnotationsAuthorizingMethodInterceptor.java:89)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.authz.aop.AuthorizingMethodInterceptor.invoke(AuthorizingMethodInterceptor.java:39)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.spring.security.interceptor.AopAllianceAnnotationsAuthorizingMethodInterceptor.invoke(AopAllianceAnnotationsAuthorizingMethodInterceptor.java:123)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
2024-11-06 18:58:19 test-track          |       at io.metersphere.controller.IssuesController$$SpringCGLIB$$0.getPluginCustomFields(<generated>)
2024-11-06 18:58:19 test-track          |       at jdk.internal.reflect.GeneratedMethodAccessor207.invoke(Unknown Source)
2024-11-06 18:58:19 test-track          |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-11-06 18:58:19 test-track          |       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.spring.security.interceptor.AopAllianceAnnotationsAuthorizingMethodInterceptor$1.proceed(AopAllianceAnnotationsAuthorizingMethodInterceptor.java:89)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.authz.aop.AuthorizingMethodInterceptor.invoke(AuthorizingMethodInterceptor.java:39)
2024-11-06 18:58:19 test-track          |       at org.apache.shiro.spring.security.interceptor.AopAllianceAnnotationsAuthorizingMethodInterceptor.invoke(AopAllianceAnnotationsAuthorizingMethodInterceptor.java:123)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
2024-11-06 18:58:19 test-track          |       at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
2024-11-06 18:58:19 test-track          |       at io.metersphere.controller.IssuesController$$SpringCGLIB$$1.getPluginCustomFields(<generated>)
2024-11-06 18:58:19 test-track          |       at jdk.internal.reflect.GeneratedMethodAccessor207.invoke(Unknown Source)
2024-11-06 18:58:19 test-track          |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-11-06 18:58:19 test-track          |       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2024-11-06 18:58:19 test-track          |       at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
2024-11-06 18:58:19 test-track          |       at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
2024-11-06 18:58:19 test-track          |       at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
2024-11-06 18:58:19 test-track          |       at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926)
2024-11-06 18:58:19 test-track          |       at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831)
2024-11-06 18:58:19 test-track          |       at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
2024-11-06 18:58:19 test-track          |       at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
2024-11-06 18:58:19 test-track          |       at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
2024-11-06 18:58:19 test-track          |       at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
2024-11-06 18:58:19 test-track          |       ... 80 common frames omitted
2024-11-06 18:58:22 eureka              | 2024-11-06 18:58:22,560  INFO eureka.registry.AbstractInstanceRegistry:1252 - Running the evict task with compensationTime 0ms
2024-11-06 18:58:25 ms-node-controller  | ts=2024-11-06T10:58:25.604Z caller=collector.go:169 level=error msg="collector failed" name=netstat duration_seconds=1.2298e-05 err="couldn't get netstats: open /host/proc/net/netstat: no such file or directory"
2024-11-06 18:58:25 ms-node-controller  | ts=2024-11-06T10:58:25.607Z caller=collector.go:169 level=error msg="collector failed" name=arp duration_seconds=1.1603e-05 err="could not get ARP entries: Error Reading File: error reading arp /host/proc/net/arp: open /host/proc/net/arp: no such file or directory"
2024-11-06 18:58:25 ms-node-controller  | ts=2024-11-06T10:58:25.607Z caller=collector.go:169 level=error msg="collector failed" name=softnet duration_seconds=5.951e-06 err="could not get softnet statistics: open /host/proc/net/softnet_stat: no such file or directory"
2024-11-06 18:58:25 ms-node-controller  | ts=2024-11-06T10:58:25.609Z caller=stdlib.go:105 level=error msg="error gathering metrics: 2 error(s) occurred:\n* [from Gatherer #2] collected metric \"node_filesystem_device_error\" { label:{name:\"device\"  value:\"none\"}  label:{name:\"fstype\"  value:\"tmpfs\"}  label:{name:\"mountpoint\"  value:\"/run/user\"}  gauge:{value:1}} was collected before with the same name and label values\n* [from Gatherer #2] collected metric \"node_filesystem_device_error\" { label:{name:\"device\"  value:\"none\"}  label:{name:\"fstype\"  value:\"tmpfs\"}  label:{name:\"mountpoint\"  value:\"/mnt/wsl/docker-desktop-bind-mounts/Ubuntu/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1/run/user\"}  gauge:{value:1}} was collected before with the same name and label values"
```

**Comment by Halecoder** [comment]
正在测试 https://github.com/metersphere/metersphere/issues/27873

**Comment by Halecoder** [comment]
已解决，
加上 $config->features->apiGetModel = true; 后可正常创建缺陷
