### ISSUE TITLE
[BUG]测试计划中批量执行串行会导致只生成一个报告，且其他报告处于Running

### ISSUE THREAD

**Issue by B14Lettingo** [metersphere/metersphere#34131]
### 联系方式

1812951966@qq.com

### MeterSphere 版本

 v2.10.21-lts-f65e0842

### 使用外置数据库

否

### 问题描述

在测试计划中多选测试计划并对测试计划进行批量执行，会导致测试计划只有一个报告可以生成，其余报告则处于Running状态。
其他说明：在本次bug的复现中测试计划只使用了两条，并只关联了一条UI自动化场景

### 重现步骤

1.新建两个测试计划
2.关联两个测试用例
3.勾选两个测试计划
4.选择批量执行串行

### 相关日志输出

```shell
2024-11-12 09:38:43,689 [task-132] WARN  i.m.commons.utils.SessionUtils 114 - Method[getUser][后台获取在线用户失败: No SecurityManager accessible to the calling code, either bound to the org.apache.shiro.util.ThreadContext or as a vm static singleton.  This is an invalid application configuration.]
2024-11-12 09:38:43,985 [task-132] INFO  ms-jmeter-run-log ? - Method[genTestPlanReportBySchedule][生成测试计划报告!id:【1827773a-0e1d-43ef-8a95-fe96ad82dfa2】,PlanScenarioIdMap:【{}】,ApiTestCaseDataMap:【{}】,PerformanceIdMap:【{}】,UiScenarioIdMap:【{"27188e69-80f7-4191-bded-4afb77dc0bad":"c53ce425-ba07-bf3c-a9ec-fb92b69054d8","eabc2139-d226-410f-b795-69a69f86e30c":"4e6152fa-a270-5c4a-90c8-ad0111371db7","1b697e14-f168-4379-848b-5e7cfde0df7d":"0342b7a1-1be1-ff06-53f6-da6d9ba2436c"}】]
2024-11-12 09:38:43,986 [task-132] INFO  ms-jmeter-run-log 55 - Method[runTestPlan][预生成测试计划报告【4.操作渠道设置-2024-11-11 17:49:41】计划报告ID[1827773a-0e1d-43ef-8a95-fe96ad82dfa2]]
2024-11-12 09:38:44,017 [task-132] INFO  ms-jmeter-run-log ? - Method[executeUiCase][开始执行测试计划 UI 场景用例 1827773a-0e1d-43ef-8a95-fe96ad82dfa2]
2024-11-12 09:38:44,049 [task-132] ERROR io.metersphere.service.MicroService ? - Method[postForResultHolder][服务调用出错[serviceId:ui,url:/ui/automation/plan/run],错误信息:403 Forbidden: "{"success":false,"message":"Subject does not have permission [PROJECT_UI_SCENARIO:READ+RUN]","data":null}"]
org.springframework.web.client.HttpClientErrorException$Forbidden: 403 Forbidden: "{"success":false,"message":"Subject does not have permission [PROJECT_UI_SCENARIO:READ+RUN]","data":null}"
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:109)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:183)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:137)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:942)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:891)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:790)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:672)
	at io.metersphere.service.MicroService.postForResultHolder(MicroService.java:180)
	at io.metersphere.service.MicroService.postForDataArray(MicroService.java:245)
	at io.metersphere.service.MicroService.postForDataArray(MicroService.java:237)
	at io.metersphere.plan.service.remote.ui.PlanUiAutomationService.run(PlanUiAutomationService.java:15)
	at io.metersphere.plan.service.TestPlanService.scenarioRunModeConfig(TestPlanService.java:985)
	at io.metersphere.plan.service.TestPlanService.executeUiScenarioCase(TestPlanService.java:1107)
	at jdk.internal.reflect.GeneratedMethodAccessor1027.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:392)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at io.metersphere.plan.service.TestPlanService$$SpringCGLIB$$1.executeUiScenarioCase(<generated>)
	at jdk.internal.reflect.GeneratedMethodAccessor1027.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:392)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at io.metersphere.plan.service.TestPlanService$$SpringCGLIB$$2.executeUiScenarioCase(<generated>)
	at jdk.internal.reflect.GeneratedMethodAccessor1027.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:716)
	at io.metersphere.plan.service.TestPlanService$$SpringCGLIB$$0.executeUiScenarioCase(<generated>)
	at io.metersphere.plan.service.execute.TestPlanExecuteService.executeUiCase(TestPlanExecuteService.java:257)
	at io.metersphere.plan.service.execute.TestPlanExecuteService.countDownExecute(TestPlanExecuteService.java:139)
	at io.metersphere.plan.service.execute.TestPlanExecuteService.execute(TestPlanExecuteService.java:109)
	at io.metersphere.plan.service.execute.TestPlanExecuteService.runTestPlan(TestPlanExecuteService.java:79)
	at jdk.internal.reflect.GeneratedMethodAccessor1190.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:392)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at io.metersphere.plan.service.execute.TestPlanExecuteService$$SpringCGLIB$$0.runTestPlan(<generated>)
	at jdk.internal.reflect.GeneratedMethodAccessor1190.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:392)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at io.metersphere.plan.service.execute.TestPlanExecuteService$$SpringCGLIB$$1.runTestPlan(<generated>)
	at io.metersphere.plan.service.TestPlanService.runPlan(TestPlanService.java:1945)
	at jdk.internal.reflect.GeneratedMethodAccessor1397.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:392)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at io.metersphere.plan.service.TestPlanService$$SpringCGLIB$$1.runPlan(<generated>)
	at jdk.internal.reflect.GeneratedMethodAccessor1397.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:392)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at io.metersphere.plan.service.TestPlanService$$SpringCGLIB$$2.runPlan(<generated>)
	at jdk.internal.reflect.GeneratedMethodAccessor1397.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:716)
	at io.metersphere.plan.service.TestPlanService$$SpringCGLIB$$0.runPlan(<generated>)
	at io.metersphere.plan.service.TestPlanReportService.executeTestPlanByQueue(TestPlanReportService.java:706)
	at io.metersphere.plan.service.TestPlanReportService.testPlanExecuteOver(TestPlanReportService.java:621)
	at io.metersphere.plan.service.TestPlanReportService.executeTestPlanByQueue(TestPlanReportService.java:709)
	at io.metersphere.plan.service.TestPlanReportService.testPlanExecuteOver(TestPlanReportService.java:621)
	at io.metersphere.plan.service.TestPlanReportService.executeTestPlanByQueue(TestPlanReportService.java:709)
	at io.metersphere.plan.service.TestPlanReportService.testPlanExecuteOver(TestPlanReportService.java:621)
	at io.metersphere.plan.service.TestPlanReportService.executeTestPlanByQueue(TestPlanReportService.java:709)
	at io.metersphere.plan.service.TestPlanReportService.testPlanUnExecute(TestPlanReportService.java:635)
	at jdk.internal.reflect.GeneratedMethodAccessor2119.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:392)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:113)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by B14Lettingo** [comment]
占时无法复现
