### ISSUE TITLE
[BUG] V3.5集成禅道后，缺陷同步异常

### ISSUE THREAD

**Issue by Halecoder** [metersphere/metersphere#34439]
### MeterSphere 版本

v3.5.0

### 使用外置数据库

否

### 问题描述

禅道版本 v18.0
插件版本 zentao-plugin-v3.5.0

### 重现步骤

```sql
### Error querying database. Cause: java.sql.SQLSyntaxErrorException: Unknown column 'bcf.content' in 'field list' ### The error may exist in io/metersphere/bug/mapper/ExtBugCustomFieldMapper.xml ### The error may involve defaultParameterMap ### The error occurred while setting parameters ### SQL: select cf.name, bcf.value, bcf.content as text, bcf.bug_id, bcf.field_id as id, cf.type as type from bug_custom_field bcf left join custom_field cf on bcf.field_id = cf.id and cf.scene = 'BUG' and cf.scope_type = 'PROJECT' and scope_id = ? where bug_id in ( ? , ? ) ### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'bcf.content' in 'field list' ; bad SQL grammar []
```

### 相关日志输出

```java
2024-11-28 14:14:27,543 [SimpleAsyncTaskExecutor-25] ERROR i.metersphere.bug.service.BugService 153 - Method[handleSaveBug][org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'bcf.content' in 'field list'
### The error may exist in io/metersphere/bug/mapper/ExtBugCustomFieldMapper.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select cf.name, bcf.value, bcf.content as text, bcf.bug_id, bcf.field_id as id, cf.type as type         from bug_custom_field bcf left join custom_field cf on bcf.field_id = cf.id         and cf.scene = 'BUG' and cf.scope_type = 'PROJECT' and scope_id = ?         where bug_id in          (               ?          )
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'bcf.content' in 'field list'
; bad SQL grammar []]
org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'bcf.content' in 'field list'
### The error may exist in io/metersphere/bug/mapper/ExtBugCustomFieldMapper.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select cf.name, bcf.value, bcf.content as text, bcf.bug_id, bcf.field_id as id, cf.type as type         from bug_custom_field bcf left join custom_field cf on bcf.field_id = cf.id         and cf.scene = 'BUG' and cf.scope_type = 'PROJECT' and scope_id = ?         where bug_id in          (               ?          )
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'bcf.content' in 'field list'
; bad SQL grammar []
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:246)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:107)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:92)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:439)
	at jdk.proxy2/jdk.proxy2.$Proxy108.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80)
	at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:141)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
	at jdk.proxy2/jdk.proxy2.$Proxy349.getBugAllCustomFields(Unknown Source)
	at io.metersphere.bug.service.BugService.handleAndSaveCustomFields(BugService.java:1138)
	at io.metersphere.bug.service.BugService.handleSaveBug(BugService.java:2137)
	at io.metersphere.bug.service.BugService.lambda$doSyncAllPlatformBugs$20(BugService.java:831)
	at io.metersphere.plugin.zentao.impl.ZentaoPlatform.syncAllBugs(ZentaoPlatform.java:550)
	at io.metersphere.bug.service.BugService.execSyncAll(BugService.java:630)
	at io.metersphere.bug.service.BugService.doSyncAllPlatformBugs(BugService.java:849)
	at io.metersphere.bug.service.BugService.syncPlatformAllBugs(BugService.java:590)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:379)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at io.metersphere.bug.service.BugService$$SpringCGLIB$$0.syncPlatformAllBugs(<generated>)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:379)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:113)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'bcf.content' in 'field list'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:912)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:65)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:80)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:65)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:336)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:158)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:110)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:169)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:59)
	at jdk.proxy2/jdk.proxy2.$Proxy434.query(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at io.metersphere.system.interceptor.MybatisInterceptor.intercept(MybatisInterceptor.java:38)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:59)
	at jdk.proxy2/jdk.proxy2.$Proxy434.query(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at io.metersphere.system.interceptor.UserDesensitizationInterceptor.intercept(UserDesensitizationInterceptor.java:27)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:59)
	at jdk.proxy2/jdk.proxy2.$Proxy434.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:154)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:142)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:425)
	... 39 common frames omitted
```

**Comment by song-cc-rock** [comment]
补充一个字段
ALTER TABLE bug_custom_field ADD COLUMN `content` longtext COMMENT '字段文本';

**Comment by fit2-zhao** [comment]
安装包还是源码启动的呢？

**Comment by Halecoder** [comment]
> 补充一个字段
> ALTER TABLE bug_custom_field ADD COLUMN `content` longtext COMMENT '字段文本';

成功了，感谢

**Comment by Halecoder** [comment]
> 补充一个字段 ALTER TABLE bug_custom_field ADD COLUMN `content` longtext COMMENT '字段文本';
您好，我现在出现了很多字段缺失问题：请求重开issue
执行场景用例出现：
### Error updating database. Cause: java.sql.SQLSyntaxErrorException: Unknown column 'deleted' in 'where clause' ### The error may exist in io/metersphere/system/mapper/ExtExecTaskMapper.xml ### The error may involve defaultParameterMap ### The error occurred while setting parameters ### SQL: UPDATE exec_task SET `status` = ?, create_user = ? WHERE id in ( ? ) and project_id = ? and `status` = 'RUNNING' and deleted = false ### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'deleted' in 'where clause' ; bad SQL grammar []

还有下面：
![image](https://github.com/user-attachments/assets/b202164b-03bf-406b-93b3-bddf951cc0cb)

估计我升级没执行好，我现在该怎们做，才能杜绝这个问题？

**Comment by song-cc-rock** [comment]
> > 补充一个字段 ALTER TABLE bug_custom_field ADD COLUMN `content` longtext COMMENT '字段文本';
> > 您好，我现在出现了很多字段缺失问题：请求重开issue
> > 执行场景用例出现：
> 
> ### Error updating database. Cause: java.sql.SQLSyntaxErrorException: Unknown column 'deleted' in 'where clause' ### The error may exist in io/metersphere/system/mapper/ExtExecTaskMapper.xml ### The error may involve defaultParameterMap ### The error occurred while setting parameters ### SQL: UPDATE exec_task SET `status` = ?, create_user = ? WHERE id in ( ? ) and project_id = ? and `status` = 'RUNNING' and deleted = false ### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'deleted' in 'where clause' ; bad SQL grammar []
> 还有下面： ![image](https://private-user-images.githubusercontent.com/75030331/390929296-b202164b-03bf-406b-93b3-bddf951cc0cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NzYwMTEsIm5iZiI6MTczMjg3NTcxMSwicGF0aCI6Ii83NTAzMDMzMS8zOTA5MjkyOTYtYjIwMjE2NGItMDNiZi00MDZiLTkzYjMtYmRkZjk1MWNjMGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDEwMjE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNzRlNjk3ZGJmYzgxZmQ5Mjg3NmJkNWU3MmU2ZWY2YTk0MmJhYmU5NGMxZmY2Zjg0Yjg3ZWY5ZmRhNjhlNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1YSqwBiZQAZv35Ktl2y1JYaueMF8R1o3wkDx8KkcFEA)
> 
> 估计我升级没执行好，我现在该怎们做，才能杜绝这个问题？

应该是升级的 3.5版本flyway未执行

**Comment by song-cc-rock** [comment]
这里面有漏掉的所有SQL, 其中包括上面的那一条, 注意排除后再执行.
[https://github.com/metersphere/metersphere/blob/v3.x/backend/framework/domain/src/main/resources/migration/3.5.0/ddl/V3.5.0_2__ga_ddl.sql](url)
[https://github.com/metersphere/metersphere/blob/v3.x/backend/framework/domain/src/main/resources/migration/3.5.0/dml/V3.5.0_2_1__data.sql](url)

上面执行完, 把这两条执行记录success字段改为true, 这样不影响后续升级.
![image](https://github.com/user-attachments/assets/41caeda7-a81d-462f-b2bc-83963ba02171)
