### ISSUE TITLE
[BUG] 版本升级后, 在接口测试中使用历史上传的第三方jar包时，发现不可用

### ISSUE THREAD

**Issue by gqq5555** [metersphere/metersphere#34585]
### MeterSphere 版本

v2.10.21

### 使用外置数据库

否

### **项目文件截图**
![image](https://github.com/user-attachments/assets/9ff99dd2-6b7c-4597-bda6-11d637ed80f2)

### **node-controller日志**
`2024-12-10 15:39:35,941 qtp1346009488-28 INFO  ms-jmeter-run-log ? - Method[downloadProjectJar][开始同步上传的JAR：http://xx.xx.xx.xx:8081/api/jmeter/download/jar]
2024-12-10 15:39:35,947 qtp1346009488-28 INFO  ms-jmeter-run-log ? - Method[downloadProjectJar][REPORT-ID: null] http://xx.xx.xx.xx:8081/api/jmeter/download/jar 下载的文件名称为空
2024-12-10 15:39:35,947 qtp1346009488-28 ERROR ms-jmeter-run-log ? - Method[ALLATORIxDEMO][文件下载失败！]
java.io.FileNotFoundException: /opt/metersphere/data/api-folder/jar/node (Is a directory)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
        at io.metersphere.api.service.utils.HttpClientUtil.ALLATORIxDEMO(cb:53)
        at io.metersphere.api.service.utils.HttpClientUtil.ALLATORIxDEMO(cb:595)
        at io.metersphere.api.service.utils.HttpClientUtil.downloadJarDb(cb:321)
        at io.metersphere.api.jmeter.MsDriverManager.downloadProjectJar(jc:193)
        at io.metersphere.api.service.JMeterExecuteService.runStart(hb:180)
        at io.metersphere.api.service.JMeterExecuteService.debug(hb:119)
        at io.metersphere.api.controller.JmeterExecuteController.apiDebug(JmeterExecuteController.java:37)
        at jdk.internal.reflect.GeneratedMethodAccessor126.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:547)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
        at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)
        at org.eclipse.jetty.ee10.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:195)
        at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
        at io.metersphere.config.JettyFilter.doFilter(xa:92)
        at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:208)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
        at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:113)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547)
        at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:824)
        at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436)
        at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
        at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:717)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)
        at org.eclipse.jetty.server.Server.handle(Server.java:182)
        at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:662)
        at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:414)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
        at java.base/java.lang.Thread.run(Thread.java:840)`

### **apt-test日志**
`2024-12-10 15:39:35,943 [qtp1229204995-265782] WARN  o.s.w.s.m.s.DefaultHandlerExceptionResolver ? - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public org.springframework.http.ResponseEntity<byte[]> io.metersphere.controller.ApiJMeterFileController.downloadJmeterFiles(java.util.Map<java.lang.String, java.util.List<io.metersphere.dto.ProjectJarConfig>>)]`

### **file_metadata表中jar包数据**
+----------+------+---------+---------------+----------+--------------------------------------+-----------------------------------+
| name     | type | storage | resource_type | load_jar | module_id                            | path                              |
+----------+------+---------+---------------+----------+--------------------------------------+-----------------------------------+
| json     | JAR  | NULL    | WORKSPACE     |        1 | bd8ebc06-f82c-45d9-89d3-41dabb9835a6 | /opt/metersphere/data/jar/json.jar|
+----------+------+---------+---------------+----------+--------------------------------------+-----------------------------------+

### 重现步骤

1.项目管理-文件管理中存在老版本文件记录： file_metadata中有如描述中展示的jar包记录 && 服务器本地存在相同path下的对应文件
2. 接口测试中使用自定义脚本，在脚本中引用1中的第三方jar包
3. 调试/运行

### 期待的正确结果

正确加载第三方jar包

**Comment by 13290445582** [comment]
你好，根据日志看起来URL有些问题，是不是当前站点URL配置错误呢。
![image](https://github.com/user-attachments/assets/f91c0bf8-21c0-43ed-956e-dfdfcbc1fa82)
还有请问是哪个版本升级上来的。

**Comment by gqq5555** [comment]
站点没有配置错误，只是我这边隐藏了真正IP
版本升级是从1.19.2

**Comment by 13290445582** [comment]
您好，版本有点久远了，重新上传下jar包可以正常使用吗

**Comment by gqq5555** [comment]
重新上传是可以的，也是我这边的临时解决办法，但数量蛮多的，还是希望了解下根本原因

**Comment by gqq5555** [comment]
因为node-controller没开源，这个问题又是node-controller报出来的，所以我这边也没办法深入查，你们帮忙评估下能否查一下呢

**Comment by 13290445582** [comment]
您好，目前V2只进行影响主流程的修复，可规避问题暂不考虑了，一些老版本兼容引起的问题再修改起来可能引发更多的问题，为了保持稳定，暂不处理该情况了，遇到的话手动替换下吧，非常抱歉。

**Comment by xchnshi** [comment]
> [<img alt="@github-actions" width="20" height="20" src="https://private-avatars.githubusercontent.com/in/15368?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MzQyNjEzNjAsIm5iZiI6MTczNDI2MDE2MCwicGF0aCI6Ii9pbi8xNTM2OCJ9.lf2IKPo5alYIWBb4SApqkO_ZbqeuZiBxEh-xToPTjvo&amp;s=40&amp;v=4">](/apps/github-actions) [github-actions](/apps/github-actions) bot added [ 状态:待用户反馈 ](/metersphere/metersphere/labels/%E7%8A%B6%E6%80%81%3A%E5%BE%85%E7%94%A8%E6%88%B7%E5%8F%8D%E9%A6%88) and removed [ 状态:待处理 ](/metersphere/metersphere/labels/%E7%8A%B6%E6%80%81%3A%E5%BE%85%E5%A4%84%E7%90%86) labels [Dec 13, 2024](#event-15644471408)
我们也遇到了这个问题，这个不修复，项目jar文件基本就用不了吧？
