### ISSUE TITLE
[BUG] ms升级后不断重启

### ISSUE THREAD

**Issue by Halecoder** [metersphere/metersphere#34671]
### MeterSphere 版本

v3.6.0

### 使用外置数据库

否

### 问题描述

无法启动，不断重启

### 重现步骤

启动docker后出现
```java
2024-12-16 17:24:50 2024-12-16 17:24:50,903  INFO       com.zaxxer.hikari.HikariDataSource: 109 - DatebookHikariCP - Starting...
2024-12-16 17:24:51 2024-12-16 17:24:51,137  INFO        com.zaxxer.hikari.pool.HikariPool: 554 - DatebookHikariCP - Added connection com.mysql.cj.jdbc.ConnectionImpl@1263d20d
2024-12-16 17:24:51 2024-12-16 17:24:51,140  INFO       com.zaxxer.hikari.HikariDataSource: 122 - DatebookHikariCP - Start completed.
2024-12-16 17:24:51 2024-12-16 17:24:51,183  INFO         org.flywaydb.core.FlywayExecutor:  37 - Database: jdbc:mysql://172.25.51.69:3308/metersphere (MySQL 8.0)
2024-12-16 17:24:51 2024-12-16 17:24:51,358  INFO flywaydb.core.internal.command.DbMigrate:  37 - Current version of schema `metersphere`: 3.5.0.2
2024-12-16 17:24:51 2024-12-16 17:24:51,404  WARN ConfigServletWebServerApplicationContext: 633 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'schedulerStarter': Unsatisfied dependency expressed through field 'scheduler': Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Schema `metersphere` contains a failed migration to version 3.5.0.2 !
2024-12-16 17:24:51 2024-12-16 17:24:51,405  INFO       com.zaxxer.hikari.HikariDataSource: 349 - DatebookHikariCP - Shutdown initiated...
2024-12-16 17:24:51 2024-12-16 17:24:51,431  INFO       com.zaxxer.hikari.HikariDataSource: 351 - DatebookHikariCP - Shutdown completed.
2024-12-16 17:24:51 2024-12-16 17:24:51,454  INFO .logging.ConditionEvaluationReportLogger:  82 - 
2024-12-16 17:24:51 
2024-12-16 17:24:51 Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-12-16 17:24:51 2024-12-16 17:24:51,473 ERROR g.springframework.boot.SpringApplication: 859 - Application run failed
2024-12-16 17:24:51 org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'schedulerStarter': Unsatisfied dependency expressed through field 'scheduler': Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Schema `metersphere` contains a failed migration to version 3.5.0.2 !
2024-12-16 17:24:51     at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:788)
2024-12-16 17:24:51     at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:768)
2024-12-16 17:24:51     at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:145)
2024-12-16 17:24:51     at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:509)
2024-12-16 17:24:51     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1439)
2024-12-16 17:24:51     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
2024-12-16 17:24:51     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
2024-12-16 17:24:51     at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
2024-12-16 17:24:51     at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
2024-12-16 17:24:51     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
2024-12-16 17:24:51     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:205)
2024-12-16 17:24:51     at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:277)
2024-12-16 17:24:51     at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:806)
2024-12-16 17:24:51     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:609)
2024-12-16 17:24:51     at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
2024-12-16 17:24:51     at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
2024-12-16 17:24:51     at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
2024-12-16 17:24:51     at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
2024-12-16 17:24:51     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
2024-12-16 17:24:51     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
2024-12-16 17:24:51     at io.metersphere.Application.main(Application.java:30)
2024-12-16 17:24:51 Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Schema `metersphere` contains a failed migration to version 3.5.0.2 !
2024-12-16 17:24:51     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1806)
2024-12-16 17:24:51     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600)
2024-12-16 17:24:51     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
2024-12-16 17:24:51     at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
2024-12-16 17:24:51     at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
2024-12-16 17:24:51     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
2024-12-16 17:24:51     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
2024-12-16 17:24:51     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:313)
2024-12-16 17:24:51     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
2024-12-16 17:24:51     at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
2024-12-16 17:24:51     at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443)
2024-12-16 17:24:51     at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353)
2024-12-16 17:24:51     at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:785)
2024-12-16 17:24:51     ... 20 common frames omitted
2024-12-16 17:24:51 Caused by: org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Schema `metersphere` contains a failed migration to version 3.5.0.2 !
2024-12-16 17:24:51     at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:218)
2024-12-16 17:24:51     at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:139)
2024-12-16 17:24:51     at org.flywaydb.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:58)
2024-12-16 17:24:51     at org.flywaydb.database.mysql.MySQLConnection.lock(MySQLConnection.java:150)
2024-12-16 17:24:51     at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:145)
2024-12-16 17:24:51     at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:139)
2024-12-16 17:24:51     at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:97)
2024-12-16 17:24:51     at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:202)
2024-12-16 17:24:51     at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:205)
2024-12-16 17:24:51     at org.flywaydb.core.Flyway.migrate(Flyway.java:147)
2024-12-16 17:24:51     at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
2024-12-16 17:24:51     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
2024-12-16 17:24:51     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1802)
2024-12-16 17:24:51     ... 32 common frames omitted
2024-12-16 17:24:51 17:24:51,478 |-INFO in ch.qos.logback.classic.AsyncAppender[infoAsyncAppender] - Worker thread will flush remaining events before exiting. 
2024-12-16 17:24:51 17:24:51,479 |-INFO in ch.qos.logback.classic.AsyncAppender[infoAsyncAppender] - Queue flush finished successfully within timeout.
2024-12-16 17:24:51 17:24:51,479 |-INFO in ch.qos.logback.classic.AsyncAppender[warnAsyncAppender] - Worker thread will flush remaining events before exiting. 
2024-12-16 17:24:51 17:24:51,480 |-INFO in ch.qos.logback.classic.AsyncAppender[warnAsyncAppender] - Queue flush finished successfully within timeout.
2024-12-16 17:24:51 17:24:51,480 |-INFO in ch.qos.logback.classic.AsyncAppender[errorAsyncAppender] - Worker thread will flush remaining events before exiting. 
2024-12-16 17:24:51 17:24:51,481 |-INFO in ch.qos.logback.classic.AsyncAppender[errorAsyncAppender] - Queue flush finished successfully within timeout.
```

**Comment by liuruibin** [comment]
https://metersphere.io/docs/v3.x/ask_question/install_question/?h=mig#2-mysql
