### ISSUE TITLE
[BUG]测试接口时请求接口超时，再次点击测试按钮，会出现获取报告失败的提示，并且请求地址和请求头为空

### ISSUE THREAD

**Issue by kouzhijian** [metersphere/metersphere#3630]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.10
**Bug 描述**
简要描述您碰到的问题
如题
**Bug 重现步骤**
1、接口定义页面，测试接口时，请求接口超时
2、再次点击测试接口，弹出提示”获取报告失败“，此时看到请求内容中的请求地址和请求头都为空

**期待的正确结果**
正确情况下应该是什么样的？
不报错，再次点击请求会再次发起请求
**截图**
如果有截图，请附上截图.
![QQ截图20210608171753](https://user-images.githubusercontent.com/33210000/121159885-2ceb8880-c87e-11eb-9f41-2ab791e1dec0.png)

**Comment by zyyfit** [comment]
您好，请问是必现的吗？这边没有复现呢

**Comment by kouzhijian** [comment]
2021-06-17 15:54:08,808 [qtp1101598632-39] INFO  org.apache.jmeter.util.JMeterUtils 349 - Setting Locale to zh_CN
2021-06-17 15:54:08,809 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine ? - Running the test!
2021-06-17 15:54:08,810 [StandardJMeterEngine] INFO  o.apache.jmeter.samplers.SampleEvent ? - List of sample_variables: []
2021-06-17 15:54:08,811 [StandardJMeterEngine] INFO  o.a.j.v.backend.BackendListener 315 - 0530ba58: Starting worker with class: class io.metersphere.api.jmeter.APIBackendListenerClient and queue capacity: 5000
2021-06-17 15:54:08,812 [StandardJMeterEngine] INFO  o.a.j.v.backend.BackendListener 322 - 0530ba58: Started  worker with class: class io.metersphere.api.jmeter.APIBackendListenerClient
2021-06-17 15:54:09,144 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine ? - Starting ThreadGroup: 1 : ThreadGroup
2021-06-17 15:54:09,144 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine 511 - Starting 1 threads for group ThreadGroup.
2021-06-17 15:54:09,144 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine 521 - Thread will continue on error
2021-06-17 15:54:09,144 [StandardJMeterEngine] INFO  o.apache.jmeter.threads.ThreadGroup 220 - Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false
2021-06-17 15:54:09,149 [StandardJMeterEngine] INFO  o.apache.jmeter.threads.ThreadGroup 248 - Started thread group number 1
2021-06-17 15:54:09,149 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine 462 - All thread groups have been started
2021-06-17 15:54:09,149 [ThreadGroup 1-1] INFO  o.apache.jmeter.threads.JMeterThread 727 - Thread started: ThreadGroup 1-1
2021-06-17 15:54:09,784 [ThreadGroup 1-1] INFO  o.apache.jmeter.threads.JMeterThread 327 - Thread finished: ThreadGroup 1-1
2021-06-17 15:54:09,795 [StandardJMeterEngine] INFO  o.a.j.engine.StandardJMeterEngine 214 - Notifying test listeners of end of test
2021-06-17 15:54:09,796 [Thread-54] INFO  o.a.j.v.backend.BackendListener 235 - Worker ended
2021-06-17 15:54:09,802 [StandardJMeterEngine] WARN  o.a.j.engine.StandardJMeterEngine 223 - Error encountered during shutdown of org.apache.jmeter.visualizers.backend.BackendListener@257500c8
java.lang.IllegalStateException: Failed calling teardownTest
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:377)
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:383)
        at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:218)
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:493)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.metersphere.commons.exception.MSException: Test cannot be found:
        at io.metersphere.commons.exception.MSException.throwException(MSException.java:14)
        at io.metersphere.api.service.ApiDefinitionService.addResult(ApiDefinitionService.java:606)
        at io.metersphere.api.service.ApiDefinitionService$$FastClassBySpringCGLIB$$72d8ca15.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
        at io.metersphere.api.service.ApiDefinitionService$$EnhancerBySpringCGLIB$$eff0535.addResult(<generated>)
        at io.metersphere.api.service.ApiDefinitionService$$FastClassBySpringCGLIB$$72d8ca15.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
        at io.metersphere.api.service.ApiDefinitionService$$EnhancerBySpringCGLIB$$6403f381.addResult(<generated>)
        at io.metersphere.api.jmeter.APIBackendListenerClient.teardownTest(APIBackendListenerClient.java:217)
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:375)
        ... 4 common frames omitted

**Comment by xulinde** [comment]
使用新版本还有此问题吗
