### ISSUE TITLE
[BUG] 使用变量生成url，多加了方括号

### ISSUE THREAD

**Issue by juewuer** [metersphere/metersphere#445]
**MeterSphere 版本**
v1.2.1

**Bug 描述**
使用变量生成url，多加了方括号

**Bug 重现步骤**
1.  在预执行脚本里增加
vars.put("neutron_url", "10.111.82.18:9696");
2. 请求url  http://${neutron_url}/v2.0/domains
3. 调试执行发现实际执行结果 GET http://[10.111.82.18:9696]/v2.0/domains
4. 响应报错
java.net.URISyntaxException: Malformed IPv6 address at index 8: http://[10.111.82.18:9696]/v2.0/domains
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.parseIPv6Reference(URI.java:3469)
	at java.net.URI$Parser.parseServer(URI.java:3219)
	at java.net.URI$Parser.parseAuthority(URI.java:3155)
	at java.net.URI$Parser.parseHierarchical(URI.java:3097)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URL.toURI(URL.java:953)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.sample(HTTPHC4Impl.java:535)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:67)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1282)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1271)
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:627)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:551)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:490)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:257)
	at java.lang.Thread.run(Thread.java:748)

**期待的正确结果**

**截图**
如果有截图，请附上截图.

**Comment by liuruibin** [comment]
这个冒号被jmeter识别成了一个ipv6的地址，可以对端口使用单独的变量

**Comment by AgAngle** [comment]
可以在环境配置统一的url
