### ISSUE TITLE
[BUG] 配置外部kafka提示Error connecting to node kafka:9092

### ISSUE THREAD

**Issue by 619851705** [metersphere/metersphere#454]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？

**Bug 描述**
简要描述您碰到的问题

**Bug 重现步骤**
1.  
2. 
3. 
4. 

2020-09-22 19:53:01,705 WARN o.a.k.c.NetworkClient: [Producer clientId=producer-1] Error connecting to node kafka:9092 (id: 1001 rack: null)
java.net.UnknownHostException: kafka
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281) ~[?:1.8.0_242]
	at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[?:1.8.0_242]
	at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[?:1.8.0_242]
	at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:104) ~[jmeter.backendlistener.kafka-1.0.2.jar:?]
	at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(ClusterConnectionStates.java:403) ~[jmeter.backendlistener.kafka-1.0.2.jar:?]
	at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.access$200(ClusterConnectionStates.java:363) ~[jmeter.backendlistener.kafka-1.0.2.jar:?]
	at org.apache.kafka.clients.ClusterConnectionStates.currentAddress(ClusterConnectionStates.java:151) ~[jmeter.backendlistener.kafka-1.0.2.jar:?]
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:943) [jmeter.backendlistener.kafka-1.0.2.jar:?]
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288) [jmeter.backendlistener.kafka-1.0.2.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.sendProducerData(Sender.java:357) [jmeter.backendlistener.kafka-1.0.2.jar:?]
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:330) [jmeter.backendlistener.kafka-1.0.2.jar:?]

**Comment by 619851705** [comment]
配置kafka.bootstrap-servers=192.168.10.161:9092还是连接kafka：9092

**Comment by wangzhen-fit2cloud** [comment]
你好, 目前安装包是通过容器环境变量的方式加载配置的, 环境变量的优先级要高于配置文件, 因此在 metersphere.properties 中修改的配置不会生效.
可以修改安装目录中的 docker-compose-server.yaml 文件, 注释掉 kafka 相关配置, 或直接修改安装目录(默认 /opt/metersphere) 中的 .env 文件中的变量值, 执行 msctl reload 重新加载应用来修改相关配置

**Comment by qianhangkang** [comment]
metersphere-offline-installer-v2.10.18 也遇到这样的问题，只启动 node-controller，install.conf 和 .env 里确定配置了正确的kafka地址，msctl reload 后还是提示 Error connecting to node kafka:9092 

临时解决方案是把本地启动的 kafka 容器和 zk 容器的网络切换到 node-controller 所在的网络 metersphere_ms-network
但如果你是通过二进制包的方式启动 kafka 和 zk，那还是得想办法解决 node-controller 参数传递的问题 :(
