### ISSUE TITLE
[BUG]性能测试报错，有日志

### ISSUE THREAD

**Issue by seasoncool** [metersphere/metersphere#5034]
您所使用的 MeterSphere 版本是？
1.11

**Bug 描述**

不确定是不是，**我们加了 backend lisenter的原因**，开始测试的时候日志中报错了，而且我们**没有收到 backend lisenter的监听数据**。

简要描述您碰到的问题

2021-07-26 09:48:13,301 Error filtering class com.google.common.collect.MapMakerInternalMap$WeakValueReferenceImpl, it will be ignored java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_275]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757) ~[?:1.8.0_275]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_275]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[?:1.8.0_275]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_275]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_275]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_275]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_275]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_275]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_275]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_275]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_275]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_275]
	at org.apache.jorphan.reflect.ClassFinder$ExtendsClassFilter.isChildOf(ClassFinder.java:100) ~[jorphan.jar:5.4.1]
	at org.apache.jorphan.reflect.ClassFinder$ExtendsClassFilter.accept(ClassFinder.java:86) ~[jorphan.jar:5.4.1]
	at org.apache.jorphan.reflect.ClassFinder.applyFiltering(ClassFinder.java:404) ~[jorphan.jar:5.4.1]
	at org.apache.jorphan.reflect.ClassFinder.lambda$findClassesInOnePath$2(ClassFinder.java:364) ~[jorphan.jar:5.4.1]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) [?:1.8.0_275]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) [?:1.8.0_275]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) [?:1.8.0_275]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) [?:1.8.0_275]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) [?:1.8.0_275]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) [?:1.8.0_275]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) [?:1.8.0_275]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) [?:1.8.0_275]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_275]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) [?:1.8.0_275]
	at org.apache.jorphan.reflect.ClassFinder.findClassesInOnePath(ClassFinder.java:362) [jorphan.jar:5.4.1]
	at org.apache.jorphan.reflect.ClassFinder.findClasses(ClassFinder.java:326) [jorphan.jar:5.4.1]
	at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:299) [jorphan.jar:5.4.1]
	at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:231) [jorphan.jar:5.4.1]
	at org.apache.jmeter.engine.util.CompoundVariable.<clinit>(CompoundVariable.java:72) [ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.engine.util.ValueReplacer.<init>(ValueReplacer.java:43) [ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.engine.PreCompiler.<init>(PreCompiler.java:54) [ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:362) [ApacheJMeter_core.jar:5.4.1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
2021-07-26 09:48:25,897 Backend Listener: Starting worker with class: class io.github.rahulsinghai.jmeter.backendlistener.kafka.KafkaBackendClient and queue capacity: 20000
2021-07-26 09:48:25,940 Backend Listener: Started  worker with class: class io.github.rahulsinghai.jmeter.backendlistener.kafka.KafkaBackendClient

**期待的正确结果**
我在jmeter 里面自己添加的 后台监听 希望能够正确回传 数据

**Comment by liuruibin** [comment]
在node-controller的info.log 里找到
![image](https://user-images.githubusercontent.com/23045261/127425739-af43c45c-eaec-45d2-9208-534fd998f1d5.png)
这样的地址，下载到本地检查jmx是否复合要求
