### ISSUE TITLE
快速安装启动不成功

### ISSUE THREAD

**Issue by itlidaye** [metersphere/metersphere#528]
按照快速开始的步骤进行部署
执行完了curl -sSL https://github.com/metersphere/metersphere/releases/latest/download/quick_start.sh | sh命令后

执行 msctl status 后结果如下

       Name                     Command                  State                              Ports                        
-------------------------------------------------------------------------------------------------------------------------
kafka                /opt/bitnami/scripts/kafka ...   Up (healthy)   0.0.0.0:19092->19092/tcp, 9092/tcp                  
ms-data-streaming    /deployments/run-java.sh         Restarting                                                         
ms-node-controller   /deployments/run-java.sh         Exit 1                                                             
ms-server            /deployments/run-java.sh         Exit 1                                                             
mysql                docker-entrypoint.sh mysqld      Up (healthy)   0.0.0.0:3307->3306/tcp, 33060/tcp                   
zookeeper            /opt/bitnami/scripts/zooke ...   Up (healthy)   0.0.0.0:2181->2181/tcp, 2888/tcp, 3888/tcp, 8080/tcp

多次重试后结果一样

**Comment by wangzhen-fit2cloud** [comment]
请执行下以下命令查看启动日志
```bash
docker logs ms-server
```

**Comment by itlidaye** [comment]
docker logs ms-server

ERROR in ch.qos.logback.core.rolling.RollingFileAppender[debugAppender] - openFile(/opt/metersphere/logs/metersphere/debug.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/metersphere/debug.log (Permission denied)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[infoAppender] - openFile(/opt/metersphere/logs/metersphere/info.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/metersphere/info.log (Permission denied)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[errorAppender] - openFile(/opt/metersphere/logs/metersphere/error.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/metersphere/error.log (Permission denied)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[warnAppender] - openFile(/opt/metersphere/logs/metersphere/warn.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/metersphere/warn.log (Permission denied)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[debugAppender] - openFile(/opt/metersphere/logs/metersphere/debug.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/metersphere/debug.log (Permission denied)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[infoAppender] - openFile(/opt/metersphere/logs/metersphere/info.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/metersphere/info.log (Permission denied)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[errorAppender] - openFile(/opt/metersphere/logs/metersphere/error.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/metersphere/error.log (Permission denied)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[warnAppender] - openFile(/opt/metersphere/logs/metersphere/warn.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/metersphere/warn.log (Permission denied)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:169)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:80)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:118)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:313)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:288)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:246)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:223)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at io.metersphere.Application.main(Application.java:28)
	... 8 more

docker logs ms-data-streaming

eption: /opt/metersphere/logs/data-streaming/debug.log (Permission denied)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[infoAppender] - openFile(/opt/metersphere/logs/data-streaming/info.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/data-streaming/info.log (Permission denied)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[errorAppender] - openFile(/opt/metersphere/logs/data-streaming/error.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/data-streaming/error.log (Permission denied)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[warnAppender] - openFile(/opt/metersphere/logs/data-streaming/warn.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/data-streaming/warn.log (Permission denied)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:169)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:80)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:118)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:313)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:288)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:246)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:223)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at io.metersphere.streaming.Application.main(Application.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)

docker logs ms-node-controller

ERROR in ch.qos.logback.core.rolling.RollingFileAppender[warnAppender] - openFile(/opt/metersphere/logs/node-controller/warn.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/node-controller/warn.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[debugAppender] - Failed to create parent directories for [/opt/metersphere/logs/node-controller/debug.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[debugAppender] - openFile(/opt/metersphere/logs/node-controller/debug.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/node-controller/debug.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[infoAppender] - Failed to create parent directories for [/opt/metersphere/logs/node-controller/info.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[infoAppender] - openFile(/opt/metersphere/logs/node-controller/info.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/node-controller/info.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[errorAppender] - Failed to create parent directories for [/opt/metersphere/logs/node-controller/error.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[errorAppender] - openFile(/opt/metersphere/logs/node-controller/error.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/node-controller/error.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[warnAppender] - Failed to create parent directories for [/opt/metersphere/logs/node-controller/warn.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[warnAppender] - openFile(/opt/metersphere/logs/node-controller/warn.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/node-controller/warn.log (No such file or directory)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:169)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:80)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:118)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:313)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:288)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:246)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:223)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at io.metersphere.node.Application.main(Application.java:17)
	... 8 more


[root@shiku183 data-streaming]# ls
debug.log  error.log  info.log  warn.log
[root@shiku183 data-streaming]# pwd
/opt/metersphere/logs/data-streaming
[root@shiku183 data-streaming]# cd ../metersphere/
[root@shiku183 metersphere]# ls
debug.log  error.log  info.log  warn.log
[root@shiku183 metersphere]# pwd
/opt/metersphere/logs/metersphere
[root@shiku183 metersphere]# cd ../ms-node-controller/
[root@shiku183 ms-node-controller]# ls
debug.log  error.log  info.log  warn.log
[root@shiku183 ms-node-controller]# pwd
/opt/metersphere/logs/ms-node-controller
[root@shiku183 ms-node-controller]# 

这些文件都是创建了并且存在的

**Comment by itlidaye** [comment]
[root@shiku183 ms-node-controller]# msctl status

       Name                     Command                  State                              Ports                        
-------------------------------------------------------------------------------------------------------------------------
kafka                /opt/bitnami/scripts/kafka ...   Up (healthy)   0.0.0.0:19092->19092/tcp, 9092/tcp                  
ms-data-streaming    /deployments/run-java.sh         Restarting                                                         
ms-node-controller   /deployments/run-java.sh         Exit 1                                                             
ms-server            /deployments/run-java.sh         Exit 1                                                             
mysql                docker-entrypoint.sh mysqld      Up (healthy)   0.0.0.0:3307->3306/tcp, 33060/tcp                   
zookeeper            /opt/bitnami/scripts/zooke ...   Up (healthy)   0.0.0.0:2181->2181/tcp, 2888/tcp, 3888/tcp, 8080/tcp

**Comment by itlidaye** [comment]
@wangzhen-fit2cloud @fit2cloudrd

**Comment by wangzhen-fit2cloud** [comment]
请检查下 selinux 状态，如果是开启状态，请尝试关闭后再重启 docker 及 metersphere 试一下
```bash
systemctl restart docker
msctl reload
```

**Comment by itlidaye** [comment]
已解决，谢谢
