### ISSUE TITLE
[BUG]ms-server 微服务报空指针

### ISSUE THREAD

**Issue by junejulyjune** [metersphere/metersphere#5605]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？ v1.11.3

**Bug 描述**

ms-server 微服务报空指针

**Bug 重现步骤**

1. docker logs ms-server

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by junejulyjune** [comment]
2021-08-24 06:44:41,234  INFO ion.mgt.AbstractValidatingSessionManager: 275 - Validating all active sessions...
2021-08-24 06:44:41,234  INFO ion.mgt.AbstractValidatingSessionManager: 308 - Finished session validation.  No sessions were stopped.
CN-50
CN-50
CN-50
CN-50
CN-50
CN-50
CN-50
CN-50
java.lang.NullPointerException
	at java.lang.String.replace(String.java:2240)
	at io.metersphere.api.dto.definition.request.sampler.MsHTTPSamplerProxy.getRestParameters(MsHTTPSamplerProxy.java:569)
	at io.metersphere.api.dto.definition.request.sampler.MsHTTPSamplerProxy.setSamplerPath(MsHTTPSamplerProxy.java:361)
	at io.metersphere.api.dto.definition.request.sampler.MsHTTPSamplerProxy.toHashTree(MsHTTPSamplerProxy.java:209)
	at io.metersphere.api.dto.definition.request.MsScenario.toHashTree(MsScenario.java:176)
	at io.metersphere.api.dto.definition.request.MsThreadGroup.toHashTree(MsThreadGroup.java:42)
	at io.metersphere.api.dto.definition.request.MsTestPlan.lambda$toHashTree$0(MsTestPlan.java:28)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at io.metersphere.api.dto.definition.request.MsTestPlan.toHashTree(MsTestPlan.java:27)
	at io.metersphere.api.service.ApiAutomationService.generateHashTree(ApiAutomationService.java:1268)
	at io.metersphere.api.service.ApiAutomationService.excute(ApiAutomationService.java:1379)
	at io.metersphere.api.service.ApiAutomationService.run(ApiAutomationService.java:1405)
	at io.metersphere.api.service.ApiAutomationService$$FastClassBySpringCGLIB$$a31b65d1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at io.metersphere.api.service.ApiAutomationService$$EnhancerBySpringCGLIB$$418fc281.run(<generated>)
	at io.metersphere.api.service.ApiAutomationService$$FastClassBySpringCGLIB$$a31b65d1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at io.metersphere.api.service.ApiAutomationService$$EnhancerBySpringCGLIB$$89a82975.run(<generated>)
	at io.metersphere.job.sechedule.ApiScenarioTestJob.businessExecute(ApiScenarioTestJob.java:78)
	at io.metersphere.job.sechedule.ApiScenarioTestJob.execute(ApiScenarioTestJob.java:55)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

**Comment by zyyfit** [comment]
您好，请问是什么情况下出现的这个问题呢

**Comment by junejulyjune** [comment]
表象是：内存溢出后，启动ms-server会概率出站报空指针发自我的华为手机-------- 原始邮件 --------发件人： zyyfit ***@***.***>日期： 2021年8月26日周四 00:20收件人： metersphere/metersphere ***@***.***>抄送： junejulyjune ***@***.***>, Author ***@***.***>主    题： Re: [metersphere/metersphere] [BUG]ms-server 微服务报空指针 (#5605)

您好，请问是什么情况下出现的这个问题呢

**Comment by xulinde** [comment]
该问题已解决，您这个版本太老了，建议升级下
