### ISSUE TITLE
[BUG]1.12最新版性能压测依旧各种问题

### ISSUE THREAD

**Issue by rayshen3** [metersphere/metersphere#6042]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？   
v1.12

**Bug 描述**

简要描述您碰到的问题

从自动化接口创建压测任务
1、执行后，压测报告一致running状态，就算压测时间结束了，还是running状态
2、执行性能测试：报"Cannot read property 'jmx' of null"
3、压测报告所有页面无任何返回值， 但实际去看业务，已经有压测流量过来了

![image](https://user-images.githubusercontent.com/9734936/132480516-671fc14f-35ef-4dcd-b4fc-d06751121d18.png)
![image](https://user-images.githubusercontent.com/9734936/132480175-d84c92ff-25b7-4815-b3f3-a724074e58a7.png)
![image](https://user-images.githubusercontent.com/9734936/132479861-85381260-017c-4bf9-b71a-a6ebb39d3ffc.png)

4、node-controller error日志(/opt/metersphere/logs/node-controller/error.log)
```
2021-09-08 16:56:27,448 [docker-java-stream-721054442] ERROR i.m.n.service.JmeterOperateService$1 169 - Method[onComplete][Remove container error: ]
org.springframework.kafka.KafkaException: Send failed; nested exception is org.apache.kafka.common.errors.TimeoutException: Topic JMETER_LOGS not present in metadata after 60000 ms.
        at org.springframework.kafka.core.KafkaTemplate.doSend(KafkaTemplate.java:591)
        at org.springframework.kafka.core.KafkaTemplate.send(KafkaTemplate.java:380)
        at io.metersphere.node.service.KafkaProducer.sendMessage(KafkaProducer.java:15)
        at io.metersphere.node.service.JmeterOperateService$1.onComplete(JmeterOperateService.java:88)
        at com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec$1.onComplete(AbstrAsyncDockerCmdExec.java:51)
        at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:276)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.errors.TimeoutException: Topic JMETER_LOGS not present in metadata after 60000 ms.
2021-09-08 17:02:37,316 [docker-java-stream-439705491] ERROR i.m.n.service.JmeterOperateService$1 169 - Method[onComplete][Remove container error: ]
com.github.dockerjava.api.exception.NotFoundException: Status 404: Could not find the file /jmeter-log/d3ead87d-d705-4899-bb02-476669627051.jtl in container 9065afe80fc1126edbf69ae03d5959d72a676caec5f0da5736e6c4038f6a9aba
        at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:62)
        at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:172)
        at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:160)
        at org.glassfish.jersey.process.internal.Stages.process(Stages.java:147)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:302)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:630)
        at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:665)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:659)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
        at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:659)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:629)
        at com.github.dockerjava.jaxrs.JerseyDockerHttpClient.execute(JerseyDockerHttpClient.java:297)
        at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
        at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:202)
        at com.github.dockerjava.core.exec.CopyArchiveFromContainerCmdExec.execute(CopyArchiveFromContainerCmdExec.java:30)
        at com.github.dockerjava.core.exec.CopyArchiveFromContainerCmdExec.execute(CopyArchiveFromContainerCmdExec.java:13)
        at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
        at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
        at com.github.dockerjava.core.command.CopyArchiveFromContainerCmdImpl.exec(CopyArchiveFromContainerCmdImpl.java:70)
        at io.metersphere.node.service.JmeterOperateService.copyTestResources(JmeterOperateService.java:133)
        at io.metersphere.node.service.JmeterOperateService.access$000(JmeterOperateService.java:35)
        at io.metersphere.node.service.JmeterOperateService$1.onComplete(JmeterOperateService.java:81)
        at com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec$1.onComplete(AbstrAsyncDockerCmdExec.java:51)
        at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:276)
        at java.lang.Thread.run(Thread.java:748)
2021-09-08 17:03:40,982 [docker-java-stream--1535845265] ERROR i.m.n.service.JmeterOperateService$1 ? - Method[onComplete][Remove container error: ]
com.github.dockerjava.api.exception.NotFoundException: Status 404: Could not find the file /jmeter-log/ff2854e4-1c29-4adf-a458-dbb48e557d95.jtl in container cd5ad3b852b081686aee164de18b54e8a3985e8345288e81c7f3a755ac4aa641
        at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:62)
        at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:172)
        at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:160)
        at org.glassfish.jersey.process.internal.Stages.process(Stages.java:147)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:302)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:630)
        at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:665)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:659)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
        at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:659)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:629)
        at com.github.dockerjava.jaxrs.JerseyDockerHttpClient.execute(JerseyDockerHttpClient.java:297)
        at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
        at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:202)
        at com.github.dockerjava.core.exec.CopyArchiveFromContainerCmdExec.execute(CopyArchiveFromContainerCmdExec.java:30)
        at com.github.dockerjava.core.exec.CopyArchiveFromContainerCmdExec.execute(CopyArchiveFromContainerCmdExec.java:13)
        at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
        at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
        at com.github.dockerjava.core.command.CopyArchiveFromContainerCmdImpl.exec(CopyArchiveFromContainerCmdImpl.java:70)
        at io.metersphere.node.service.JmeterOperateService.copyTestResources(JmeterOperateService.java:133)
        at io.metersphere.node.service.JmeterOperateService.access$000(JmeterOperateService.java:35)
        at io.metersphere.node.service.JmeterOperateService$1.onComplete(JmeterOperateService.java:81)
        at com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec$1.onComplete(AbstrAsyncDockerCmdExec.java:51)
        at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:276)
        at java.lang.Thread.run(Thread.java:748)
```

node-controller info.log

```
2021-09-08 17:13:13,506 [kafka-producer-network-thread | producer-1] WARN  o.apache.kafka.clients.NetworkClient ? - [Producer clientId=producer-1] Connection to node -1 (/192.168.17.245:19092) could not be established. Broker may not be available.
2021-09-08 17:13:13,506 [kafka-producer-network-thread | producer-1] WARN  o.apache.kafka.clients.NetworkClient ? - [Producer clientId=producer-1] Bootstrap broker 192.168.17.245:19092 (id: -1 rack: null) disconnected
2021-09-08 17:13:14,460 [kafka-producer-network-thread | producer-1] WARN  o.apache.kafka.clients.NetworkClient ? - [Producer clientId=producer-1] Connection to node -1 (/192.168.17.245:19092) could not be established. Broker may not be available.
2021-09-08 17:13:14,461 [kafka-producer-network-thread | producer-1] WARN  o.apache.kafka.clients.NetworkClient 1079 - [Producer clientId=producer-1] Bootstrap broker 192.168.17.245:19092 (id: -1 rack: null) disconnected
2021-09-08 17:13:15,514 [kafka-producer-network-thread | producer-1] WARN  o.apache.kafka.clients.NetworkClient ? - [Producer clientId=producer-1] Connection to node -1 (/192.168.17.245:19092) could not be established. Broker may not be available.
2021-09-08 17:13:15,515 [kafka-producer-network-thread | producer-1] WARN  o.apache.kafka.clients.NetworkClient ? - [Producer clientId=producer-1] Bootstrap broker 192.168.17.245:19092 (id: -1 rack: null) disconnected
2021-09-08 17:13:16,618 [kafka-producer-network-thread | producer-1] WARN  o.apache.kafka.clients.NetworkClient ? - [Producer clientId=producer-1] Connection to node -1 (/192.168.17.245:19092) could not be established. Broker may not be available.
2021-09-08 17:13:16,619 [kafka-producer-network-thread | producer-1] WARN  o.apache.kafka.clients.NetworkClient ? - [Producer clientId=producer-1] Bootstrap broker 192.168.17.245:19092 (id: -1 rack: null) disconnected
2021-09-08 17:13:17,773 [kafka-producer-network-thread | producer-1] WARN  o.apache.kafka.clients.NetworkClient ? - [Producer clientId=producer-1] Connection to node -1 (/192.168.17.245:19092) could not be established. Broker may not be available.
2021-09-08 17:13:17,773 [kafka-producer-network-thread | producer-1] WARN  o.apache.kafka.clients.NetworkClient ? - [Producer clientId=producer-1] Bootstrap broker 192.168.17.245:19092 (id: -1 rack: null) disconnected
2021-09-08 17:13:18,777 [kafka-producer-network-thread | producer-1] WARN  o.apache.kafka.clients.NetworkClient ? - [Producer clientId=producer-1] Connection to node -1 (/192.168.17.245:19092) could not be established. Broker may not be available.
2021-09-08 17:13:18,778 [kafka-producer-network-thread | producer-1] WARN  o.apache.kafka.clients.NetworkClient ? - [Producer clientId=producer-1] Bootstrap broker 192.168.17.245:19092 (id: -1 rack: null) disconnected
2021-09-08 17:13:19,832 [kafka-producer-network-thread | producer-1] WARN  o.apache.kafka.clients.NetworkClient ? - [Producer clientId=producer-1] Connection to node -1 (/192.168.17.245:19092) could not be established. Broker may not be available.
2021-09-08 17:13:19,832 [kafka-producer-network-thread | producer-1] WARN  o.apache.kafka.clients.NetworkClient ? - [Producer clientId=producer-1] Bootstrap broker 192.168.17.245:19092 (id: -1 rack: null) disconnected
2021-09-08 17:13:20,836 [kafka-producer-network-thread | producer-1] WARN  o.apache.kafka.clients.NetworkClient ? - [Producer clientId=producer-1] Connection to node -1 (/192.168.17.245:19092) could not be established. Broker may not be available.
2021-09-08 17:13:20,837 [kafka-producer-network-thread | producer-1] WARN  o.apache.kafka.clients.NetworkClient ? - [Producer clientId=producer-1] Bootstrap broker 192.168.17.245:19092 (id: -1 rack: null) disconnected
2021-09-08 17:13:21,890 [kafka-producer-network-thread | producer-1] WARN  o.apache.kafka.clients.NetworkClient ? - [Producer clientId=producer-1] Connection to node -1 (/192.168.17.245:19092) could not be established. Broker may not be available.
2021-09-08 17:13:21,890 [kafka-producer-network-thread | producer-1] WARN  o.apache.kafka.clients.NetworkClient 1079 - [Producer clientId=producer-1] Bootstrap broker 192.168.17.245:19092 (id: -1 rack: null) disconnected
2021-09-08 17:13:22,844 [kafka-producer-network-thread | producer-1] WARN  o.apache.kafka.clients.NetworkClient ? - [Producer clientId=producer-1] Connection to node -1 (/192.168.17.245:19092) could not be established. Broker may not be available.
2021-09-08 17:13:22,845 [kafka-producer-network-thread | producer-1] WARN  o.apache.kafka.clients.NetworkClient ? - [Producer clientId=producer-1] Bootstrap broker 192.168.17.245:19092 (id: -1 rack: null) disconnected
2021-09-08 17:13:23,798 [kafka-producer-network-thread | producer-1] WARN  o.apache.kafka.clients.NetworkClient ? - [Producer clientId=producer-1] Connection to node -1 (/192.168.17.245:19092) could not be established. Broker may not be available.
2021-09-08 17:13:23,798 [kafka-producer-network-thread | producer-1] WARN  o.apache.kafka.clients.NetworkClient ? - [Producer clientId=producer-1] Bootstrap broker 192.168.17.245:19092 (id: -1 rack: null) disconnected
```

**Comment by liuruibin** [comment]
检查运行jmeter的镜像是否是 registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master:5.4.1-ms9-jdk8

**Comment by rayshen3** [comment]
> 检查运行jmeter的镜像是否是 registry.cn-qingdao.aliyuncs.com/metersphere/jmeter-master:5.4.1-ms9-jdk8

感谢，确实是版本的问题，用的是ms8-jdk8，更新后解决，但我是按官方手册命令执行的msctl upgrade，不知道哪里出的错..
