### ISSUE TITLE
[BUG]mac部署失败

### ISSUE THREAD

**Issue by a252937166** [metersphere/metersphere#657]
**MeterSphere 版本**
release-v1.4.0

**Bug 描述**
install过程中，出现：

```
WARNING: The HOSTNAME variable is not set. Defaulting to a blank string.
Starting ms-node-controller ...
Creating mysql              ...
Creating zookeeper          ... error

Creating mysql              ... error
e_ms-zookeeper-data/_data: operation not permitted
Starting ms-node-controller ... done
ERROR: for mysql  Cannot create container for service mysql: failed to chmod on /var/lib/docker/volumes/metersphere_ms-mysql-data/_data: chmod /var/lib/docker/volumes/metersphere_ms-mysql-data/_data: operation not permitted

ERROR: for zookeeper  Cannot create container for service zookeeper: failed to chmod on /var/lib/docker/volumes/metersphere_ms-zookeeper-data/_data: chmod /var/lib/docker/volumes/metersphere_ms-zookeeper-data/_data: operation not permitted

ERROR: for mysql  Cannot create container for service mysql: failed to chmod on /var/lib/docker/volumes/metersphere_ms-mysql-data/_data: chmod /var/lib/docker/volumes/metersphere_ms-mysql-data/_data: operation not permitted
ERROR: Encountered errors while bringing up the project.
```

**Bug 重现步骤**
1.  下载metersphere-release-v1.4.0
2. 解压，执行`sudo ./install.sh`
3. 控制台报错
4. 查看docker日志:

```
11:25:30,594 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[debugAppender] - Active log file name: /opt/metersphere/logs/node-controller/debug.log

11:25:30,594 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[debugAppender] - File property is set to [/opt/metersphere/logs/node-controller/debug.log]

11:25:30,600 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[debugAppender] - Failed to create parent directories for [/opt/metersphere/logs/node-controller/debug.log]

11:25:30,601 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[debugAppender] - openFile(/opt/metersphere/logs/node-controller/debug.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/node-controller/debug.log (No such file or directory)

at java.io.FileNotFoundException: /opt/metersphere/logs/node-controller/debug.log (No such file or directory)

at at java.io.FileOutputStream.open0(Native Method)

at at java.io.FileOutputStream.open(FileOutputStream.java:270)

at at java.io.FileOutputStream.<init>(FileOutputStream.java:213)

at at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)

at at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:204)

at at ch.qos.logback.core.FileAppender.start(FileAppender.java:127)

at at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:100)

at at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)

at at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)

at at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)

at at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)

at at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)

at at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)

at at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)

at at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)

at at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)

at at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)

at at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)

at at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)

at at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)

at at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)

at at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)

at at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)

at at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)

at at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)

at at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)

at at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:273)

at at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:196)

at at io.metersphere.node.Application.main(Application.java:17)

at at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at at java.lang.reflect.Method.invoke(Method.java:498)

at at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)

at at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)

at at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)

at at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)

11:25:30,604 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]

11:25:30,605 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [infoAppender]

11:25:30,608 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1972439101 - No compression will be used

11:25:30,608 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1972439101 - Will use the pattern /opt/metersphere/logs/node-controller/history/info.%d{yyyyMMdd}-%i.log for the active file

11:25:30,610 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@77a567e1 - The date pattern is 'yyyyMMdd' from file name pattern '/opt/metersphere/logs/node-controller/history/info.%d{yyyyMMdd}-%i.log'.

11:25:30,610 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@77a567e1 - Roll-over at midnight.

11:25:30,611 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@77a567e1 - Setting initial period to Mon Nov 02 11:25:30 CST 2020

11:25:30,612 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@77a567e1 - SizeAndTimeBasedFNATP is deprecated. Use SizeAndTimeBasedRollingPolicy instead

11:25:30,612 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@77a567e1 - For more information see http://logback.qos.ch/manual/appenders.html#SizeAndTimeBasedRollingPolicy

11:25:30,612 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property

11:25:30,614 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[infoAppender] - Active log file name: /opt/metersphere/logs/node-controller/info.log

11:25:30,614 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[infoAppender] - File property is set to [/opt/metersphere/logs/node-controller/info.log]

11:25:30,616 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[infoAppender] - Failed to create parent directories for [/opt/metersphere/logs/node-controller/info.log]

11:25:30,620 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[infoAppender] - openFile(/opt/metersphere/logs/node-controller/info.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/node-controller/info.log (No such file or directory)

at java.io.FileNotFoundException: /opt/metersphere/logs/node-controller/info.log (No such file or directory)

at at java.io.FileOutputStream.open0(Native Method)

at at java.io.FileOutputStream.open(FileOutputStream.java:270)

at at java.io.FileOutputStream.<init>(FileOutputStream.java:213)

at at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)

at at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:204)

at at ch.qos.logback.core.FileAppender.start(FileAppender.java:127)

at at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:100)

at at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)

at at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)

at at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)

at at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)

at at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)

at at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)

at at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)

at at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)

at at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)

at at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)

at at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)

at at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)

at at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)

at at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)

at at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)

at at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)

at at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)

at at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)

at at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)

at at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:273)

at at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:196)

at at io.metersphere.node.Application.main(Application.java:17)

at at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at at java.lang.reflect.Method.invoke(Method.java:498)

at at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)

at at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)

at at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)

at at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)

11:25:30,621 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]

11:25:30,622 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [errorAppender]

11:25:30,625 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1936628443 - No compression will be used

11:25:30,625 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1936628443 - Will use the pattern /opt/metersphere/logs/node-controller/history/error.%d{yyyyMMdd}-%i.log for the active file

11:25:30,626 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6d21714c - The date pattern is 'yyyyMMdd' from file name pattern '/opt/metersphere/logs/node-controller/history/error.%d{yyyyMMdd}-%i.log'.

11:25:30,626 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6d21714c - Roll-over at midnight.

11:25:30,627 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6d21714c - Setting initial period to Mon Nov 02 11:25:30 CST 2020

11:25:30,627 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6d21714c - SizeAndTimeBasedFNATP is deprecated. Use SizeAndTimeBasedRollingPolicy instead

11:25:30,628 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@6d21714c - For more information see http://logback.qos.ch/manual/appenders.html#SizeAndTimeBasedRollingPolicy

11:25:30,628 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property

11:25:30,629 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[errorAppender] - Active log file name: /opt/metersphere/logs/node-controller/error.log

11:25:30,629 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[errorAppender] - File property is set to [/opt/metersphere/logs/node-controller/error.log]

11:25:30,632 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[errorAppender] - Failed to create parent directories for [/opt/metersphere/logs/node-controller/error.log]

11:25:30,632 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[errorAppender] - openFile(/opt/metersphere/logs/node-controller/error.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/node-controller/error.log (No such file or directory)

at java.io.FileNotFoundException: /opt/metersphere/logs/node-controller/error.log (No such file or directory)

at at java.io.FileOutputStream.open0(Native Method)

at at java.io.FileOutputStream.open(FileOutputStream.java:270)

at at java.io.FileOutputStream.<init>(FileOutputStream.java:213)

at at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)

at at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:204)

at at ch.qos.logback.core.FileAppender.start(FileAppender.java:127)

at at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:100)

at at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)

at at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)

at at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)

at at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)

at at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)

at at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)

at at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)

at at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)

at at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)

at at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)

at at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)

at at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)

at at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)

at at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)

at at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)

at at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)

at at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)

at at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)

at at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)

at at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:273)

at at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:196)

at at io.metersphere.node.Application.main(Application.java:17)

at at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at at java.lang.reflect.Method.invoke(Method.java:498)

at at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)

at at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)

at at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)

at at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)

11:25:30,633 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]

11:25:30,634 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [warnAppender]

11:25:30,636 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@277630005 - No compression will be used

11:25:30,636 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@277630005 - Will use the pattern /opt/metersphere/logs/node-controller/history/warn.%d{yyyyMMdd}-%i.log for the active file

11:25:30,638 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@4ccabbaa - The date pattern is 'yyyyMMdd' from file name pattern '/opt/metersphere/logs/node-controller/history/warn.%d{yyyyMMdd}-%i.log'.

11:25:30,638 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@4ccabbaa - Roll-over at midnight.

11:25:30,639 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@4ccabbaa - Setting initial period to Mon Nov 02 11:25:30 CST 2020

11:25:30,639 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@4ccabbaa - SizeAndTimeBasedFNATP is deprecated. Use SizeAndTimeBasedRollingPolicy instead

11:25:30,639 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@4ccabbaa - For more information see http://logback.qos.ch/manual/appenders.html#SizeAndTimeBasedRollingPolicy

11:25:30,640 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property

11:25:30,641 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[warnAppender] - Active log file name: /opt/metersphere/logs/node-controller/warn.log

11:25:30,641 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[warnAppender] - File property is set to [/opt/metersphere/logs/node-controller/warn.log]

11:25:30,644 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[warnAppender] - Failed to create parent directories for [/opt/metersphere/logs/node-controller/warn.log]

11:25:30,645 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[warnAppender] - openFile(/opt/metersphere/logs/node-controller/warn.log,true) call failed. java.io.FileNotFoundException: /opt/metersphere/logs/node-controller/warn.log (No such file or directory)

at java.io.FileNotFoundException: /opt/metersphere/logs/node-controller/warn.log (No such file or directory)

at at java.io.FileOutputStream.open0(Native Method)

at at java.io.FileOutputStream.open(FileOutputStream.java:270)

at at java.io.FileOutputStream.<init>(FileOutputStream.java:213)

at at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)

at at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:204)

at at ch.qos.logback.core.FileAppender.start(FileAppender.java:127)

at at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:100)

at at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)

at at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)

at at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)

at at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)

at at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)

at at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)

at at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)

at at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)

at at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)

at at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)

at at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)

at at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)

at at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)

at at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)

at at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)

at at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
```

**Comment by wangzhen-fit2cloud** [comment]
你好，mac 安装不能使用 root 用户，请使用普通用户并在该用户有权限的目录执行安装脚本
