### ISSUE TITLE
[BUG]mac本地部署 Kafka 不可用，请检查配置

### ISSUE THREAD

**Issue by a252937166** [metersphere/metersphere#660]
**MeterSphere 版本**
release-v1.4.0

**Bug 描述**
性能测试时，提示"Kafka 不可用，请检查配置"

**Bug 重现步骤**
1.  测试docker端口

```
docker exec ms-server nc -zv kafka 19092
kafka (172.22.0.3:19092) open

docker exec ms-server nc -zv docker.for.mac.host.internal 19092
docker.for.mac.host.internal (192.168.65.2:19092) open

docker exec ms-server nc -zv 10.9.49.67 19092
10.9.49.67 (10.9.49.67:19092) open
```

2. 

```
msctl status

       Name                     Command                   State                               Ports
---------------------------------------------------------------------------------------------------------------------------
kafka                /opt/bitnami/scripts/kafka ...   Up (healthy)     0.0.0.0:19092->19092/tcp, 9092/tcp
ms-data-streaming    /deployments/run-java.sh         Up (unhealthy)   0.0.0.0:8084->8084/tcp, 0.0.0.0:8085->8085/tcp
ms-node-controller   /deployments/run-java.sh         Up (healthy)     0.0.0.0:8082->8082/tcp
ms-server            /deployments/run-java.sh         Up (healthy)     0.0.0.0:8081->8081/tcp
mysql                docker-entrypoint.sh mysqld      Up (healthy)     0.0.0.0:3307->3306/tcp, 33060/tcp
zookeeper            /opt/bitnami/scripts/zooke ...   Up (healthy)     0.0.0.0:2181->2181/tcp, 2888/tcp, 3888/tcp, 8080/tcp
```

3.  .env文件

```
MS_MODE=allinone
MS_KAFKA_TOPIC=JMETER_METRICS
MS_MYSQL_HOST=mysql
MS_KAFKA_LOG_TOPIC=JMETER_LOGS
MS_KAFKA_EXT_HOST=
MS_NODE_CONTROLLER_PORT=8082
MS_TAG=v1.4.0
MS_KAFKA_HOST=10.9.49.67
MS_BASE=/Users/ouyangduning
MS_EXTERNAL_KAFKA=false
MS_KAFKA_PORT=9092
MS_MYSQL_USER=root
MS_EXTERNAL_MYSQL=false
MS_KAFKA_EXT_PORT=19092
MS_PREFIX=registry.cn-qingdao.aliyuncs.com/metersphere
MS_MYSQL_DB=metersphere
MS_MYSQL_PASSWORD=Password123@mysql
MS_JMETER_TAG=5.3-ms11
MS_PORT=8081
MS_MYSQL_PORT=3306
```

**Comment by a252937166** [comment]
ms-data-streaming重要日志：

1.

```
2020-11-03 09:54:24,587  INFO he.kafka.clients.admin.AdminClientConfig: 347 - AdminClientConfig values: 
	bootstrap.servers = [10.9.49.67:9092]
	client.dns.lookup = default
	client.id = 
	connections.max.idle.ms = 300000
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 120000

	retries = 5
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	send.buffer.bytes = 131072
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = https
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS

2020-11-03 09:54:24,812  INFO .apache.kafka.common.utils.AppInfoParser:   ? - Kafka version: 2.3.1
2020-11-03 09:54:24,813  INFO .apache.kafka.common.utils.AppInfoParser: 118 - Kafka commitId: 18a913733fb71c01
2020-11-03 09:54:24,814  INFO .apache.kafka.common.utils.AppInfoParser: 119 - Kafka startTimeMs: 1604368464809
2020-11-03 09:54:24,895  WARN   org.apache.kafka.clients.NetworkClient: 748 - [AdminClient clientId=adminclient-1] Connection to node -1 (/10.9.49.67:9092) could not be established. Broker may not be available.
```
2.

```
2020-11-03 09:54:54,836 ERROR rg.springframework.kafka.core.KafkaAdmin: 149 - Could not configure topics
org.springframework.kafka.KafkaException: Timed out waiting to get existing topics; nested exception is java.util.concurrent.TimeoutException
	at org.springframework.kafka.core.KafkaAdmin.lambda$checkPartitions$4(KafkaAdmin.java:239)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at org.springframework.kafka.core.KafkaAdmin.checkPartitions(KafkaAdmin.java:218)
	at org.springframework.kafka.core.KafkaAdmin.addTopicsIfNeeded(KafkaAdmin.java:204)
	at org.springframework.kafka.core.KafkaAdmin.initialize(KafkaAdmin.java:174)
	at org.springframework.kafka.core.KafkaAdmin.afterSingletonsInstantiated(KafkaAdmin.java:144)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:899)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at io.metersphere.streaming.Application.main(Application.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.util.concurrent.TimeoutException: null
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:108)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:272)
	at org.springframework.kafka.core.KafkaAdmin.lambda$checkPartitions$4(KafkaAdmin.java:221)
	... 23 common frames omitted
2020-11-03 09:54:55,240  WARN   org.apache.kafka.clients.NetworkClient: 748 - [AdminClient clientId=adminclient-1] Connection to node -1 (/10.9.49.67:9092) could not be established. Broker may not be available.
```

**Comment by a252937166** [comment]
kafka启动信息：
```
2020-11-03 02:18:01,131 [myid:1] - INFO  [main:Environment@98] - Server environment:java.library.path=/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
2020-11-03 02:18:01,132 [myid:1] - INFO  [main:Environment@98] - Server environment:java.io.tmpdir=/tmp
2020-11-03 02:18:01,132 [myid:1] - INFO  [main:Environment@98] - Server environment:java.compiler=<NA>
2020-11-03 02:18:01,133 [myid:1] - INFO  [main:Environment@98] - Server environment:os.name=Linux
2020-11-03 02:18:01,134 [myid:1] - INFO  [main:Environment@98] - Server environment:os.arch=amd64
2020-11-03 02:18:01,135 [myid:1] - INFO  [main:Environment@98] - Server environment:os.version=5.4.39-linuxkit
2020-11-03 02:18:01,136 [myid:1] - INFO  [main:Environment@98] - Server environment:user.name=?
2020-11-03 02:18:01,136 [myid:1] - INFO  [main:Environment@98] - Server environment:user.home=?
2020-11-03 02:18:01,136 [myid:1] - INFO  [main:Environment@98] - Server environment:user.dir=/
2020-11-03 02:18:01,137 [myid:1] - INFO  [main:Environment@98] - Server environment:os.memory.free=1009MB
2020-11-03 02:18:01,138 [myid:1] - INFO  [main:Environment@98] - Server environment:os.memory.max=1024MB
2020-11-03 02:18:01,138 [myid:1] - INFO  [main:Environment@98] - Server environment:os.memory.total=1024MB
2020-11-03 02:18:01,139 [myid:1] - INFO  [main:ZooKeeperServer@128] - zookeeper.enableEagerACLCheck = false
2020-11-03 02:18:01,142 [myid:1] - INFO  [main:ZooKeeperServer@136] - zookeeper.digest.enabled = true
2020-11-03 02:18:01,142 [myid:1] - INFO  [main:ZooKeeperServer@140] - zookeeper.closeSessionTxn.enabled = true
2020-11-03 02:18:01,143 [myid:1] - INFO  [main:ZooKeeperServer@1433] - zookeeper.flushDelay=0
2020-11-03 02:18:01,143 [myid:1] - INFO  [main:ZooKeeperServer@1442] - zookeeper.maxWriteQueuePollTime=0
2020-11-03 02:18:01,144 [myid:1] - INFO  [main:ZooKeeperServer@1451] - zookeeper.maxBatchSize=1000
2020-11-03 02:18:01,144 [myid:1] - INFO  [main:ZooKeeperServer@241] - zookeeper.intBufferStartingSizeBytes = 1024
2020-11-03 02:18:01,150 [myid:1] - INFO  [main:BlueThrottle@141] - Weighed connection throttling is disabled
2020-11-03 02:18:01,154 [myid:1] - INFO  [main:ZooKeeperServer@1246] - minSessionTimeout set to 4000
2020-11-03 02:18:01,154 [myid:1] - INFO  [main:ZooKeeperServer@1255] - maxSessionTimeout set to 40000
2020-11-03 02:18:01,157 [myid:1] - INFO  [main:ResponseCache@45] - Response cache size is initialized with value 400.
2020-11-03 02:18:01,157 [myid:1] - INFO  [main:ResponseCache@45] - Response cache size is initialized with value 400.
2020-11-03 02:18:01,161 [myid:1] - INFO  [main:RequestPathMetricsCollector@111] - zookeeper.pathStats.slotCapacity = 60
2020-11-03 02:18:01,161 [myid:1] - INFO  [main:RequestPathMetricsCollector@112] - zookeeper.pathStats.slotDuration = 15
2020-11-03 02:18:01,162 [myid:1] - INFO  [main:RequestPathMetricsCollector@113] - zookeeper.pathStats.maxDepth = 6
2020-11-03 02:18:01,162 [myid:1] - INFO  [main:RequestPathMetricsCollector@114] - zookeeper.pathStats.initialDelay = 5
2020-11-03 02:18:01,163 [myid:1] - INFO  [main:RequestPathMetricsCollector@115] - zookeeper.pathStats.delay = 5
2020-11-03 02:18:01,163 [myid:1] - INFO  [main:RequestPathMetricsCollector@116] - zookeeper.pathStats.enabled = false
2020-11-03 02:18:01,169 [myid:1] - INFO  [main:ZooKeeperServer@1470] - The max bytes for all large requests are set to 104857600
2020-11-03 02:18:01,170 [myid:1] - INFO  [main:ZooKeeperServer@1484] - The large request threshold is set to -1
2020-11-03 02:18:01,171 [myid:1] - INFO  [main:ZooKeeperServer@329] - Created server with tickTime 2000 minSessionTimeout 4000 maxSessionTimeout 40000 clientPortListenBacklog -1 datadir /bitnami/zookeeper/data/version-2 snapdir /bitnami/zookeeper/data/version-2
2020-11-03 02:18:01,224 [myid:1] - INFO  [main:Log@169] - Logging initialized @1285ms to org.eclipse.jetty.util.log.Slf4jLog
2020-11-03 02:18:01,376 [myid:1] - WARN  [main:ContextHandler@1520] - o.e.j.s.ServletContextHandler@17bffc17{/,null,UNAVAILABLE} contextPath ends with /*
2020-11-03 02:18:01,376 [myid:1] - WARN  [main:ContextHandler@1531] - Empty contextPath
2020-11-03 02:18:01,406 [myid:1] - INFO  [main:Server@359] - jetty-9.4.24.v20191120; built: 2019-11-20T21:37:49.771Z; git: 363d5f2df3a8a28de40604320230664b9c793c16; jvm 11.0.6+10
2020-11-03 02:18:01,475 [myid:1] - INFO  [main:DefaultSessionIdManager@333] - DefaultSessionIdManager workerName=node0
2020-11-03 02:18:01,475 [myid:1] - INFO  [main:DefaultSessionIdManager@338] - No SessionScavenger set, using defaults
2020-11-03 02:18:01,479 [myid:1] - INFO  [main:HouseKeeper@140] - node0 Scavenging every 600000ms
2020-11-03 02:18:01,507 [myid:1] - INFO  [main:ContextHandler@825] - Started o.e.j.s.ServletContextHandler@17bffc17{/,null,AVAILABLE}
2020-11-03 02:18:01,531 [myid:1] - INFO  [main:AbstractConnector@330] - Started ServerConnector@2034b64c{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2020-11-03 02:18:01,535 [myid:1] - INFO  [main:Server@399] - Started @1595ms
2020-11-03 02:18:01,535 [myid:1] - INFO  [main:JettyAdminServer@178] - Started AdminServer on address 0.0.0.0, port 8080 and command URL /commands
2020-11-03 02:18:01,557 [myid:1] - INFO  [main:ServerCnxnFactory@169] - Using org.apache.zookeeper.server.NIOServerCnxnFactory as server connection factory
2020-11-03 02:18:01,560 [myid:1] - WARN  [main:ServerCnxnFactory@309] - maxCnxns is not configured, using default value 0.
2020-11-03 02:18:01,564 [myid:1] - INFO  [main:NIOServerCnxnFactory@666] - Configuring NIO connection handler with 10s sessionless connection timeout, 1 selector thread(s), 12 worker threads, and 64 kB direct buffers.
2020-11-03 02:18:01,568 [myid:1] - INFO  [main:NIOServerCnxnFactory@674] - binding to port 0.0.0.0/0.0.0.0:2181
2020-11-03 02:18:01,592 [myid:1] - INFO  [main:WatchManagerFactory@42] - Using org.apache.zookeeper.server.watch.WatchManager as watch manager
2020-11-03 02:18:01,593 [myid:1] - INFO  [main:WatchManagerFactory@42] - Using org.apache.zookeeper.server.watch.WatchManager as watch manager
2020-11-03 02:18:01,596 [myid:1] - INFO  [main:ZKDatabase@132] - zookeeper.snapshotSizeFactor = 0.33
2020-11-03 02:18:01,597 [myid:1] - INFO  [main:ZKDatabase@152] - zookeeper.commitLogCount=500
2020-11-03 02:18:01,609 [myid:1] - INFO  [main:SnapStream@61] - zookeeper.snapshot.compression.method = CHECKED
2020-11-03 02:18:01,620 [myid:1] - INFO  [main:FileSnap@85] - Reading snapshot /bitnami/zookeeper/data/version-2/snapshot.1aff
2020-11-03 02:18:01,633 [myid:1] - INFO  [main:DataTree@1730] - The digest in the snapshot has digest version of 2, , with zxid as 0x1aff, and digest value as 42356415688
2020-11-03 02:18:01,766 [myid:1] - INFO  [main:FileTxnSnapLog@363] - 1118 txns loaded in 65 ms
2020-11-03 02:18:01,767 [myid:1] - INFO  [main:ZKDatabase@289] - Snapshot loaded in 169 ms, highest zxid is 0x1f5d, digest is 42285489094
2020-11-03 02:18:01,768 [myid:1] - INFO  [main:FileTxnSnapLog@470] - Snapshotting: 0x1f5d to /bitnami/zookeeper/data/version-2/snapshot.1f5d
2020-11-03 02:18:01,778 [myid:1] - INFO  [main:ZooKeeperServer@519] - Snapshot taken in 9 ms
2020-11-03 02:18:01,799 [myid:1] - INFO  [main:RequestThrottler@74] - zookeeper.request_throttler.shutdownTimeout = 10000
2020-11-03 02:18:01,821 [myid:1] - INFO  [main:ContainerManager@83] - Using checkIntervalMs=60000 maxPerMinute=10000 maxNeverUsedIntervalMs=0
2020-11-03 02:18:01,824 [myid:1] - INFO  [main:ZKAuditProvider@42] - ZooKeeper audit is disabled.
2020-11-03 02:18:04,453 [myid:1] - INFO  [SyncThread:0:FileTxnLog@284] - Creating new log file: log.1f5e
2020-11-03 02:18:06,642 [myid:1] - WARN  [NIOWorkerThread-3:NIOServerCnxn@364] - Unexpected exception
EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /127.0.0.1:56068, session = 0x100002407690001
	at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
	at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
	at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-11-03 02:18:13,887 [myid:1] - WARN  [NIOWorkerThread-4:NIOServerCnxn@364] - Unexpected exception
EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /127.0.0.1:56126, session = 0x100002407690003
	at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
	at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
	at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-11-03 02:18:21,066 [myid:1] - WARN  [NIOWorkerThread-1:NIOServerCnxn@364] - Unexpected exception
EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /127.0.0.1:56176, session = 0x100002407690004
	at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
	at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
	at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by holysor** [comment]
刚搭建的环境，运行性能测试也这个提示：Kafka 不可用，请检查配置

**Comment by holysor** [comment]
> 刚搭建的环境，运行性能测试也这个提示：Kafka 不可用，请检查配置

![image](https://user-images.githubusercontent.com/17400810/98229476-ec98f480-1f94-11eb-9e42-e4220a616b75.png)

**Comment by xulinde** [comment]
您好，参照https://metersphere.io/docs/faq/#qkafka

**Comment by a252937166** [comment]
你好，我已经参照过文档了，kafka服务正常，但是依旧提示不可用，走到“联系技术支持那个流程了”

**Comment by shizp** [comment]
这个有解决办法么，遇到一样的问题

**Comment by Notfound1011** [comment]
我也遇到了这个问题，麻烦技术大大看看啦

**Comment by abcanqi** [comment]
兄弟们，把 hostname 配到 /etc/hosts 里

1. 通过`hostname`命令获取hostname
2. 将部署 node-controller 的机器的ip地址，配置到部署 ms-server 的机器的 /etc/hosts 里

例如：
```vim
127.0.0.1 hostname
```
