### ISSUE TITLE
[BUG]拖动有用例的模块到另一个模块下报错

### ISSUE THREAD

**Issue by Joyyangit** [metersphere/metersphere#6632]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.13

**Bug 描述**

拖动有用例的模块到另一个模块下报错

**Bug 重现步骤**

1.  新建同级模块A和B
2. 拖动A模块到B模块成为B模块的子模块，此时可以拖动成功，无报错
3. 将A模块拖动到和B模块为同级模块
4. 在A模块下方新建一条用例
5. 拖动A模块到B模块下级，此时报错SQL error happened, please check logs.
6. `Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'order' cannot be null
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:832)
`

**期待的正确结果**
拖动有用例的模块到另一个模块下可正常成为另一个模块的子模块

**截图**

如果有截图，请附上截图.

**Comment by xulinde** [comment]
v1.13.1已修复
