### ISSUE TITLE
[BUG]性能测试 跑几个小时 导致mysql 挂掉

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#6646]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
V1.13.1
**Bug 描述**
性能测试 跑几个小时 导致mysql 挂掉
简要描述您碰到的问题

**Bug 重现步骤**

1.

Method[run][Could not open JDBC Connection for transaction; nested exception is java.sql.SQLTransientConnectionException: DatebookHikariCP - Connection is not available, request timed out after 47651ms.]
org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is java.sql.SQLTransientConnectionException: DatebookHikariCP - Connection is not available, request timed out after 47651ms.
        at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:309)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:595)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:382)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
        at io.metersphere.notice.service.NotificationService$$EnhancerBySpringCGLIB$$4c0f9d09.countNotification(<generated>)
        at io.metersphere.websocket.NotificationWebSocket$NotificationCenter.run(NotificationWebSocket.java:100)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: java.sql.SQLTransientConnectionException: DatebookHikariCP - Connection is not available, request timed out after 47651ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
        at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:265)
        ... 12 common frames omitted
Caused by: java.sql.SQLNonTransientConnectionException: **No operations allowed after connection closed.**
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
        at com.mysql.cj.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:2480)
        at com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:566)
        at com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:173)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)

2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
感谢反馈，我们排查一下问题

**Comment by liuruibin** [comment]
错误显示后台查询通知时无法获取链接，这个是10s一次
