### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by YellowFly2** [metersphere/metersphere#6759]
**MeterSphere 版本**
>v1.13.1

**Bug 描述**

运行case无法找到环境中的URL
    org.apache.http.client.ClientProtocolException: URI does not specify a valid host name: http:/api/dkb/v1/stateNotification
	at org.apache.http.impl.client.CloseableHttpClient.determineTarget(CloseableHttpClient.java:95)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.executeRequest(HTTPHC4Impl.java:935)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.sample(HTTPHC4Impl.java:646)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:66)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1296)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1285)
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:652)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:571)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:486)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:250)
	at java.lang.Thread.run(Thread.java:748)

**Bug 重现步骤**

1.  接口test可以找到host地址
2. 接口case运行环境找不到host地址

**Comment by zyyfit** [comment]
您好，没有复现这个问题，能描述一下详细操作步骤吗？或者升级到最新版看看还有没有这个问题
