### ISSUE TITLE
[BUG]在页面上切回旧版，选择导出json文件的接口，切回新版，导入接口文件，报解析错误

### ISSUE THREAD

**Issue by shenkaibo** [metersphere/metersphere#7228]
**MeterSphere 版本**
>v1.10是MeterSphere的首个LTS版本，建议升级到该版本后再次验证是否能重现该问题。

您所使用的 MeterSphere 版本是？
v1.13.2
**Bug 描述**
在页面上切回旧版，选择导出json文件的接口，切回新版，导入接口文件，报解析错误
简要描述您碰到的问题

**Bug 重现步骤**

1.
切回旧版
![image](https://user-images.githubusercontent.com/30038088/139042860-ef459184-02f5-49a6-a011-7ddef98e799c.png)
2.
切回新版
3.
导入
![image](https://user-images.githubusercontent.com/30038088/139043681-a69ccafb-c5a3-4969-b7db-aeed0d92cbf1.png)

4.报错日志
2021-10-27 17:52:11,636 [qtp1261714285-77216] ERROR i.m.api.service.ApiDefinitionService ? - Method[apiTestImport][syntax error, pos 1, line 1, column 2MS API CONFIG]
com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2MS API CONFIG
        at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1481)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1367)
        at com.alibaba.fastjson.JSON.parse(JSON.java:182)
        at com.alibaba.fastjson.JSON.parse(JSON.java:192)
        at com.alibaba.fastjson.JSON.parse(JSON.java:148)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:253)
        at com.alibaba.fastjson.JSONObject.getJSONObject(JSONObject.java:131)
        at io.metersphere.api.parse.MsAbstractParser.parseMsHTTPSamplerProxy(MsAbstractParser.java:20)
        at io.metersphere.api.dto.definition.parse.MsDefinitionParser.lambda$parsePluginFormat$0(MsDefinitionParser.java:59)
        at java.util.LinkedHashMap$LinkedKeySet.forEach(LinkedHashMap.java:559)
        at io.metersphere.api.dto.definition.parse.MsDefinitionParser.parsePluginFormat(MsDefinitionParser.java:54)
        at io.metersphere.api.dto.definition.parse.MsDefinitionParser.parse(MsDefinitionParser.java:47)
        at io.metersphere.api.dto.definition.parse.MsDefinitionParser.parse(MsDefinitionParser.java:23)
        at io.metersphere.api.service.ApiDefinitionService.apiTestImport(ApiDefinitionService.java:935)
        at io.metersphere.api.service.ApiDefinitionService$$FastClassBySpringCGLIB$$72d8ca15.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

**Comment by zyyfit** [comment]
旧版和新版数据格式不一致，建议采用系统自带的数据迁移功能
