### ISSUE TITLE
[BUG]本地MS平台已开通网络端口的情况下，添加华为云node节点失败

### ISSUE THREAD

**Issue by zhangzhaox** [metersphere/metersphere#7503]
**MeterSphere 版本**
版本:   v1.13.2-6ac3675a
![image](https://user-images.githubusercontent.com/82088551/140270061-b075f2e5-94d7-4015-8785-7e639196f911.png)
![image](https://user-images.githubusercontent.com/82088551/140270266-2591b952-9ada-42b9-9b07-8475c0f65cdf.png)
node端开放了8082 9100端口  MS平台端 开放了8081 19092端口

**Bug 描述**
2021-11-04 14:42:27,840 [qtp114109618-13057] ERROR i.m.service.NodeResourcePoolService ? - Method[validateNode][503 Service Unavaliable: [<html><head></head><body>The site you are accessing matched the timeout or default action. The URL or page has been blocked.</body></html>]]
org.springframework.web.client.HttpServerErrorException$ServiceUnavailable: 503 Service Unavaliable: [<html><head></head><body>The site you are accessing matched the timeout or default action. The URL or page has been blocked.</body></html>]
	at org.springframework.web.client.HttpServerErrorException.create(HttpServerErrorException.java:112)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:188)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)
	at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:361)
	at io.metersphere.service.NodeResourcePoolService.validateNode(NodeResourcePoolService.java:101)
	at io.metersphere.service.NodeResourcePoolService.validate(NodeResourcePoolService.java:69)
	at io.metersphere.service.NodeResourcePoolService$$FastClassBySpringCGLIB$$7e636630.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at io.metersphere.service.NodeResourcePoolService$$EnhancerBySpringCGLIB$$b7550833.validate(<generated>)
	at io.metersphere.service.NodeResourcePoolService$$FastClassBySpringCGLIB$$7e636630.invoke(<generated>)

**Comment by youliyuan-fit2cloud** [comment]
看看本地MS平台的ms-server容器和华为云node节点网络是否是通的

**Comment by zhangzhaox** [comment]
[root@ZHCS-XNCSPT-AP3 ~]# docker exec -i 3d330b16f44a /bin/bash
OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown
![image](https://user-images.githubusercontent.com/82088551/141223762-6a5cd9d4-e781-414e-940c-1ac591e31a1a.png)

没反映
V13.2版本

**Comment by zhangzhaox** [comment]
![image](https://user-images.githubusercontent.com/82088551/141226085-a81015e4-bf97-4447-a48b-a5bdab912489.png)

**Comment by zhangzhaox** [comment]
问题已解决，本地MS服务器的网络权限配置问题
