### ISSUE TITLE
[BUG]metersphere服务所在服务器需要添加外网代理才能访问外网，但在ms-server容器里也配置好了外网代理，且通过系统命令能成功访问外网的前提下，使用ms-server发送企业微信消息失败，日志显示连接外网超时。

### ISSUE THREAD

**Issue by sephirothgao** [metersphere/metersphere#7586]
**MeterSphere 版本**

v1.2

**Bug 描述**

[BUG]metersphere服务所在服务器需要添加外网代理才能访问外网，但在ms-server容器里也配置好了外网代理，且通过系统命令能成功访问外网的前提下，使用ms-server发送企业微信消息失败，日志显示连接外网超时。

**Bug 重现步骤**

1.  登录到ms-server中，使用系统命令可以成功访问外网。
/ # curl  http://qyapi.weixin.qq.com
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

2. 使用ms-server的系统消息发送功能，发送企业微信消息，日志显示连接外网服务超时。
2021-11-08 10:55:00,166 [Async-Executor-3] INFO  i.m.n.sender.impl.WeComNoticeSender ? - Method[sendWechatRobot][企业微信收件人: [null]]
2021-11-08 10:55:14,204 [Async-Executor-3] ERROR i.m.n.sender.impl.WeComNoticeSender 176 - Method[sendWechatRobot][Connect to qyapi.weixin.qq.com:443 [qyapi.weixin.qq.com/183.192.202.172, qyapi.weixin.qq.com/117.184.242.103] failed: Operation timed out (Connection timed out)]
org.apache.http.conn.HttpHostConnectException: Connect to qyapi.weixin.qq.com:443 [qyapi.weixin.qq.com/183.192.202.172, qyapi.weixin.qq.com/117.184.242.103] failed: Operation timed out (Connection timed out)
    at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
    at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
4. 

**期待的正确结果**

成功发送企业微信消息。

**截图**

如果有截图，请附上截图.

**Comment by sephirothgao** [comment]
@shenkaibo

**Comment by shenkaibo** [comment]
@wangzhen-fit2cloud

**Comment by wangzhen-fit2cloud** [comment]
你好，发送消息通知的相关功能目前无法应用到系统配置的相关参数，会在后续版本修改解决。

**Comment by xulinde** [comment]
最新版本v1.20.4已修复，建议升级
