### ISSUE TITLE
[BUG]MailService不支持非SSL的SMTP邮件服务器

### ISSUE THREAD

**Issue by password36** [metersphere/metersphere#768]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
1.4.3
**Bug 描述**
简要描述您碰到的问题
邮件配置使用非SSL SMTP服务器时会返回
Exception in thread "main" org.springframework.mail.MailSendException: Mail server connection failed; nested exception is javax.mail.MessagingException: Could not connect to SMTP host: mail.xxxxxxxxxx port: 25;
  nested exception is:
	javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?. Failed messages: javax.mail.MessagingException: Could not connect to SMTP host: mail.xxxxxxxx, port: 25;
  nested exception is:
	javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?; message exception details (1) are:
Failed message 1:
javax.mail.MessagingException: Could not connect to SMTP host: mail.xxxxxxxx port: 25;
  nested exception is:
	javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2212)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:722)
	at javax.mail.Service.connect(Service.java:342)
	at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:518)
	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:437)
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:361)
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:356)
	at io.metersphere.notice.service.MailService.sendApiOrLoadNotification(MailService.java:105)
	at io.metersphere.notice.service.TestMailService.main(TestMailService.java:10)

问题在于master版本MailService.java的getMailSender() 未实现界面配置的选项。
javaMailSender.setProtocol("smtps"); 默认使用了SMTPS
props.put("mail.smtp.starttls.enable", "true");  关联选项也是写死的
props.put("mail.smtp.starttls.required", "true");
**Bug 重现步骤**
1.  邮件配置SMTP，端口使用25
2. 不勾选开启TLS，开启SSL

**期待的正确结果**
正确情况下应该是什么样的？

**截图**
如果有截图，请附上截图.

**Comment by password36** [comment]
经实际测试，修改代码里的下属内容可以连接到非SSL的SMTP并正常发送邮件
javaMailSender.setProtocol("smtp"); 
props.put("mail.smtp.starttls.enable", "false"); 
props.put("mail.smtp.starttls.required", "false");

**Comment by wangzhen-fit2cloud** [comment]
你好，十分感谢你的反馈。我们会确认下这个问题，然后建议这种情况可以直接给我们提交 pull request 哈
