### ISSUE TITLE
[QUESTION] zookeeper一直报错，无法联通其它docker

### ISSUE THREAD

**Issue by mythinks** [metersphere/metersphere#8302]
zookeeper中一直报如下错误（使用快速安装）：

猜想，应该是各docker中的hostname没配置导致，但无法最终确认问题，请帮助确认，感谢！
另外，zookeeper是否也独立出来进行部署？

2021-12-02 13:53:09,044 [myid:1] - INFO  [SessionTracker:ZooKeeperServer@600] - Expiring session 0x1001030d0b10131, timeout of 30000ms exceeded
2021-12-02 13:53:11,876 [myid:1] - WARN  [NIOWorkerThread-3:NIOServerCnxn@364] - Unexpected exception
EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /127.0.0.1:53894, session = 0x1001030d0b1013a
	at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
	at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
	at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-12-02 13:53:15,044 [myid:1] - INFO  [SessionTracker:ZooKeeperServer@600] - Expiring session 0x1001030d0b10132, timeout of 30000ms exceeded
2021-12-02 13:53:18,606 [myid:1] - WARN  [NIOWorkerThread-6:NIOServerCnxn@364] - Unexpected exception
EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /127.0.0.1:53898, session = 0x1001030d0b1013c
	at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
	at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
	at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by mythinks** [comment]
是否还有其它信息需要提供？

**Comment by wangzhen-fit2cloud** [comment]
你好，请检查下 selinux 的状态是否开启。如果是开启状态，可以关闭 selinux 后，重启 docker 服务及 metersphere 的容器再试一下
```
setenforce 0
service docker restart
msctl restart
```

**Comment by mythinks** [comment]
你好，这些均已尝试，无论在阿里云，还是线下使用vmware虚拟机，均报一样的错误

**Comment by wangzhen-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/27671436/147427174-ec5d595e-1b67-43ee-86d9-edb5032003a7.png)
你好，如果方便的话可以加下微信群联系我们同事远程看一下。

**Comment by liuruibin** [comment]
我在测试中发现执行一段时间后zookeeper的health check会不停的报这个EndOfStreamException，在v1.18中会将docker-compose-kafka.yml中的health check脚本修改，你可以自行查看installer工程的v1.18分支
