### ISSUE TITLE
[BUG]jython-standalone版本不兼容出现 URI is not hierarchical错误

### ISSUE THREAD

**Issue by Laimf1995** [metersphere/metersphere#8370]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.15

**Bug 描述**

jython-standalone版本不兼容出现 URI is not hierarchical错误
不能执行Beanshell的python脚本
Tips：本地IDEA运行没问题

**Bug 重现步骤**

1.  打jar包运行
2. 启动报错 URI is not hierarchical. 
3.  at java.io.File.<init>(File.java:418)
  at org.python.core.PrePy.getJarFileNameFromURL(PrePy.java:427)
  at org.python.core.PrePy._getJarFileName(PrePy.java:362)
  at org.python.core.PrePy.getJarFileName(PrePy.java:345)
  at org.python.core.PySystemState.doInitialize(PySystemState.java:1195)
  at org.python.core.PySystemState.initialize(PySystemState.java:1130)
  at org.python.core.PySystemState.initialize(PySystemState.java:1085)
  at org.python.core.PySystemState.initialize(PySystemState.java:1080)
  at org.python.core.PySystemState.initialize(PySystemState.java:1075)
  at org.python.core.PySystemState.initialize(PySystemState.java:1070)
  at org.python.core.ThreadStateMapping.getThreadState(ThreadStateMapping.java:56)
  at org.python.core.Py.getThreadState(Py.java:1741)
  at org.python.core.Py.getThreadState(Py.java:1737)
  at org.python.core.Py.getSystemState(Py.java:1757)
  at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:100)
  at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:93)
  at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:70)
  at io.metersphere.listener.AppStartListener.initPythonEnv(AppStartListener.java:148)
  at io.metersphere.listener.AppStartListener.onApplicationEvent(AppStartListener.java:82)
  at io.metersphere.listener.AppStartListener.onApplicationEvent(AppStartListener.java:30)
  at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
  at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
  at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
  at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
  at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:111)
  at org.springframework.boot.SpringApplicationRunListeners.lambda$running$6(SpringApplicationRunListeners.java:79)
  at java.util.ArrayList.forEach(ArrayList.java:1257)
  at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
  at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
  at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:79)
  at org.springframework.boot.SpringApplication.run(SpringApplication.java:353)
  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
  at io.metersphere.Application.main(Application.java:30)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
  at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
  at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
  at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

**期待的正确结果**

建议修改版本为2.7.0，可解决问题
jython-standalone 2.7.0

**截图**

如果有截图，请附上截图.

**Comment by fit2-zhao** [comment]
@Laimf1995 l 请问用的是我们发布的安装包吗，未曾发现启动有这个错误。如果是特殊脚本执行有错误，可以贴出来看一下，是否新版本语法有调整。

**Comment by Laimf1995** [comment]
经过排查，该问题可能会出现在第一次启动的时候。

非安装包，是拉取的github工程，自己编译打包的。

具体日志为
2021-12-07 20:12:55,951  INFO                              io.undertow: 120 - starting server: Undertow - 2.2.10.Final
2021-12-07 20:12:55,955  INFO .web.embedded.undertow.UndertowWebServer: 119 - Undertow started on port(s) 8083 (https)
2021-12-07 20:12:56,300  INFO k.scheduling.quartz.SchedulerFactoryBean: 732 - Will start Quartz Scheduler [clusterScheduler] in 60 seconds
================= 应用启动 =================
java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(File.java:418)
	at org.python.core.PrePy.getJarFileNameFromURL(PrePy.java:427)
	at org.python.core.PrePy._getJarFileName(PrePy.java:362)
	at org.python.core.PrePy.getJarFileName(PrePy.java:345)
	at org.python.core.PySystemState.doInitialize(PySystemState.java:1195)
	at org.python.core.PySystemState.initialize(PySystemState.java:1130)
	at org.python.core.PySystemState.initialize(PySystemState.java:1085)
	at org.python.core.PySystemState.initialize(PySystemState.java:1080)
	at org.python.core.PySystemState.initialize(PySystemState.java:1075)
	at org.python.core.PySystemState.initialize(PySystemState.java:1070)
	at org.python.core.ThreadStateMapping.getThreadState(ThreadStateMapping.java:56)
	at org.python.core.Py.getThreadState(Py.java:1741)
	at org.python.core.Py.getThreadState(Py.java:1737)
	at org.python.core.Py.getSystemState(Py.java:1757)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:100)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:93)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:70)
	at io.metersphere.listener.AppStartListener.initPythonEnv(AppStartListener.java:148)
	at io.metersphere.listener.AppStartListener.onApplicationEvent(AppStartListener.java:82)
	at io.metersphere.listener.AppStartListener.onApplicationEvent(AppStartListener.java:30)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:111)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$running$6(SpringApplicationRunListeners.java:79)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:79)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:353)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
	at io.metersphere.Application.main(Application.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

**Comment by fit2-zhao** [comment]
@Laimf1995 检查一下打的包中是否有 /lib/ext/  jython-standalone.jar

**Comment by Laimf1995** [comment]
在linux中运行我把默认配置改为读取/opt目录下，打出的jar包，也copy到该目录。
具体出现问题，可参考该文章。出现报错是一样的。
https://www.bianchengquan.com/article/546726.html

Tips：观察你node节点版本还是2.7.0，这个版本不会报错

**Comment by fit2-zhao** [comment]
@Laimf1995  感谢反馈
![image](https://user-images.githubusercontent.com/70558837/145520364-f8a29ef9-601f-4aa9-92a3-16101e2285b9.png)

**Comment by kingfocus31** [comment]
大佬，怎么解决的？出现同样问题
