### ISSUE TITLE
[BUG]接口测试用例执行卡死，无消息推送

### ISSUE THREAD

**Issue by Saco93** [metersphere/metersphere#8807]
**MeterSphere 版本**

1.16.0

**Bug 描述**

接口测试用例执行卡死，无消息推送

**Bug 重现步骤**

1.  执行接口用例。
2. 页面持续在执行状态，无消息推送

执行日志
```log
2021-12-24 11:31:24,949 [Async-Executor-15] INFO  i.m.n.sender.AbstractNoticeSender ? - Method[handleFollows][FOLLOW_PEOPLE: []]
2021-12-24 11:31:24,949 [Async-Executor-15] INFO  i.m.n.sender.impl.InSiteNoticeSender ? - Method[sendAnnouncement][发送站内通知: [Receiver(userId=noah.huang, type=SYSTEM_NOTICE)]]
2021-12-24 11:31:28,253 [Timer-96] ERROR i.m.w.ApiReportWebSocket$ApiReportTask 176 - Method[run][UT003037: Message is null]
java.lang.IllegalArgumentException: UT003037: Message is null
        at io.undertow.websockets.jsr.WebSocketSessionRemoteEndpoint$BasicWebSocketSessionRemoteEndpoint.sendText(WebSocketSessionRemoteEndpoint.java:255)
        at io.metersphere.websocket.ApiReportWebSocket$ApiReportTask.run(ApiReportWebSocket.java:98)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
2021-12-24 11:31:31,255 [Timer-96] ERROR i.m.w.ApiReportWebSocket$ApiReportTask 176 - Method[run][UT003037: Message is null]
java.lang.IllegalArgumentException: UT003037: Message is null
        at io.undertow.websockets.jsr.WebSocketSessionRemoteEndpoint$BasicWebSocketSessionRemoteEndpoint.sendText(WebSocketSessionRemoteEndpoint.java:255)
        at io.metersphere.websocket.ApiReportWebSocket$ApiReportTask.run(ApiReportWebSocket.java:98)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
2021-12-24 11:31:34,253 [Timer-96] ERROR i.m.w.ApiReportWebSocket$ApiReportTask 176 - Method[run][UT003037: Message is null]
java.lang.IllegalArgumentException: UT003037: Message is null
        at io.undertow.websockets.jsr.WebSocketSessionRemoteEndpoint$BasicWebSocketSessionRemoteEndpoint.sendText(WebSocketSessionRemoteEndpoint.java:255)
        at io.metersphere.websocket.ApiReportWebSocket$ApiReportTask.run(ApiReportWebSocket.java:98)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
2021-12-24 11:31:37,255 [Timer-96] ERROR i.m.w.ApiReportWebSocket$ApiReportTask 176 - Method[run][UT003037: Message is null]
java.lang.IllegalArgumentException: UT003037: Message is null
        at io.undertow.websockets.jsr.WebSocketSessionRemoteEndpoint$BasicWebSocketSessionRemoteEndpoint.sendText(WebSocketSessionRemoteEndpoint.java:255)
        at io.metersphere.websocket.ApiReportWebSocket$ApiReportTask.run(ApiReportWebSocket.java:98)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
2021-12-24 11:31:40,255 [Timer-96] ERROR i.m.w.ApiReportWebSocket$ApiReportTask 176 - Method[run][UT003037: Message is null]
java.lang.IllegalArgumentException: UT003037: Message is null
        at io.undertow.websockets.jsr.WebSocketSessionRemoteEndpoint$BasicWebSocketSessionRemoteEndpoint.sendText(WebSocketSessionRemoteEndpoint.java:255)
        at io.metersphere.websocket.ApiReportWebSocket$ApiReportTask.run(ApiReportWebSocket.java:98)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
2021-12-24 11:31:43,255 [Timer-96] ERROR i.m.w.ApiReportWebSocket$ApiReportTask 176 - Method[run][UT003037: Message is null]
java.lang.IllegalArgumentException: UT003037: Message is null
        at io.undertow.websockets.jsr.WebSocketSessionRemoteEndpoint$BasicWebSocketSessionRemoteEndpoint.sendText(WebSocketSessionRemoteEndpoint.java:255)
        at io.metersphere.websocket.ApiReportWebSocket$ApiReportTask.run(ApiReportWebSocket.java:98)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
2021-12-24 11:31:46,255 [Timer-96] ERROR i.m.w.ApiReportWebSocket$ApiReportTask 176 - Method[run][UT003037: Message is null]
java.lang.IllegalArgumentException: UT003037: Message is null
        at io.undertow.websockets.jsr.WebSocketSessionRemoteEndpoint$BasicWebSocketSessionRemoteEndpoint.sendText(WebSocketSessionRemoteEndpoint.java:255)
        at io.metersphere.websocket.ApiReportWebSocket$ApiReportTask.run(ApiReportWebSocket.java:98)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
2021-12-24 11:31:49,254 [Timer-96] ERROR i.m.w.ApiReportWebSocket$ApiReportTask 176 - Method[run][UT003037: Message is null]
java.lang.IllegalArgumentException: UT003037: Message is null
        at io.undertow.websockets.jsr.WebSocketSessionRemoteEndpoint$BasicWebSocketSessionRemoteEndpoint.sendText(WebSocketSessionRemoteEndpoint.java:255)
        at io.metersphere.websocket.ApiReportWebSocket$ApiReportTask.run(ApiReportWebSocket.java:98)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
```

**期待的正确结果**

执行结束（成功/失败），右上角消息推送。

**截图**

![image](https://user-images.githubusercontent.com/34698664/147313042-f95f3f56-4fe7-4ec3-8cd0-2b91ecad2c8f.png)

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by Saco93** [comment]
### MeterSphere 版本：1.16.5
 
**_问题依然存在_**

### info.log报错
```log
2022-01-18 19:42:42,830 [XNIO-1 task-13] INFO  i.m.commons.utils.SessionUtils ? - Method[getCurrentWorkspaceId][WORKSPACE: null]
2022-01-18 19:42:43,049 [XNIO-1 task-1] ERROR io.undertow.websockets.jsr.request ? - UT026001: Unable to instantiate endpoint
java.lang.IllegalArgumentException: Illegal character in path at index 27: /api/definition/run/report/[object%20Object]/run
	at java.net.URI.create(URI.java:852)
	at io.undertow.websockets.jsr.EndpointSessionHandler.onConnect(EndpointSessionHandler.java:121)
	at io.undertow.websockets.jsr.JsrWebSocketFilter$1.handleUpgrade(JsrWebSocketFilter.java:165)
	at io.undertow.server.protocol.http.HttpReadListener.exchangeComplete(HttpReadListener.java:390)
	at io.undertow.server.protocol.http.HttpServerConnection.exchangeComplete(HttpServerConnection.java:244)
	at io.undertow.server.HttpServerExchange.invokeExchangeCompleteListeners(HttpServerExchange.java:1353)
	at io.undertow.server.HttpServerExchange.terminateResponse(HttpServerExchange.java:1637)
	at io.undertow.server.Connectors.terminateResponse(Connectors.java:176)
	at io.undertow.server.protocol.http.HttpTransferEncoding$3.handleEvent(HttpTransferEncoding.java:199)
	at io.undertow.server.protocol.http.HttpTransferEncoding$3.handleEvent(HttpTransferEncoding.java:197)
	at io.undertow.conduits.HeadStreamSinkConduit.exitFlush(HeadStreamSinkConduit.java:192)
	at io.undertow.conduits.HeadStreamSinkConduit.flush(HeadStreamSinkConduit.java:133)
	at org.xnio.conduits.ConduitStreamSinkChannel.flush(ConduitStreamSinkChannel.java:162)
	at io.undertow.channels.DetachableStreamSinkChannel.flush(DetachableStreamSinkChannel.java:119)
	at org.xnio.channels.Channels.flushBlocking(Channels.java:63)
	at io.undertow.servlet.spec.ServletOutputStreamImpl.close(ServletOutputStreamImpl.java:619)
	at io.undertow.servlet.spec.HttpServletResponseImpl.closeStreamAndWriter(HttpServletResponseImpl.java:497)
	at io.undertow.servlet.spec.HttpServletResponseImpl.responseDone(HttpServletResponseImpl.java:586)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:339)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:260)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.URISyntaxException: Illegal character in path at index 27: /api/definition/run/report/[object%20Object]/run
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3063)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 34 common frames omitted

```

**Comment by fit2-zhao** [comment]
@Saco93  您这个问题我们一直未能复现，方便远程看看吗，从这个错误来看像是版本没升级成功。

**Comment by Saco93** [comment]
> @Saco93 您这个问题我们一直未能复现，方便远程看看吗，从这个错误来看像是版本没升级成功。

可以先加一个联系方式，我在微信群![image](https://user-images.githubusercontent.com/34698664/150048427-a2b379c2-1d66-4653-ba17-3f4f244ffe3d.png)和QQ群![Uploading image.png…]()里，叫Saco

**Comment by youliyuan-fit2cloud** [comment]
重新升级后未复现了
