### ISSUE TITLE
[BUG]通过Jenkins执行测试计划中场景测试，大量Not started

### ISSUE THREAD

**Issue by Saco93** [metersphere/metersphere#8969]
**MeterSphere 版本**

1.15.4

**Bug 描述**

通过Jenkins执行测试计划中场景测试，大量Not started

**Bug 重现步骤**

1.  执行中出现的报错日志
```log
2021-12-29 14:33:55,896 [StandardJMeterEngine] INFO  i.m.a.s.ApiScenarioReportService ? - Method[updateSchedulePlanCase][收到测试计划场景[ccc3a219-7050-4ea6-a2cb-6cf5ef2f2840]的执行信息，开始保存]
2021-12-29 14:33:55,915 [StandardJMeterEngine] INFO  i.m.a.s.ApiScenarioReportService ? - Method[updateSchedulePlanCase][测试计划场景[ccc3a219-7050-4ea6-a2cb-6cf5ef2f2840]保存结束]
2021-12-29 14:33:55,917 [StandardJMeterEngine] ERROR i.m.api.service.TestResultService ? - Method[saveResult][java.lang.NullPointerException]
java.lang.NullPointerException: null
        at io.metersphere.api.service.ApiScenarioReportService.getEnvironment(ApiScenarioReportService.java:634)
        at io.metersphere.api.service.ApiScenarioReportService$$FastClassBySpringCGLIB$$692fefe4.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
        at io.metersphere.api.service.ApiScenarioReportService$$EnhancerBySpringCGLIB$$d801f1e.getEnvironment(<generated>)
        at io.metersphere.api.service.ApiScenarioReportService$$FastClassBySpringCGLIB$$692fefe4.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
        at io.metersphere.api.service.ApiScenarioReportService$$EnhancerBySpringCGLIB$$9e19e6d4.getEnvironment(<generated>)
        at io.metersphere.api.service.TestResultService.saveResult(TestResultService.java:103)
        at io.metersphere.api.service.TestResultService$$FastClassBySpringCGLIB$$63cf7459.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
        at io.metersphere.api.service.TestResultService$$EnhancerBySpringCGLIB$$41469d9d.saveResult(<generated>)
        at io.metersphere.api.service.TestResultService$$FastClassBySpringCGLIB$$63cf7459.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
        at io.metersphere.api.service.TestResultService$$EnhancerBySpringCGLIB$$85965741.saveResult(<generated>)
        at io.metersphere.api.jmeter.APIBackendListenerHandler.handleTeardownTest(APIBackendListenerHandler.java:54)
        at io.metersphere.api.jmeter.APIBackendListenerHandler$$FastClassBySpringCGLIB$$fcb7e501.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
        at io.metersphere.api.jmeter.APIBackendListenerHandler$$EnhancerBySpringCGLIB$$c6d79895.handleTeardownTest(<generated>)
        at io.metersphere.api.jmeter.APIBackendListenerHandler$$FastClassBySpringCGLIB$$fcb7e501.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
        at io.metersphere.api.jmeter.APIBackendListenerHandler$$EnhancerBySpringCGLIB$$35865fa9.handleTeardownTest(<generated>)
        at io.metersphere.api.jmeter.APIBackendListenerClient.teardownTest(APIBackendListenerClient.java:46)
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:375)
        at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:383)
        at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:218)
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:493)
        at java.lang.Thread.run(Thread.java:748)
```

**期待的正确结果**

计划中所有场景正常执行

**截图**

![image](https://user-images.githubusercontent.com/34698664/147634059-43d6c825-4344-4e58-9a41-52c7c8441d69.png)

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，复现了。下个版本我们会修复

**Comment by youliyuan-fit2cloud** [comment]
v1.16.6版本已解决，升级下吧
