### ISSUE TITLE
[BUG]升级1.16.4后，ms-server 启动后，Failure obtaining db row lock: Table 'metersphere.QRTZ_LOCKS' doesn't exist

### ISSUE THREAD

**Issue by baiqiang1979** [metersphere/metersphere#9258]
**MeterSphere 版本**

您所使用的 MeterSphere 版本是？
1.16.4
**Bug 描述**
升级后，ms-server 启动后，查看日志报错
简要描述您碰到的问题

**Bug 重现步骤**

1.  
2. 
3. 
4. 

**期待的正确结果**

正确情况下应该是什么样的？

**截图**

如果有截图，请附上截图.

2022-01-11 20:30:24,216 [QuartzScheduler_clusterScheduler-7a951ae242451641902508758_ClusterManager] ERROR o.s.s.quartz.LocalDataSourceJobStore 3941 - ClusterManager: Error managing cluster: Failure obtaining db row lock: Table 'metersphere.QRTZ_LOCKS' doesn't exist
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: Table 'metersphere.QRTZ_LOCKS' doesn't exist
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3335)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3935)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3972)
Caused by: java.sql.SQLSyntaxErrorException: Table 'metersphere.QRTZ_LOCKS' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 4 common frames omitted

多个QRTZ_* 如上面的，都是大写的表名，但是数据库小写的，找不到这个表，所以报错。

**Comment by youliyuan-fit2cloud** [comment]
感谢反馈，我们会尽快修复的

**Comment by AgAngle** [comment]
你好，这个报错请修改下数据库参数，忽略表名大小写即可，或者把相关表删除，重新建个小写的表

**Comment by baiqiang1979** [comment]
已经解决 是升级的时候文件权限不对 mysql配置文件没有读取成功导致。另外有个问题请教下 ，安装或者升级的时候不用跑数据库脚本？如果有的话在哪里跑脚本的呢 ，我微信13813921324，手机号如果能微信聊最好，谢谢啊



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jianxing ***@***.***&gt;
发送时间: 2022年1月13日 09:47
收件人: metersphere/metersphere ***@***.***&gt;
抄送: baiqiang1979 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [metersphere/metersphere] [BUG]升级1.16.4后，ms-server 启动后，Failure obtaining db row lock: Table 'metersphere.QRTZ_LOCKS' doesn't exist (Issue #9258)





 
你好，这个报错请修改下数据库参数，忽略表名大小写即可，或者把相关表删除，重新建个小写的表
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
