### ISSUE TITLE
[BUG]关联jira后提交问题失败

### ISSUE THREAD

**Issue by fan01xiao** [metersphere/metersphere#960]
**MeterSphere 版本**
您所使用的 MeterSphere 版本是？
版本: v1.5-7ee95222

**Bug 描述**
简要描述您碰到的问题
配置关联jira后，在测试计划里提交bug issue到jira失败。后台查看日志发现是因为我们jira里规范了提交bug有“期望完成日期”的必填字段
**Bug 重现步骤**
1. 配置关联jira
2. 在测试用例下“提缺陷”
3. 报“调用jira接口创建缺陷失败”

**期待的正确结果**
正确情况下应该是什么样的？
应该统一写个当前时间+2天的日期吧，或者绕过不填。
**截图**
如果有截图，请附上截图.
![image](https://user-images.githubusercontent.com/76150609/102457340-8d42ff80-407d-11eb-886c-a09d9bb0ad7e.png)
![image](https://user-images.githubusercontent.com/76150609/102457353-9633d100-407d-11eb-816f-f324fca7a14b.png)

**Comment by fan01xiao** [comment]
![image](https://user-images.githubusercontent.com/76150609/102457658-0e9a9200-407e-11eb-8774-3bb7b062cff6.png)

**Comment by fan01xiao** [comment]
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)
2020-12-17 15:09:35,491 [qtp917768476-352] ERROR i.m.track.issue.JiraPlatform ? - Method[addJiraIssue][400 : [{"errorMessages":[],"errors":{"customfield_10206":"期望完成日期是必需的。"}}]]
org.springframework.web.client.HttpClientErrorException$BadRequest: 400 : [{"errorMessages":[],"errors":{"customfield_10206":"期望完成日期是必需的。"}}]
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:101)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:170)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:112)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:782)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:740)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:674)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:583)
	at io.metersphere.track.issue.JiraPlatform.addJiraIssue(JiraPlatform.java:158)
	at io.metersphere.track.issue.JiraPlatform.addIssue(JiraPlatform.java:129)

**Comment by fan01xiao** [comment]
图片上传失败。补上error log

**Comment by wangzhen-fit2cloud** [comment]
你好，由于 jira 那边可以增加自定义字段并可以设置自定义字段为必填，目前该问题不是很好处理，建议先在 jira 上将该字段设置为非必填，后续我们会考虑支持配置 jira 的 issue 模板来进行适配。

**Comment by fan01xiao** [comment]
好的  目前已经设置字段必填为选填，但是其实设置必填是一早要求的 这样需求管理上就做出了让步，也会造成一些管理需求缺陷的麻烦，期待ms上的配置改善 谢谢
